### ISSUE TITLE
require_once 'autoload.php' is not precise enough

### ISSUE THREAD

**Issue by websupporter** [podlove/podlove-publisher#1003]
### Expected behavior
Load the correct autoloader

### Actual behavior
To be honest, I do not really get it. But in my WP-Starter/composer installation `require_once 'autoload.php';` loads [here](https://github.com/podlove/podlove-publisher/blob/c8bacd16b6173ddc72c82b5419e1e10104933acc/bootstrap/bootstrap.php#L2) a autoload.php but not yours.

### System information (see `Podlove > Support` menu)
WP-Starter (https://github.com/wecodemore/wpstarter)

//Related: https://wordpress.org/support/topic/fatal-error-ajax-class-is-missing/

**Comment by eteubert** [comment]
It is possible that the way we use composer is not compatible with WP Starter. If you or someone else can look into it and figure out what the issue is, maybe we can find a solution. 

To be honest I'm unsure how popular WP Starter is and how much time I'm willing to spend on this though.

**Comment by eteubert** [comment]
Oh I see you already sent a pull request. Seems easy enough, I'll test it for the next release :)
