### ISSUE TITLE
Subscribe-Button-Shortcode Doku: fehlende/verwirrende Infos

### ISSUE THREAD

**Issue by mespotine** [podlove/podlove-publisher#1007]
Beim Durchschauen der Doku zum Shortcode des Subscribe-Buttons ist mir aufgefallen, dass das Element show="showslug" nicht dokumentiert ist.

Das macht das setzen von Shows etwas schwierig.

Auch ist nicht klar ersichtlich, warum auf der Seite Podlove -> Modules "[podlove-subscribe-button]" als Shortcut steht, auf der Dokuseite selbst aber [podlove-podcast-subscribe-button] steht:
https://docs.podlove.org/podlove-publisher/reference/shortcodes.html#subscribe-button

Eventuell wäre es auch noch eine Idee, die Shortcode-Doku noch auf der Module-Seite direkt zu verlinken, so dass man auch gleich weiß, wo man nachschlagen kann.
Hätte man mir nicht die Doku gezeigt, ich wär im Leben nicht drauf gekommen, dass man da mehr einstellen kann und ich kann mir das durchaus auch bei Anderen vorstellen.

**Comment by eteubert** [comment]
Alles gute Hinweise, danke 👍🏻
