### ISSUE TITLE
wordpress 5.0 create new episode is impossible 

### ISSUE THREAD

**Issue by frankbash** [podlove/podlove-publisher#1020]
after updating Wordpress to version 5.0

when i press on create new episode, wordpress switch to a blank page

**Comment by eteubert** [comment]
It works for me. Can you provide a PHP error log?

**Comment by eteubert** [comment]
I've heard installing the [Classic Editor](https://wordpress.org/plugins/classic-editor/) helps.

**Comment by sneakpodbob** [comment]
Same here. Editing an existing episode works, creating a new one return a 500. 
Installing the Classic Editor helps!

**Comment by eteubert** [comment]
Can anyone post a list of active plugins? (for example from the Publisher support menu)

I can't reproduce this so far.

**Comment by frankbash** [comment]
i think maybe wordpress added the portfolio (new post type since vers. 5) and change structure in the back ???

**Comment by eteubert** [comment]
Still no luck getting the error. Can you provide a PHP error log?

**Comment by frankbash** [comment]
sure where do i find it?

**Comment by eteubert** [comment]
Your webserver is probably already creating a log file but it is very system dependent where that might be. You can also temporarily let WordPress write the logs:

```php
// wp-config.php

// Enable WP_DEBUG mode
define( 'WP_DEBUG', true );

// Enable Debug logging to the /wp-content/debug.log file
define( 'WP_DEBUG_LOG', true );
```

(via https://codex.wordpress.org/Debugging_in_WordPress)

**Comment by frankbash** [comment]
i send your a email with the log

**Comment by eteubert** [comment]
Thanks, already had a look. Unfortunately no clue there. All log entries are from other plugins, not the Publisher. And just minor warnings, nothing that would lead to a 500/white site.

Thanks for your help so far but I'm out of ideas what else to look for.

**Comment by MacGyver-NRW** [comment]
Hi @eteubert ,
i have in this case this php error logs found and point them on this issue:

> [:error] [pid ****] [client *****] PHP Warning:  SimpleXMLElement::addChild(): unterminated entity reference ACTION! in /var/www/**DOMAIN**/blog/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/lib/modules/oembed/oembed.php on line 38

and other error:

> [:error] [pid ****] [client *****] WordPress-Datenbank-Fehler Unknown column 'wp_podlove_episode.subtitle' in 'where clause' f\xc3\xbcr Abfrage SELECT SQL_CALC_FOUND_ROWS  wp_posts.ID FROM wp_posts  WHERE 1=1  AND (\n\t\t\t\n\t\t\t(\n\t\t\t\t(wp_posts.post_title LIKE '%historie%')\n\t\t\t\tOR\n\t\t\t\t(wp_posts.post_content LIKE '%historie%')\n\t\t\t\tOR\n\t\t\t\t(wp_podlove_episode.subtitle LIKE '%historie%')\n\t\t\t\tOR\n\t\t\t\t(wp_podlove_episode.summary LIKE '%historie%')\n\t\t\t\tOR\n\t\t\t\t(wp_podlove_episode.chapters LIKE '%historie%')\n\t\t\t))  AND (wp_posts.post_password = '')  AND wp_posts.post_type IN ('post', 'podcast') AND (wp_posts.post_status = 'publish')  ORDER BY wp_posts.post_date DESC LIMIT 0, 10 von require('wp-blog-header.php'), wp, WP->main, WP->query_posts, WP_Query->query, WP_Query->get_posts

PHP Version                5.6.36
WordPress Version          5.0.3
Publisher Version          2.7.20
Web Player Version         player_v4

**Comment by eteubert** [comment]
I tried a few things with release 2.7.22. Please give it a try and see if it helps. And if not, I think at least the errors should be different :)

**Comment by errotu** [comment]
I had the same problem (and fixed it as well by installing the Classic Editor).
The problem occurred on a shared hosting installation of wordpress with 1&1 as webhoster.

PHP Version 7.2
WordPress Version 5.2.2
Podlove Version 2.8.9
