### ISSUE TITLE
Permalinks gehen sporadisch verloren

### ISSUE THREAD

**Issue by MariusQuabeck** [podlove/podlove-publisher#1038]
Seitdem wir auf [nerdzoom.de](https://nerdzoom.de/) und [librezoom.net](https://librezoom.net/) den Podlove Publisher einsetzen ist das einbinden von Artikeln auf anderen Seiten nicht mehr möglich.
Einer unserer Autoren hat dieses Problem entdeckt weil er Artikel bei uns auch auf seinem Blog [einbettet](https://blog.ahahn94.de/2019/03/15/serialisierung-von-c-klassen-mit-moeglichst-wenig-code/).

Wir haben heute mal alle Plugins deaktiviert und einzeln wieder aktiviert und haben festgestellt dass mit deaktiviertem Podlove Publisher die Einbettungen angezeigt werden.

Auf Nachfrage bei unserem Hoster meinte er dass das Plugin wohl eigene Rewrites setzt die für Probleme sorgen beim einbetten und auch dafür verantwortlich sein können dass manchmal Seiten (Pages, nicht Beiträge) nicht angezeigt werden können (404 obwohl die Adresse richtig ist).
Dieses Problem lässt sich nur beheben wenn man die Permalinks neu generiert. Ist gerade beim Impressum sehr unpraktisch.

**Comment by pixelcatcher** [comment]
habe ähnliche Probleme - allerdings mit Woocommerce + Podlove. 
Konntest du es lösen? Ist ja echt blöd dass hier keiner was antwortet.

**Comment by MariusQuabeck** [comment]
@pixelcatcher nein, leider nicht.

**Comment by eteubert** [comment]
Das Problem (also: Permalinks gehen sporadisch kaputt; mit Einbetten hat das nichts zu tun) ist mir seit langem bekannt, lässt sich jedoch nur schwierig reproduzieren und es ist mir bisher nicht gelungen, das zu beheben.

Ich habe aber zumindest eine grobe Ahnung, aus welcher Richtung es kommen könnte. Ich muss das die Tage noch mal zusammentragen, vielleicht finde ich diesmal eine Lösung oder wenigstens einen Workaround.

Wenn jemand Hinweise zum Reproduzieren hat, gerne her damit. Meiner Erfahrung nach passiert es _manchmal_, wenn man Plugins aktualisiert.

**Comment by eteubert** [comment]
Vermutlich gleicher Bug: #1185

**Comment by eteubert** [comment]
Vermutlich gleicher Bug: #941

**Comment by pixelcatcher** [comment]
Servus! Also ich kann es im verlinkten Bug jedes mal reproduzieren. Wenn ich zur Lösung beitragen kann lass es mich wissen.

**Comment by MariusQuabeck** [comment]
Hallo Eric,

danke für die Antwort, ja das Problem mit den Permalinks passiert mir öfters nach einem Yoast SEO Update. Allerdings kann ich das Problem mit den eingebetteten Artikeln durchaus auf Podlove zurückführen. Wenn ich alle Plugins deaktiviere dann funktioniert auf anderen Webseiten der Embedd von meinen Blogposts, sobald ich Podlove wieder aktiviere, nicht. Ich helfe gerne beim reproduzieren, ich vermute allerdings du bräuchtest eher die Infos von dem Blog auf dem es nicht angezeigt werden kann?

Mit allen Plugins aktiviert:
![image](https://user-images.githubusercontent.com/17063564/105636885-b61f9700-5e6a-11eb-9d94-cab9f918e4b7.png)

Mit Podlove Podcast Publisher deaktiviert:
![image](https://user-images.githubusercontent.com/17063564/105636906-d51e2900-5e6a-11eb-832f-a698abd1d8f4.png)

**Comment by eteubert** [comment]
Workaround Vermutung:

In der `plugin.php` des Publisher Plugins die Zeile 

```php
require_once \Podlove\PLUGIN_DIR.'includes/permalinks.php';
``` 

auskommentieren:

```php
// require_once \Podlove\PLUGIN_DIR.'includes/permalinks.php';
```

⚠️ Dann funktionieren folgende zwei Einstellungen (aus Expert Settings) nicht mehr:

<img width="852" alt="Screenshot 2021-01-24 at 23 30 31" src="https://user-images.githubusercontent.com/235918/105645784-3ad6d900-5e9c-11eb-8de9-451f723bd073.png">

bzw. verhalten sie sich so wie im Screenshot zu sehen. 

----

Meine Bitte an euch:

1) Berichtet, welche Einstellungen ihr dort aktuell habt.
2) Probiert meinen o.g. Workaround aus und beobachtet, ob das Problem damit verschwindet. 

Wenn es mit dem SEO Plugin derzeit zuverlässig auftritt, kann auch [hier](https://wordpress.org/plugins/wordpress-seo/advanced/#download-previous-link) eine alte Version des Plugins geladen werden, um anschließend wieder updaten zu können.

Danke euch 🙏

**Comment by MariusQuabeck** [comment]
Danke Eric, ich teste und berichte am Wochenende :)

**Comment by pixelcatcher** [comment]
Guten Morgen Eric,

danke für deinen Einsatz!
Das hat geholfen! Zumindest kann ich den Fehler auf dem von mir beschriebenen Weg nicht mehr hervorrufen. Ich kann aber nicht sagen, ob es noch auf anderen wegen passiert. Ich beobachte es definitiv.

Meine Optionen sahen wie folgt aus:
<img width="1357" alt="Bildschirmfoto 2021-01-25 um 08 52 06" src="https://user-images.githubusercontent.com/33382133/105676414-c414fc80-5eea-11eb-850a-492c5a818a45.png">

**Comment by pixelcatcher** [comment]
vielleicht ist es noch interessant zu sagen, dass ich alle Podcasts mit einem Passwort versehe - nicht weil ich das möchte sondern weil ich die automatisch erzeugten Podcast Seiten nicht haben möchte.

**Comment by pixelcatcher** [comment]
habe gerade gesehen, dass ein update (3.3.1) erschien. Wurde das Problem dort behoben oder ist damit zu rechnen dass es wieder auftritt?

**Comment by eteubert** [comment]
Nein das Problem besteht weiterhin. Vermutlich werde ich mir einen Pfad überlegen müssen, die beiden Funktionen zu entfernen.

**Comment by eteubert** [comment]
Ein Ansatz, die Features zu entfernen: https://github.com/podlove/podlove-publisher/commit/c5e0a4a7c676fb65696f9a4339e2a8c657e05824#diff-9e6e4772050998a5c0dc3c61acf3dab0a7e594566171fa5746d6b62f9598efb6

**Comment by Inrumpo** [comment]
Könnte das möglicherweise auch der Grund für dieses mysteriöse Problem sein?

https://community.podlove.org/t/redirect-error-stops-pages-from-loading-err-too-many-redirects/1551

**Comment by eteubert** [comment]
@Inrumpo Ausschließen kann ich es nicht, aber 🤷‍♂️ 

Ich mache hier zu, da Release 3.5.0 das Feature entfernt hat. Sollte es erneut auftreten, bitte ein neues issue öffnen.

**Comment by pixelcatcher** [comment]
Bad News: Bug is still active in version 3.6.1 
Good News Workaround is still working.
