### ISSUE TITLE
Rss Feed is not working

### ISSUE THREAD

**Issue by hannesN** [podlove/podlove-publisher#1039]
### Expected behavior

The RSS Feed is complete as it was before.

### Actual behavior

IN the middle of the latest episodes description the feed is broken and the apache log shows:

[Fri Mar 22 15:19:16.498958 2019] [php7:error] [pid 11739] [client 95.91.8.213:56302] PHP Fatal error:  Declaration of Twig_Extensions_TokenParser_Trans::parse(Twig_Token $token) must be compatible with Twig\\TokenParser\\TokenParserInterface::parse(Twig\\Token $token) in <PATH>/plugins/podlove-podcasting-plugin-for-wordpress/vendor/twig/extensions/lib/Twig/Extensions/TokenParser/Trans.php on line 0, referer: <URL>

### System information (see `Podlove > Support` menu)

Website                    https://www.hannesniederhausen.de
PHP Version                7.2.15-0ubuntu0.18.04.1
WordPress Version          5.1.1
WordPress Theme             v
Active Plugins             
           - Advanced Custom Fields v5.7.12
           - Advanced Excerpt v4.2.8
           - AJAX Thumbnail Rebuild v1.13
           - Cookie Notice v1.2.46
           - Disable Comments v1.9.0
           - Duplicate Page v3.3
           - Duplicator v1.3.10
           - MailPoet 3 (New) v3.21.1
           - Podlove Podcast Publisher v2.7.23
           - Quick Featured Images v13.3.3
           - Shariff for Wordpress v1.0.11
           - Yoast SEO v10.0.1
           - Prosodia VGW OS für Zählmarken (VG WORT) v3.20.7
WordPress Database Charset utf8
WordPress Database Collate 
Publisher Version          2.7.23
Web Player Version         player_v4
Twig Version               1.38.0
open_basedir               ok
curl Version               7.58.0
iconv                      available
simplexml                  ok
max_execution_time         30
upload_max_filesize        2M
memory_limit               256M
disable_classes            
disable_functions          pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wifcontinued,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_get_handler,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,pcntl_async_signals,
permalinks                 ok (/%category%/%postname%/)
podlove_permalinks         ok
podcast_settings           ok
web_player                 ok
podlove_cache              on
assets                     
  - mp3    audio/mpeg       https://www.hannesniederhausen.de/feed/mp3/
cron                       ok

0 errors
0 notices
Nice, Everything looks fine!

**Comment by eteubert** [comment]
`Publisher Version 2.7.23` ships with `Twig Version 1.38.3` but your debug output shows `Twig Version 1.38.0`, which contains a bug. So there might be another plugin you are using that contains this problematic version of Twig which seems to get precendence over the Publisher included version of Twig.

Possibly [MailPoet.](https://github.com/mailpoet/mailpoet/blob/master/composer.lock#L723) Can you try deactivating it? The "real" fix would be for MailPoet to update their Twig dependency.

**Comment by hannesN** [comment]
Yes, after deactivating Mailpoet it worked.
