### ISSUE TITLE
Web Player not showing

### ISSUE THREAD

**Issue by ednyfed** [podlove/podlove-publisher#1043]
No settings were changed, but the web player stopped showing on the pages.  There was an issue with Podlove Publisher and Mail Poet, but the Mail Poet plugin is disabled and that corrected that issue.  I am uncertain if this issue began before or after that.  This has happened within the last week.

Same issue happens regardless of what Player I select in the Podlove Publisher settings

URL as an example:
https://koltikvahdayton.com/purim

Happened in:
FireFox 65.0.2
Chrome 73.0.3683.86

Website                    https://koltikvahdayton.com
PHP Version                7.2.16
WordPress Version          5.1.1
WordPress Theme            Nirvana v1.5.1.1
Active Plugins             
           - WP Assistant v5.2.0
           - Akismet Anti-Spam v4.1.1
           - All In One WP Security v4.3.8.3
           - BackWPup v3.6.8
           - Broken Link Checker v1.11.8
           - Contact Form 7 v5.1.1
           - Cryout Serious Theme Settings v0.5.9
           - Display Posts v3.0.1
           - Elementor v2.5.9
           - Flamingo v1.9
           - Jetpack by WordPress.com v7.1.1
           - Podlove Podcast Publisher v2.7.23
           - Podlove Subscribe Button v1.3.6
           - Podlove Web Player v2.1.0
           - Print, PDF & Email by PrintFriendly v3.14.4
           - Statify v1.6.3
           - TinyMCE Advanced v5.1.0
WordPress Database Charset utf8
WordPress Database Collate 
Publisher Version          2.7.23
Web Player Version         player_v4
Twig Version               1.38.3
open_basedir               ok
curl Version               7.38.0
iconv                      available
simplexml                  ok
max_execution_time         30
upload_max_filesize        67108864
memory_limit               268435456
disable_classes            
disable_functions          
permalinks                 ok (/%postname%)
podlove_permalinks         ok
podcast_settings           ok
web_player                 ok
podlove_cache              on
assets                     
  - mp3    audio/mpeg       https://koltikvahdayton.com/feed/mp3
cron                       ok

0 errors
0 notices
Nice, Everything looks fine!

**Comment by eteubert** [comment]
Likely a Publisher issue more than a player issue.

What are your Publisher template settings?
Can you find anything in the PHP error log?

**Comment by ednyfed** [comment]
This can be closed - somehow the template setting got changed to no auto insert the player.  Not sure what happened, but once I set it back, the player showed again.
