### ISSUE TITLE
Incompatibility with Disk Usage Sunburst

### ISSUE THREAD

**Issue by deermo** [podlove/podlove-publisher#1055]
# Actual behavior
When the plugin "Disk Usage Sunburst" is installed and activated, the charts on the "Analytics-Page" don't load

**Comment by eteubert** [comment]
That's something this plugin should fix. The issue here is that they include d3.js library which is in conflict with the d3.js version Publisher uses. However there is really no reason for Sunburst to load this js file anywhere but on their own admin page.
