### ISSUE TITLE
WP log flood

### ISSUE THREAD

**Issue by Backpackstudio** [podlove/podlove-publisher#1065]
### Expected behavior

Clear WP log

### Actual behavior

Lot of log entries like:

2019-08-22 05:33:59] Podlove.DEBUG: [job] [id 45] done [] []

### System information 

Website ***
PHP Version 7.3.8
WordPress Version 5.2.2
WordPress Theme Contentberg v1.6
Active Plugins

ContentBerg Core v1.1.0
Disable Comments v1.10.2
Force Regenerate Thumbnails v2.0.6
Podlove Podcast Publisher v2.9.1
Regenerate Thumbnails v3.1.1
Sphere Core v1.0.7
WP Retina 2x v5.5.6
WP User Avatar v2.2.4
WordPress Database Charset utf8mb4
WordPress Database Collate
Publisher Version 2.9.1
Web Player Version player_v4
Twig Version 1.42.2
open_basedir ok
curl Version 7.54.1
iconv available
simplexml ok
max_execution_time 30
upload_max_filesize 2047M
memory_limit 1024M
disable_classes
disable_functions
permalinks ok (/%category%/%postname%/)
podlove_permalinks ok
podcast_settings ok
web_player ok
podlove_cache on
assets
mp3 audio/mpeg ***
cron ok
duplicate_guids ok
0 errors
0 notices
Nice, Everything looks fine!

**Comment by eteubert** [comment]
Are you running your WordPress in debug mode? Otherwise those messages should not appear.

**Comment by Backpackstudio** [comment]
> Are you running your WordPress in debug mode? Otherwise those messages should not appear.

Thank you for asking. To trace properly WordPress issues, hidden error log is used. 

```
define('WP_DEBUG', true);
define('WP_DEBUG_LOG', '<--path-to-log-file-->');
define('WP_DEBUG_DISPLAY', false);
```

I guess you are pushing log entries wheneever WP_DEBUG is set to true?  But this is not the best way how to handle it as it floods the WP log with your messages and makes it hard to trace down actual errors.

**Comment by eteubert** [comment]
> It is not recommended to use WP_DEBUG or the other debug tools on live sites; they are meant for local testing and staging installs.

 via https://wordpress.org/support/article/debugging-in-wordpress/

**Comment by Backpackstudio** [comment]
> > It is not recommended to use WP_DEBUG or the other debug tools on live sites; they are meant for local testing and staging installs.
> 
> via https://wordpress.org/support/article/debugging-in-wordpress/

For first this is bad excuse for wrongly using WP log. The main purpose of WP LOG is to trace down errors. Your plugin causes flood on log, which makes it hard to trace down actual errors. You should fix the logic, so if I don't need this log, this should be disabled.

Also your claim is not 100% true. Please note that since WP 5 there is huge change on using log. Log can be stored in secure place, which is not publicly available. Also we install new plugins, themes or do upgrades on LIVE sites, on which cases error debugging is necessary. 

Instead of forcing users of your plugin to not to use WP LOG, you shall fix the behaviour of your plugin, which by the way shouldn't be complicated. Also as seen from code below, you are using your own constant already for debugging which overrides WP_DEBUG anyway, which makes your claim even more ridiculous.

```
	public function is_debug_enabled() {
		return defined('WP_DEBUG') && WP_DEBUG || defined('PODLOVE_LOGGER_DEBUG') && PODLOVE_LOGGER_DEBUG;
	}
```

Just add an option to the settings panel and update the code:

```
	public function is_debug_enabled() {
		return (bool) get_option( 'PODLOVE_LOGGER_DEBUG');
	}
```

**Comment by eteubert** [comment]
I'm happy to take Pull Request into consideration.

**Comment by Backpackstudio** [comment]
Please could you update class Log?

We cannot use WordPress update feature for this plugin becouse of log flood. 

Please note that WP_DEBUG is meant for something else than plugins internal log.

**Comment by eteubert** [comment]
I don't have time to work on this at the moment. If you can provide the code required in a Pull Request I'm sure it will find its way into a release.

**Comment by eteubert** [comment]
Hi @Backpackstudio, I'm sorry it took so long but I believe this is the fix you're asking for.
