### ISSUE TITLE
Podlove Web Player plugin is outdated

### ISSUE THREAD

**Issue by Backpackstudio** [podlove/podlove-publisher#1067]
### Expected behavior

Podlove Web Player plugin updated.

### Actual behavior

Last updated: 3 years ago

### Notes

[Podlove Web Player](https://wordpress.org/plugins/podlove-web-player/) plugin is outdated approc 3 years. You just released update for Publisher, which contains an updated version of web-player. 

When you plan update the [Podlove Web Player](https://wordpress.org/plugins/podlove-web-player/) plugin?

**Comment by eteubert** [comment]
I do not develop the web player plugin. There is currently no one maintaining the web player plugin, which is why there are no updates. 

Closing because it's not Publisher related.

**Comment by Backpackstudio** [comment]
Thank you for response! 

How about some kind of solution, which doesn’t require any updates for web player plugin on external sites or proper oembed response to easily embed podcasts on external sites?

I’m willing to help, but there should be some kind of clear strategy.

**Comment by Backpackstudio** [comment]
Related issue: #1063
