### ISSUE TITLE
Podcast feed broken

### ISSUE THREAD

**Issue by sbonham22** [podlove/podlove-publisher#1075]
### Expected behavior
My podcast feed has remained the same for 3 years and I’ve never had an issue. 

### Actual behavior
All of the sudden, all my episodes after August 29th have not been uploading. When I try to reload them on iTunes or Spotify it just says there are no new episodes. When I go in to the actual iTunes podcast verification all episodes are there though and now on my phone there is the “old feed” that has the image, description, etc. but no new epidsodes. Then there’s the “new feed” with all the episodes but no image or description. No idea what the disconnect is and I’m not saavy enough to edit the wordpress files myself. Any kind of insight would be appreciated.

### System information (see `Podlove > Support` menu)
https://importantnonsense.com/feed/podcast/ 1

**Comment by eteubert** [comment]
Please check the image for episode 54, it's `https://i1.wp.com/importantnonsense.com/wp-content/uploads/2019/07/podcast-e1567655292369.jpg?fit=500%2C500&ssl=1` and I believe it should not contain an `&` character. Maybe you can set it up like the other images?

Found via https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fimportantnonsense.com%2Ffeed%2Fpodcast%2F. All other warnings can be ignored but the parsing error might be the reason it can't be updated by itunes.

You can also check here https://podba.se/validate/?url=https://importantnonsense.com/feed/podcast/ which doesn't run through at the moment.

**Comment by sbonham22** [comment]
This got it. Thank you. 

Steve Bonham
Co-Owner/Founder
ImportantNonsense.com
