### ISSUE TITLE
Add order by start date for seasons

### ISSUE THREAD

**Issue by camsteffen** [podlove/podlove-publisher#1080]
I would like to be able to iterate seasons, and season.episodes, from newest to oldest like

```
{% for season in podcast.seasons({orderby: 'startDate', order: 'DESC'}) %}
    {% for episode in season.episode({orderby: 'publicationDate', order: 'DESC'}) %}
```

**Comment by eteubert** [comment]
Both `order` paramers are added in the current release. You don't need any `orderby` parameter.

**Comment by camsteffen** [comment]
Thanks for adding this so quickly!

**Comment by camsteffen** [comment]
@eteubert The eposide order is working but the season order is not working for me. It always shows in ascending order. Could you double check? My template looks like this:

    {% for season in podcast.seasons({order: 'DESC'}) %}
        {% for episode in season.episodes({order: 'DESC'}) %}

**Comment by peerdicken** [comment]
> @eteubert The eposide order is working but the season order is not working for me. It always shows in ascending order. Could you double check? My template looks like this:
> 
> ```
> {% for season in podcast.seasons({order: 'DESC'}) %}
>     {% for episode in season.episodes({order: 'DESC'}) %}
> ```

Same here for me.
