### ISSUE TITLE
RSS feed not working

### ISSUE THREAD

**Issue by Yonjuni** [podlove/podlove-publisher#1090]
### Expected behavior
- A valid and consistent RSS feed that can be parsed by other services

### Actual behavior
- The feed does not update at all: it shows a date from June, but I installed the plugin in November.
- The feed is available here: https://backpackersguide.de/feed/mp3/
- Most of the time it is just empty without any data in it, but sometimes -and this is really odd- it has data in it but not about the episode that I published
- All feed validators output that the feed is invalid

I've already tried the following but nothing has worked:
- Switching off all other plugins
- Re-installing the plugin
- I made sure that the podcast settings are complete
- I made sure to toggle the box in the feed to allow discovering by other services
- I deleted the feed and set it up again
- I used the provided tools from Podlove menu (clear cache and attempt repair)
- I checked the cron jobs

I would love to use the plugin to host the podcast by myself. Please, let me know if there is anything else I can do :-) Any help appreciated. 

### System information (see `Podlove > Support` menu)
Website                    https://backpackersguide.de
PHP Version                7.0.33-0ubuntu0.16.04.7
WordPress Version          5.3
WordPress Theme            Hueman Child v1.0.0
Active Plugins             
           - Polylang v2.6.7
           - WPBruiser v3.1.35
           - ADL Post Slider v1.6.4
           - Better Delete Revision v1.6.1
           - Contact Form 7 Captcha v0.0.3
           - Contact Form 7 v5.1.6
           - Count Per Day v3.6.1
           - Hueman Addons v2.2.7
           - Media Library Folders for WordPress v5.1.1
           - Nimble Page Builder v1.9.12
           - Podlove Podcast Publisher v2.9.6
           - Portfolio Gallery v2.4.2
           - Regenerate Thumbnails v3.1.2
           - Responsive Lightbox & Gallery v2.2.2
           - Huge IT Slider v4.0.6
           - Statify v1.6.3
           - Twitter Cards Meta v2.9.0
           - Unattach and Re-attach Media Attachments v1.2
           - WordPress Importer v0.6.4
           - WP-PageNavi v2.93.1
           - WP User Avatar v2.2.4
WordPress Database Charset utf8
WordPress Database Collate 
Publisher Version          2.9.6
Web Player Version         player_v4
Twig Version               1.42.2
open_basedir               ok
curl Version               7.47.0
iconv                      available
simplexml                  ok
max_execution_time         300
upload_max_filesize        280M
memory_limit               256M
disable_classes            
disable_functions          pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wifcontinued,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,
permalinks                 ok (/%postname%/)
podlove_permalinks         ok
podcast_settings           ok
web_player                 ok
podlove_cache              on
assets                     
  - mp3    audio/mpeg       https://backpackersguide.de/feed/mp3/
  - jpg    image/jpeg       no feed
cron                       ok
duplicate_guids            ok

0 errors
0 notices
Nice, Everything looks fine!

**Comment by eteubert** [comment]
The title of the RSS feed is `Kommentare zu:`, which suggests to me that some plugin (or the theme) took over the feed URL and tries to deliver some comments feed here. Also the "generator" is `https://wordpress.org/?v=5.3`, meaning this feed is not generated by Podlove Publisher but WordPress. 

I just remembered an issue with the RSS feed in the theme you use a few years ago: https://github.com/presscustomizr/hueman/issues/256 Maybe the theme is still doing something unorthodox here. Might be worth a shot since it looks like the only thing you didn't try is switching to a default theme.

If it turns out to be the theme, I suggest you contact the theme support.

**Comment by Yonjuni** [comment]
Thanks for the quick reply. 

I did the following, but no changes in the feed :(

- I switched to the Twenty Twenty Theme
- I cleared all caches
- I deleted the feed and set it up again
- I also checked from another browser

**Comment by eteubert** [comment]
Hmm but there I see a self reference to `https://backpackersguide.de/de/feed/mp3/` which is not an expected URL. Maybe an incompatibility with polylang then.

But I'm just guessing. I've never had a behavior like yours reported before.

**Comment by Yonjuni** [comment]
Apparently, polylang is the problem. I removed it completely and then the feed worked. I also found a way to bring the feed to working with polylang:

- By default, polylang does not consider custom post types. Episodes by Podlove are custom, thus before adding the first episode the following settings from Polylang have to be activated:
      

     `Settings > Custom post types and taxonomies > episodes`

- Doing this after publishing episodes won't work

- Furthermore, the feed is not available under the listed url, you have to add the language tag
