### ISSUE TITLE
Not compatible with Spotify (RSS Feed)

### ISSUE THREAD

**Issue by abcgmbh** [podlove/podlove-publisher#1092]
### Expected behavior
Tags `<description>` and `<email>` should not be empty when filled in settings
### Actual behavior
Tag `<description>` is every time empty
Tag `<email>` is not in the RSS Feed
### System information (see `Podlove > Support` menu)
Website                    https://blog.hiddencandidates.com
PHP Version                7.3.12-1+ubuntu18.04.1+deb.sury.org+1
WordPress Version          5.3
WordPress Theme            Lovecraft v1.31
Active Plugins             
           - The SEO Framework v4.0.4
           - Classic Editor v1.5
           - Custom Fonts v1.2.0
           - File Manager Advanced v3.1
           - Podlove Podcast Publisher v2.9.6
           - Social Icons Widget by WPZOOM v3.4.1
           - UpdraftPlus – Sichern/Wiederherstellen v1.16.20
           - WP-Optimize - Clean, Compress, Cache v3.0.14
           - WP User Avatar v2.2.4
WordPress Database Charset utf8mb4
WordPress Database Collate 
Publisher Version          2.9.6
Web Player Version         player_v4
Twig Version               1.42.2
open_basedir               ok
curl Version               7.58.0
iconv                      available
simplexml                  ok
max_execution_time         30
upload_max_filesize        24M
memory_limit               256M
disable_classes            
disable_functions          pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wifcontinued,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_get_handler,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,pcntl_async_signals,
permalinks                 ok (/%category%/%post_id%/)
podlove_permalinks         ok
podcast_settings           ok
web_player                 ok
podlove_cache              on
assets                     
  - mp3    audio/mpeg       https://blog.hiddencandidates.com/feed/mp3/
cron                       ok
duplicate_guids            ok

0 errors
0 notices
Nice, Everything looks fine!

**Comment by eteubert** [comment]
It might be your SEO plugin overriding the description field. Please try deactivating it, then clearing caches via Podlove Publisher tools, then checking the feed again.

**Comment by abcgmbh** [comment]
I have deactivate the SEO plugin, cleaned the cache with the Podlove Publisher tool and checked the feed again.

Description is empty!
E-Mail is not in the rss feed!

**Comment by abcgmbh** [comment]
I also deactivated two other plugins, but its the same error

Website                    https://blog.hiddencandidates.com
PHP Version                7.3.12-1+ubuntu18.04.1+deb.sury.org+1
WordPress Version          5.3
WordPress Theme            Lovecraft v1.31
Active Plugins             
           - Classic Editor v1.5
           - Custom Fonts v1.2.0
           - File Manager Advanced v3.1
           - Podlove Podcast Publisher v2.9.6
           - Social Icons Widget by WPZOOM v3.4.1
           - WP User Avatar v2.2.4
WordPress Database Charset utf8mb4
WordPress Database Collate 
Publisher Version          2.9.6
Web Player Version         player_v4
Twig Version               1.42.2
open_basedir               ok
curl Version               7.58.0
iconv                      available
simplexml                  ok
max_execution_time         30
upload_max_filesize        24M
memory_limit               256M
disable_classes            
disable_functions          pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wifcontinued,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_get_handler,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,pcntl_async_signals,
permalinks                 ok (/%category%/%post_id%/)
podlove_permalinks         ok
podcast_settings           ok
web_player                 ok
podlove_cache              on
assets                     
  - mp3    audio/mpeg       https://blog.hiddencandidates.com/feed/mp3/
cron                       ok
duplicate_guids            ok

0 errors
0 notices
Nice, Everything looks fine!
