### ISSUE TITLE
.vtt file not uploading correctly

### ISSUE THREAD

**Issue by tkuhns** [podlove/podlove-publisher#1097]
### Expected behavior
.vtt file to import successfully.

### Actual behavior
Uploading valid .vtt file gives the following error:

Transcript file must be webvtt. Is: application/octet-stream

<img width="827" alt="Screen Shot 2020-02-05 at 2 25 01 PM" src="https://user-images.githubusercontent.com/38292798/73884580-6a23ae80-4823-11ea-89d1-421b30ae0bb5.png">

Here is the .vtt file I am using:
[Ep 204 - the-gate.vtt.zip](https://github.com/podlove/podlove-publisher/files/4162116/Ep.204.-.the-gate.vtt.zip)

I have tried this in both Chrome and Firefox with similar results. 

### System information (see `Podlove > Support` menu)
Website                    http://2guys.red40net.com
PHP Version                7.2.27
WordPress Version          5.3.2
WordPress Theme            Podcast Child v1.0.4.1577710049
Active Plugins             
           - Antispam Bee v2.9.1
           - Child Theme Configurator v2.5.2
           - Easy Social Icons v3.0.7
           - Google Analytics for WordPress by MonsterInsights v7.10.4
           - Podcast Subscribe Buttons v1.2.1
           - Podlove Podcast Publisher v2.9.6
           - Podlove Subscribe Button v1.3.7
           - Post Grid by PickPlugins v2.0.43
           - Testimonial Rotator v3.0.1
           - Yoast SEO v12.9.1
WordPress Database Charset utf8
WordPress Database Collate 
Publisher Version          2.9.6
Web Player Version         player_v4
Twig Version               1.42.2
open_basedir               ok
curl Version               7.38.0
iconv                      available
simplexml                  ok
max_execution_time         30
upload_max_filesize        100M
memory_limit               2048M
disable_classes            
disable_functions          
permalinks                 ok (/%year%/%monthnum%/%day%/%postname%/)
podlove_permalinks         ok
podcast_settings           ok
web_player                 ok
podlove_cache              on
assets                     
  - mp3    audio/mpeg       http://2guys.red40net.com/feed/mp3/
cron                       ok
duplicate_guids            ok
multisite                  ok

0 errors
0 notices
Nice, Everything looks fine!

**Comment by eteubert** [comment]
I fixed several upload issues in the beta branch. Hopefully that solves this as well.
