### ISSUE TITLE
Remove Flattr

### ISSUE THREAD

**Issue by eteubert** [podlove/podlove-publisher#1103]
It's dead, Jim.

- [ ] remove from readme
- [ ] remove module
- [ ] remove from template API

**Comment by chemiker** [comment]
- [ ]  prune settings

This needs discussion. On the one hand, why clutter the database and/or leave unused entries? On the other hand: How should this be implemented? Deleting without users permission is meh...

**Comment by eteubert** [comment]
Done: 2da0a7e
