### ISSUE TITLE
PodLove corrupting Recent Posts when displayed from a Category page.

### ISSUE THREAD

**Issue by OdinWynd** [podlove/podlove-publisher#1104]
### Expected behavior

To just show recent posts.

### Actual behavior

Shows all kinds of activities and changes as Posts. Like when I import an event, or when I update an oAuth.

The issue clears up when I disable PodLove in wordpress.

This is a security issue, and I will have to uninstall PodLove.

### System information (see `Podlove > Support` menu)

Website                    REDACTED
PHP Version                7.3.16
WordPress Version          5.3.2
WordPress Theme            Neve Child v1.0.0
Active Plugins             
           - Async JavaScript v2.20.03.01
           - bbPress v2.6.4
           - BuddyPress v5.1.2
           - Contact Form 7 v5.1.7
           - Cooked Odin Customizations v1.0.0
           - Cooked v1.7.6
           - Smash Balloon Custom Facebook Feed v2.13
           - Eonet Live Notifications v1.0.11
           - Eonet Manual User Approve v2.1.3
           - GTmetrix for WordPress v0.4.4
           - Health Check & Troubleshooting v1.4.2
           - Import Social Events v1.6.9
           - Invisible reCaptcha v1.2.3
           - Neve Pro Addon v1.1.9
           - Newsletter v6.5.7
           - WP OAuth Server v3.7.92
           - Odin Admin Bar v1.0.0
           - Podlove Podcast Publisher v2.9.9
           - RDP Wiki Embed v1.2.16
           - Sensei Certificates v2.0.0
           - Sensei LMS Course Progress v2.0.2
           - Sensei LMS v2.4.0
           - Sensei Media Attachments v2.0.0
           - Wordfence Security v7.4.6
           - Yoast SEO v13.3
           - Magic Embeds v3.0.8
           - WP Mail SMTP Plugin by Mail Bank v4.0.10
           - WPFront User Role Editor Personal Pro v2.14.3
           - Embed Plus for YouTube - Gallery, Channel, Playlist, Live Stream v13.2.3
WordPress Database Charset utf8mb4
WordPress Database Collate 
Publisher Version          2.9.9
Web Player Version         player_v4
Twig Version               1.42.2
open_basedir               ok
curl Version               7.62.0
iconv                      available
simplexml                  ok
max_execution_time         6000
upload_max_filesize        128M
memory_limit               768M
disable_classes            
disable_functions          
permalinks                 ok (/%year%/%monthnum%/%day%/%postname%/)
podlove_permalinks         ok
podcast_settings           ok
web_player                 ok
podlove_cache              on
assets                     
  - mp3    audio/mpeg       REDACTED
cron                       ok
duplicate_guids            ok

0 errors
0 notices
Nice, Everything looks fine!

**Comment by OdinWynd** [comment]
Uninstalling for security.

**Comment by OdinWynd** [comment]
Deactivating does clear this up. if this issue is resolved I will continue using PodLove. It is great software, but it is literally corrupting "Recent Posts" when you click on a "Category"

I will get output like..

Recent Posts:
Real Post works
(no title) - goes to 404
Imported event from Facebook - goes to 404
(no title) - goes to 404
Changed oAuth key - !!!!!Security flaw and a 404 on the link

I have read on your support community that this has been an issue since 2018 and has not been addressed.

**Comment by OdinWynd** [comment]
I have gotten word from a support topic on the wordpress site that this behavior is caused due to not refreshing the queue after a custom loop...

https://developer.wordpress.org/reference/functions/wp_reset_query/#more-information

**Comment by eteubert** [comment]
Yes, unfortunately a known problem without a real solution (see #1017) but there is a workaround: put this constant definition in your `wp-config.php` above `/* That's all, stop editing! Happy blogging. */`:

```php
define('PODLOVE_DISABLE_TAG_AND_CATEGORY_SEARCH', true);
```

**Comment by OdinWynd** [comment]
so the wp_reset_query would not fix this bug?

And thanks for the workaround.

**Comment by eteubert** [comment]
> so the wp_reset_query would not fix this bug?

No, because there is no custom loop.
