### ISSUE TITLE
Podigee Webplayer not working after 2.10.0 update

### ISSUE THREAD

**Issue by douglaskastle** [podlove/podlove-publisher#1108]
### Expected behavior
The embedded webplayer stopped working for me after 2.10.0 update

### Actual behavior
I was using the podigee player.  Installing and switching to webplayer 5.0 get a embedded player back

### System information (see `Podlove > Support` menu)
`[podlove-web-player publisher=“5919”]`

**Comment by vahost** [comment]
Same thing here.

**Comment by eteubert** [comment]
Can you be more specific? You were running Podigee Player and that stopped working after updating to 2.10.0? What exactly happened / how does "stopped working" look like? 

Related forum thread: https://community.podlove.org/t/podlove-web-player-not-displaying/2150

**Comment by douglaskastle** [comment]
As described, instead of the player all that is printed to the page is

[podlove-web-player publisher=“5919”]

Instead

**Comment by douglaskastle** [comment]
Here is an example of a website that was working before update, but is now failing after

https://grinncomedy.com/one-liner-comedians/

![image](https://user-images.githubusercontent.com/79840/80544117-37173400-89a8-11ea-84c6-0d5f9db17d1f.png)

```
Website                    https://grinncomedy.com
PHP Version                7.2.30
WordPress Version          5.4
WordPress Theme            Uptempo v1.19.7
Active Plugins             
           - Akismet Anti-Spam v4.1.4
           - Total Upkeep v1.13.3
           - BoldGrid Easy SEO v1.6.5
           - BoldGrid Gallery v1.5
           - BoldGrid Inspirations v2.3.1
           - DreamHost Panel Login v1.0.0
           - iTunes Podcast Review Manager v3.7
           - Jetpack by WordPress.com v8.4.2
           - Podlove Podcast Publisher v2.10.0
           - Post and Page Builder Premium v1.0.4
           - Post and Page Builder v1.13.0
           - WP Super Cache v1.7.1
           - WPForms Lite v1.6.0.1
WordPress Database Charset utf8
WordPress Database Collate 
Publisher Version          2.10.0
Web Player Version         podigee
Twig Version               1.42.2
open_basedir               ok
curl Version               7.58.0
iconv                      available
simplexml                  ok
max_execution_time         30
upload_max_filesize        64M
memory_limit               500M
disable_classes            
disable_functions          
permalinks                 ok (/%postname%/)
podlove_permalinks         ok
podcast_settings           Your podcast needs a title.
web_player                 ok
podlove_cache              on
assets                     
  - mp3    audio/mpeg       https://grinncomedy.com/feed/mp3/
cron                       ok
duplicate_guids            ok

1 ERROR: 
- Your podcast needs a title.
0 notices
```

**Comment by eteubert** [comment]
You should be using `[podlove-episode-web-player]`, not `[podlove-web-player]`. And the Podigee shortcode does not take parameters like a post id, so I'm not sure why it ever worked for you to be honest 🤔

**Comment by vahost** [comment]
I don't set a shortcode at all. I just use the "Insert At Top" setting in Publisher > Templates.

**Comment by douglaskastle** [comment]
Agreed, this is just an episode page for me, so no shortcodes are used here, what you see is the rendered result

**Comment by Daedalus3** [comment]
Same here.

**Comment by douglaskastle** [comment]
This appears to be fixed on the most recent update.

**Comment by eteubert** [comment]
Various web player issues were fixed since this was reported. Please open a new issue if something else occurs.
