### ISSUE TITLE
Dienste-Links sind zu kompliziert bzw. kaputt (Patreon)

### ISSUE THREAD

**Issue by gitlik** [podlove/podlove-publisher#1110]
### Expected behavior
Nur Usernamen angeben müssen, bei allen Diensten. https:// tippen ist soooo 2018.

### Actual behavior
Patreon Links scheinen kaputt. Ich weiß auch nie ob man den gesamten Link oder nur den User Namen angeben muss. Angenehmer fände ich wenn man nicht überall https dazu tippen müsste ... Das System sollte sich doch mit dem User Namen begnügen können?
### System information (see `Podlove > Support` menu)
![image](https://user-images.githubusercontent.com/26041973/81508936-767a4480-9307-11ea-9c84-6041bcef3cbc.png)
![image](https://user-images.githubusercontent.com/26041973/81508938-7aa66200-9307-11ea-96ea-f1c7872d63b5.png)
![image](https://user-images.githubusercontent.com/26041973/81508941-7d08bc00-9307-11ea-9397-f8d574dcf68f.png)

**Comment by eteubert** [comment]
Sofern uns das URL-Schema bekannt ist, ist nur der Accountname einzutragen. Bei Patreon z.B. `malikfm`, dann funktioniert auch der Link.

**Comment by gitlik** [comment]
Ja, aber das ist inkonsequent (mal ja, mal nein) und man weiß es nicht vorher. Und https:// kann man doch bei jedem Link sowieso annehmen, wieso muss man das umständlich von Hand tippen? Ich finde, das könnte der Computer für einen übernehmen.

**Comment by eteubert** [comment]
Du musst ja eben nicht https tippen. Es ist genau so wie du es dir wünschst?
