### ISSUE TITLE
Template using episode player does not work anymore with version 2.11.1 

### ISSUE THREAD

**Issue by aheil** [podlove/podlove-publisher#1114]
### Expected behavior
Web player with latest episode should be shown when using a template 

```[podlove-template id="latest-episode"]```

with the follwing template code: 
```
{% for episode in podcast.episodes({ orderby: "publicationDate", order: "DESC", limit: 1 }) %}
    {{ episode.player }}
{% endfor %}
```

This seem to be a breaking change.

Deleting caches, rapair etc. has ben performed. 

### Actual behavior
`Nothin is shown anymore, however this worked until the update to version 2.11.1.

### System information (see `Podlove > Support` menu)
Website                    https://podcast.hack-the-planet.tv
PHP Version                7.2.13
WordPress Version          5.4.1
WordPress Theme            Twenty Thirteen v2.9
Active Plugins             
           - Advanced Cron Manager v2.3.10
           - Podlove Podcast Publisher v2.11.1
WordPress Database Charset utf8
WordPress Database Collate 
Publisher Version          2.11.1
Web Player Version         player_v4
Twig Version               1.42.2
open_basedir               ok
curl Version               7.52.1
iconv                      available
simplexml                  ok
max_execution_time         30
upload_max_filesize        64M
memory_limit               256M
disable_classes            
disable_functions          
permalinks                 ok (/%year%/%monthnum%/%day%/%postname%/)
podlove_permalinks         ok
podcast_settings           ok
web_player                 ok
podlove_cache              on
assets                     
  - mp3    audio/mpeg       https://podcast.hack-the-planet.tv/feed/mp3/
  - m4a    audio/mp4        https://podcast.hack-the-planet.tv/feed/m4a/
  - png    image/png        no feed
  - psc    application/xml  no feed
  - srt    application/x-subripno feed
  - mp4    video/mp4        https://podcast.hack-the-planet.tv/feed/mp4/
cron                       ALTERNATE_WP_CRON active
duplicate_guids            ok

0 errors
1 HINWEIS (no dealbreaker, but should be fixed if possible): 
- ALTERNATE_WP_CRON is active. This may sometimes cause failing downloads.

**Comment by aheil** [comment]
Installing Podlove Web Player 5 and setting it as default fixed the issue.

**Comment by eteubert** [comment]
Thanks for the update. I will look into it as it should still work with version 4 as well.

**Comment by vasilisvg** [comment]
Same issue here. Player 3 stopped working.

**Comment by eteubert** [comment]
Closing, as PWP3 support was dropped and PWP4 deprecated in Release 3.0.
