### ISSUE TITLE
E_COMPILE_ERROR

### ISSUE THREAD

**Issue by tine-schreibt** [podlove/podlove-publisher#1115]
### Expected behavior
Load, not crash my website.

### Actual behavior
Doesn't load, crashes my website. In recovery mode, I'm presented with this: 

An error of type E_COMPILE_ERROR was caused by line 7 of the file  /usr/www/users/softyc/etc.net/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/lib/modules/logging/wpdbhandler.php. 
Error message: Declaration of Podlove\Modules\Logging\WPDBHandler::write(array $record) must be compatible with Monolog\Handler\AbstractProcessingHandler::write(array $record): void

### System information (see `Podlove > Support` menu)
Since the plugin must be deactivated for me to even be able to load the backend, I can't access this menu and the info contained within. I'm running Wordpress 5.4.1., though, and the plugin is version 2.11.1.

**Comment by eteubert** [comment]
Hi, can you give me a list of your installed plugins? I suspect another plugin is using the same Logging library and the versions are incompatible. Then I can have a look at it.

**Comment by tine-schreibt** [comment]
Oh hi :)
I'm using:
Akismet 4.1.5 by Automattic
Classic editor 1.5 by WordPress-Mitwirkende
Name Directory 1.6 by Jeroen Peters
PHP Compatibility Checker 1.5.0 by WP Engine
Podlove Podcast Publisher 2.11.1 by Podlove
Podlove Subscribe Button 1.3.7 by Podlove
Podlove Web Player 5.2.1 by Podlove
SmartCrawl 2.6.1 by WPMU DEV
UpdraftPlus 1.16.25 by UpdraftPlus.com
Wordfence Security 7.4.7 by Wordfence
WP Meta SEo 4.2.5. by JoomUnited 
WE-Optimize 3.1.0 by David Anderson et al

**Comment by tine-schreibt** [comment]
You gave me the idea to just do a trial and I found out that it's the WP-Optimize Plugin which causes the error. 
Might you find a way to fix this? I don't need to have this plugin active all the time, but it is really useful sometimes...

**Comment by tine-schreibt** [comment]
I guess I should just contact the developers of WP-Optimize and inform them, although I don't know if it's a Podlove or a WP-Optimize update that brought this about. 
It was all working fine yesterday and I haven't updated anything since then.

**Comment by tine-schreibt** [comment]
Ok, so I just went to look at when both plugins were last updated because I swear there wasn't any updating happening yesterday. But there was; WP-Optimize. Still I was able to access the page after I installed it yesterday. It's really weird. 
There also was another update today, which didn't fix the issue, though. 

Is this info of any interest, since I found a workaround for now? Or am I just rambling here?

**Comment by eteubert** [comment]
Yep it's WP-Optimize :)

I just released a fix with v 2.11.2, should be available any minute. Please check if upgrading solves it for you.

To give it some more background, neither WP-Optimize nor Publisher do something wrong, it's just that we use a common library with different versions and that clashed now because they use a higher version than Publisher. I can't upgrade though because that would increase the minimum PHP requirement for Podlove Publisher from 5.4 to 7.2, which would break even more installs, so I could only implement a workaround by disabling logging in Publisher if there is a version conflict.

**Comment by tine-schreibt** [comment]
Oh cool! Yes, that fixed the issue. Thanks so much, and thanks for explaining :) 
Have a great rest of the week!

**Comment by tine-schreibt** [comment]
Achso, und dann mach ich hier mal dicht.
