### ISSUE TITLE
Using array_key_exists() on objects is deprecated.

### ISSUE THREAD

**Issue by circuscode** [podlove/podlove-publisher#1138]
On episode posts 45 PHP errors are thrown caused by the podlove plugin. All of them refers to commands, which are depreciated. Maybe this only happens if you are using the twig templates. Please see screenshot enclosed for more details. I am using PHP 7.4. Impact on functionality there is none.

<img width="1280" alt="2020-08-24_19-51-40" src="https://user-images.githubusercontent.com/20133480/91078710-4ef38180-e643-11ea-9e34-aa92ee4b4f44.png">

**Comment by eteubert** [comment]
This warning is thrown in a third party library, Twig. It's already updated on the Beta branch which I can hopefully release soon as 3.0, which should solve the warnings.
