### ISSUE TITLE
The Podlove player no longer loads on my webpage (since the 3rd of September)

### ISSUE THREAD

**Issue by DJDennis** [podlove/podlove-publisher#1146]
### Expected behavior
A player visible  and usable at https://djdennis.net/index.php/2020/03/26/hv175-music-is-life/
### Actual behavior
only [podlove-episode-web-player publisher="2203" post_id="2203"] visible and not usable on same episode. This is the same for all my Podlove Episodes.
### System information (see `Podlove > Support` menu)
Website                    https://djdennis.net
PHP Version                7.2.33
WordPress Version          5.5.1
WordPress Theme            Music v10.0.0
Active Plugins             
           - Akismet Anti-Spam v4.1.6
           - All In One WP Security v4.4.4
           - Blog2Social: Social Media Auto Post & Scheduler v6.4.2
           - Force HTTPS v1.2.0
           - Health Check & Troubleshooting v1.4.5
           - CAOS v3.7.7
           - Image Widget v4.4.7
           - MC4WP: Mailchimp for WordPress v4.8.1
           - Mashshare - Google Analytics Integration v1.0.9
           - Mashshare - Social Networks Add-On v2.5.0
           - Mashshare - Responsive Add-On v2.0.7
           - Mashshare - Sharebar Add-On v1.4.9
           - Mashshare Share Buttons v3.7.7
           - MaxButtons v8.2
           - WP Health (Formerly My WP Health Check) v1.8.14
           - PixelYourSite v7.1.13
           - Podlove Podcast Publisher v3.0.4
           - Really Simple SSL v3.3.5
           - Slider Revolution v6.2.23
           - Wordpress Share Buttons v1.11
           - SSL Insecure Content Fixer v2.7.2
           - Temporary Login Without Password v1.6.4
           - UpdraftPlus - Backup/Restore v2.16.29.24
           - GDPR Cookie Consent v2.3.0
           - Weglot Translate v3.1.9
           - Google Reviews Widget v1.8.8
           - Yoast SEO Premium v14.9
           - Asset CleanUp: Page Speed Booster v1.3.6.9
           - WP Fastest Cache Premium v1.5.9
           - WP Fastest Cache v0.9.1.0
           - WP-ServerInfo v1.66
           - Smush v3.7.0
           - WPForms Lite v1.6.2.3
           - Yoast SEO: Local v13.5
           - Yoast SEO: Search index purge v1.1.0
WordPress Database Charset utf8
WordPress Database Collate 
Publisher Version          3.0.4
Web Player Version         player_v2
Twig Version               2.12.5
Monolog Version            1
open_basedir               ok
curl Version               7.72.0
iconv                      available
simplexml                  ok
max_execution_time         30
upload_max_filesize        256M
memory_limit               256M
disable_classes            
disable_functions          
permalinks                 ok (/index.php/%year%/%monthnum%/%day%/%postname%/)
podlove_permalinks         ok
podcast_settings           ok
web_player                 ok
podlove_cache              on
assets                     
  - mp3    audio/mpeg       https://djdennis.net/index.php/feed/mp3/
  - ogg    audio/ogg        no feed
cron                       ok
duplicate_guids            ok

0 errors
0 notices
Nice, Everything looks fine!

**Comment by eteubert** [comment]
You still have Podlove Web Player 2 selected, which is not available any more. Please go to "Podcast Settings > Web Player" and select a different web player.

TODO for me:

- [ ] show warning / upgrade notice if a player is selected that does not exist

**Comment by DJDennis** [comment]
Thank you for your help. That solved my problem. Podigee Podcast Player seems to work fine. Kind regards, DJDennis.net

 

De : Eric Teubert <notifications@github.com>
Répondre à : podlove/podlove-publisher <reply@reply.github.com>
Date : jeudi 17 septembre 2020 à 15:24
À : podlove/podlove-publisher <podlove-publisher@noreply.github.com>
Cc : DJDennis <DennisD@orange.fr>, Author <author@noreply.github.com>
Objet : Re: [podlove/podlove-publisher] The Podlove player no longer loads on my webpage (since the 3rd of September) (#1146)

 

You still have Podlove Web Player 2 selected, which is not available any more. Please go to "Podcast Settings > Web Player" and select a different web player.

TODO for me:
show warning / upgrade notice if a player is selected that does not exist
