### ISSUE TITLE
Permalinks setting not shown (and episode page empty)

### ISSUE THREAD

**Issue by pgerstbach** [podlove/podlove-publisher#1157]
On my installation the expert settings are not show correctly. 
Although permalink structure is disabled, the details how to set the permalinks are not shown:
![expert-settings](https://user-images.githubusercontent.com/10688467/94723318-d7f38c00-0358-11eb-97d7-9956e1c79f2f.png)

However, it is possible to enter the respective settings, when disabling the "display:none" css style:
![expert-settings-tweak](https://user-images.githubusercontent.com/10688467/94723518-2739bc80-0359-11eb-9206-72e56c7bd750.png)

Using this tweak it is possible to save and settings are used as it should be.

I don't know if this second problem is related, but the paginated episode page does not work as well.
The page is completely empty (but no 404).

Any ideas what might be the problem?
Permalinks (for blog & pages) are enabled and work as expected.

### System information 
To be fair, this is not a fresh installation and I did not use the importer because of #1143 
Instead I wrote a DB script and imported episodes from another installation. Maybe this script corrupted something or some vital data has not been set up. I tried "repair" - no change.

PHP Version                7.4.3
WordPress Version          5.5.1
WordPress Theme            JupiterX
Publisher Version          3.0.4
permalinks                 ok (/%year%/%monthnum%/%day%/%postname%/)
podlove_permalinks         ok
podcast_settings           ok
web_player                 ok
podlove_cache              on
assets                     
  - mp3    audio/mpeg       URL...
  - m4a    audio/mp4        URL...
cron                       ok
duplicate_guids            ok

0 errors
0 notices
Nice, Everything looks fine!

**Comment by eteubert** [comment]
Becoming irrelevant as these features will be removed due to #1038, see also: https://github.com/podlove/podlove-publisher/blob/c5e0a4a7c676fb65696f9a4339e2a8c657e05824/readme.txt#L111-L130
