### ISSUE TITLE
Supporting podcastindex.org namespaces

### ISSUE THREAD

**Issue by benhartwich** [podlove/podlove-publisher#1166]
Podcastindex.org tries to implement generic rules for namespaces, e.g. transcripts etc. Perhaps it would be good supporting these namespaces for the podlove feeds:
https://github.com/Podcastindex-org/podcast-namespace

**Comment by eteubert** [comment]
Closing because the issue is too generic to be useful / impossible to "finish". But yes, I'll keep working on supporting podcastindex.org specs :)
