### ISSUE TITLE
Template: descending order doesn't work for seasons

### ISSUE THREAD

**Issue by tomtjes** [podlove/podlove-publisher#1169]
### Expected behavior

```
{% for season in podcast.seasons({order: 'DESC'}) %}
<p>{{season.number}}</p>
{% endfor %}
```

should result in
3
2
1

### Actual behavior

code results in
1
2
3

(note: the documentation is inconsistent about whether the parameter name should be in quotes)

### System information (see `Podlove > Support` menu)

PHP Version                7.4.11
WordPress Version          5.5.3
Active Plugins             
           - Cookie Notice v1.3.2
           - Enable jQuery Migrate Helper v1.1.0
           - Font Awesome v4.0.0-rc20
           - Podlove Podcast Publisher v3.1.0
           - Podlove Web Player v5.3.0
           - WebP Converter for Media v1.5.0
WordPress Database Charset utf8mb4
WordPress Database Collate 
Publisher Version          3.1.0
Web Player Version         player_v5
Twig Version               2.12.5
Monolog Version            1
open_basedir               ok
curl Version               7.71.0
iconv                      available
simplexml                  ok
max_execution_time         180
upload_max_filesize        1G
memory_limit               2G
disable_classes            
disable_functions          
permalinks                 ok (/%year%/%monthnum%/%day%/%postname%/)
podlove_permalinks         ok
podcast_settings           ok
web_player                 ok
podlove_cache              on
cron                       ok
duplicate_guids            ok
twig_versions              ok

0 errors
0 notices
Nice, Everything looks fine!

**Comment by eteubert** [comment]
fixed in fc6701103169
