### ISSUE TITLE
RSS generation error when using non-ansi characters in filenames [REGRESSION,BREAKING]

### ISSUE THREAD

**Issue by gpapp** [podlove/podlove-publisher#1179]
Great plugin, really the best! I appreciate it and would love to contribute. Unfortunately I can barely find the time to use it. :(

When using a fajlname that contains non-latin-1 characters e.g. á,é,ő,ö,ü,ó,í (I just love Hungarian) the urls are encoded wrong in the iTunes links (and ONLY there, the RSS feed uses proper URL encoding otherwise)
Podcast images, episode image references are encoded using html encoding and not URL encoding way.

Steps to reproduce:
Refer the link as your podcast image: "https://felho.itworks.hu/podcast/zártosztály.jpeg" or upload an image to your episode and set it as episode image.

### Expected behavior
RSS feed should contain: 
`<image><url>https://felho.itworks.hu/podcast/z&#xE1;rtoszt&#xE1;ly-lowres.jpg</url><title>Z&#xE1;rtoszt&#xE1;ly</title><link>https://podcast.itworks.hu</link></image>`
...
	`<itunes:image` href="https://felho.itworks.hu/podcast/z%C3%A1rtoszt%C3%A1ly.jpeg"/>

### Actual behavior
RSS feed contains:
`<image><url>https://felho.itworks.hu/podcast/z&#xE1;rtoszt&#xE1;ly-lowres.jpg</url><title>Z&#xE1;rtoszt&#xE1;ly</title><link>https://podcast.itworks.hu</link></image>`
...
	`<itunes:image` href="https://felho.itworks.hu/podcast/z&aacute;rtoszt&aacute;ly-lowres.jpg"/>

### System information (see `Podlove > Support` menu)
Website                    https://podcast.itworks.hu
PHP Version                7.4.9
WordPress Version          5.5.3
WordPress Theme            myPortfolio v1.0.6
Active Plugins             
           - Akismet Anti-Spam v4.1.7
           - Download Free Images v1.4.0
           - Site Kit by Google v1.21.0
           - Hummingbird v2.7.0
           - Jetpack by WordPress.com v9.1
           - Limit Login Attempts Reloaded v2.16.0
           - Podlove Podcast Publisher v3.2.0
           - Podlove Web Player v5.4.3
           - NextScripts: Social Networks Auto-Poster v4.3.19
           - Smush Nonstop v2.0.0
           - Pexels: Free Stock Photos v1.2.2
           - Smush v3.7.3
WordPress Database Charset utf8
WordPress Database Collate 
Publisher Version          3.2.0
Web Player Version         player_v5
Monolog Version            1
open_basedir               ok
curl Version               7.68.0
iconv                      available
simplexml                  ok
max_execution_time         600
upload_max_filesize        64M
memory_limit               256M
disable_classes            
disable_functions          pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wifcontinued,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_get_handler,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,pcntl_async_signals,pcntl_unshare,
permalinks                 ok (/%postname%/)
podlove_permalinks         ok
podcast_settings           ok
web_player                 ok
podlove_cache              on
assets                     
  - mp3    audio/mpeg       https://podcast.itworks.hu/feed/mp3/
  - ogg    audio/ogg        https://podcast.itworks.hu/feed/ogg/
  - chapters.txttext/plain       https://podcast.itworks.hu/feed/chapters/
cron                       ok
duplicate_guids            ok

0 errors
0 notices
Nice, Everything looks fine!

**Comment by gpapp** [comment]
Relates to the fix for #1176

**Comment by gpapp** [comment]
Found the issue, provided the proposed fix.

**Comment by eteubert** [comment]
Possible solution: #1181
