### ISSUE TITLE
CORS Header missconfiguration for API ressources

### ISSUE THREAD

**Issue by benhartwich** [podlove/podlove-publisher#1184]
It seems that podlove is setting CORS header to some URLs like episode assets, but at some not. E.g. the transcript URL (/?podlove_transcript=json) has no CORS header set, so it can´t be used for initialising the player at a foreign website. 

As I can set the CORS header generally at my nginx webserver there should be a possibility to disable any CORS header generation in podlove or an option to enable CORS header to all ressources.

**Comment by eteubert** [comment]
The Publisher only sets CORS headers for two specific requests: the config files for Podigee player and PWP4: https://github.com/search?q=Access-Control-Allow-Origin+repo%3Apodlove%2Fpodlove-publisher+extension%3Aphp&type=Code

I remember we discussed this on other channels. Did you find a solution for your issues? I don't think the Publisher is doing anything wrong here.

**Comment by benhartwich** [comment]
Thanks, I haven´t found any further problems / causes regarding CORS. I think, we can close.
