### ISSUE TITLE
Slack API change

### ISSUE THREAD

**Issue by mdornseif** [podlove/podlove-publisher#1191]
### Expected behavior
Shownotes are Pulled from Slack

### Actual behavior
Endless Spinner

### System information (see `Podlove > Support` menu)
New and current setup

See https://sendegate.de/t/slacknotes-debuggen/13189/2 - The current API used by the slacknotes Plugin will stop Working for all Apps in Feb 2021. For Apps created after Summer 2020 it already stopped working. The https://slack.com/api/conversations.history has to be used instead.

**Comment by mdornseif** [comment]
Unfortuanately I can not submit a PR right now. 

Line 129 has to be changed to:

    $api_url = 'https://slack.com/api/conversations.history';

Line 139 has to be changed to

          $api_args['limit'] = 1000;

Also the Bot has to be invited into the Channel. E.G. `\invite @Podlove Slack Notes `.

**Comment by eteubert** [comment]
Thank you for your research 🙏 

I'm going to have a closer look myself. And I assume https://docs.podlove.org/podlove-publisher/guides/slacknotes.html needs to be rewritten as well then.

**Comment by mdornseif** [comment]
I think the docs are correct except the invitation issue.
