### ISSUE TITLE
CSV-Export crash

### ISSUE THREAD

**Issue by pediehl** [podlove/podlove-publisher#1193]
when to export the statics to csv is not possible anymore. 

Die Website ist nicht erreichbar

when to export the statics to json is possible. It works still fine.

Podlove Podcast Publisher v3.3.1

Ein Fehler vom Typ E_ERROR wurde in der Zeile 57 der Datei /html/wordpress/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/includes/api/analytics.php verursacht. Fehlermeldung: Uncaught Error: Call to undefined method League\Csv\Writer::setEncodingFrom() in /html/wordpress/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/includes/api/analytics.php:57

**Comment by eteubert** [comment]
fixed in 1354c2ed9fa166ac47749c8f9db8ce54999ccf33

Will release this tomorrow I hope.
