### ISSUE TITLE
Detailed Show Analytics are showing all tags

### ISSUE THREAD

**Issue by marxphil** [podlove/podlove-publisher#1196]
### Expected behavior
Only the titles of the show are shown on the Analytics page.

### Actual behavior
We're using tags for the episodes for years now. With Podlove v3.4.0 all these tags are shown on the Analytics page.
![image](https://user-images.githubusercontent.com/43323989/109479645-e3b7bb80-7a7a-11eb-808c-386f41c0a7d2.png)
Based on the wide use of tags in the episodes, the list contains several hundrets of entries.

**Comment by eteubert** [comment]
Ohh I see the issue. Shows are a taxonomy and the data query works for _all_ taxonomies, not just shows. Fix coming very soon :)
