### ISSUE TITLE
Incompatibility with Matomo Analytics Plugin

### ISSUE THREAD

**Issue by bildstrich** [podlove/podlove-publisher#1206]
### Expected behavior
Fo the last year I used the podlove-publisher and the [Matomo Plugin](https://de.wordpress.org/plugins/matomo/) for Wordpress side by side without any Problems. The Matomo Dashboard (viewing reports and stats) and the publisher worked as expected.

<img width="1876" alt="Screenshot 2021-04-05 at 17 04 47" src="https://user-images.githubusercontent.com/7063600/113589984-58f64d80-9632-11eb-914a-3fb98352459a.png">

### Actual behavior
Suddenly the Matomo Plugin stopped working and the[ Error "Cache not supported" comes up.]

<img width="1139" alt="Screenshot 2021-04-05 at 17 00 42" src="https://user-images.githubusercontent.com/7063600/113590008-614e8880-9632-11eb-98b4-a45945925a87.png">

I don't know when the problems started exactly or which podlove version may cause the issue - I've tested all the plugins in my Wordpress installation and I could reproduce the issue with an other Wordpress instance too.
Turning off podlove cache has no impact.

**As soon as the Podlove Publisher Plugin is activated, the Matomo Plugin stops working.**

### System information (see `Podlove > Support` menu)
Website                    https://www.germanriot.de
PHP Version                7.3.27
WordPress Version          5.7
WordPress Theme            Enfold Child v1.0
Active Plugins             
           - Antispam Bee v2.9.4
           - Contact Form 7 v5.4
           - Email Encoder - Protect Email Addresses v2.1.0
           - Header Footer Code Manager v1.1.9
           - Matomo Analytics – Ethische Statistiken. Nachhaltige Erkenntnisse. v4.2.0
           - Podlove Podcast Publisher v3.4.1
           - Podlove Subscribe Button v1.3.7
           - Podlove Web Player v5.4.11
           - WooCommerce PayPal Checkout Gateway v2.1.1
           - WooCommerce Stripe-Gateway v5.0.0
           - WooCommerce Shipping & Tax v1.25.10
           - WooCommerce v5.1.0
           - WordPress Importer v0.7
           - Yoast SEO v16.0.2
           - WP Maintenance Mode v2.3.0
           - WP User Avatar v2.2.15
WordPress Database Charset utf8
WordPress Database Collate 
Publisher Version          3.4.1
Web Player Version         player_v5
Monolog Version            1
open_basedir               ok
curl Version               7.76.0
iconv                      available
simplexml                  ok
max_execution_time         90
upload_max_filesize        2048M
memory_limit               256M
disable_classes            
disable_functions          
permalinks                 ok (/%postname%/)
podlove_permalinks         ok
podcast_settings           ok
web_player                 ok
podlove_cache              on
assets                     
  - mp3    audio/mpeg       https://www.germanriot.de/feed/mp3/
cron                       ok
duplicate_guids            ok

0 errors
0 notices
Nice, Everything looks fine!

**Comment by eteubert** [comment]
Possibly we're having a composer dependency in common that creates the incompatibility.

- their repo: https://github.com/matomo-org/wp-matomo
- vendor directory: https://github.com/matomo-org/wp-matomo/tree/develop/app/vendor (not sure how this is installed / why this is versioned but I couldn't find the composer.json for this directory)
- might be geoip/maxmind/spyc

If that's the case then the fix is to vendor-prefix more dependencies using php-scoper like I've done with Twig.

**Comment by jbin** [comment]
Anything new here? The problem persists exactly as described above in my case.
Is there a workaround for the time being?

**Comment by jbin** [comment]
Seems (from my logs) like the podlove vendor/piwik/device-detector is causing the trouble, which makes sense, since matomo is the successor of piwik.

**Comment by devinjdawson** [comment]
I am also currently experiencing this, any update? Over a year since being reported.

**Comment by eteubert** [comment]
Haven't looked into it yet but I will. Pinned the issue just now so I'll remember.

**Comment by devinjdawson** [comment]
I very much appreciate it. Currently, this plugin seems to be disabling a few interactivity features between matomo and wordpress, aside from not being able to access the matomo dashboard from within wordpress. I notice the Matomo Analytics opt-out for GDPR compliance seems to be disabled when podlove is active. Technically, this is kind-of site breaking, but I'm not too worried as we don't have a lot of traction. That being said, we do have a shop and some other features which utilize analytics. and it would be best practice to make sure the site regains compliance as soon as possible.

**Comment by eteubert** [comment]
I applied the vendor prefix. It's now being tested in a beta release and I hope to make it public in the next patch release.

**Comment by fewie** [comment]
Hey, this issue still persists!

- PHP v7.4.20
- WordPress v6.1.1
- Matomo Analytics v4.13.3
- Podlove Podcast Publisher v3.8.4

is there any fix or workaround to get the cache working again?

**Comment by eteubert** [comment]
@fewie Until now this fix was only on the beta branch. But I just made a separate release 3.8.6 that includes this.
