### ISSUE TITLE
Wrongly formatted chapter marks for opus feeds

### ISSUE THREAD

**Issue by blaueente** [podlove/podlove-publisher#1221]
### Expected behavior
Interpret Minutes:Seconds as such
### Actual behavior
Interpret as Hours:Minutes:00
e.g. for https://wochendaemmerung.de/feed/opus/
See also:
https://github.com/AntennaPod/AntennaPod/issues/5105

Not sure which version of podlove publisher this is.
Seems to work with other, mp3 feeds.

![image](https://user-images.githubusercontent.com/10434139/118401807-6c4ffc00-b667-11eb-813d-57e7643951be.png)

**Comment by dnkbln** [comment]
Hello,

I try to analyze this issue. Actually the https://wochendaemmerung.de/feed/opus/ feed don't use podlove and chapters. I created an own opus feed and it works. 

Do you have another example for this issue?

**Comment by commi** [comment]
Just to clarify...if the chapters are not in the feed, the offending timestamps must be in the published opus-files themselves?

**Comment by blaueente** [comment]
Yes, the timestamps are in the opus-files.
Ok sorry, this is apparently a problem with podigee, I mixed it up.
