### ISSUE TITLE
Add ability for podcasters to set a title for each of their soundbites, otherwise leave the soundbite title field blank

### ISSUE THREAD

**Issue by mitchdowney** [podlove/podlove-publisher#1237]
It's very exciting to see Podlove adopting Podcasting 2.0 namespaces. We at Podverse are especially excited to see you now support the <podcast:soundbite> tag.

There are two parts to this feature request...

1) We'd like to suggest Podlove add the ability for podcasters to optionally set a title with their soundbites. If a podcaster provides a title for their soundbite, it gives more context and can lead to a better UX in podcast apps than soundbites without titles (just like setting titles for Chapters provides a better experience than Chapters without titles).

2) My understanding is that Podlove currently sets all soundbite titles to be the title of the episode. If a podcaster does _not_ provide a title for their soundbite, I think it would be preferable for Podlove to leave the soundbite title blank, as the fact it is blank signals to podcast apps that they should use a placeholder for the soundbite title. There are different UX implications for soundbites that podcasters set a title for, and soundbites that they do not set a title for, and having this empty field as a signal to use a placeholder is very helpful.

Related to 2) I just created [a related PR](https://github.com/Podcastindex-org/podcast-namespace/pull/295) for the Podcasting 2.0 namespace as I think the phrasing of the spec is unclear. The spec makes it sound like RSS publishers are supposed to set the title of a soundbite to the title of the episode, but I actually think the intention is for RSS publishers to leave the soundbite title blank, and then leave it up to podcast apps to use a placeholder such as the title of the episode for the title of the soundbite.

If Podlove decides to go forward with this Github issue, I would be willing to work on it and create a PR. Thank you so much for supporting Podcasting 2.0, and please let me know if you have any questions.

**Comment by eteubert** [comment]
I agree with both points and I'll be happy to accept a PR. Or maybe @dnkbln wants to chime in, he has implemented the current soundbite code.

For reference, here's the short Twitter thread explaining why the suggested behavior is preferable: https://twitter.com/Podverse/status/1438733476669317121

**Comment by dnkbln** [comment]
I think there are two different use cases. The first use case is to support automated audiogram generation (e.q headliner.app). This is the case we want to support with the implementation. The second case is the support of soundbites. This is currently not implemented. We can create only one podcast:soundbite item per episode.
I will check if the first use case still works when we remove the episode title. I will discuss with @eteubert if we can support the second use case.
