### ISSUE TITLE
Column generation fails, due to missing close bracket 

### ISSUE THREAD

**Issue by gpapp** [podlove/podlove-publisher#1239]
https://github.com/podlove/podlove-publisher/blob/40e6ec499c97cde34df908b38ccb202a69a8ea0e/lib/model/episode.php#L467

**Comment by gpapp** [comment]
Episode::property('soundbite_start', 'VARCHAR(255');

Episode::property('soundbite_start', 'VARCHAR(255)');

**Comment by eteubert** [comment]
Fixed with https://github.com/podlove/podlove-publisher/pull/1238
