### ISSUE TITLE
Non-available audio files should not be in eposides feed enclosure / Spotify panicking

### ISSUE THREAD

**Issue by marxphil** [podlove/podlove-publisher#1254]
### Expected behavior
If an audio file/asset file is not available, it should not be listed as an enclosure in the RSS feed.

### Actual behavior
A file, which is not available, is still listed as an enclosure file in the RSS feed.
This leads to irritiation of feed services, primarily Spotify: Spotify tries to access this file again and again, pushing the download stats to the limits.

See attached image for the impact.
![Download attempts rising dramatically after feed with non-existent episode files are provided to Spotify](https://user-images.githubusercontent.com/43323989/148024309-e5a72281-efad-4961-a85f-0e2cc6498032.png)

It would be an option to set affcted posts to drafts, but then all the contents/shownotes beside the episode aren't available.

**Comment by marxphil** [comment]
If someone has the same problem:
You can disable the attached media files, so it won't be handled as a missing file.

For single posts you can disable the checkbox for media files in the appropriate post.
![image](https://user-images.githubusercontent.com/43323989/148032401-73c24426-29a8-4877-be16-17529f5b596c.png)

If you have multiple episodes to edit, this is a massive work (in my case: >250 episodes)
The connection between WordPress Posts, Episodes in Podlove and their mediafiles is done in the SQL tables ``{wp_prefix}podlove_episode`` (connection Post ID <-> Episode ID) and ``{wp_prefix}podlove_episode`` (connection Episode ID <-> Media Files). If you delete the appropriate rows in ``{wp_prefix}podlove_episode``, the media files aren't enabled anymore.

My approach (SQL knowledge required; WP CLI required; backup first!)
Know what you do or leave it. I'm not responsible for any problems.

1. Find out the WordPress Post IDs of podcast episodes (WP CLI) and export them to CSV
``wp post list --post_type=podcast --format=csv``

2. Open CSV in Excel (or other program), use the slug to identify episodes with online files and delete the rows. The remaining rows are the episodes with offline files.

3. Copy the colum with the post IDs (first column) and join them into one line, separated by a comma (i did it with Visual Studio Code and [Multi Line Editing](https://code.visualstudio.com/docs/editor/codebasics#_multiple-selections-multicursor))

4. Start up your favourite SQL editing tool (phpmyadmin, adminer, ...), backup your table ``{wp_prefix}podlove_mediafile}`` and execute the following command (replace ``{wp_prefix}`` with your WordPress table prefix and ``{post_ids}`` with your IDs from step 3): ``DELETE FROM `{wp_prefix}podlove_mediafile` WHERE id IN (SELECT id FROM {wp_prefix}podlove_episode WHERE post_id IN({post_ids))``

As a result, all media files attached to episodes are now marked as not available and aren't listed as enclosure in the RSS feed anymore.

You can also cleanup your download stats in ``{wp_prefix}podlove_downloadintent`` with the following command: ``DELETE FROM {wp_prefix}podlove_downloadintent WHERE media_file_id NOT IN (SELECT id FROM {wp_prefix}podlove_mediafile)``.
Beware: This will delete ALL matching download intents. If the file was available at some time and was taken offline afterwards, you should fiddle around with the column ``accessed_at`` to narrow down the time frame.
Then regenerate the statistics in ``Podlove -> Tools``.

**Comment by eteubert** [comment]
> If an audio file/asset file is not available, it should not be listed as an enclosure in the RSS feed.

I'm going to disagree with you on this one. A file may be temporarily unavailable, then it should still remain in the feed.

Files should only disappear from the feed when the podcaster explicitly wants them to, and as you pointed  out, that's possible using the asset UI.

Thanks for sharing what you've learned to deal with your situation to others 👍
