### ISSUE TITLE
Download Attempt of non-existent media file is counted as download

### ISSUE THREAD

**Issue by marxphil** [podlove/podlove-publisher#1255]
### Expected behavior
If a media file is attached to an episode, but not available, this attempt should not be counted as download.

### Actual behavior
If a media file is attached to an episode, but not available, this attempt will be counted as an download attempt.
This leads to wrong statistics because some Feed Reader or Services like Spotify are trying to access the file regulary. Every attempt is then counted, even if there is no "real download".

**Comment by eteubert** [comment]
Unfortunately the Publisher does not know if the file is available at them moment of the request or not. Checking the availability of the file before each request is impractical.
