### ISSUE TITLE
Different feed versions (caching issue)

### ISSUE THREAD

**Issue by benhartwich** [podlove/podlove-publisher#1271]
It seems that every time a feed is requested, podlove delivers another version of this feed. I am using the show module. 
The field itunes_summary delivers at the one time the default fallback description from the show itself, another time the episode description. Can this be a podlove caching issue? 

### System information (see `Podlove > Support` menu)
`PHP Version                7.4.27
WordPress Version          5.9
WordPress Theme            Koji v2.0.9
Active Plugins             
           - ASAP v1.0
           - Bulk Media Register v1.25
           - Code Snippets v2.14.3
           - Admin Columns v4.4.5
           - Disable Comments v2.3.3
           - Disable Gutenberg v2.6
           - Notification v8.0.10
           - Podlove Podcast Publisher v3.7.2
           - Podlove Web Player v5.4.15
           - WPO365 | PROFILE PLUS v16.1
           - WPO365 | LOGIN v16.1
WordPress Database Charset utf8mb4
WordPress Database Collate 
Publisher Version          3.7.2
Publisher Database Version 153
Web Player Version         player_v5
Monolog Version            1
open_basedir               /srv/customers/xy/websites/audiocms:/usr/share/php:/tmp:/var/ngx_pagespeed_cache:/var/fastcgi-cache:/var/run
curl Version               7.74.0
iconv                      available
simplexml                  ok
max_execution_time         300
upload_max_filesize        256M
memory_limit               512M
disable_classes            
disable_functions          dl,passthru,shell_exec,system,proc_open,popen,parse_ini_file,show_source
permalinks                 ok (/%year%/%monthnum%/%day%/%postname%/)
podlove_permalinks         ok
podcast_settings           ok
web_player                 ok
podlove_cache              on
assets                     
  - mp3    audio/mpeg       https://xy.at/feed/mp3/
  - m4a    audio/mp4        https://xy.at/feed/mobile/
  - vtt    text/vtt         no feed
cron                       ok
duplicate_guids            ok
multisite                  ok

0 errors
1 HINWEIS (no dealbreaker, but should be fixed if possible): 
- The PHP setting "open_basedir" is not empty. This is incompatible with curl, a library required by Podlove Publisher. We have a workaround in place but it is preferred to fix the issue. Please ask your hoster to unset "open_basedir".`

**Comment by eteubert** [comment]
fixed with fb43d40244aaca092902a82c4231ddadd20f7af6
