### ISSUE TITLE
Monero Icon fehlt

### ISSUE THREAD

**Issue by hundehausen** [podlove/podlove-publisher#1281]
### Expected behavior

Monero Logo wird angezeigt

### Actual behavior

Monero Logo wird nicht angezeigt / wird nicht gefunden

### System information (see `Podlove > Support` menu)

Website                    https://moneromumble.de
PHP Version                7.4.28
WordPress Version          5.9
WordPress Theme            Twenty Twenty v1.9
Active Plugins             
           - Podlove Podcast Publisher v3.8.0
WordPress Database Charset utf8
WordPress Database Collate 
Publisher Version          3.8.0
Publisher Database Version 153
Web Player Version         player_v4
Monolog Version            1
open_basedir               ok
curl Version               7.81.0
iconv                      available
simplexml                  ok
max_execution_time         90
upload_max_filesize        2048M
memory_limit               512M
disable_classes            
disable_functions          
permalinks                 ok (/%postname%/)
podlove_permalinks         ok
podcast_settings           ok
web_player                 ok
podlove_cache              on
assets                     
  - mp3    audio/mpeg       https://moneromumble.de/feed/mp3/
  - m4a    audio/mp4        https://moneromumble.de/feed/mp4/
  - ogg    audio/ogg        https://moneromumble.de/feed/ogg/
  - opus   audio/ogg;codecs=opushttps://moneromumble.de/feed/opus/
cron                       ok
duplicate_guids            ok

0 errors
0 notices
Nice, Everything looks fine!

![Screenshot 2022-02-20 at 20-46-28 MoneroMumble – MoneroMumble – Der erste deutsche Monero Podcast](https://user-images.githubusercontent.com/25672277/154862444-9d87948e-f064-42f3-aeeb-cb2fee7352fd.png)

**Comment by dnkbln** [comment]
Hallo,
das Bild ist nicht verfügbar. Das Bild soll eigentlich hier liegen
https://moneromumble.de/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/lib/modules/social/images/icons/monero.png
Das Github Icon ist z.B. verfügbar
https://moneromumble.de/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/lib/modules/social/images/icons/github.png

Es gibt z.Zt eine Möglichkeiten das Problem zu lösen.
1. Das Icon im Ordner https://moneromumble.de/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/lib/modules/social/images/icons ablegen 

Feature-Request:
Hinzufügen von Social Services ermöglichen (per Rest-API und UI)

**Comment by eteubert** [comment]
Zum Verständnis, das hier ist ein Feature Request, Monero oder generell generische Services definieren zu können?

Denn Monero ist als Service gar nicht definiert, also kann auch das Icon nicht "fehlen" 🤔

**Comment by dnkbln** [comment]
Es gab eine Diskussion im Sendegate, wie zuzsätzliche Services hinzugefügt werden können. https://sendegate.de/t/custom-sites-bei-mitwirkende/14967 und für diesen erzeugten Eintrag fehlt das Icon. Darauf zielte mein Hinweis. 
Aber generell ist es ein Feature Request, deshalb hatte ich den Eintrag gepinnt.

**Comment by eteubert** [comment]
Verstehe, dann schließe ich hier mal. Ob wir grundsätzlich ermöglichen wollen, eigene Services hinzuzufügen, können wir an anderer Stelle diskutieren.
