### ISSUE TITLE
Show module: itunes summary wrong

### ISSUE THREAD

**Issue by benhartwich** [podlove/podlove-publisher#1298]
### Expected behavior
If an episode description is filled, it should also be used at itunes summary.

### Actual behavior
When the show module is activated the show description is used for the itunes summary.

**Comment by eteubert** [comment]
@benhartwich Not sure when we will publish the next release, but it's a simple one line change that you can do yourself if you don't want to wait, see: 7cbe9e8d09cdcfe720ec78f160dc1d14d70d584d

**Comment by benhartwich** [comment]
Thanks, worked!
