### ISSUE TITLE
API: include season number in episode

### ISSUE THREAD

**Issue by eteubert** [podlove/podlove-publisher#1309]
The episode endpoint must include the season number as a readonly attribute.

Code that calculates season number: https://github.com/podlove/podlove-publisher/blob/85946fdb1973ab3351b145317993e0cc2c05b34b/lib/modules/seasons/model/season.php#L18-L21

- when no season is found, is should be null (but not integer `0`)
- when a season is found, it should be an integer value

**Comment by dnkbln** [comment]
I create a PullRequest to solve this issue (#1310)
