### ISSUE TITLE
Add more metadata support in episodeSaga

### ISSUE THREAD

**Issue by eteubert** [podlove/podlove-publisher#1328]
To import all fields from an Auphonic Production, I need _write_ support of the following fields:

## Important / Blocker

- [x] **duration** (and a definition of the transport format, is it ms? npt? Timestamp?)
- [x] **slug**

## Low Priority

- [ ] **license** and **license_url** (it's an expert setting enablind license settings per episode)
- [ ] **tags** (technically it's a post value but it's something we [are currently supporting](https://github.com/podlove/podlove-publisher/blob/66e4225b4d80ccb7363ddd8d1eeaebf72b695e8c/lib/modules/auphonic/admin.js#L193))

**Comment by alexander-heimbuch** [comment]
* `duration` is already part of the episode store and persisted as the iso timestamp (npt not possible since it has to be serializable)
* `slug` is currently not exposed in the v2 API (as well as license and tags)

**Comment by dnkbln** [comment]
- slug isn't documented but it is contained in the v2 API

**Comment by eteubert** [comment]
@alexander-heimbuch right, duration just works, not sure what confused me last time I checked 

@dnkbln only thing missing was that the slug wasn't returned in `get_item` but I just added it

**Comment by dnkbln** [comment]
Rest API added low priority item with PullRequest #1345
