### ISSUE TITLE
More Translation support in Vue components

### ISSUE THREAD

**Issue by eteubert** [podlove/podlove-publisher#1337]
Just the `__` helper is not enough.

Example:

```
<em>{{ entry.title }}</em> in the Auphonic Production is:
```

I think it should be `{{ sprintf( __('<em>%1s</em> in the Auphonic Production is:'), entry.title ) }}` but I can't get it to work. And then we need to allow html rendering, otherwise we get escaped html (but we also need to ensure we can't get XSS through translations?)

For what it's worth, my attempt in extending the translations module was this: 

```ts
const translate = get(window, ['wp', 'i18n', '__'], (translation: string) => translation)
const sprintf = get(window, ['wp', 'i18n', 'sprintf'], (translation: string) => translation)

export default {
  install(app: App, options: { domain: string }) {
    app.config.globalProperties['__'] = (translation: string, domain?: string) =>
      translate(translation, domain || options.domain)
    app.config.globalProperties['sprintf'] = (translation: string, ...args: string) =>
      sprintf(translation, ...args)
  },
}
```

Example usage in WP core: https://github.com/WordPress/wordpress-develop/blob/2648a5f984b8abf06872151898e3a61d3458a628/src/js/_enqueues/wp/password-strength-meter.js#L64-L70

**Comment by alexander-heimbuch** [comment]
This is related to the Vue XSS protection since dynamic generated html could lead to security issues. If it is absolutely required you can use the `v-html` directive to achieve this.
