### ISSUE TITLE
Convert Related Episodes Section

### ISSUE THREAD

**Issue by Fischaela** [podlove/podlove-publisher#1340]

**Comment by dnkbln** [comment]
Ich habe eine erste Version des neuen "Related Episodes UI" erstellt. 

Branch: feat/related-ui

Offene Punkte;
- Suche in der Listbox durch Texteingabe
- Darstellung als Tags mit der Möglichkeit den EIntrag zu löschen

**Comment by dnkbln** [comment]
Done with PR #1365
