### ISSUE TITLE
Cannot set multiple categories of the iTunes directory for the feed

### ISSUE THREAD

**Issue by gpapp** [podlove/podlove-publisher#1357]
### Expected behavior
iTunes allows multiple categories, which already has place in the DB model.

I expect to have 3 selection options on the Directory tab to be able to set up the 3 categories 

### Actual behavior
Only a single category is available, category_2 or 3 cannot be set in the config or show up in the feed

**Comment by eteubert** [comment]
A while ago Apple dropped support for multiple categories, that's why we adjusted the user interface accordingly. The database model has not been cleaned up yet.

See https://help.apple.com/itc/podcasts_connect/#/itcb54353390

> Although you can specify more than one category and subcategory in your RSS feed, Apple Podcasts only recognizes the first category and subcategory.

**Comment by gpapp** [comment]
ITunes currently uses the two level category selection, but multiple selection is honored by several podcast directories (podcast.hu, Listennotes.com that I care about)

**Comment by eteubert** [comment]
Changed my mind, it's in the beta now. Thanks!
