### ISSUE TITLE
Post did not find mp3 file when Tracking URL Parameters & Analytics in on.

### ISSUE THREAD

**Issue by robertknotek** [podlove/podlove-publisher#1366]
### Expected behavior

Tracking URL Parameters & Analytics in on.
Find mp3 file

### Actual behavior

Tracking URL Parameters & Analytics in on.
Post did not find mp3 file

### System information (see `Podlove > Support` menu)

Website                    https://www.patientinnenportal.at
PHP Version                8.1.16
WordPress Version          6.1.1
WordPress Theme            Weaver Xtreme v5.0.7
Active Plugins             
           - JCH Optimize Pro vpro-3.2.3
           - Akismet Anti-Spam v5.0.2
           - All-in-One Security and Firewall Premium v1.0.1
           - All In One WP Security v5.1.5
           - Annual Archive v1.6.0
           - Button Generator v2.3.4
           - Classic Editor v1.6.2
           - Disable XML-RPC Pingback v1.2.2
           - EWWW Image Optimizer v6.9.3
           - Site Kit by Google v1.95.0
           - GTranslate v2.9.15
           - Health Check & Troubleshooting v1.5.1
           - HTML Editor Syntax Highlighter v2.4.4
           - Improved Include Page v1.2
           - Lightweight Grid Columns v1.0
           - Podlove Podcast Publisher v3.8.5
           - Podlove Subscribe Button v1.3.10
           - Podlove Web Player v5.7.1
           - Post Snippets (free) v4.0.2
           - Relevanssi v4.18.3
           - Optimize Database after Deleting Revisions v5.0.110
           - SF Admin Bar Tools v4.0
           - Weaver Show Posts v1.6
           - Temporary Login Without Password v1.8.1.1
           - Advanced Editor Tools (previously TinyMCE Advanced) v5.6.0
           - UpdraftPlus - Backup/Restore v2.22.25.26
           - Weaver Xtreme Plus v4.0
           - Weaver Xtreme Theme Support v6.2
           - Yoast SEO Premium v20.2.1
           - Yoast SEO v20.2.1
           - Nested Pages v3.2.3
           - WP-Matomo Integration v1.0.27
           - WP Revisions Control v1.4.3
           - Yoast SEO: Video v14.6
           - Embed Plus YouTube WordPress Plugin Pro v14.1.4.1
           - ZI Hide Featured Image v1.0.0
WordPress Database Charset utf8mb4
WordPress Database Collate 
Publisher Version          3.8.5
Publisher Database Version 153
Web Player Version         player_v5
Monolog Version            1
open_basedir               /home/.sites/144/site580/web:/home/.sites/144/site580/tmp:/usr/share/pear:/usr/bin/php_safemode
curl Version               7.61.1
iconv                      available
simplexml                  ok
max_execution_time         150
upload_max_filesize        120M
memory_limit               320M
disable_classes            
disable_functions          
permalinks                 ok (/%year%/%monthnum%/%postname%/)
podlove_permalinks         ok
podcast_settings           ok
web_player                 ok
podlove_cache              on
assets                     
  - mp3    audio/mpeg       https://www.patientinnenportal.at/feed/mp3/
  - mp4    video/mp4        https://www.patientinnenportal.at/feed/mp4/
cron                       ok
duplicate_guids            ok

0 errors
1 NOTICE (no dealbreaker, but should be fixed if possible): 
- The PHP setting "open_basedir" is not empty. This is incompatible with curl, a library required by Podlove Publisher. We have a workaround in place but it is preferred to fix the issue. Please ask your hoster to unset "open_basedir".

**Comment by eteubert** [comment]
It looks like  you found a fix, I looked into your feed and it has working tracking URLs.
