### ISSUE TITLE
Possible bug in get_the_excerpt filter

### ISSUE THREAD

**Issue by retrorism** [podlove/podlove-publisher#1372]
Hi everyone! First of all: thank you for creating this plugin, we rely on it on one of our largest projects and it's been great to have this solution available.
We stumbled upon a bug on this project, which we traced back to a hook definition found in this plugin:

### Expected behavior
When rendering an excerpt for a post, I would think that there should be no filters that interfere with the retrieval of the post's excerpt.
To ensure that this is the case, all filters that hook into `get_the_excerpt` need to use the hook's (optional) argument to pass the post object. Using the global `$post` object can cause side effects.

### Actual behavior
In the method definition below, the global `$post` is used to retrieve the post object: 
https://github.com/podlove/podlove-publisher/blob/4557a2db8f5b0c2a1d0273f5a82c7a625cfa601b/lib/podcast_post_type.php#L132-L144

Instead, it should source the object from the `$post` parameter. In this method, the hook argument is called `$excerpt`. This is probably because you would expect that a filter takes in the excerpt string to return the filtered excerpt (I would make the same assumption).
I'm not sure if simply switching away from the global $post object would have unexpected side effects for others, though! One way to ensure backwards compatibility would be to compare the global post object with the one passed, and if they are different posts, favour the one passed as an argument -- or do nothing.

### System information (see `Podlove > Support` menu)
```
Not relevant

**Comment by retrorism** [comment]
Thanks Eric! @avovkdesign and I were able to find a workaround in the interim, but with this merged, we can soon update and get rid of that workaround. 
Funny question perhaps: do you happen to know a Ruodger (Roddi)?

**Comment by eteubert** [comment]
I talked to him a couple times, not sure if that counts as “knowing” him ;)On 28. Apr 2023, at 20:48, Willem Prins ***@***.***> wrote:﻿
Thanks Eric! @avovkdesign and I were able to find a workaround in the interim, but with this merged, we can soon update and get rid of that workaround.
Funny question perhaps: do you happen to know a Ruodger (Roddi)?
