### ISSUE TITLE
Contributor Roles

### ISSUE THREAD

**Issue by nitramred** [podlove/podlove-publisher#1386]
Feedback von Podlove Community:

"There is another issue with the Contributors Plugin that I noticed after publishing two episodes after installing the beta:

If I leave a contributor’s role unchanged, they seem to be not added to that actual role.
I have several roles, where “moderator” is the default. If I add people with other roles, I change their role of course. But if I add a moderator, I want to leave their role unchanged. However, they then won’t be displayed on the website (not as a moderator and also not with another role). I then have to delete them from the episode and add them again (or change their role to another role, save, and then return to the original role)."

https://community.podlove.org/t/release-4-0-0-beta/3162/12

**Comment by alexander-heimbuch** [comment]
@dnkbln could you have a look if that might be an API issue?
