### ISSUE TITLE
Issues with asset detection

### ISSUE THREAD

**Issue by gpapp** [podlove/podlove-publisher#1396]
Error in asset detection started with the 4.0+ versions, used to work before

### Expected behavior
When saving an episode, after validating corresponding assets they should show up in the asset overview (Podlove Dashboard tab) and show up when reopening the episode for edit.

### Actual behavior
When saving an episode, after validating corresponding files are there (cover.jpeg. mp3 mp4 files) the assets are not shown except for the mp3.  Clicking on the red x to revalidate ends up in error.
Reopening the episode for edit displays file not found errors.  Revalidation from the edit screen finds them again.

No errors are displayed in the server or application logs.

### System information (see `Podlove > Support` menu)

```
Website                    https://zartosztaly.hu
PHP Version                8.1.12-1ubuntu4.3
WordPress Version          6.3.2
WordPress Theme            Zártosztály Podcast v2 v1.0
Active Plugins             
           - Akismet Anti-spam: Spam Protection v5.3
           - Site Kit by Google v1.111.1
           - Jetpack Protect v1.4.2
           - Jetpack v12.7.1
           - Limit Login Attempts Reloaded v2.25.26
           - Podlove Podcast Publisher v4.0.1
           - Podlove Web Player v5.7.1
           - Social Media Auto Publish v3.2
           - W3 Total Cache v2.5.0
           - Converter for Media v5.11.2
           - Pexels: Free Stock Photos v1.2.2
WordPress Database Charset utf8
WordPress Database Collate 
Publisher Version          4.0.1
Publisher Database Version 153
Web Player Version         player_v5
open_basedir               ok
curl Version               7.88.1
iconv                      available
simplexml                  ok
max_execution_time         30
upload_max_filesize        32M
memory_limit               256M
disable_classes            
disable_functions          
permalinks                 ok (/%postname%/)
podlove_permalinks         ok
podcast_settings           ok
web_player                 ok
podlove_cache              on
assets                     
  - mp3    audio/mpeg       https://zartosztaly.hu/feed/mp3/
  - mp4    video/mp4        https://zartosztaly.hu/feed/mp4/
  - jpg    image/jpeg       no feed
  - jpg    image/jpeg       no feed
  - psc    application/xml  no feed
cron                       ok
duplicate_guids            ok

0 errors
0 notices
Nice, Everything looks fine!
```

**Comment by gpapp** [comment]
Also, as the episode cover assets are not detected, the artwork is not added to the RSS, shown on the web player, etc..

**Comment by gpapp** [comment]
https://xxxx/wp-admin/admin-ajax.php?action=podlove-file-update&file_id=yyyy
returns a 400 error.
Seems like the functionality was removed from the  /lib/ajax/ajax.php and the /lib/ajax/file_controller.php cripling this function.
Bluntly replacing files with 3.x version resolves the issue,

**Comment by eteubert** [comment]
Looks like we were too eager to delete some old code :)

**Comment by gpapp** [comment]
Thank you for the quick fix, tested and works!
