### ISSUE TITLE
Missing chapter marks when importing from Auphonic after Update to Podlove 4.x

### ISSUE THREAD

**Issue by tautologe** [podlove/podlove-publisher#1401]
### Expected behavior

When loading a production from Auphonic with Podlove 4.x, all chapters are imported as it worked with Podlove 3.x.

### Actual behavior

After selecting an episode from the dropdown, it show several metadata that can be imported. Chapters are not listed there, although they are shown on the linked auphonic result page. Also when clicking "Import all from Auphonic", the list remains empty.

I tried with a two week old episode, that had already been imported successfully with Podlove 3.x. When selecting the auphonic production from the dropdown with Podlove 4.x it does not even show any metadata to import.  

The auphonic production was not created from Wordpress/Podlove but via Auphonic App + Website. The chapter marks do not contain urls or images.

### System information (see `Podlove > Support` menu)

```
PHP Version                8.2.12
WordPress Version          6.3.2
Active Plugins             
           - Admin Menu Editor v1.12
           - Classic Editor v1.6.3
           - Contact Form 7 v5.8.2
           - Custom Permalinks v2.5.2
           - Yoast Duplicate Post v4.5
           - Newsletter v7.9.2
           - Podlove Podcast Publisher v4.0.1
           - Podlove Subscribe Button v1.3.10
           - Podlove Web Player v5.7.1
           - Redirection v5.3.10
           - Remove Comments Absolutely v1.1.2
           - The Events Calendar v5.14.1
           - Connect Matomo v1.0.30
WordPress Database Charset utf8
WordPress Database Collate 
Publisher Version          4.0.1
Publisher Database Version 153
Web Player Version         player_v4
open_basedir               ok
curl Version               7.74.0
iconv                      available
simplexml                  ok
max_execution_time         30
upload_max_filesize        5M
memory_limit               256M
disable_classes            
disable_functions          
permalinks                 ok (/%year%/%monthnum%/%postname%/)
podlove_permalinks         ok
podcast_settings           ok
web_player                 ok
podlove_cache              on
assets                     
  - mp3    audio/mpeg       https://****/feed/mp3/
cron                       ok
duplicate_guids            ok

0 errors
1 HINWEIS (no dealbreaker, but should be fixed if possible): 
- Episode Database Charset is not UTF-8! (is latin1_swedish_ci)
```

**Comment by eteubert** [comment]
Thanks for the report, will be fixed with https://github.com/podlove/podlove-publisher/commit/a14c45776952f2ba79eb5403c22f2c7b1137c721 in the next patch

**Comment by tautologe** [comment]
Thanks for the really quick response and bugfix release! 

Unfortunately in 4.0.2 it still does not work properly, the import seems to mistakenly interprete auphonic seconds as milliseconds.

E.g. a chapter mark at 00:03:11 is imported as 00:00:00.191.

**Comment by eteubert** [comment]
This should fix it. We will get there eventually 🫣 https://github.com/podlove/podlove-publisher/commit/5f01871d16a5f1c6ebdc91be35913f8cb5a61a7f

**Comment by tautologe** [comment]
Hi Eric, many thanks, 4.0.3 fixes the problem!
