### ISSUE TITLE
Extensive use of flush_rewrite_rules() breaks WPML / ACF compatibility

### ISSUE THREAD

**Issue by klubdergutenseiten-user** [podlove/podlove-publisher#1432]
Hey there,
we have had a very strange behaviour, where one of our customers experienced a 500 Internal Server error, everytime the user updated a custom options page (created using ACF-Options page) in a non-default language (using WPML). After **heavy** investigation, it came across my mind, that the htaccess file is being modified once the options page is **opened** (wtf?).

After further investigation I found out, it was due to `flush_rewrite_rules()` being called extensivley.

The pattern in: [extras.php](https://github.com/podlove/podlove-publisher/blob/daeb3dc0c1ce3145fc64b7ee2462f7747d01400d/includes/extras.php#L20C31-L20C31)
doesn't look very  neat to me. I checked and the transients are set multiple times, so the `flush_rewrite_rules` are called very often (which is also a performance issue at this point).

Would you be able to reconsider using the `flush_rewrite_rules()` on every 'init' action call or at leaste provide an option / setting to opt-out with this? I tried to think of a different solution / hook when to call `flush_rewrite_rules()` for your case, but I have no deep understanding of when you would need to refresh the rules.

### Expected behavior
* don't refresh the rewrite rules, when opening any admin-view

### Actual behavior
* `flush_rewrite_rules` is called (and breaks other unexpected behaivour)

### System information (see `Podlove > Support` menu)
-

### Temporary fix:
* uncomment [this line](https://github.com/podlove/podlove-publisher/blob/daeb3dc0c1ce3145fc64b7ee2462f7747d01400d/includes/extras.php#L20C31-L20C31)

regards,
flo

**Comment by eteubert** [comment]
Hi, I faintly remember this. I will need to check every place where `podlove_needs_to_flush_rewrite_rules` is set. Should at least be possible to only set it after changing values, not on opening certain settings pages 🤔

**Comment by klubdergutenseiten-user** [comment]
Thanks man, you fixed it very quick. I already tried it on our staging environment and it works like a charm. Thank you very much, for the quick response!
