### ISSUE TITLE
Duplicate column name 'active'

### ISSUE THREAD

**Issue by Isoldemalduschen** [podlove/podlove-publisher#1437]
### Expected behavior

Not showing this error:

![image](https://github.com/podlove/podlove-publisher/assets/111002328/26ef2b68-ef6e-46dc-a355-dd3164e194b2)

### Actual behavior

Error: Duplicate column name 'active'

Query: ALTER TABLE `jaw5k_podlove_mediafile` ADD COLUMN `active` TINYINT

### System information (see `Podlove > Support` menu)

Website                    https://www.stvo2go.de
PHP Version                8.0.30
WordPress Version          6.4.2
WordPress Theme            Kadence v1.1.51
Active Plugins             
           - ManageWP - Worker v4.9.19
           - Ads.txt Manager v1.0.9
           - Code Snippets v3.6.2
           - Data Tables Generator by Supsystic v1.10.31
           - Download Monitor v4.9.8
           - Easy Social Share Buttons for WordPress v9.3
           - Enable Media Replace v4.1.5
           - Ezoic v2.9.5
           - Google Listings and Ads v2.5.15
           - XML Sitemap Generator for Google v4.1.18
           - Jetpack v13.0
           - Kadence Blocks - PRO Extension v2.2.4
           - Kadence Blocks - Gutenberg Blöcke für Page Builder Features v3.2.19
           - Kadence Conversions - Popups, slide-ins v1.0.8
           - Kadence Galleries v1.3.1
           - Kadence Pro - Premium addon for the Kadence Theme v1.0.19
           - Kadence Reading Time v1.0.3
           - Kadence Captcha v1.3.1
           - Kadence Related Content v1.0.11
           - Kadence AI Starter Templates v2.0.6
           - Kadence Shop Kit v2.0.28
           - LearnDash LMS - Achievements v1.2.1
           - LearnDash LMS - Certificate Builder v1.0.4
           - LearnDash LMS - Course Grid v2.0.9
           - LearnDash Licensing & Management v1.3
           - LearnDash LMS - ProPanel v2.2.2
           - LearnDash LMS - WooCommerce Integration v1.9.7
           - MailPoet v4.42.0
           - OG — Better Share on Social Media v3.2.7
           - Podlove Podcast Publisher v4.0.11
           - Podlove Web Player v5.7.3
           - PublishPress Authors v4.3.1
           - LearnDash LMS v4.10.2
           - Temporary Login Without Password v1.8.3
           - Uncanny Toolkit for LearnDash v3.6.4.8
           - vendidero Helper v2.2.2
           - Vimeo v1.2.2
           - Payment Plugins for Stripe WooCommerce v3.3.55
           - NextMove Lite - Thank You Page for WooCommerce v2.17.0
           - Germanized für WooCommerce Pro v3.9.0
           - Germanized für WooCommerce v3.15.5
           - WooCommerce Google Analytics Integration v1.8.13
           - WooCommerce Multilingual & Multicurrency v5.3.2
           - WooPayments v7.1.0
           - WooCommerce v8.5.2
           - WP Mail SMTP v3.11.1
           - Prosodia VGW OS v3.25.3
WordPress Database Charset utf8
WordPress Database Collate 
Publisher Version          4.0.11
Publisher Database Version 154
Web Player Version         player_v5
open_basedir               ok
curl Version               7.81.0
iconv                      available
simplexml                  ok
max_execution_time         30
upload_max_filesize        200M
memory_limit               512M
disable_classes            
disable_functions          
permalinks                 ok (/%postname%/)
podlove_permalinks         ok
podcast_settings           ok
web_player                 ok
podlove_cache              off
assets                     
  - mp3    audio/mpeg       https://www.stvo2go.de/feed/stvo2go/
  - mp3    audio/mpeg       https://www.stvo2go.de/feed/grossraum-und-schwerverkehr/
  - mp3    audio/mpeg       https://www.stvo2go.de/feed/arbeitsstellen/
cron                       ok
duplicate_guids            ok

0 errors
0 notices
Nice, Everything looks fine!

### Notes
I don't think that this is a big issue. I don't need a quick fix because I think everything is working fine at the moment. I wanted to report this issue just in case anyone has it as well.

**Comment by eteubert** [comment]
This is an issue, you should not be able to manage media files without resolving this.

It means adding a column to a database table failed during database migration, which was part of the latest update. Have you tried running the suggested query?

After adding the column manually, you also need to run the next query from the migration:

```sql
UPDATE jaw5k_podlove_mediafile SET `active` = CASE
  WHEN size IS NOT NULL THEN 1
  ELSE 0
END
```

**Comment by Isoldemalduschen** [comment]
Hi eteubert,

thanks for coming back to me so quickly. I hope your suggestion helps other users.
Referring to my situation, I can only be completely honest with you: I have no idea what you are talking about. I have no programming background. I can only do a little CSS because I got used to it by working with WordPress.
