### ISSUE TITLE
Shoeboxes werden nicht angezeigt

### ISSUE THREAD

**Issue by pwpbln** [podlove/podlove-publisher#1487]
![IMG_3539](https://github.com/user-attachments/assets/4fed35c2-957e-4edf-b61c-5e6477d67ea3)
DAs Problem habe ich neulich schon mal bei einem Podlove Podcast gehauen. Glaube Logbuch Netzpolitik.

**Comment by eteubert** [comment]
Show notes meinst du, ja? Stehen definitiv im Feed. Vielleicht liegt es am Catcher, welchen auch immer du benutzt. Ich mach hier mal zu, wenn es erneut auftritt, bitte auch den verwendeten Catcher und RSS Feed dazu angeben.
