### ISSUE TITLE
Cannot change the itunes:explicit tag

### ISSUE THREAD

**Issue by Inrumpo** [podlove/podlove-publisher#1490]
### Expected behavior
Checking/unchecking the explicit checkbox in the episode view should set that episode to explicit (true) or not explicit (false). The chosen state should be saved.

### Actual behavior
Changes to the explicit checkbox are not saved.
Revisiting/reloading the episode view will show that the explicit checkbox is still set to whatever state it was before.

### System information

> Website                    https://GameTalk.FM
> PHP Version                8.2.18
> WordPress Version          6.6.1
> WordPress Theme            Joeys Twenty Fifteen Child v2.6.1
> Active Plugins             
>            - Akismet Anti-spam: Spam Protection v5.3.3
>            - Classic Editor v1.6.4
>            - Limit Login Attempts v1.7.2
>            - Podlove Podcast Publisher v4.1.13
>            - Podlove Web Player v5.8.0
>            - Yoast SEO v23.2
> WordPress Database Charset utf8
> WordPress Database Collate 
> Publisher Version          4.1.13
> Publisher Database Version 157
> Web Player Version         player_v5
> open_basedir               ok
> curl Version               7.87.0
> iconv                      available
> simplexml                  ok
> max_execution_time         50
> upload_max_filesize        100M
> memory_limit               256M
> disable_classes            
> disable_functions          exec, shell_exec, system, dl, passthru, proc_open, proc_close
> permalinks                 ok (/%postname%/)
> podlove_permalinks         ok
> podcast_settings           ok
> web_player                 ok
> podlove_cache              on
> assets                     
>   - mp3    audio/mpeg       https://GameTalk.FM/feed/mp3/
>   - m4a    audio/mp4        https://GameTalk.FM/feed/m4a/
> cron                       ok
> duplicate_guids            ok
> 
> 0 errors
> 0 notices
> Nice, Everything looks fine!

**Comment by dnkbln** [comment]
Thanks for the feedback. If the PR #1504 has been merged, it should work.

**Comment by Inrumpo** [comment]
Thank you for the fix!
I'll test this as soon as it is released.

**Comment by Inrumpo** [comment]
Version 4.1.16 has fixed the problem. Thank you!
As a result, I was now able to manually remove the explicit tag from all affected episodes, which was set by an earlier update.
