### ISSUE TITLE
Link aus Iframe zu WordPress ersetzt nur iframe

### ISSUE THREAD

**Issue by eteubert** [podlove/podlove-publisher#1516]
Am Ende des Import-Pfads wird auf die Episoden-Liste verlinkt. Der Link hat nicht den gewünschten Effekt:

![Screenhot Firefox Developer Edition 2024-10-11 22 19 39@2x](https://github.com/user-attachments/assets/1cf3e80f-f077-4d6a-8b82-5d48c9b98274)

**Comment by kun18911** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
