### ISSUE TITLE
Auphonic: Cover image not included when creating production

### ISSUE THREAD

**Issue by lumaxis** [podlove/podlove-publisher#1518]
I'm not sure when this stopped working but when we create an Auphonic production via a preset using Podlove, the plugin appears to send all metadata except the episode image to Auphonic, requiring what feels like an unnecessary manual step in our production pipeline.

**Comment by eteubert** [comment]
Just to narrow it down, setting to manage covers do you use?

![Screenhot Firefox Developer Edition 2024-10-21 19 33 23@2x](https://github.com/user-attachments/assets/5ad8d6c0-4095-4dd7-b658-7ff3e4194875)

**Comment by kun18911** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by eteubert** [comment]
Thanks for the follow-up, the fix will be included in the next release.

**Comment by lumaxis** [comment]
Fantastic, thank you!
