### ISSUE TITLE
Beta: Onboarding Assistant - Button "To episode List" reopens the web backend

### ISSUE THREAD

**Issue by liferadioat** [podlove/podlove-publisher#1528]
Hi,

it seems that the onboarding assistant is a kind of iframe. When the import process is finished I can view my episode by the button "view my episodes" at the onboarding assistant. This opens another web sessions within the backend and I need to login again, but then I´ve got two wordpress backends behind each other. Perhaps a simple link target="_blank" could help?

**Comment by eteubert** [comment]
`target="_top"` is the solution in iframes. I already had a fix ready but had not merged yet. https://github.com/podlove/publisher-services/pull/50 It's merged now but I'll keep the issue open until the fix is verified.

**Comment by eteubert** [comment]
Confirmed fixed
