### ISSUE TITLE
musicBrainz integration

### ISSUE THREAD

**Issue by fuddl** [podlove/podlove-publisher#249]
[musicBrainz](http://musicbrainz.org/) ist eine freie Musik-Meta-Datenbank, ursprünglich gedacht für Metadaten von sogenannt *Compact Discs*. Mittlerweile aber für jede Art von Audio-Aufname die es so gibt.

Jede Entität in Musicbrainz hat eine UUID die man auch in [Wikidata](https://www.wikidata.org/) verkünpfen kann und umgedreht. 

Die UUID kann auch in den Meta-Daten der jeweiligen Audiodatei gespeichert werden was es zu einem praktischen Archivierungstool macht.

Hier einige Beispiele für Podcasts in MB:

* [CRE](http://musicbrainz.org/release-group/e95e4931-9618-478b-b20b-a33254e4be64)
* [WMR](http://musicbrainz.org/release-group/6b0d6f74-3249-4312-9ece-3dd26ad352a3)

Und ein Beispiel einzelnen Podcast:
* [CRE185](http://musicbrainz.org/release/afd19fec-4191-4448-9e49-c360e5c710cb) 
  Mit Mitwirkenden, Recording Location download link und Cover art.

Man muss leider dazu sagen das musicBrainz nicht für Podcasts designed ist und daher etwas anstrengend.

## Podcast-Ausgabe anlegen ##

Um eine Podcast Ausgabe in der musicBrainz an zu legen braucht man einen Account und (vorausgesetzt die anderen Entitäten wie *Künstler*, die *Podcast-Reihe* usw bestehen bereits) muss man sich durch [dieses Formular](http://musicbrainz.org/release/add)  durchklicken.

![add-podcast](https://f.cloud.github.com/assets/842548/1698122/7c4303e6-5f2b-11e3-8692-876cdc8c7eee.png)

Dann sollte man natürlich noch:

* Das Cover hochladen (sofern für einzelausgabe vorhanden)
* mögliche außerordentliche Mitwirkende/Interviewpartner als Artist anlegen und/oder verlinken
* mögliche recording location als Venue anlegen und/oder verlinken
* download und streaming link anlegen

### Automatisierung

Leider hat musicBrainz keine Schnittstelle mit Schreibrechten aber zumindest das anlegen eines releases lässt sich halb-automatisieren.

Man kann mittels post das *Add release*-Formular vorausfüllen. [siehe hier](https://wiki.musicbrainz.org/Development/Release_Editor_Seeding). Dann muss man sich nur noch durchklicken. Ich hab mir ein php script geschrieben das mir aus dem CRE-feed dieses formular vorausfüllt, das kann ich hier veröffentlichen falls gewünscht.

**Comment by eteubert** [comment]
Feature-Diskussionen ab sofort nur noch in [Trello](//trello.com/b/zB4mKQlD/podlove-publisher) oder [Podlove Community](//community.podlove.org).

Hier verlinkt: https://trello.com/c/TphoNRJe/357-type-music
