### ISSUE TITLE
"File not found" but found

### ISSUE THREAD

**Issue by socialhack** [podlove/podlove-publisher#296]
In the media files section of an episode and the dashboard I see for all Assets the red warning "File not found", which stays even after refreshing, BUT clicking on the link of Asset File name clearly links to the existing file. 

Permissions on the whole directory are set on 777 (for debug), still no change. EpisodeSlug comes from auphonic and URL scheme unchanged as default. 

example: http://www.net-politics.eu/wp-content/uploads/episodes/NPEU11-TSM.mp3 *leak* 

What's wrong? 

Thanks for your time and efforts!

**Comment by Xjs** [comment]
I have the same symptoms. I can click the filename and get to the MP3 file, but the interface says »not found«. Often, the filename disappears, too. (I haven't found out yet why.) Permissions are such that www-data can read and write the directory on the server, although the interface seems to suggest that Podlove accesses the file via HTTP. This is possible, too.

The file is at http://infracast.de/oben/ic001.mp3

My server does send Content-Length:

$ curl -IL http://infracast.de/oben/ic001.mp3
HTTP/1.1 200 OK
Date: Wed, 18 Nov 2015 12:42:24 GMT
Server: Apache/2.2.22 (Debian)
Last-Modified: Tue, 17 Nov 2015 00:20:30 GMT
ETag: "c81570-3ca79c4-524b17e47cf80"
Accept-Ranges: bytes
Content-Length: 63601092
Content-Type: audio/mpeg

**Comment by eteubert** [comment]
Can you post the output from `Podlove > Support` menu?

**Comment by Xjs** [comment]
Thanks, but I already fixed it. The support menu told me that the curl PHP extension was not installed, so I installed it and everything is working now.

**Comment by eteubert** [comment]
Great, happy podcasting :)

**Comment by stevenproctor** [comment]
Thanks!!! This helped me out as well, as I saw @Xjs referenced that the curl extension was not installed.
