### ISSUE TITLE
Bitlove Integration

### ISSUE THREAD

**Issue by pierew** [podlove/podlove-publisher#302]
Ich wollte Bitlove integrieren, aber ich bekomme keine Aufforderung für einen API Zugang oder ähnlichem oder wie sage ich dem Plugin es soll das Asset BitTorrent mit Bitlove verknüpfen bzw. mir die Dateien auf dem Server laden

---

Website             http://pierewoehl.de/wordpress
PHP Version         5.5.1
WordPress Version   3.8.1
Publisher Version   1.9.12-alpha
Web Player Version  2.0.17
curl Version        7.19.7
iconv               available
allow_url_fopen     1
simplexml           ok
max_execution_time  30
upload_max_filesize 290M
memory_limit        256M
disable_classes  
disable_functions  
permalinks          ok
podcast_settings  
web_player          ok

0 errors
0 notices
Nice, Everything looks fine!

**Comment by sethiele** [comment]
> Derzeit leistet das Modul nur das automatische Auflisten der von Bitlove bereits angebotenen Download-Dateien auf der Website.

@timpritlove Wie kann ich das erreichen? Ich bin alle Einstellungen durchgegangen und finde das leider nicht. Ich hätte das auch gerne so [wie bei Bitlove](http://bitlove.org/help/podcaster/widget#podlove) beschrieben.

Danke
