### ISSUE TITLE
FR: pair-wise hyperlinking of chapter marks and shownote sections

### ISSUE THREAD

**Issue by KonScience** [podlove/podlove-publisher#349]
With the WP plugin [Add ID to header tags](http://wordpress.org/plugins/add-ids-to-header-tags/) it is possible to address each heading in a post individually. Using those links for the chaptermarks enables a quick transition from hearing a chapter to reading its notes. And the other way if one via the your [Deep Links](http://podlove.org/deep-link/) :-) See attached screenshots (only a draft; Would committing these changes flush the episode to the top of the feed?). Both tasks are however tedious copy-paste-fests if done manually.
![screen shot 2014-03-21 at 20 55 31](https://f.cloud.github.com/assets/6566930/2487331/4b9decce-b133-11e3-9f02-7dc68ea49611.png)
![screen shot 2014-03-21 at 20 55 37](https://f.cloud.github.com/assets/6566930/2487332/4b9f7030-b133-11e3-9ac3-5723ce661f4f.png)

How about implementing an option do automate this in the Publisher? Maybe by parsing the heading-tag (or only a pre-defined one, or simply the lowest), comparing them with the chaptermarks (or generating them at this point) and inserting the respective links in each matching case? Maybe via a template that defines the back-link in the show notes like WP already does with the  tag.

**Comment by eteubert** [comment]
Feature-Diskussionen ab sofort nur noch in [Trello](//trello.com/b/zB4mKQlD/podlove-publisher) oder [Podlove Community](//community.podlove.org).

Siehe auch: http://podlove.org/2015/04/22/the-podlove-community-and-support/

________________________

Feature-discussion will be moved to [Trello](//trello.com/b/zB4mKQlD/podlove-publisher) or [Podlove Community](//community.podlove.org).

See also: http://podlove.org/2015/04/22/the-podlove-community-and-support/
