### ISSUE TITLE
Verbesserungen Projektseiten podlove.org zum einfacheren Weiterempfehlen

### ISSUE THREAD

**Issue by holgerd77** [podlove/podlove-publisher#367]
Hallo,
ich wollte gerade auf App.net jemanden den Umstieg auf Podlove Publisher/Webplayer empfehlen, ich habe dann rumgesucht, was ich am besten verlinken sollte, bin auf http://podlove.org angefangen, habe keinen richtig guten Einstiegspunkt gefunden und nach 10 Minuten war mein Enthusiasmus wieder etwas erlahmt und ich habe es dann gelassen.

Folgende Dinge würden hier ggf. Besserung schaffen:
- 1-2 Screenshots jeweils für Publisher und Webplayer auf den jeweiligen Projektseiten und/oder auf der Wordpress-Plugin Seite. Ich weiß, Screenshots bergen immer etwas die Gefahr in sich, dass sie veralten, aber so kann man sich überhaupt nicht vorstellen, womit man es so zu tun haben könnte, wenn man vom Projekt noch nie gehört hat.
- 4-5 verlinkte Beispielprojekte (ggf. sogar nicht Metaebene falls vorhanden :-)), möglichst auch mindestens 1x in englisch, damit man die Software direkt auch einmal ausprobieren kann.
- Speziell auf der Publisher Projektseite ist der Link zum Wordpress Plugin auch noch deutlich zu schlecht zu finden - speziell wenn man die Seite einfach nur nutzen will - um zum Plugin zu gelangen. Ein Link in den ersten 2-3 Sätzen oder in der Seitenleiste würde hier helfen.
- Eine Verlinkung des Publisher-Einführungsvideos (https://www.youtube.com/watch?v=YWebs8p8_As) auf YouTube wäre auch sinnvoll.

Viele Grüße, danke für Eure tolle Arbeit!
Holger Drewes

**Comment by eteubert** [comment]
Kaum ein Jahr später und schon: publisher.podlove.org :tada:

**Comment by holgerd77** [comment]
Bearbeitungsgeschwindigkeit kenn ich aus Erfahrung bei eigenen OSS-Projekten, ich verbuche das mal unter Fast-Lichtgeschwindigkeit! :-)

Sieht aber echt schick aus auf den ersten Blick!
