### ISSUE TITLE
Can't add contributors

### ISSUE THREAD

**Issue by sodaflo** [podlove/podlove-publisher#425]
Hi,

I just updated the Podlove-Publisher and since then i can't add contributors to an episode. A click on the "+"-button doesn't do anything. I tried Safari and Chrome.

Beneath that small problem the Podlove Publisher is awesome, thank you so much!

**Comment by noplanman** [comment]
Hi guys, this issue isn't fixed yet ;-)
The problem is the old version of the chosen jQuery addon that Podlove is still using. If any other plugin uses a newer version, a conflict occurs and one of the two versions gets overridden.
I've fixed this problem here: #770

**Comment by eteubert** [comment]
Will be fixed once 2.3 is released. It's already merged, see d21cb3294c6ca2bfc3c87a065d65945ac57e0d53
