### ISSUE TITLE
"following" web player

### ISSUE THREAD

**Issue by loki-lab** [podlove/podlove-publisher#439]
Normally I use a Podcast client on my iPod to listen to some podcasts, but today I exceptionally used the podlove webplayer on the website of this podcast.While I was listening to this podcasts I scrolled down on their website to follow the Shownotes, which were quite long. When I paused the player then I had to scroll to the top of the page, and after clicking on play again I had to scroll down. Would it be possible to integrate some feature into the player / the wordpress plugin, that there is a possibility to control the webplayer without having to scroll to the top of the page. I'm not familliar with wordpress, but a player, which "follows", when I scorll down would be really nice.

**Comment by eteubert** [comment]
Feature-Diskussionen ab sofort nur noch in [Trello](//trello.com/b/zB4mKQlD/podlove-publisher) oder [Podlove Community](//community.podlove.org).

Siehe auch: http://podlove.org/2015/04/22/the-podlove-community-and-support/

________________________

Feature-discussion will be moved to [Trello](//trello.com/b/zB4mKQlD/podlove-publisher) or [Podlove Community](//community.podlove.org).

See also: http://podlove.org/2015/04/22/the-podlove-community-and-support/
