### ISSUE TITLE
Gekilltes Feature "Force Download"

### ISSUE THREAD

**Issue by Channelcast** [podlove/podlove-publisher#440]
Im letzten Changelog wurde das Feature "Force Download" herausgenommen. Seitdem können Hörer Audiodateien nicht mehr herunterladen. Die Audio-Files werden nunmehr im Browser geöffnet und abgespielt. Leider sehe ich keine Möglichkeit, meinen Hörern weiterzuhelfen. In der Folge sind die Downloads um 70 Prozent eingebrochen.
Zwar wird geraten, serverseitig die Konfiguration anzupassen, doch als Nutzer eines Web-Pakets (hier Host Europe) bietet sich diese Option nicht. 
Welche Möglichkeit haben Podcaster, die keinen eigenen Server betreiben, ihren Hörern wieder einen funktionierenden Download anzubieten? Kann man das Feature "Force Download" nicht wieder optional anbieten, wenngleich es sicherlich Gründe gab dieses herauszunehmen? Wenigstens als Zwischenlösung bis es eine Lösung für Nutzer gibt die ihren Server nicht konfigurieren können?

**Comment by markusk** [comment]
Übrigens: Die besagte .htaccess-Datei muss(te bei mir, Provider all-inkl.)  in genau dem Ordner liegen, wo die zu Dateien zum Download liegen.

Also z.B. sinngemäß unter http://media.reich-und-knapp.de/.htaccess
