### ISSUE TITLE
Template-Änderungen nicht sichtbar

### ISSUE THREAD

**Issue by nitramred** [podlove/podlove-publisher#457]
Hallo,
ich habe ein etwas merkwürdiges Verhalten bei den Templates festgestellt. Änderungen am Template haben ab einem mir nicht ersichtlichen Zeitpunkt keinen Effekt mehr auf die Anzeige im Frontend. D.h., jede Änderung, Umsortierung oder Anpassung im Template wird nicht mehr dargestellt. Erstelle ich ein neues Template mit dem gleichen Inhalt und binde dieses ein, wird alles korrekt angezeigt, bis auch das dann Änderungen darin nicht mehr auf der Live-Site angezeigt werden. Ich kann es leider nicht besser beschreiben, hoffe aber, das Problem wurde klar.
Beste Grüße
Martin

**Comment by HorstFrank** [comment]
Hallo Zusammen!
Wir haben das Problem auch (1.12.1-alpha).

Ich vermute, dass die Seite von WP gecachet wird. Ich habe eben die Episode immer über das Kategoriemenü aufgerufen und aktualisiert, keine änderungen im Template wurden angezeigt. Dann habe ich die Episode einmal über aktuelle Beiträge aufgerufen (das habe ich vorher nicht gemacht) und dort wurden die änderungen dann angezeigt. Ich konnte dann zwischen der falschen darstellung und der richtigen wechseln, je nach aufruf über das Menü. (Design-Template unabhängig)
Cacht WP die Seiten an Podlove vorbei irgendwo? kann ich evtl. ein caching in wp irgendwo ausschalten?
Der vorgeschlagene Workflow von David 1701 funktioniert bei mir. Wenn ich ein neues anlege und dieses wieder in den alten namen zurück benenne, wird das ganz alte template angezeigt. Irgendwo merkt sich WP das scheinbar.
