### ISSUE TITLE
Scientific Author IDs in Contributors

### ISSUE THREAD

**Issue by matthiasfromm** [podlove/podlove-publisher#462]
Hi!

There is a growing number of podcasts around with a focus on science (some of them is made by scientists, in some of them scientists appear as guests). It would be great if you could integrate scientific author IDs into the "Social" list of the contributors module.

I think the <a href="http://orcid.org/">Open Researcher and Contributor ID (ORCID)</a> would be preferrable, however the <a href="http://help.scopus.com/Content/h_autsrch_intro.htm">Scopus Author ID</a> might also be helpful.

Much appreciated!

Cheers,
Matthias

**Comment by katrinleinweber** [comment]
@matthiasfromm Tauchen diese neuen Social Services als Option in deinen Podlove-Instanzen auf? Bei uns nicht. 

````
Website             http://www.konscience.de
PHP Version         5.4.36-0+deb7u3 (upgrade to 5.5 brings enhanced performance)
WordPress Version   4.1
Publisher Version   1.12.1-alpha
Web Player Version  2.0.17
curl Version        7.26.0
iconv               available
allow_url_fopen     1
simplexml           ok
max_execution_time  60
upload_max_filesize 50M
memory_limit        256M
disable_classes     
disable_functions   
permalinks          ok
podcast_settings    
web_player          ok
podlove_cache       on
assets              
	mp3    audio/mpeg
	m4a    audio/mp4
	opus   audio/opus
	mp4    video/mp4
	pdf    application/pdf

0 errors
0 notices
Nice, Everything looks fine!
````

**Comment by timpritlove** [comment]
Bitte mal den "Repair" Button drücken. Dann sollten die eigentlich auftauchen.

**Comment by katrinleinweber** [comment]
Habe ich natürlich gemacht ;-) Auch Ab- und Wiederanschalten des Contributor-Moduls, und Anlegen eines neuen Contributors bringt diese 3 Optionen nicht zum Vorschein.

**Comment by matthiasfromm** [comment]
@katrinleinweber Also ich sehe es ganz normal in den Social Services in der Dropdown-Liste:

![image](https://cloud.githubusercontent.com/assets/2086207/5839523/33f00f88-a18f-11e4-92ce-0a2e5277f95c.png)

**Comment by chemiker** [comment]
@katrinleinweber Die Social-Geschichte hat ein eigenes Modul. Das liegt nicht im Contributors-modul drin. Das sollte eigentlich auch dort vorhanden sein. Es sei denn die Migration hätte nicht geklappt.

**Comment by katrinleinweber** [comment]
Letztes ist vermutlich der Fall. Die Reihenfolge der Module ist ganz schon anders (External Services, System, Metadata, Web Publishing), als in einer neu aufgesetzten Test-Instanz (Metadata, Web Publishing, System, External Services). Ganzes Plugin neu installieren, oder vor dem nächsten Update nochmal Reparieren?

**Comment by eteubert** [comment]
Versuch mal folgendes:

1. Sicherstellen, dass sowohl "Contributors" als auch "Social & Donations" Module aktiv sind
2. In der Datenbank in `wp_options` nach `option_name = "podlove_database_version"` suchen.
3. Diesen Wert auf `85` setzen
4. Hoffentlich über tolle Services freuen

> Bitte mal den "Repair" Button drücken. Dann sollten die eigentlich auftauchen. — @timpritlove 

Nope, der Repair-Button löscht nur Duplikate. Aber das sollte er auch mit übernehmen, da die Social-Migrationen alle einem Denkfehler<sup>[1]</sup> unterliegen und darum nicht bei allen funktionieren.

[1]: Das Social-Modul muss an sein

**Comment by katrinleinweber** [comment]
Danke schön, diese Schritte haben's gelöst :-)
