### ISSUE TITLE
Subtitle & Summary auf Feed-Ebene anpassen?

### ISSUE THREAD

**Issue by nicolasschabram** [podlove/podlove-publisher#463]
Hey,

wir wollen auf unserer Seite gerne verschiedene Formate anbieten, die jeweils in eigenen Feeds veröffentlicht werden sollen. Sehe ich das richtig, dass man bislang nur den Titel auf Feed-Ebene ändern kann, nicht aber Subtitle und Summary?

Besten Dank,
Nicolas

**Comment by eteubert** [comment]
Voraussichtlich in https://trello.com/c/njJosaJY/193-2-6-episode-types-shows enthalten 
________________________

Feature-Diskussionen ab sofort nur noch in [Trello](//trello.com/b/zB4mKQlD/podlove-publisher) oder [Podlove Community](//community.podlove.org).

Siehe auch: http://podlove.org/2015/04/22/the-podlove-community-and-support/

________________________

Feature-discussion will be moved to [Trello](//trello.com/b/zB4mKQlD/podlove-publisher) or [Podlove Community](//community.podlove.org).

See also: http://podlove.org/2015/04/22/the-podlove-community-and-support/
