### ISSUE TITLE
idea: expose average episode release interval in feed

### ISSUE THREAD

**Issue by Cathryne** [podlove/podlove-publisher#472]
In [this discussion about variable update update intervals for a podcatcher](https://github.com/danieloeh/AntennaPod/issues/475) the consensus seems to be that per-feed intervals would be very useful. Since the Podlove [Publisher determines this interval already](https://github.com/podlove/podlove-publisher/issues/428), how about exposing it in the feed? Podcatchers that want to support per-feed update intervals, would then not have to calculate them.

**Comment by eteubert** [comment]
Feature-Diskussionen ab sofort nur noch in [Trello](//trello.com/b/zB4mKQlD/podlove-publisher) oder [Podlove Community](//community.podlove.org).

Siehe auch: http://podlove.org/2015/04/22/the-podlove-community-and-support/

________________________

Feature-discussion will be moved to [Trello](//trello.com/b/zB4mKQlD/podlove-publisher) or [Podlove Community](//community.podlove.org).

See also: http://podlove.org/2015/04/22/the-podlove-community-and-support/
