### ISSUE TITLE
Feed is created twice

### ISSUE THREAD

**Issue by DavidDwier** [podlove/podlove-publisher#485]
My Feed is generated twice by the podlover plugin. 
I can access it by entering http://altersweise.net/feed/radio/ and http://altersweise.net/radio/
the files are identical. Under Settings - Feeds - Radio - Slug I have entered "radio",
so that the example given directly points to url/feed/radio.
Did I misconfigure something?

**Comment by eteubert** [comment]
Feature-Diskussionen ab sofort nur noch in [Trello](//trello.com/b/zB4mKQlD/podlove-publisher) oder [Podlove Community](//community.podlove.org).

Siehe auch: http://podlove.org/2015/04/22/the-podlove-community-and-support/

________________________

Feature-discussion will be moved to [Trello](//trello.com/b/zB4mKQlD/podlove-publisher) or [Podlove Community](//community.podlove.org).

See also: http://podlove.org/2015/04/22/the-podlove-community-and-support/
