### ISSUE TITLE
Add Hook for PaidMembershipPro

### ISSUE THREAD

**Issue by fluxlabs** [podlove/podlove-publisher#488]
We would like to protect the podcasts for paid members only. We are using PaidMembershipPro from http://www.paidmembershipspro.com. I was wondering where I would add the hooks so I am able to control the podcast produced pages under Episodes.

http://www.paidmembershipspro.com/documentation/require-membership-function/

**Comment by eteubert** [comment]
Feature-Diskussionen ab sofort nur noch in [Trello](//trello.com/b/zB4mKQlD/podlove-publisher) oder [Podlove Community](//community.podlove.org).

Siehe auch: http://podlove.org/2015/04/22/the-podlove-community-and-support/

________________________

Feature-discussion will be moved to [Trello](//trello.com/b/zB4mKQlD/podlove-publisher) or [Podlove Community](//community.podlove.org).

See also: http://podlove.org/2015/04/22/the-podlove-community-and-support/
