### ISSUE TITLE
Download-Button und -Link öffnet eine Seite mit Player

### ISSUE THREAD

**Issue by Jagdfunk** [podlove/podlove-publisher#491]
Ein Hörer meldete mir, dass der Download auf eine Seite mit einem Player führt. Ich kann das reproduzieren.

Vermutlich ist es nur eine EInstellung. Hat jemand einen Tip für mich?

Besten Dank.

**Comment by versicherungs-vergleicher** [comment]
Hallo, hat das funktioniert bei dir mit Quick Cache? Hast du weitere Dinge gemacht ? Wäre es möglich wenn du es "nachhaltig" gelöst hast, dass du das nochmal hier reinstellst, Danke Grüße Carsten

**Comment by Erdebene** [comment]
Gern. Seit der Umstellung auf Quick Cache hatte ich keine Probleme mehr. Es schreibt nichts in der htaccess rum. Das erspart die beschriebenen Schmerzen. Es funktioniert einfach und meckert nicht. Mittlerweile heißt das Plugin allerdings Zen Cache.

Ich weiß nicht, was dazu noch zu sagen ist. Wenn Dir Fragen einfallen, dann antworte ich gern so gut ich kann.

**Comment by versicherungs-vergleicher** [comment]
Ok, Danke, das probiere ich aus - dein Download-Button habe ich gerade getestet.

Ist erstaunlich, ich habe jetzt erneut von jemandem gehört, bei ihm "funktioniert alles" allerdings er dachte, dass nach dem Drücken des download Button muss sich das Fenster des Players öffnen, habe viele podcast entdeckt, die sich des "Problemchen" garnicht bewusst sind.....

Danke für die Info, ich kämpfe mit den feeds, 
https://github.com/podlove/podlove-publisher/issues/696
aber vielleicht löst sich das ja mit dem W3 Problem - ich schalte am WE mal alle Plugins ab und geh mal etwas strukturierter vor - vielleicht sieht man sich im Mai auf dem PPW15a - bist du da? Grüße carsten
