### ISSUE TITLE
Unicode problem: mp4 video with chapters

### ISSUE THREAD

**Issue by PhilipBanse** [podlove/podlove-publisher#517]
Hi,

The latest video file in this podlove created feed has chapters, but in podcast clients (instacast, downcast) the chapter titles show no Umlaute (ä, ö, ü) and no "ß".

http://www.kuechenstud.io/datenschau/feed/mp4/

In VLC etc the chapter titles are displayed correctly. 
Also the audio feeds with chapters look fine in instacast/downcast

http://www.kuechenstud.io/datenschau/feed/mp3/
http://www.kuechenstud.io/datenschau/feed/aac

**Comment by eteubert** [comment]
Any insights?

**Comment by larsauswsw** [comment]
Same problem with feed title and feed description.
Feed: http://www.ztua.de/feed/m4a

Website             http://www.ztua.de
PHP Version         5.4.4
WordPress Version   4.2.2
Publisher Version   2.2.4
Web Player Version  2.0.17
Twig Version        1.18.1
open_basedir        ok
curl Version        7.19.7
iconv               available
simplexml           ok
max_execution_time  30
upload_max_filesize 64M
memory_limit        256M
disable_classes     
disable_functions   
permalinks          ok (/%year%/%monthnum%/%postname%/)
podlove_permalinks  ok
podcast_settings    ok
web_player          ok
podlove_cache       on
assets              
	mp3    audio/mpeg
	m4a    audio/mp4
	oga    audio/ogg
	psc    application/xml
	json   application/json
	opus   audio/opus

0 errors
0 notices
Nice, Everything looks fine!

**Comment by larsauswsw** [comment]
My problem occurs only in Instacast
