### ISSUE TITLE
Benutzerdefiniertes Standard-Avatarbild

### ISSUE THREAD

**Issue by nicolasschabram** [podlove/podlove-publisher#518]
Hey Leute,

momentan ist es so, dass Contributor ohne Avatar automatisch dieses graue Standard-Icon von Gravatar zugewiesen bekommen. Bei meinem aktuellen Projekt wäre es total praktisch, wenn ich ein eigenes Standardbild definieren könnte. Besser noch eins für Männer und eins für Frauen.

Wahrscheinlich bin ich mit dem Wunsch nach diesem Feature gerade relativ allein. Aber was haltet ihr prinzipiell von der Idee?

Beste Grüße,
Nico

**Comment by eteubert** [comment]
Feature-Diskussionen ab sofort nur noch in [Trello](//trello.com/b/zB4mKQlD/podlove-publisher) oder [Podlove Community](//community.podlove.org).

Siehe auch: http://podlove.org/2015/04/22/the-podlove-community-and-support/

________________________

Feature-discussion will be moved to [Trello](//trello.com/b/zB4mKQlD/podlove-publisher) or [Podlove Community](//community.podlove.org).

See also: http://podlove.org/2015/04/22/the-podlove-community-and-support/
