### ISSUE TITLE
Nutzer-Berechtigungen

### ISSUE THREAD

**Issue by nicolasschabram** [podlove/podlove-publisher#519]
Ich baue gerade für ein relativ großes Team eine Website auf. Dort gibt es zum einen die Episoden verschiedener Podcasts und zum anderen ein davon unabhängiges Blog. Alles läuft unter der selben Installation. Das klappt soweit auch alles sehr gut. Allerdings würde ich gerne die Zuständigkeiten auf mehrere Leute verteilen. Wenn ich das richtig sehe, kann ich aber mit den Standard-Benutzerrollen von Wordpress nicht einstellen, dass jemand Zugriff auf alle *Beiträge*, nicht aber die *Episoden* hat. Das ist tendenziell heikel, weil nicht unbedingt jeder der Redakteure den allergrößten technischen Sachverstand mitbringt, nicht versehentlich irgend etwas kaputt zu machen. Deshalb meine Frage: Gibt es einen Weg, die Befugnisse individueller zu vergeben?

Beste Grüße,
Nico

**Comment by eteubert** [comment]
Feature-Diskussionen ab sofort nur noch in [Trello](//trello.com/b/zB4mKQlD/podlove-publisher) oder [Podlove Community](//community.podlove.org).

Siehe auch: http://podlove.org/2015/04/22/the-podlove-community-and-support/

________________________

Feature-discussion will be moved to [Trello](//trello.com/b/zB4mKQlD/podlove-publisher) or [Podlove Community](//community.podlove.org).

See also: http://podlove.org/2015/04/22/the-podlove-community-and-support/
