### ISSUE TITLE
Insert player automatically problem - Template Internationalisation

### ISSUE THREAD

**Issue by hippyruth** [podlove/podlove-publisher#522]
Hi

I'm aware that Internalisation isn't the top of the priority list at the moment, thats OK. The webplayer is graphical enough that it's not a big problem. 

I use qtranslate and podlove in wordpress. (http://test.kiamainz.de/) For plain html or php qtranslate can distinguish between languages like so:
German textEnglish text
For some reason this doesn't work inside the template environment. 

At the moment I make two templates for each application, one for each language. That's great for the feed page and home page, however I initially couldn't get it to work on the episode pages. When I create a new episode the default template is inserted automatically. In "settings/Insert player automatically" I have it set it to "Insert manually via shortcode". This doesn't seem to make a difference. The episode page always includes the content from [podlove-template id="default"]. To get around this I made the default template completely blank. 

I have posted this here firstly because I may have missed a much more elegant solution - and if anyone has one that would be great! If not because I think that, without worrying about .po files or anything, you could make podlove much easier for multilingual wordpress sites by: 
1 - figuring out how to stop the episode page automatically inserting the default template
2 - perhaps figuring out how to get twig and qtranslate to play together nicely
3 - writing some brief documentation on how to use templates on multilingual sites (I would be happy to write/contribute to this)

I love your plugin. Thanks for all your work :o)

Ruth

p.s. is there any forum to upload user generated template ideas? I would love to share my templates and see others.

**Comment by eteubert** [comment]
Feature-Diskussionen ab sofort nur noch in [Trello](//trello.com/b/zB4mKQlD/podlove-publisher) oder [Podlove Community](//community.podlove.org).

Siehe auch: http://podlove.org/2015/04/22/the-podlove-community-and-support/

________________________

Feature-discussion will be moved to [Trello](//trello.com/b/zB4mKQlD/podlove-publisher) or [Podlove Community](//community.podlove.org).

See also: http://podlove.org/2015/04/22/the-podlove-community-and-support/
