### ISSUE TITLE
Fresh WordPress 4.0 install: Allowed memory size exhausted when adding first episode

### ISSUE THREAD

**Issue by treyturner** [podlove/podlove-publisher#527]
Hello,
I just completed a fresh installation of Wordpress 4.0 on a sandbox subdomain where I am demoing version 1.10.21-alpha of your plugin. The plugin seemed to install correctly (via the Wordpress 'Add plugin' flow), and I was able to configure the plugin settings without issue, but when I click 'Add New' to create my first episode, I receive the following error:

Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 65484 bytes) in /home/username/podlove/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/lib/helper.php on line 11

The rest of this installation and my primary domain seem to be working correctly; do you have any ideas why this error might be occurring? Thanks for your help.

**Comment by treyturner** [comment]
Sorry about that. About a month after your last response, I booted up a new droplet and it seemed to work without issue - it must have been something about the cPanel installation or the subdomain configuration. Thanks for your willingness to troubleshoot further.

**Comment by eteubert** [comment]
ok, nice, thanks for coming back to reply :)

**Comment by vedinasvlad** [comment]
Wordpress sets by default tha max memory limit to 256M. This overides the php.ini memory_limit. You can change it from /wp-includes/default-constants.php line 28
