### ISSUE TITLE
Podcast Clients können mit Tracking URL's nicht umgehen.

### ISSUE THREAD

**Issue by MircoBlitz** [podlove/podlove-publisher#528]
Wenn man das Tracking Feature eingeschaltet hat, dann können die Clients PodcastApp (Apple) und Castro (Instacast komischerweise nicht) die heruntergeladene Datei nicht speichern und zeigen einen Fehler an. Castro sagt "No valid media file". Die Podcastapp weigert sich nach nem dowload komplett die Folge ab zu spielen, nicht einmal streamen geht dann. 

Streamen ging aber immer, von daher schätze ich, das die falschen Dateiendungen ankommen und die Clients dann ins stolpern kommen. Einzige Möglichkeit das wieder zu fixen, ist das Tracking feature zu deaktivieren und den Feed aus dem Client zu löschen und neu an zu legen.

**Comment by schaarsen** [comment]
Reproduzierbar ist es nicht, aber ich bekomme ähnliches Feedback. Bei mir betrifft es zwei Podcasts und immer sind es Nutzer der Apple Podcast-App. Der Feed wird korrekt angezeigt, aber die Episoden lassen sich nicht abspielen. Allerdings, und das meine ich mit "nicht reproduzierbar", scheint es nicht immer und überall zu passieren: Bei einem Hörer verschwand das Problem von alleine wieder und bei einem anderen tauchte es erst mit mehreren Wochen Verzögerung überhaupt auf. Ich werde die Funktion mal testweise ausschalten und dann noch einmal berichten.

**Comment by eteubert** [comment]
Wir konnten bisher einen Fehlerfall aufdecken, auf den wir in Zukunft auch automatisiert hinweisen werden:

Wenn die *Webseite über https* ausgeliefert wird aber die *Dateien über http*, streiken die Clients, weil von einem sicheren Medium auf ein unsicheres weitergeleitet wird. Dagegen hilft nur a) Fileserver auf https umstellen oder b) Tracking ausschalten.
