### ISSUE TITLE
Piwik / Spyc code conflict (due to multiple composer based plugins)

### ISSUE THREAD

**Issue by nichtsistwahr** [podlove/podlove-publisher#542]
After updating the Podlove plugin to 1.10.22-alpha, my wp-piwik/Piwik instance stopped working:

```
PHP Fatal error:  Cannot redeclare class Spyc in <redacted>/piwik/vendor/mustangostang/spyc/Spyc.php on line 57
```

It seems to conflict with the newly-introduced vendor/mustangostang/spyc/Spyc.php

Reverting back to 1.10.21-alpha resolved the issue.

**Comment by nickfmc** [comment]
I think getting some attention on this ticket would help fix this issue at the root cause. https://github.com/mustangostang/spyc/issues/48
