### ISSUE TITLE
Is it possible to have a video feed but not have video in episode player?

### ISSUE THREAD

**Issue by runneraaron** [podlove/podlove-publisher#543]
I am wondering if it is possible to have a video feed, but I don't want the video player in each episode slowing down my site. Also video seems to be having problems playing on my test site. File downloads to podcatcher fine however. http://www.aaronolson82.dreamhosters.com/

**Comment by eteubert** [comment]
Feature-Diskussionen ab sofort nur noch in [Trello](//trello.com/b/zB4mKQlD/podlove-publisher) oder [Podlove Community](//community.podlove.org).

Siehe auch: http://podlove.org/2015/04/22/the-podlove-community-and-support/

________________________

Feature-discussion will be moved to [Trello](//trello.com/b/zB4mKQlD/podlove-publisher) or [Podlove Community](//community.podlove.org).

See also: http://podlove.org/2015/04/22/the-podlove-community-and-support/
