### ISSUE TITLE
Feature Request: Add support for .sbv subtitles

### ISSUE THREAD

**Issue by runneraaron** [podlove/podlove-publisher#544]
Will podlove support .sbv subtitles?

**Comment by eteubert** [comment]
Feature-Diskussionen ab sofort nur noch in [Trello](//trello.com/b/zB4mKQlD/podlove-publisher) oder [Podlove Community](//community.podlove.org).

Siehe auch: http://podlove.org/2015/04/22/the-podlove-community-and-support/

________________________

Feature-discussion will be moved to [Trello](//trello.com/b/zB4mKQlD/podlove-publisher) or [Podlove Community](//community.podlove.org).

See also: http://podlove.org/2015/04/22/the-podlove-community-and-support/
