### ISSUE TITLE
Einzelne Episode aus dem Feed ausschließen

### ISSUE THREAD

**Issue by nicolasschabram** [podlove/podlove-publisher#545]
Hey,

gibt es die Möglichkeit, eine einzelne Episode aus dem Feed auszuschließen? Ggf. mit Custom Fields oder so?

Besten Dank,
Nicolas

**Comment by eteubert** [comment]
Feature-Diskussionen ab sofort nur noch in [Trello](//trello.com/b/zB4mKQlD/podlove-publisher) oder [Podlove Community](//community.podlove.org).

Siehe auch: http://podlove.org/2015/04/22/the-podlove-community-and-support/

________________________

Feature-discussion will be moved to [Trello](//trello.com/b/zB4mKQlD/podlove-publisher) or [Podlove Community](//community.podlove.org).

See also: http://podlove.org/2015/04/22/the-podlove-community-and-support/
