### ISSUE TITLE
Schlagwörter für Kapitel & Schlagwortwolken-Wigdet

### ISSUE THREAD

**Issue by KonScience** [podlove/podlove-publisher#546]
Die WordPress-eigene Schlagwortwolke bezieht sich leider nur auf ganze Episoden (oder Beiträge). Um einzelne Kapitel auch über verschiedene Folgen (und später auch über verschiedene Podcasts) hinweg besser zu adressieren, wäre eine Podlove-eigene Verschlagwortung wünschenswert.

Diese Idee ist noch etwas roh, Redebeiträge dazu auch [hier](http://www.radiomono.net/?podcast=rmn-019-ganzohr2014-4-vortrag-dr-sebastian-ritterbusch#t=16:35.269). Im Endeffekt sollten Schlagwörter während der Erstellung der Sendungsnotizen zu einzelnen Kapiteln hinzugefügt werden können. Vielleicht als `#Schlagwort` im Kapiteltitel oder als @shownotes Tags (ähnlich [diesen](https://github.com/shownotes/OpenShownotesFormat/issues/12) & [beiden](https://github.com/shownotes/OpenShownotesFormat/issues/11) Ideen).

**Comment by eteubert** [comment]
Feature-Diskussionen ab sofort nur noch in [Trello](//trello.com/b/zB4mKQlD/podlove-publisher) oder [Podlove Community](//community.podlove.org).

Siehe auch: http://podlove.org/2015/04/22/the-podlove-community-and-support/

________________________

Feature-discussion will be moved to [Trello](//trello.com/b/zB4mKQlD/podlove-publisher) or [Podlove Community](//community.podlove.org).

See also: http://podlove.org/2015/04/22/the-podlove-community-and-support/
