### ISSUE TITLE
Feed not accesible for validation

### ISSUE THREAD

**Issue by ghost** [podlove/podlove-publisher#548]
Does anyone know why I would be getting this error? "Feed Paleo Runner AAC Audio is not accessible for validation" 

Could it have something to do with my managed WP hosting on GoDaddy? http://paleorunner.org/feed/aac/
http://paleorunner.org/

Website             http://paleorunner.org
PHP Version         5.4.16 (upgrade to 5.5 brings enhanced performance)
WordPress Version   4.0
Publisher Version   1.10.22-alpha
Web Player Version  2.0.17
curl Version        7.19.7
iconv               available
allow_url_fopen     1
simplexml           ok
max_execution_time  30
upload_max_filesize 64M
memory_limit        256M
disable_classes  
disable_functions  
permalinks          ok
podcast_settings  
web_player          ok
podlove_cache       on
assets  
    mp3    audio/mpeg
    m4a    audio/mp4
    srt    application/x-subrip
    chapters.txttext/plain
    psc    application/xml

0 errors
0 notices
Nice, Everything looks fine!

**Comment by auxiliaryjoel** [comment]
I am trying to generate a podcast feed rss in wordpress via a plugin called podlove  and the Podlove dashboard keeps giving me the error: 
Feed mp3-audio is not accessible for validation. 
I have no idea what this means or how to fix it?

**Comment by eteubert** [comment]
In your feed settings, make sure an URL slug is set 

![podcast_feeds_ _logbuch_netzpolitik_ _wordpress](https://cloud.githubusercontent.com/assets/235918/7557806/6ff676b6-f7ca-11e4-83e9-71ceefe4b730.png)

If that is not the cause, please paste your support snippet from `Podlove > Support`
