### ISSUE TITLE
Design Probleme mit Podlove Plugin 

### ISSUE THREAD

**Issue by GadgetSofa** [podlove/podlove-publisher#549]
Ich möchte jetzt auch endlich für meine Webseite Podcasts anbieten und habe schon seit einer sehr langen und sehr Glücklichen Zeit das WordPress Design Waipoua von Elmastudio (http://www.elmastudio.de/wordpress-themes/waipoua/). Doch genau jetzt macht es Probleme. Das Plugin Podlove ist Installiert und fertig eingerichtet. Als ich dann mein ersten Podcast Hochladen wollte und diesen veröffentlichen wollte bemerkte ich das die Seite komplett komisch aus sieht. Und zwar ist die Rechte Info Spalte jetzt unter dem Text. Und auch sonst hat sich die ganze Reihenfolge geändert. Aber nur dort.

Beispiel:
Podcast Seite:

http://gadgetsofa.de/2014/10/30/der-podcast-erblickt-das-licht-der-welt/

Normale Seite:

http://gadgetsofa.de/2013/03/24/refill-tanken-war-noch-nie-so-spannend-2/

Wie bekomme ich meine Podcast Seite genau so hin wie die anderen?

Vielen dank schon mal für jede Hilfe :)
Lg Steffen

**Comment by eteubert** [comment]
Sieht aus, als hättest du es noch hinbekommen :)
