### ISSUE TITLE
Feed caching

### ISSUE THREAD

**Issue by germanstudent** [podlove/podlove-publisher#585]
I'd like to suggest adding feed caching capabilities in podlove publisher out of the box. 

While there are caching plugins that work quite well it's usually kinda difficult to set them up, especially for beginners. When a podcast reaches > 100 episodes (or so) and the podcaster would like to offer all episodes, wordpress requires a substantial amount of time to deliver the feed, depending on the server setup, which can even lead to timeouts that trigger a delisting from podcast directories.

Since almost all feed delivery services like feedburner and feedpress are basically c***, self hosting feeds is more important nowadays, so it would be nice to have feed caching within podlove publisher.

**Comment by eteubert** [comment]
From feedback I got we have reached the _good enough_ area here, so I will close.
