### ISSUE TITLE
Backend: Contributor-Links werden doppelt geöffnet

### ISSUE THREAD

**Issue by nitramred** [podlove/podlove-publisher#605]
Hallo,
wenn ich beim Editieren der Contributors auf die neben den Services angezeigten "Testlinks" klicke, werden jedes Mal zwei Tabs geöffnet mit dem entsprechenden Link – einer würde aber genügen :-)
![contributors](https://cloud.githubusercontent.com/assets/4311852/5514751/c9350ce2-8849-11e4-95e0-a34997c6e60e.png)
Beste Grüße
Martin

**Comment by eteubert** [comment]
Hm, bei mir nicht. @chemiker kannst du das reproduzieren?

**Comment by chemiker** [comment]
@nitramred Welcher Browser?

**Comment by nitramred** [comment]
@chemiker Safari 8.0.2 unter Mac OS X 10.10.1

**Comment by chemiker** [comment]
@nitramred Besteht das Problem immer noch?

**Comment by nitramred** [comment]
Nein, alles bestens!
