### ISSUE TITLE
new template editor destroys existing templates, cannot create new templates

### ISSUE THREAD

**Issue by tobybaier** [podlove/podlove-publisher#610]
Hi,
I just updated to Wordpress 4.1 and Podlove Publisher 1.12.1. With much joy, I saw the new template editor, but the joy quickly turned into shock: the template I tried to edit was just empty then. Creating a new template did not work either. Deleting the template worked, but not the re-creation.

Please help, quickly, thank you :D

**Comment by blkdev** [comment]
I noticed the same issue. I guess you can use the 'Save' button in the upper-right corner as well but have to reload the page.

**Comment by eteubert** [comment]
> I noticed the same issue. I guess you can use the 'Save' button at the upper-right corner as well but have to reload the page.

This I could reproduce and is fixed in the next release.

**Comment by tobybaier** [comment]
Thank you, this is closed :)
