### ISSUE TITLE
Bitlove API ist http, was von https-Seiten geblockt wird

### ISSUE THREAD

**Issue by tabacha** [podlove/podlove-publisher#611]
Wenn ich meinen Podcast ( https://opsluten.de ) mit https öffen und die Chrome Java-Script Console öffne bekomme ich eine Fehler:

>Mixed Content: The page at 'https://opsluten.de/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://api.bitlove.org/by-enclosure.json?url=http%3A%2F%2Ffiles.opsluten.de….opsluten.de%2Fops002.ogg&url=http%3A%2F%2Ffiles.opsluten.de%2Fops002.opus'. This request has been blocked; the content must be served over HTTPS.

**Comment by eteubert** [comment]
Aktuell kannst du denke ich nur das Bitlove Modul deaktivieren, um das zu umgehen.

@astro ich erinnere mich schwach, dass du dich mit Tim darüber auf dem C3 unterhalten hast. Kannst 
du hier bitte noch mal den Stand zusammenfassen?

**Comment by astro** [comment]
Brauche noch ein Zertifikat.

**Comment by astro** [comment]
Jetzt gibts eins. Danke an @gglnx.

Vermutlich sollten die Torrent-Links im Response-JSON auch auf https-URLs zeigen, nech?

**Comment by timpritlove** [comment]
Wäre zu prüfen, wie gut BitTorrent-RSS-Clients mit https klarkommen. In der normalen Podcast-App-Welt gibt es da noch einige Probleme.

**Comment by astro** [comment]
API ist für Browser und betrifft RSS-Feeds nicht. Aber eigentlich sollte dort das selbe zutreffen: was über https angefragt wird sollte https-Links beinhalten. Gab da auch schon einen Patch der deployed werden will: https://github.com/astro/bitlove-ui/commit/74f7bfba87918ef777a9767c343e3a88791734ae

**Comment by timpritlove** [comment]
Dann habe ich Dich wohl falsch verstanden. Was für Links stehen in dem Response-JSON?

**Comment by astro** [comment]
Jene für die Browser.

**Comment by eteubert** [comment]
Wurde in c216cbdb behoben
