### ISSUE TITLE
Media Library Files not found

### ISSUE THREAD

**Issue by Chainmediafs** [podlove/podlove-publisher#617]
Hi,

I upload the media files with the media uploader in Wordpress,in the base url I inserted "www.domanin.com"/wp-content/uploads/ (domain.com being my website),but when I try to create a post it can not find the uploaded files.
I also tried to use the expert settings and change the url to this:
%media_file_base_url%%year%/%month%%episode_slug%%suffix%.%format_extension% in order to respect the wordpress structure but it is not working,an idea about how to fix this?

Thanks for your time

**Comment by eteubert** [comment]
For now, the Publisher expects all your files to be in the same directory.
Unfortunately, this cannot be done using the WordPress uploader. So please use an sFTP app instead for uploading files.
