### ISSUE TITLE
HELP! No RSS-Feed any more...

### ISSUE THREAD

**Issue by OlafDammann** [podlove/podlove-publisher#618]
Good Morning
I am panicing a bit: PodLove doesn’t create my RSS-Feed any more.
Feed-Address: http://leben-fuehren.de/feed/podcast
Errormessage: 
[2015-01-05 05:59:18] Validate feed LEBEN-FÜHREN.
[2015-01-05 05:59:18] Error: XML parsing error: :1:0: no element found, line 1 in Feed LEBEN-FÜHREN. 
------------------------------------------------
Website             http://leben-fuehren.de
PHP Version         
WordPress Version   4.1
Publisher Version   1.12.1-alpha
Web Player Version  2.0.17
curl Version        7.37.1
iconv               available
allow_url_fopen     
simplexml           ok
max_execution_time  180
upload_max_filesize 50M
memory_limit        256M
disable_classes     
disable_functions   
permalinks          ok
podcast_settings    
web_player          ok
podlove_cache       on
assets              
	mp3    audio/mpeg
1 ERROR: 
- allow_url_fopen must be activated in your php.ini
0 notices
------------------------------------------------
Created a new feed, klicked the repair-button, checked all episodes for something that looks different, no result.... I even changed the php.ini-setting to avoid the error in the systemsumary.

any idea how to bring it back to live?
Olaf

**Comment by timpritlove** [comment]
did you try hitting the repair button in Podlove -> Support?

**Comment by OlafDammann** [comment]
Yes :)

**Comment by eteubert** [comment]
I think you actually don't need `allow_url_fopen` any more. I will verify and probably remove that warning in the next version.
Try upgrading PHP (you are using 5.6.0 but the path to 5.6.4 provides several fixes — I could only verify locally that it works with 5.6.2).
Also, try deactivating your cache plugin to see if it is responsible.

**Comment by OlafDammann** [comment]
Thnaks for comments, here is what I did:
"WP Super Chache" off = no changes.
chaged PHP-VErsion to 5.6.2 = still no feed :( 
tried with several browsers, but the problem seems to sit in the Plugin: It states in the Dashboard: "LEBEN-FÜHREN	podcast	2 hours ago	0 B (2 B)	Entscheiden Sie sich für Führung!", looks to me as if it doesn't even create the XML-File...

**Comment by OlafDammann** [comment]
Damn... Even reinstalling te entire Plugin ddn't chane anything :(

**Comment by OlafDammann** [comment]
After lots of manual work everything is back now- Lesson learned. I'll be back to review PodLove again, once it has reached a more stabile status.
Thanks everyone for your effort!

**Comment by timpritlove** [comment]
Strange. First time we see this kind of behaviour. let us know if this keeps coming back.

**Comment by OlafDammann** [comment]
BANG! Happened again, but now I know why:
This is what I do: Each Podcast Episode has the Article and a different Summary-Text. Podlove creates the RSS-Feed out of these Summary Texts. I want to have a featured-Podcast article on the Frontpage, a teaser so to say. Avoid writing this text manually I use(d) RSS Multi Importer from Allen Weiss to read the Podlove RSS-Feed and simply publish the first entry on my Frontpage. This gives me automatically the Summary-Test as a featured-Article.
I finished the clean up from the big bang tonight so I activated the RSS Multi Importer again. After max 30 minutes the Podlove Feed collapsed (NOT immediately). The really bad part is, that I couldn’t manage to reanimate it, regardless of what I did de- or reactivate. Reinstalling Podlove and restore the backup from today brought it all back.
No clue, why these plugins don’t like each other. What really sucks, is that the Podlove didn’t came back at all.
Maybe this can help you guys a little.

**Comment by OlafDammann** [comment]
And my final one: Feed died today in the middle of the day, again. I am not aware of any changes in the system, so this was it.
Thanks

**Comment by timpritlove** [comment]
We still like to find the cause of this because it is really strange. Can you give us a list of WP Plugins you run alongside the Podlove Publisher in addition to "RSS Multi Importer"?

There are also alternatives to do what you want to do. With Podlove Templates you can easily create the snippet you want to have.

Unfortunately our lead developer @eteubert is on a trip to Asia right now so it might take another day to find the time to test this. But we probably want to recreate the setup to find out what is going wrong here. It might or might not be related to the Publisher at all as it might as well be WordPress cutting off the path to the Publisher for some weird reason. However, I am just speculating here.

**Comment by eteubert** [comment]
> After max 30 minutes the Podlove Feed collapsed (NOT immediately)

This might be due to caching. Add this to your wp-config.php to temporarily deactivate Podlove Caching, which should help tracing the issue:

```php
# wp-config.php
define('PODLOVE_TEMPLATE_CACHE', false);
```

I'm currently reading the RSS Multi Importer code to look for cues as to where there might be a conflict. I found one thing so far:

You *MUST NOT* put a slug in here that is used by the publisher

![rss-plugin](https://cloud.githubusercontent.com/assets/235918/5690317/a380c1a8-98bb-11e4-812e-d001375b5582.jpg)

Unfortunately there is no way for us to automatically check if any plugin registers a conflicting feed. If more than one feed is registered at the same path, WordPress just shrugs indifferently and ignores all but the last registered one.

**Comment by OlafDammann** [comment]
Nabend
@Tim: Here is the List of Plugins:
2 Click Social Media Buttons Von H.-Peter Pfeufer
404 to Start Von Jürgen Schulze 
Import Files Von Dion Hulse
Google Analytics by Yoast Von Team Yoast
iThemes Security Von iThemes.com
Jetpack von WordPress.com auswählen	Jetpack von WordPress.com (nur Statistics aktiv)
MailPoet Newsletter Von MailPoet
MainWP Child Von MainWP 
NextScripts Von Next Scripts
RSS Multi Importer Von Allen Weiss (is off now)
Social Login Von Claude Schlesser
Social Sharing Toolkit Von linksalpha
Subscribe to Comments Reloaded Von camu, Reedyseth, Raam Dev 
TinyMCE Visual Editor Comment Von Aaron Tran
UpdraftPlus - Backup/Restore Von UpdraftPlus.Com
WordPress Importer Von wordpressdotorg
WordPress SEO Von Team Yoast
WP Super Cache Von Automattic (switched it on and off)

@Eric: I didn't configure the export-Section, otherwise a conflict would be understandable. 

@both: what makes (my) live complicate is that Podlove doesnt' come back at a point in time. Messing up some config can happen, I guess, but what I experence here is that something really destroyed PodLove in my system.
I am really sorry, but I need to migrate off to Powerpress next week. I really like the idea behind podlove, to do more then yust publishing Podcasts but assisting with creating them. 
And I would like to use a german tool.

Schönen Abend euch beiden :) 
OLAF

**Comment by eteubert** [comment]
I will close since we still have no clue what creates the conflict in your setup and you moved on.
See you in a while & happy podcasting :)
