### ISSUE TITLE
Statistik-Feature unverträglich mit Windows Phone-Podcatcher

### ISSUE THREAD

**Issue by henningkrause** [podlove/podlove-publisher#619]
Ich habe im Resonator-Podcast das Podlove-Statistik-Feature aktiviert. Von unseren fünfstelligen Hörerzahlen hat bislang nur einer gemeckert, dass sein Client seitdem mit dem Abruf der Episoden nicht mehr klar kommt. Hier seine Hard-/Software-Konfiguration:

Podcatcher: Podcast Lounge Version 2.4.5.0 Full Version
Betriebssystem Windows Phone 8.1 (Version 8.10.12397.895)
Endgerät: Nokia Lumia 630

Er bekommt die Fehlermeldung: "Transfer faild :( [The http network provider returned an err". Rest der Fehlermeldung ist abgeschnitten und nicht lesbar.

Der Fehler tritt auch auf, wenn er unseren http- statt unseres https-Feed abonniert. Kann man was tun, außer ihn an den App-Hersteller zu verweisen? Danke!

**Comment by timpritlove** [comment]
Das Tracking-Feature macht keinen nennenswerten Voodoo. Hier werden lediglich HTTP-Redirects erzeugt. Damit sollte jeder Client klarkommen und Clients, die damit nicht klarkommen, sind schlicht fehlerhaft. Empfehle also eine Beschwerde bei Podcast Lounge.

**Comment by henningkrause** [comment]
OK, danke für die Einschätzung.

**Comment by henningkrause** [comment]
Nun meckern auch die BeyondPod-User unter Android, siehe https://twitter.com/hoemcke/status/552585448942747648 und https://twitter.com/Eastpak1984/status/552737782733750272

Was mir aufgefallen ist: Wir haben ja Webseite und Feed sowohl in http als auch in https. Im beiden Feeds (Beispiel http://resonator-podcast.de/feed/m4a/) sind jedoch die sowohl im <link>- als auch im <enclosure> https-URLs referenziert. Liegt das an einer Base-URL, die ich irgendwo gesetzt habe? In jedem Fall stehen dann Dinge wie https://resonator-podcast.de/podlove/file/1476/s/feed/c/m4a/RES049_Kurz_zu_Verdauungssystem_und_Gehirn.m4a im Enclosure. Das forwarded bei uns auf http://files.wrint.de/RES049_Kurz_zu_Verdauungssystem_und_Gehirn.m4a und da gibt es kein https. Kann es sein, dass die Clients bei dieser speziellen Konstruktion (Files auf anderer Domain ohne SSL-Zertifikat) berechtigterweise sagen: Vorsicht, da will mich jemand aus einer sicheren Umgebung in eine unsichere weiterleiten? Und deswegen abbrechen?

Was kann man tun? Gibt es Alternativen zum Ablegen der Files auf dem Wordpress-System?

Sorry fürs Rumnerven mit unserem https. Ich wollte doch bloß Gutes tun...

**Comment by eteubert** [comment]
Es kann sein, dass BeyondPod einen HTTP-Client benutzt, der zickt, wenn von https auf http redirected wird. Im Moment sehe ich für dich nur folgende Optionen:

a) Tracking ausschalten
b) http://files.wrint.de auf https umstellen
c) bei BeyondPod nachhaken

Wir können von uns aus (glaube ich) nicht viel nachbessern. Das Tracking läuft über die Webseite, also müssen wir das Protokoll nutzen, das dort ist — in deinem Fall https.

@timpritlove kennst du jemanden, der sich besser mit dem SSL Kram auskennt, der meine Theorie bestätigen kann? Dann könnten wir auf das Szenario zumindest automatisch testen und Warnungen spucken (\*hust\* conflicts \*hust\*)

**Comment by henningkrause** [comment]
Downcast (http://img.ly/B0fq) und Instacast sind auch betroffen. Ich habe daher das Tracking im Resonator nun wieder ausgeschaltet.

**Comment by timpritlove** [comment]
Ich finde Erics Vorschlag, den Download-Server auch mit https zu versehen eigentlich ganz gut. 

Ansonsten solltet ihr Euer SSL-Setup auch mal überarbeiten. Das sagt Chrome dazu:

The identity of this website has been verified by RapidSSL SHA256 CA - G3 but does not have public audit records.

The site is using outdated security settings that may prevent future versions of Chrome from being able to safely access it.

Your connection to resonator-podcast.de is encrypted with obsolete cryptography. However, this page includes other resources which are not secure. These resources can be viewed by others while in transit, and can be modified by an attacker to change the look of the page.

The connection uses TLS 1.2.

The connection is encrypted using AES_256_CBC, with SHA1 for message authentication and ECDHE_RSA as the key exchange mechanism.

**Comment by m0dprobe** [comment]
> Ansonsten solltet ihr Euer SSL-Setup auch mal überarbeiten.

Ich muss da @henningkrause mal verteidigen. 
tl;dr: Die SSL-Infrastruktur von [resonator-podcast.de](https://resonator-podcast.de) ist in Ordnung.

---

[SSLLabs spuckt ein "A"](https://www.ssllabs.com/ssltest/analyze.html?d=resonator-podcast.de) für `resonator-podcast.de` aus.

> The site is using outdated security settings that may prevent future versions of Chrome from being able to safely access it.

Das zeigt Chrome an, wenn ein Zertifikat in der trust chain mit SHA-1 verschlüsselt ist, was potentiell unsicher sein kann. Das unsichere Zertifikat hier ist aber nicht das von `resonator-podcast.de`, sondern das Root-Zertifikat von GeoTrust, mit dem das CA-Zertifikat von RapidSSL signiert wurde. Darauf hat @henningkrause also null Einfluss.

> Your connection to resonator-podcast.de is encrypted with obsolete cryptography. However, this page includes other resources which are not secure.

Diese Ressourcen sind hauptsächlich die eingebundenen Files von `files.wrint.de`, was eben kein Zertifikat besitzt. Das ist imho der einzige Punkt an dem man ansetzen könnte und auch das Einzige was in puncto SSL Probleme macht bzw. machen könnte. Falls holgi kein Interesse hat, [wrint.de](http://www.wrint.de) abzusichern, kann man bei [StartSSL](https://www.startssl.com) für eine Domain ein kostenloses Zertifikat bekommen. Alternativ sollte es als Podcast der Helmholtz-Gemeinschaft doch nicht so schwierig sein, ein Zertifikat von einem der Teilnehmer der [DFN-PKI](https://www.pki.dfn.de) zu bekommen ;)

Das Setup von `resonator-podcast.de` ist also wirklich nicht das Problem hier, sondern eher das von `files.wrint.de`.
