### ISSUE TITLE
Feed incompatible with theme "getnoticed"

### ISSUE THREAD

**Issue by GoetzMueller** [podlove/podlove-publisher#620]
More details to be found here http://feedvalidator.org/check.cgi?url=http%3A%2F%2Fwww.geemco.de%2Ffeed%2Fmp3%2F

Podlove itself also recognizes these issues. Excerpt from the Dashboard log:
[2015-01-12 11:07:41] Validate feed mp3.
[2015-01-12 11:07:41] Warning: Use of unknown namespace: http://podlove.org/simple-chapters, line 1 in Feed mp3.
[2015-01-12 11:07:41] Warning: Implausible date, line 9 in Feed mp3.
[2015-01-12 11:07:41] Warning: Self reference doesn't match document location, line 10 in Feed mp3.
[2015-01-12 11:07:43] Validate feed ACC.
[2015-01-12 11:07:43] Warning: Use of unknown namespace: http://podlove.org/simple-chapters, line 1 in Feed ACC.
[2015-01-12 11:07:43] Warning: Implausible date, line 9 in Feed ACC.
[2015-01-12 11:07:43] Warning: Self reference doesn't match document location, line 10 in Feed ACC.
[2015-01-12 11:07:43] End scheduled feed validation.

There should be two episodes, also according to the Dashboard log:
[2015-01-12 08:07:36] Begin scheduled asset validation.
[2015-01-12 08:07:36] Validate episode	Kaizen 2 go 002 – Was ist denn KVP überhaupt?
[2015-01-12 08:07:36] Validate episode	Kaizen 2 go 001 – Worum geht’s hier eigentlich?
[2015-01-12 08:07:36] End scheduled asset validation.

But the feed doesn't include them.

Any ideas?

**Comment by eteubert** [comment]
> Warning: Use of unknown namespace: http://podlove.org/simple-chapters, line 1 in Feed ACC.

This warning is a feedvalidator bug and can be ignored

> Warning: Implausible date, line 9 in Feed ACC.

This will disappear once you have a published episode.

> There should be two episodes. But the feed doesn't include them. Any ideas?

In the Podlove Dashboard box "Validate Podcast Files", are there green checkmarks?
Sorry for the dumb question but I have to ask: are the episodes published? :)

For my own reference, your support output: https://github.com/podlove/podlove-publisher/issues/616#issuecomment-68927859

**Comment by GoetzMueller** [comment]
Yes, they have been published.
http://www.geemco.de/artikel/k2g-001-worum-gehts-hier-eigentlich/
http://www.geemco.de/artikel/kaizen-2-go-002-was-ist-denn-kvp-ueberhaupt/

All positions in the Dashboard have green checkmarks.

![bildschirmfoto 2015-01-13 um 19 57 33](https://cloud.githubusercontent.com/assets/10376917/5726796/7d881e60-9b5e-11e4-86f2-526fefa36c32.png)

**Comment by eteubert** [comment]
Looking good so far.

Can you also send me a screenshot of

1) your Episode Assets screen and
2) One of your Feed configs?

**Comment by GoetzMueller** [comment]
![bildschirmfoto 2015-01-15 um 13 03 28](https://cloud.githubusercontent.com/assets/10376917/5757024/1a600802-9cb7-11e4-8412-8e59036de1e4.png)

![bildschirmfoto 2015-01-15 um 13 05 27](https://cloud.githubusercontent.com/assets/10376917/5757034/42c47ef4-9cb7-11e4-84e1-5be539c1bc03.png)

![bildschirmfoto 2015-01-15 um 13 07 05](https://cloud.githubusercontent.com/assets/10376917/5757051/79e2dd2c-9cb7-11e4-8c5e-dbaf5b0029e2.png)

![bildschirmfoto 2015-01-15 um 13 08 39](https://cloud.githubusercontent.com/assets/10376917/5757078/bfcb696c-9cb7-11e4-90b7-47a8a288bfa5.png)

**Comment by eteubert** [comment]
Looks perfectly correct.

At this point I would have to debug on the code level. So I offer you a debugging on your system if you want to.

I would need:

1) a WordPress admin account
2) (s)FTP access to the WordPress directory

to eric@ericteubert.de

**Comment by GoetzMueller** [comment]
Admin account has been added and sent to your email address. The login area is also secured, same account and password.

The password for the sftp account is the same but without special characters. I'll send you the sftp account via email. It provides access of wp-content.

**Comment by GoetzMueller** [comment]
Can we somehow sync our activities? I'll need to add and schedule two episodes by Sunday night (18.1.) for publication on Monday morning resp. the following Monday and want to avoid any interference.

**Comment by eteubert** [comment]
I just tried to login but without success. I can't get through the HTTP Authentication using the WordPress login.
sFTP might work, it looks like I'm currently ip-blocked for too many failed Login attempts, so I can't try again.
You can write here when you start/stop working.

**Comment by eteubert** [comment]
Solution Summary:

The theme "getnoticed" hooks into the `pre_get_posts` hook and overrides the post types — whereby it kills the podcast post type for all feeds:

```php
global $_THEME;
$types = $_THEME->get('mainfeed');
if ( ! is_array($types) ) $types = array();
$query->set( 'post_type', $types );
```

I will fix this in the Publisher by hooking in after the theme and overriding the post type again (but only, of course, in the scope of podcast feeds):

```php
add_action('pre_get_posts', function ($query) {
	$query->set('post_type', 'podcast');
}, 20);
```

**Comment by GoetzMueller** [comment]
Great! Many thanks for the support!
