### ISSUE TITLE
Feature Request: freesound.org in service.social

### ISSUE THREAD

**Issue by HorstFrank** [podlove/podlove-publisher#621]
könntet ihr freesound.org in die service.social übernehmen? Oder hat der webservice eine eher kleine relevanz?

**Comment by timpritlove** [comment]
Könnten wir. Du bist der erste der fragt. Mir war noch gar nicht bewusst, dass hier öffentliche Profile rumlungern. Können wir einbauen. Gibt es da ein quadratisches Logo irgendwo? Sehe da nur den ewig breiten Schriftzug.

**Comment by eteubert** [comment]
Feature-Diskussionen ab sofort nur noch in [Trello](//trello.com/b/zB4mKQlD/podlove-publisher) oder [Podlove Community](//community.podlove.org).

Siehe auch: http://podlove.org/2015/04/22/the-podlove-community-and-support/

________________________

Feature-discussion will be moved to [Trello](//trello.com/b/zB4mKQlD/podlove-publisher) or [Podlove Community](//community.podlove.org).

See also: http://podlove.org/2015/04/22/the-podlove-community-and-support/
