### ISSUE TITLE
wordpress plugin section

### ISSUE THREAD

**Issue by alokpant** [podlove/podlove-publisher#622]
I am having a strange problem. Whenever I install Podlove Publisher, my wordpress admin section for new plugin installation shows error as:

'An unexpected error occurred. Something may be wrong with WordPress.org or this server’s configuration. If you continue to have problems, please try the support forums.'

Suggested plugins from Wordpress does not appear. And when I uninstall/ deactivate Podlove, it comes back again.

![podlove](https://cloud.githubusercontent.com/assets/6135761/5709366/8a06f866-9a99-11e4-9e29-31b5e0df3afb.png)

I am using Wordpress 4.1 version. I have done a fresh installation twice. Don't know what the problem is.

**Comment by alokpant** [comment]
I again deleted Wordpress, removed database and then installed Wordpress. The same thing happened. As soon as I install Podlove plugin (before that I installed other plugins) the unexpected error message is displayed.

**Comment by eteubert** [comment]
Does it happen if you only activate the Publisher Plugin?
Does it happen if you try the search more than once?
Does it only happen for search results or other tabs, too?

I was able to *sometimes* see a similar result — however, plugin section *always* worked for me, only did WordPress write the error message into the error log.

**Comment by alokpant** [comment]
The Podcast Plugin works fine. But whenever I try to install a new plugin, I have to deactivate Podlove and then install the new plugin. The error shows everytime I try to install new plugins.
