### ISSUE TITLE
Insert Episode(s) to Post or Page

### ISSUE THREAD

**Issue by minguy** [podlove/podlove-publisher#626]
Is there a way to insert an individual episode (or several episodes) into a post or page and have it show up with the web player?  I don't see it as a shortcode.  Thanks.

**Comment by eteubert** [comment]
Right now, it's not possible.

However, we could use templates for that. They would only need an additional "post-id" parameter to set the context.

**Comment by timpritlove** [comment]
It's a feature I think we had on the list for a while. Referencing an episode by episode-slug would be most appropriate I guess.

**Comment by minguy** [comment]
Thank you for the replies.

The Podlove Web Player has its own shortcodes (http://docs.podlove.org/podlove-web-player/). I did a few tests and the [podloveaudio] shortcode seems to work fine for what I need.  I'm not sure if you intended it to be used this way.  Is this a viable solution from a developer standpoint?

**Comment by eteubert** [comment]
For now, it's a viable workaround. But it's likely you will have to adjust it once the Web Player 2.0 is released — which would _just work_ if you are using the `[podlove-web-player]` shortcode or `{{ episode.player }}` template tag.

**Comment by eteubert** [comment]
Feature-Diskussionen ab sofort nur noch in [Trello](//trello.com/b/zB4mKQlD/podlove-publisher) oder [Podlove Community](//community.podlove.org).

Siehe auch: http://podlove.org/2015/04/22/the-podlove-community-and-support/

________________________

Feature-discussion will be moved to [Trello](//trello.com/b/zB4mKQlD/podlove-publisher) or [Podlove Community](//community.podlove.org).

See also: http://podlove.org/2015/04/22/the-podlove-community-and-support/
