### ISSUE TITLE
Podcast feed validates despite errors

### ISSUE THREAD

**Issue by rodti** [podlove/podlove-publisher#627]
I've installed Podlove on Wordpress 4.1 for a user.

They have created an MP3 asset, a feed and an episode.  In Dashboard both the asset and feed validate with a green 'tick', but when they try to add the feed to iTunes it refuses to accept it.

In Dashboard the following errors appear after validating the feed:

`[2015-01-13 22:15:10] Validate feed Test.
[2015-01-13 22:15:10] Warning: guid should not be blank, line 27 in Feed Test.
[2015-01-13 22:15:10] Warning: content:encoded should not contain controls attribute, line 29 in Feed Test.
[2015-01-13 22:15:10] Warning: content:encoded should not contain preload attribute, line 29 in Feed Test.
[2015-01-13 22:15:10] Warning: content:encoded should not contain object tag, line 31 in Feed Test.
[2015-01-13 22:15:10] Warning: content:encoded should not contain script tag, line 37 in Feed Test.`

I find it odd that in the first error the RSS on line 27 is:

`               <guid isPermaLink="false"></guid>`

What could be preventing the GUID from appearing?  There is a GUID in the episode page which I have tried regenerating several times.

Line 29:

`<content:encoded><![CDATA[<audio id="podlovewebplayer_b40d698792cade34c861d24dddd8d6cd28136d7b" controls="controls" preload="none" style="width: auto; height: 30px">`

Line 31:

`  <object type="application/x-shockwave-flash" data="flashmediaelement.swf">`

Any suggestions welcome!

**Comment by eteubert** [comment]
Is there any caching plugin active that could prevent the feed from being regenerated?

**Comment by rodti** [comment]
Nope, I've tried it with all plugins disabled and with the theme reverted to vanilla Wordpress.  The server does run XCache however.

**Comment by rodti** [comment]
I tried restarting Apache etc and that didn't have any effect.

**Comment by eteubert** [comment]
How do you embed the player? Because normally it should not render in the feed context.
Also, try disabling the Podlove cache to see if it causes any problems:

```
# wp-config.php
define('PODLOVE_TEMPLATE_CACHE', false);
```

**Comment by rodti** [comment]
OK, some progress!  I looked in Templates and found one called 'Default' with the following:

`{{ episode.player }}
[podlove-episode-downloads]`

I've removed this and now most of the errors have disappeared (along with the web player/download in the post, but we can come back to that!)

Now only the GUID error persists.  I've disabled the template cache in wp-config.php and it doesn't seem to make any difference.  I've tried regenerating the GUID a few times, updating the episode, moving it to draft and back to published etc.

**Comment by eteubert** [comment]
Does it work with a default WordPress theme?
Do you use any plugins that might mangle with how feeds are generated?

**Comment by rodti** [comment]
I've tried with the default theme and all plugins (except Podlove) disabled.

Bewildering!

**Comment by rodti** [comment]
I've deleted the site and the database.  Reinstall on a fresh install of Wordpress and Podlove with basic settings only, no plugins.  I still receive these errors when validating the feed:

[2015-01-26 17:35:14] Validate feed The xxxx.
[2015-01-26 17:35:14] Warning: guid should not be blank, line 27 in Feed The xxxx
[2015-01-26 17:35:14] Warning: content:encoded should not contain controls attribute, line 29 in Feed The xxxx.
[2015-01-26 17:35:14] Warning: content:encoded should not contain preload attribute, line 29 in Feed The xxxx.
[2015-01-26 17:35:14] Warning: content:encoded should not contain object tag, line 31 in Feed The xxxx.
[2015-01-26 17:35:15] Warning: content:encoded should not contain script tag, line 37 in Feed The xxxx.

**Comment by eteubert** [comment]
Most of the warnings are because there is a player in the feed. This is a problem with our default template.

Replace `{{ episode.player }}` with

```jinja
{% if not is_feed() %}
{{ episode.player }}
{% endif %}
```

and the `content:encoded` warnings should disappear.

The main problem, the missing guid, I still cannot explain. Did you check the PHP error log for entries?
I can also offer you to inspect an export of your setup if you send it to me (WordPress export + Podlove export via the Import & Export module)

**Comment by rodti** [comment]
Thanks but have gone with another solution. Appreciate your help and will keep an eye on Podlove for future podcasts.
