### ISSUE TITLE
Web Player wird mehrfach angezeigt.

### ISSUE THREAD

**Issue by doublest** [podlove/podlove-publisher#628]
ich habe das Problem, dass wenn ich im Template Editor den Sportcode [podlove-web-player] angebe, dann wird der Player mehr im Post angezeigt.

http://coffeeclash.de

PHP Version 5.4
Wordpress 4.1
Podlove 1.12.1-Alpha

![bildschirmfoto 2015-01-15 um 21 35 04](https://cloud.githubusercontent.com/assets/4710533/5766115/3f3ad538-9cff-11e4-8c47-f41d0f2bb159.png)
![bildschirmfoto 2015-01-15 um 21 35 25](https://cloud.githubusercontent.com/assets/4710533/5766119/468e463a-9cff-11e4-820d-f6f8e5c5f55b.png)

**Comment by doublest** [comment]
zudem scheint bei den vorherigen Posts das Template nicht korrekt zu greifen, der Player sollte am Ende stehen, siehe Screenshot.

Danke für den Support im Voraus ....

**Comment by doublest** [comment]
habe einen Workaround gefunden, wenn ich alle Templates lösche und die Sportcodes direkt in den Post eintrage funktioniert es http://coffeeclash.de

**Comment by eteubert** [comment]
Kannst du mir vorübergehend einen admin-Account einrichten, damit ich mir das auf dem System ansehen kann? Lokal bei mir funktioniert "leider' alles wie es soll.

**Comment by doublest** [comment]
Nutzer im Wordpress ist angelegt, Mail ging an eric@ericteubert.de

Danke im Voraus ....

**Comment by eteubert** [comment]
Da scheint ein grundsätzliches Problem vorzuliegen: http://codex.wordpress.org/Function_Reference/get_permalink gibt bei dir immer die Startseite aus anstatt der korrekten URL. Alle deine Episoden linken nur auf die Startseite. Ich benutze den Permalink intern, da er pro Seite einzigartig ist, aber wenn er das nicht ist, passieren komische Sachen :) 
Woher das kommt, ist mir unklar. Plugins hast du ja nicht viele aktiv. Aber vielleicht hast du selbst eine Idee.

**Comment by doublest** [comment]
ok, vielen Dank fürs analysieren, das gibt mir aber auf jeden Fall schonmal eine Richtung.
