### ISSUE TITLE
template tags - uploade url

### ISSUE THREAD

**Issue by sethiele** [podlove/podlove-publisher#630]
Hallo ich habe leider keinen Weg gefunden wie ich die Upload URL aus den Settings bekomme um sie als Template tag zu benutzen.

Gibt es da eine Möglichkeit?
Bis jetzt habe ich (bis auf den Slug) meine Assets hart codiert.

Danke

**Comment by eteubert** [comment]
Was genau ist dein Ziel? Ausgabe von Download-Links? Links solltest du dir im Normalfall nicht per Hand zusammenbauen. Beispiel dafür, wie es gedacht ist:

```jinja
<ul class="episode_download_list">
	{% for file in episode.files %}
	    {% set asset = file.asset %}
	    {% if asset.downloadable %}
			<li>
				<a href="{{ file.publicUrl("download", "buttonlist") }}">{{ asset.title }}<span class="size">{{ file.size|formatBytes }}</span></a>
			</li>
	    {% endif %}
	{% endfor %}
</ul>
```

**Comment by sethiele** [comment]
Vielen Dank für die Schnelle Antwort.
Ich habe vor den Player so anzupassen das er die Kapitelmarken aus dem json anzeigt.
Möglicherweise gibt es dafür ja ein anderen Weg, was ich aber bis jetzt habe ist:

```
[podloveaudio 
        mp3="http://www.assetsURL.de/{{ episode.slug }}.mp3"
        title="{{episode.title}}" 
        subtitle="{{episode.subtitle}}"
        summary="{{episode.summary}}" 
        poster="{{ episode.imageUrlWithFallback }}"
        chapters="http://www.assetsURL.de/{{ episode.slug }}.json"
        permalink="{{episode.url}}"
        duration="{{episode.duration}}"
        chaptersVisible="true"]
```

Und dazu brauche ich die URL.
Ist das richtig oder gibt es da einen anderen Weg?

**Comment by eteubert** [comment]
Das geht viel einfacher :)

Player anzeigen per `{{ episode.player }}`.
Dann musst du dem Publisher nur noch sagen, wo er das chapters asset finden soll und der Rest funktioniert einfach™:

![chapters-asset](https://cloud.githubusercontent.com/assets/235918/5792167/f428be90-9f45-11e4-843a-9895ff080602.jpg)

Allerdings gibt es da von Haus aus nur Support für mp4chaps und das PSC Format. Wenn du die chapters nur als JSON da hast, musst du dir unter `Podlove > Expert Settings > File Types` vorher noch einen neuen Typ anlegen und diesen im Asset verwenden:

![screen shot 2015-01-18 at 19 15 55](https://cloud.githubusercontent.com/assets/235918/5792177/77087922-9f46-11e4-8753-375ed988b4ae.png)

**Comment by sethiele** [comment]
Perfekt. Vielen Dank!
