### ISSUE TITLE
disable podlove web player

### ISSUE THREAD

**Issue by alokpant** [podlove/podlove-publisher#631]
Hi, 
The Podlove web player is filled with really great options and functionality. I am developing a simple website which does not have all these functionality needed. I am trying to display in the home page the web-player for latest episode so that users can directly listen to it. I managed it successfully, but the podlove web-player is little too big for that section. I tried installing another player but the podlove web player is showed on default. So I have two options: 
1. To disable Podlove player
2. Change the skin of web player using CSS.

I am trying the second option right now. Just wanted to ask if first option is available? 

Thank you.

**Comment by alokpant** [comment]
![cropped](https://cloud.githubusercontent.com/assets/6135761/5792986/401e4e6e-9f32-11e4-87a3-fe7e2b1b5eab.jpg)

Well I have managed to turn the Podlove player into this one. Which I am more than satisfied. But still if 1 exists then it would be really great.

**Comment by eteubert** [comment]
The episode content is defined in `Podlove ➜ Templates`. The default one should look like this:

![screen shot 2015-01-19 at 00 00 05](https://cloud.githubusercontent.com/assets/235918/5793015/4035cf08-9f6e-11e4-853f-f8efe92213cd.png)

If you remove the player there, it should disappear on your site.

**Comment by alokpant** [comment]
But if I remove {{ episode.player }}, I cannot listen to the files associated with the Episode.

<?php 	

				// load podcast

				$latestEpisodePodcast = new \Podlove\Template\Podcast(\Podlove\Model\Podcast::get_instance());
				$lstEpisode = $latestEpisodePodcast->episodes();
				$latestEpisode = $lstEpisode[0];
			?>

				<div class="episode_description">
					<label>Aktuelle Folge</label>
									
					<a class="clearfix" href="<?php echo $latestEpisode->url(); ?>">

						<?php 
							if (strlen($latestEpisode->title()) > 70) {
								echo substr($latestEpisode->title(), 0, 70)."...";
							} else {
								echo $latestEpisode->title();
							}
						?>

					</a>
					<label><?php echo $latestEpisode->publicationDate('F jS, Y'); ?></label>

					<span><?
						echo $latestEpisode->player(); 
					?></span>
				</div>

Do I have to use the template-tags to load the file?

**Comment by eteubert** [comment]
I'm not sure what you mean with "I cannot listen to the files" — yes, if you don't display the player, then there is no player. And you need to find your own way to display another player (which is what you asked for... ?).

If you are not sure how to get to the audio files via the template API, here is an example:

```jinja
<ul>
	{% for file in episode.files %}
	    {% set asset = file.asset %}
	    {% if asset.downloadable %}
			<li>
				<a href="{{ file.publicUrl("download", "link") }}">{{ asset.title }}<span class="size">{{ file.size|formatBytes }}</span></a>
			</li>
	    {% endif %}
	{% endfor %}
</ul>
```

You can use the same using the PHP API. Twig works on the same template classes. All tags are documented at http://docs.podlove.org/reference/template-tags/. You only need to dig around in the code a bit to figure out how to do it in PHP, since it's not (officially) supported — but it works.

**Comment by alokpant** [comment]
Thank you very much. I have managed to work around with your code to get what I wanted. This has improved the website very much.
