### ISSUE TITLE
Exclude Contributors From Feed

### ISSUE THREAD

**Issue by LeEnno** [podlove/podlove-publisher#634]
I have a default template for all my episodes:

```
<p>{{ episode.summary }}</p>
{{ episode.player }}
[podlove-episode-downloads]
[podlove-podcast-contributor-list]
```

I also have *Include HTML Content* in feeds enabled.

What really drives me nuts is the contributors table in Overcast:

![2015-01-22 10 17 07](https://cloud.githubusercontent.com/assets/2038814/5855726/b193afe2-a23b-11e4-8966-d493d5ffe545.png)

Is there a way to hide (or modify) the table for feeds only?

**Comment by eteubert** [comment]
That should do it:

```jinja
<p>{{ episode.summary }}</p>
{{ episode.player }}
[podlove-episode-downloads]
{% if not is_feed() %}
[podlove-podcast-contributor-list]
{% endif %}
```

**Comment by LeEnno** [comment]
Works, thank you!

Didn't know I could use wordpress functions in templates as well.
