### ISSUE TITLE
new asset type: online resources / hyperlinks

### ISSUE THREAD

**Issue by katrinleinweber** [podlove/podlove-publisher#635]
For my [ongoing](https://sendegate.de/t/optimaler-kanal-fur-vortragsaufzeichnungen/518) [experiments](http://www.konscience.de/2014/06/kns023-special-how-neural-networks-process-sensory-data-giovanni-galizia/) with lecture recordings, it would sometimes be helpful to have asset types that do not require files to be present in the Media Upload Location. Such as Google Slides, Prezis or journal articles in my case, but any kind of other website as well, if it is the main reference of an episode.

The goal would be to have these assets show up in the same prominent way as the media downloads currently do, colorful button, an icon that implies hyperlink & pre-defined label.

**Comment by eteubert** [comment]
We have been discussing a redesign of the "Media Upload Location" model recently. We are aware of its limitations and plan to implement a more flexible solution in the future.

**Comment by eteubert** [comment]
Feature-Diskussionen ab sofort nur noch in [Trello](//trello.com/b/zB4mKQlD/podlove-publisher) oder [Podlove Community](//community.podlove.org).

Siehe auch: http://podlove.org/2015/04/22/the-podlove-community-and-support/

________________________

Feature-discussion will be moved to [Trello](//trello.com/b/zB4mKQlD/podlove-publisher) or [Podlove Community](//community.podlove.org).

See also: http://podlove.org/2015/04/22/the-podlove-community-and-support/
