### ISSUE TITLE
Doppelter Eintrag im Feed

### ISSUE THREAD

**Issue by neufi** [podlove/podlove-publisher#636]
Im Dashboard bekomme ich eine Episode doppelt angezeigt, obwohl ich diese unter der Ansicht "All Episodes" nur ein mal sehe.
Hier das Log:

[2015-01-22 16:07:39] Warning: Use of unknown namespace: http://podlove.org/simple-chapters, line 1 in Feed mp3-audio-lq.
[2015-01-22 16:07:39] Warning: Self reference doesn't match document location, line 10 in Feed mp3-audio-lq.
[2015-01-22 16:07:39] Warning: Non-html tag, line 35 in Feed mp3-audio-lq.
[2015-01-22 16:07:39] Error: guid values must not be duplicated within a feed, line 867 in Feed mp3-audio-lq.

Kann sich hier jemand einen Reim daraus machen?

**Comment by eteubert** [comment]
Kannst du uns den Feed verlinken?

**Comment by neufi** [comment]
Hi,
vielen Dank für die schnelle Antwort.
Hier der Link zum Feed: 
http://fotopodcast.blitzdings.info/feed/mp3-audio/

Hier noch mal das Log, ich glaube oben im Log hatte ich die Episode auf draft gesetzt - sorry.
[2015-01-22 19:23:52] Warning: Use of unknown namespace: http://podlove.org/simple-chapters, line 1 in Feed mp3-audio.
[2015-01-22 19:23:52] Warning: Self reference doesn't match document location, line 10 in Feed mp3-audio.
[2015-01-22 19:23:52] Warning: Non-html tag, line 35 in Feed mp3-audio.
[2015-01-22 19:23:52] Error: guid values must not be duplicated within a feed, line 867 in Feed mp3-audio.itzdings.info/feed/mp3-audio/

Gruß Neufi

**Comment by eteubert** [comment]
> `[2015-01-22 19:23:52] Warning: Non-html tag, line 35 in Feed mp3-audio.`

Hier geht es um die Zeile `- FotografenWiki <http://www.fotografenwiki.org/>`. Du kannst entweder die spitzen Klammern entfernen oder `<` ersetzen mit `&lt;` und `>` mit `&gt;`.

> `[2015-01-22 19:23:52] Error: guid values must not be duplicated within a feed, line 867 in Feed mp3-audio.itzdings.info/feed/mp3-audio/`

Unklar, wie das passieren kann. Wenn du Datenbankzugang hast, kannst du das bitte mal ausführen und mir das Ergebnis mitteilen?

```sql
SELECT
	p.ID, p.post_date, p.post_title, p.post_status, p.post_name, p.post_type
FROM wp_postmeta m 
	JOIN wp_posts p ON p.ID = m.post_id
WHERE
	m.meta_key = "_podlove_guid"
	AND m.meta_value = "podlove-2015-01-22t15:25:38+00:00-009abe3ad11fcf9"
```

**Comment by neufi** [comment]
Guten Morgen,
die spitzen Klammern habe ich entfernt, aber an die DB komme ich nur über ein Webfrontend :-(

Leider bekomme ich ein "keine Datensätze" zurück wenn ich folgendes absetze:
    SELECT
    p.ID, p.post_date, p.post_title, p.post_status, p.post_name, p.post_type
FROM wpBlitzdings_7_postmeta m 
    JOIN wpBlitzdings_7_posts p ON p.ID = m.post_id
WHERE
    m.meta_key = "_podlove_guid"
    AND m.meta_value = "podlove-2015-01-22t15:25:38+00:00-009abe3ad11fcf9"

**Comment by timpritlove** [comment]
Der Eintrag für FPC115 erscheint doppelt im Feed. Kannst Du mal in Deine Episodenliste schauen, ob der da auch doppelt auftaucht?

**Comment by neufi** [comment]
Nein, das ist genau das was ich nicht verstehe.
Wenn ich die Episode auf Draft setze, dann sind beide aus den Feed und stehen im Dashboard als Draft :-(

**Comment by timpritlove** [comment]
Sprich: aus irgendwelchen Gründen landet die Episode doppelt im Feed. Hast Du da vielleicht mal einen Screenshot von der Episode?

**Comment by neufi** [comment]
Ich bin mir jetzt nicht so sicher welchen Bereich Du meinst, aber ich versuche mal zu orakeln:
der Link: http://fotopodcast.blitzdings.info/fpc110/
![dashboard_fotopodcast_dewordpress](https://cloud.githubusercontent.com/assets/5246014/5877989/ddf457ce-a323-11e4-9f87-9752b359b208.png)

![episodes_wordpress](https://cloud.githubusercontent.com/assets/5246014/5878133/ecf5cb58-a324-11e4-808e-d84b4b2e6ac0.png)

![edit_episode_wordpress](https://cloud.githubusercontent.com/assets/5246014/5878060/6410d030-a324-11e4-8b17-9f4154bc165d.png)

**Comment by timpritlove** [comment]
Hm, irgendwas sorgt auf jeden Fall dafür, dass der Publisher bestimmte Episoden (hier: FCP110 und FCP115) hier doppelt zählt. Ein Fall für @eteubert

**Comment by eteubert** [comment]
Da gibt es aus unerfindlichen Gründen doppelte Episoden-Objekte (aber nur ein Post-Objekt, weshalb es in der Post/Episoden-Liste nur einmal auftaucht).

Wie ist das denn entstanden? Hast du die Episoden migriert/importiert oder ist das zu einem unbekannten Zeitpunkt _passiert_?

Ließe sich lösen, indem man in der Datenbank die doppelten Episodenobjekte herumfummelt und eins davon löscht. Alternativ kannst du die beiden Posts/Episoden löschen und neu anlegen.

**Comment by neufi** [comment]
Ich vermute das ist passierte als ich die letzte Episode erstellt habe - ist aber nur eine Vermutung.

Vor einiger Zeit hatte ich schon einmal 3 Folgen löschen und wieder anlegen müssen - ist eben schon  blöde und vor allem aufwendig wenn das häufiger passiert.

Würde es etwas bringen den Podcast auf eine neue Installation zu migrieren?
Z.zt. läuft der Fotopodcast auf einer Multisite Installation und ich würde das gerne auf eine eigene WP-Installation umziehen - ginge das mit dem Migrationsassistent oder wie könnte man das machen?

**Comment by eteubert** [comment]
Du kannst mir gerne mal einen Datenexport schicken, dann kann ich mir das genauer ansehen.
Dazu bitte das "Import & Export" Modul anschalten, dann findest du Instruktionen unter `Podlove ➜ Import & Export`. Genau so kannst du auch eine Installation umziehen :)

**Comment by neufi** [comment]
Hab Dir den Export als Email geschickt.

Vielen Dank schon mal!!!

**Comment by eteubert** [comment]
Nach dem nächsten Update bitte den Repair-Button klicken.
Danke für die Hilfe :)

**Comment by neufi** [comment]
Hey super, ich bin gespannt :-)
Und vielen Dank für den tollen Support, da können sich andere mal 'ne ganz dicke Scheibe abschneiden!!!
