### ISSUE TITLE
upgrade posts to episodes

### ISSUE THREAD

**Issue by katrinleinweber** [podlove/podlove-publisher#637]
Would it be possible to add a function that takes existing WordPress posts (drafted or published) and turns them into episodes? Use case would be lecture announcements to which the recording, contributors and more show notes should be added. The [re:publica 2014 session pages](http://14.re-publica.de/event/1/sessions) did this in a very basic way by adding embedded YouTube videos.

As long as it affects only a few posts without comments, cutting-pasting their content into new episodes is feasible, or swapping out pre-defined template snippets, but for a conferences or university courses with either many recordings coming in at once, or regularly, some kind of upgrade button or even automation would IMHO be helpful.

**Comment by eteubert** [comment]
Try https://wordpress.org/plugins/post-type-switcher/

**Comment by katrinleinweber** [comment]
Works well for small numbers of posts, thanks for the hint :-)
