### ISSUE TITLE
Can't access WP dashboard after Podlove Publisher update

### ISSUE THREAD

**Issue by dnebannoS** [podlove/podlove-publisher#641]
Hi,
I just updated the Publisher from version 1.9.5-alpha to the latest one (1.12.1-alpha).

After doing so I can't access the dashboard anymore. Instead I get forwarded to "http://textlastig.com/wp-admin/index.php?podlove_page=podlove_upgrade&_wp_http_referer=%2Fwp-admin%2F". A blank, white page. The Blog still works (even the Podlove Publisher; I can see some minor visual changes to my templates) and I'm still logged in .. but trying to access the dashboard or edit a page or setting always leeds me to that URL.

What went wrong? And how can I fix it :)

I'm using the latest WordPress 4.1.

Btw. I'm running a seperate WordPress installation to test stuff. There have been no problems with WordPress or the Publisher. Both are running on the latest version. Maybe its the jump from 1.9.5. to 1.12.1 causing problems?

Thanks in advance,
Falk

**Comment by timpritlove** [comment]
1.9.5 and 1.12 are quite a jump. might be a bug in migration

**Comment by timpritlove** [comment]
can you check your php error log files for any errors please?

**Comment by dnebannoS** [comment]
Sorry for the late reply. I'm just a "Photoshop user" and had to check how to do that :)

As soon as I activated PHP error logging in the "wp_config.php" there were quite a few errors.

These are the error messages in the browser (homepage):

**Strict Standards: call_user_func_array() expects parameter 1 to be a valid callback, non-static method archivist::get_object() should not be called statically in /www/htdocs/w01020a7/textlastig/wordpress/wp-includes/plugin.php on line 496**

These are the error messages on the login page:

**Strict Standards: call_user_func_array() expects parameter 1 to be a valid callback, non-static method archivist::get_object() should not be called statically in /www/htdocs/w01020a7/textlastig/wordpress/wp-includes/plugin.php on line 496
Warning: Cannot modify header information - headers already sent by (output started at /www/htdocs/w01020a7/textlastig/wordpress/wp-includes/plugin.php:496) in /www/htdocs/w01020a7/textlastig/wordpress/wp-login.php on line 424
Warning: Cannot modify header information - headers already sent by (output started at /www/htdocs/w01020a7/textlastig/wordpress/wp-includes/plugin.php:496) in /www/htdocs/w01020a7/textlastig/wordpress/wp-login.php on line 437**

.. all of them were also in the error log file.

Under these circumstances I couldn't even log in anymore. But I saw "Archivist" mentioned there and temporarily renamed its plugin folder via FTP. After doing that I was able to log in again.

After logging in I had the following errors in the browser (still the only thing I get to see trying to reach the dashboard, etc.):

**Notice: wpdb::escape ist seit Version 3.6 veraltet! Benutze stattdessen wpdb::prepare() or esc_sql(). in /www/htdocs/w01020a7/textlastig/wordpress/wp-includes/functions.php on line 3378 Notice: wpdb::escape ist seit Version 3.6 veraltet! Benutze stattdessen wpdb::prepare() or esc_sql(). in /www/htdocs/w01020a7/textlastig/wordpress/wp-includes/functions.php on line 3378 Warning: Cannot modify header information - headers already sent by (output started at /www/htdocs/w01020a7/textlastig/wordpress/wp-includes/functions.php:3378) in /www/htdocs/w01020a7/textlastig/wordpress/wp-includes/pluggable.php on line 1178**

In the error log file:

**[28-Jan-2015 20:06:45 UTC] PHP Notice:  wpdb::escape ist seit Version 3.6 <strong>veraltet</strong>! Benutze stattdessen wpdb::prepare() or esc_sql(). in /www/htdocs/w01020a7/textlastig/wordpress/wp-includes/functions.php on line 3378
[28-Jan-2015 20:06:45 UTC] PHP Notice:  wpdb::escape ist seit Version 3.6 <strong>veraltet</strong>! Benutze stattdessen wpdb::prepare() or esc_sql(). in /www/htdocs/w01020a7/textlastig/wordpress/wp-includes/functions.php on line 3378
[28-Jan-2015 20:06:46 UTC] PHP Warning:  Cannot modify header information - headers already sent by (output started at /www/htdocs/w01020a7/textlastig/wordpress/wp-includes/functions.php:3378) in /www/htdocs/w01020a7/textlastig/wordpress/wp-includes/pluggable.php on line 1178**


I'm not sure what all this means but I hope this stuff is somewhat useful to you guys .. and thanks for the help in advance :)

**Comment by timpritlove** [comment]
Actually, non of those error messages mention Podlove at all. Seems all to be related to other plugins and/or your WordPress installation.

**Comment by eteubert** [comment]
It's hard to say where the `wpdb::escape` error messages are coming from, could be any plugin or theme. I just checked, we still use it in one place — but only when viewing previews, so that should not be a problem for you.

You should definitely set `display_errors` to `0`, so errors will only be logged and not displayed on your system (this is what causes the `Cannot modify header information - headers already sent` warnings). You can do that in the `php.ini` or in php via `ini_set("display_errors", "0")`

From what you have posted, I can't see any _errors_, only _warnings and notices_. Only errors break a system, warnings and notices can't produce white pages. What you can always try is to rename/remove all plugins, log in, and then activate them one by one to isolate the issue.

**Comment by dnebannoS** [comment]
Thanks for the help/tips. I will definitely remove the "Archivist" plugin (it's no longer needed anyway) and then go through the rest of them and see what causes the problem.

**Comment by dnebannoS** [comment]
Quick update.

I deactivated or deleted all other plugins which didn't help with the problem.
Renaming the Podlove Publisher plugin folder solved it though. So the problem must somehow be related to it. Anyway .. I downgraded to an older version (1.9.5-alpha) from my backup. So the blog works again.

One question though. If I uninstall the Podlove Publisher plugin, what happens to all the data? Are episodes (etc.) stored in the database even after deleting the plugin? And do they show up again when a new version of the plugin is installed again? Sorry for these questions but I really don't know much about db's and plugins :/

**Comment by eteubert** [comment]
_Deactivating_ a plugin is very similar to renaming it on the file system: All data is untouched.
If you, however, _Uninstall_ a plugin, its associated data is permanently removed from your system as well.

If you ever find yourself in the mood to debug again, this is the preferred way:

- deactivate all plugins again
- switch to a default theme (for example "twentyfifteen")
- activate or update the Publisher
- check the PHP error log again

**Comment by dnebannoS** [comment]
Thanks for the tips, Eric.

So we were in the "mood to debug again" and tried a few more things as suggested :)

Not sure how helpful this is .. but here's what we found:

### Starting point

Podlove Publisher Version: 1.9.5

Status:

* Website (Wordpress) works
* WP dashboard works
* Podlove Publisher & Player works
* no PHP errors

### What we tried
##### 1. Clean-Install of 1.9.5 based on GitHub (ZIP)

* Deactivated all plugins (except the Podlove Publisher)
* We deleted every file in the Podlove Plugin folder
* We downloaded the ZIP of Podlove Publisher 1.9.5 from GitHub
* We extracted the ZIP and uploaded the files into the empty Podlove Plugin folder

Result:

* Website (Wordpress) didn't work at all. Just a blank page.
* We couldn't access WP dashboard

PHP error log:

> Warning: require_once(vendor/autoload.php): failed to open stream: No such file or directory in /www/htdocs/account/textlastig/wordpress/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/podlove.php on line 24

> Fatal error: require_once(): Failed opening required 'vendor/autoload.php' (include_path='.:/usr/share/php:..') in /www/htdocs/account/textlastig/wordpress/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/podlove.php on line 24

##### 2. Compare our old 1.9.5 Installation (from backup) with the content of the 1.9.5 (ZIP) from GitHub

* We noticed two folders in our old backup that can't be found in the 1.9.5 (ZIP):
	* \vendor\*
	* \lib\modules\podlove_web_player\player\*
* We noticed one folder in the 1.9.5 (ZIP) which is not in our backup:
	* node_modules\grunt\*
* We restored our old 1.9.5 backup to the server
* Deactivated all plugins (except the Podlove Publisher)
* Copied all files from the 1.9.5 (ZIP) to the server (overwriting existing folders and files)

Result:

* Website (Wordpress) works
* WP dashboard works 
* Podlove Publisher & Player works

PHP error log:

> Warning: include_once(player/podlove-web-player/podlove-web-player.php): failed to open stream: No such file or directory in /www/htdocs/account/textlastig/wordpress/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/lib/modules/podlove_web_player/podlove_web_player.php on line 22
> Warning: include_once(): Failed opening 'player/podlove-web-player/podlove-web-player.php' for inclusion (include_path='/www/htdocs/account/textlastig/wordpress/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/vendor/phpunit/php-token-stream:/www/htdocs/account/textlastig/wordpress/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/vendor/phpunit/php-text-template:/www/htdocs/account/textlastig/wordpress/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/vendor/phpunit/php-file-iterator:/www/htdocs/account/textlastig/wordpress/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/vendor/phpunit/php-code-coverage:/www/htdocs/account/textlastig/wordpress/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/vendor/phpunit/php-timer:/www/htdocs/account/textlastig/wordpress/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/vendor/phpunit/phpunit-mock-objects:/www/htdocs/account/textlastig/wordpress/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/vendor/phpunit in /www/htdocs/account/textlastig/wordpress/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/lib/modules/podlove_web_player/podlove_web_player.php on line 22

##### 3. Upgrade to 1.9.6

* We started again with our old 1.9.5. backup
* Deactivated all plugins (except the Podlove Publisher)
* Downloaded 1.9.6 (ZIP) from GitHub, extracted and uploaded the files to our server

Result:

* Website (Wordpress) didn't work at all. Just a blank page.
* We couldn't access WP dashboard

PHP error log:

> Warning: include_once(player/podlove-web-player/podlove-web-player.php): failed to open stream: No such file or directory in /www/htdocs/account/textlastig/wordpress/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/lib/modules/podlove_web_player/podlove_web_player.php on line 25
> Warning: include_once(): Failed opening 'player/podlove-web-player/podlove-web-player.php' for inclusion (include_path='/www/htdocs/account/textlastig/wordpress/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/vendor/phpunit/php-token-stream:/www/htdocs/account/textlastig/wordpress/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/vendor/phpunit/php-text-template:/www/htdocs/account/textlastig/wordpress/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/vendor/phpunit/php-file-iterator:/www/htdocs/account/textlastig/wordpress/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/vendor/phpunit/php-code-coverage:/www/htdocs/account/textlastig/wordpress/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/vendor/phpunit/php-timer:/www/htdocs/account/textlastig/wordpress/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/vendor/phpunit/phpunit-mock-objects:/www/htdocs/account/textlastig/wordpress/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/vendor/phpunit in /www/htdocs/account/textlastig/wordpress/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/lib/modules/podlove_web_player/podlove_web_player.php on line 25

##### 4. Update to 2.0.3

* We started again with our old 1.9.5. backup
* Deactivated all plugins (except the Podlove Publisher)
* Updated Podlove Publisher to 2.0.3 via Wordpress web-interface

Result:

* Website (Wordpress) works
* We couldn't access WP dashboard
* no PHP errors

Do you have any recommendation on how to continue?
Since the plugin seems to be the cause of the problem (from what I understand anyway) I can't simply update it. It would break the WP-dashboard or the whole site again. If I uninstall it completely and install a brand new version I seem to loose all content.
I would really like to use all the new features you guys put into the latest version though. Worst case I guess I simply stay with the super old version 1.9.5.

**Comment by eteubert** [comment]
Thanks for the effort :)

First of all, you *cannot use the GitHub zip*. Those are "raw" files that need to be built. If you want to download old versions, go to https://wordpress.org/plugins/podlove-podcasting-plugin-for-wordpress/developers/.

And this is my recommendation for you:

- start with your working 1.9.5
- upgrade to 1.9.12
- upgrade to 1.10.23
- ... until you run into a wall. But then at least we have a better understanding of where the problem starts to occur.

**Comment by dnebannoS** [comment]
Oh, wow. Sorry, I didn't know that. The archives looked totally fine to me :)
Thanks for the recommendation. We'll test that.

**Comment by dnebannoS** [comment]
I followed your recommendation. After copying 1.9.12 into the Podlove plugin folder the page doesn't work anymore. Just a blank page. No PHP error log.

Not sure this is related .. but our feed (http://textlastig.com/feed/mp3/) has some warnings as well. It seems to work though. But [podfilter.de](http://www.podfilter.de/podcasts?utf8=✓&q=textlastig) says it's offline ..

It seem we'll have to keep using 1.9.5 :(

**Comment by eteubert** [comment]
One more thing to try: https://github.com/stracker-phil/wp-no-white-screen/

The main issue is I can't infer anything from "white screen", you _must_ somehow get to an error message.  The tool I linked to above promises to help. If you try it out, please report back.

**Comment by chemiker** [comment]
Since there was activity in this thread for 2 years I'm closing it now. If the issue persists please leave a note.
