### ISSUE TITLE
"Your feed is not available via Bitlove."

### ISSUE THREAD

**Issue by magisternavis** [podlove/podlove-publisher#642]
I have four podcast feeds in publisher: aac, mp3, ogg, opus

Only the first one (aac) is shown as available within bitlove, the others are not, marked with a red 'x'. But in Bitlove all the feeds are there and up to date (there is only one episode at this moment).

Here is the [feed link list](http://podcast.in-lemgo.de/abonnieren) at the podcast website.
And here are the [feeds in bitlove](http://bitlove.org/magisternavis).

Thanks.

**Comment by timpritlove** [comment]
Where is a feed "shown as available within bitlove"? Not sure I understand what you are referencing

**Comment by magisternavis** [comment]
Please see the screenshots of the publisher below:

![safari snapz 002](https://cloud.githubusercontent.com/assets/10698841/5921346/90cd801a-a643-11e4-9608-fc17ca549735.png)
![safari snapz 003](https://cloud.githubusercontent.com/assets/10698841/5921345/90ccb4dc-a643-11e4-9ca3-03af07d80739.png)

See also [my bitlove feeds](http://bitlove.org/magisternavis). Maybe I did something erroneous there.

Thanks!

**Comment by chemiker** [comment]
Seems to be fine now. Please let us know if the issue persists.
