### ISSUE TITLE
Wordpress PubSubHubbub plugin PuSHPress

### ISSUE THREAD

**Issue by magisternavis** [podlove/podlove-publisher#643]
Does the publisher works together with the [PuSHPress plugin](https://wordpress.org/plugins/pushpress/)? So no additional PubSubHubbub server were neccesary. I need to enter an address in publishers config.

Thanks.

**Comment by timpritlove** [comment]
I don't think we have tested this yet. Our PubSubHubbub integration just adds a hub info to our feeds. While you could add your local site to that setting, the plugin still needs to read and update the podcast feeds accordingly.

**Comment by magisternavis** [comment]
It were nice to just install the plugin. I get an entry like this:
`<atom:link rel='hub' href='http://podcast.in-lemgo.de/?pushpress=hub'/>`

How can I test if a PubSubHubbub enabled feed works?

I contacted Joseph, the plugin creator about this issue.

**Comment by eteubert** [comment]
Feature-Diskussionen ab sofort nur noch in [Trello](//trello.com/b/zB4mKQlD/podlove-publisher) oder [Podlove Community](//community.podlove.org).

Siehe auch: http://podlove.org/2015/04/22/the-podlove-community-and-support/

________________________

Feature-discussion will be moved to [Trello](//trello.com/b/zB4mKQlD/podlove-publisher) or [Podlove Community](//community.podlove.org).

See also: http://podlove.org/2015/04/22/the-podlove-community-and-support/
