### ISSUE TITLE
How to setup amazon AWS Cloudfront with podlove?

### ISSUE THREAD

**Issue by runneraaron** [podlove/podlove-publisher#644]
Does anyone know how to set-up Amazon cloudfront for podlove publisher? I am currently using amazon S3 and would like to set-up cloudfront, but there are a lot of settings that I am not sure about. Any advice is much appreciated!

**Comment by runneraaron** [comment]
Thanks Eric,

I found this
http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/LinkFormat.html

I think I could make it work.

On Mon, Jan 26, 2015 at 12:24 PM, Eric Teubert <notifications@github.com>
wrote:

> I am not sure how much control you have over AWS CF URLs. But right now it
> has to be <base url>/<episode specific url section that must consist of
> parts known to the publisher>. You can customize the URL structure in Expert
> Settings ➜ Website ➜ Files & Downloads.
>
> You can see here
> https://github.com/podlove/podlove-publisher/blob/master/lib/model/media_file.php#L151
> how the URL is built. There is a filter, so you could definitely hook in
> there and add your own logic if required.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/podlove/podlove-publisher/issues/644#issuecomment-71510174>
> .
>



-- 
- Aaron
About http://about.me/aaronolson
Schedule www.meetme.so/aaronolson
Blog http://paleorunner.org

**Comment by runneraaron** [comment]
Eric, is there a better solution you can recommend?

On Mon, Jan 26, 2015 at 1:04 PM, Aaron Olson <aaronolson82@gmail.com> wrote:

> Thanks Eric,
>
> I found this
> http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/LinkFormat.html
>
> I think I could make it work.
>
> On Mon, Jan 26, 2015 at 12:24 PM, Eric Teubert <notifications@github.com>
> wrote:
>
>> I am not sure how much control you have over AWS CF URLs. But right now
>> it has to be <base url>/<episode specific url section that must consist
>> of parts known to the publisher>. You can customize the URL structure in Expert
>> Settings ➜ Website ➜ Files & Downloads.
>>
>> You can see here
>> https://github.com/podlove/podlove-publisher/blob/master/lib/model/media_file.php#L151
>> how the URL is built. There is a filter, so you could definitely hook in
>> there and add your own logic if required.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/podlove/podlove-publisher/issues/644#issuecomment-71510174>
>> .
>>
>
>
>
> --
> - Aaron
> About http://about.me/aaronolson
> Schedule www.meetme.so/aaronolson
> Blog http://paleorunner.org
>



-- 
- Aaron
About http://about.me/aaronolson
Schedule www.meetme.so/aaronolson
Blog http://paleorunner.org

**Comment by runneraaron** [comment]
Can you recommend a different CDN that would be better?

**Comment by eteubert** [comment]
Yea looks like it's possible. 
There are a lot of other CDNs out there but I don't have a lot of experience with any of them.
