### ISSUE TITLE
shortcode to list templates, analog to episode, feed or contributor list

### ISSUE THREAD

**Issue by katrinleinweber** [podlove/podlove-publisher#646]
Exchanging Podlove templates seems to be slow ATM. [A few repos exist](https://github.com/search?utf8=%E2%9C%93&q=podlove+template) and [some YouTube tutorials](https://www.youtube.com/results?search_query=podlove+template&search=Search). However, assuming that many people like to directly see what the template code is for a given website design (of their favourite podcast for example), how about giving the Podlove Publisher a function to publish the template code it uses? Like there already are for episodes, feeds and contributors.

For example `[podlove-template-list]` would render the template code (all that are configured, or only the ones in use) in a text box similar to the `podlove_system_report`. With a link to an episode or site that uses the template.

**Comment by chemiker** [comment]
The Twig codes used for shortcuts like [podlove-template-list] are available within the Publisher repository (e.g. here https://github.com/podlove/podlove-publisher/tree/master/lib/modules/contributors/templates). In addition, there is a [small guide](http://docs.podlove.org/podlove-publisher/guides/understanding-templates) on creating templates. 

@eteubert However, we should consider pointing out in the [documentation](http://docs.podlove.org/podlove-publisher/guides/understanding-templates) where the shortcode Twig templates can be found in the repo.
