### ISSUE TITLE
category menu missing

### ISSUE THREAD

**Issue by alokpant** [podlove/podlove-publisher#647]
Hallo,

The Category menu under 'Episode' has gone missing. I am able to successfully create categories via Post menu but they don't appear on the Episode Posts. The default wordpress Post and category are working fine. I can assign them via Posts.

![category_missing](https://cloud.githubusercontent.com/assets/6135761/5991864/48d8fb16-aa0a-11e4-964a-0c13728d6fb0.jpg)

I have tried these:

- Deactivate the plugin
- Attempt to repair the plugin
- Deactivated all other plugins
- Changed the theme to another one
- Uninstalled Podlove and reinstalled again.

But none of these work. This is very strange. It works perfectly in my localhost.

**Comment by timpritlove** [comment]
Have you enabled the "Categories" module in Podlove -> Modules?
