### ISSUE TITLE
Podcast Feed kann nicht gefunden werden

### ISSUE THREAD

**Issue by doublest** [podlove/podlove-publisher#648]
Podcast Feed kann im mobile Client kann zwar gefunden und angzeigt, aber nicht mehr abonniert werden. Es wird folgender Fehler (Screenshot) angezeigt. Getestet habe ich mit Instacast (neuese Version) und dem Apple Podcast Client (neueste Version).

Ich habe derzeit zwei Feeds konfiguriert:

http://coffeeclash.de/feed/mp3/ und
http://coffeeclash.de/feed/aac/

bei de URls funktionieren im Einzelaufruf und können bei Direkteingabe im Client auch abonniert werden.

Irgendwelche Ideen? Vielen Dank im Voraus.

![img_2329](https://cloud.githubusercontent.com/assets/4710533/6041122/8bb8e60a-ac79-11e4-8716-28a2dd3fa0da.PNG)

**Comment by eteubert** [comment]
Feed sieht ok aus und validiert.
Sind das auch exakt die URLs, die du bei iTunes eingetragen hast?

**Comment by doublest** [comment]
ahja, ich glaube den Fehler gefunden zu haben, in iTunes ist:

http://coffeeclash.de/feed/AAC/

registriert, also mit einem großgeschriebenen "AAC". Das macht tatsächlich einen Unterschied. Weißt du zufällig wie ich das in itunes ändern kann?

**Comment by doublest** [comment]
oder kann ich einfach den zweiten Feed in itunes angeben ?

**Comment by eteubert** [comment]
Meines Wissens kann man in iTunes gar nichts ändern, außer über den Inhalt des Feeds.
D.h. das Einreichen des zweiten Feeds ist eine gute Lösung.

**Comment by doublest** [comment]
wenn ich den mp3 Feed einreichen möchte sagt mir itunes, dass es diesen Feed schon gibt, iTunes unterscheidet daher nicht.

Ich habe versucht im Publischer -> Feed Settings den Flug probehalber wieder groß zu schreiben, die Änderungen werden aber leider nicht gespeichert,

**Comment by eteubert** [comment]
Es wird schon gespeichert, aber ich erzwinge an der Stelle lowercase, um Fehler zu vermeiden. Ob das ein Bug oder ein Feature ist, darüber lässt sich streiten :)

Aber vielleicht hilft dir http://www.apple.com/itunes/podcasts/specs.html#rss Sektion "Removing or Blocking Your RSS Podcast Feed"

**Comment by timpritlove** [comment]
Der Eintrag im iTunes Verzeichnis liefert als URL

"http://coffeeclash.de/feed/AAC/
"

Man beachte das Newline am Ende. Zumindest liefert das iTunes nach dem Abonnieren, wenn man "Copy Podcast URL" sagt. Das ist etwas merkwürdig.

Das Kernproblem ist, dass Eure Website beim Zugriff auf "http://coffeeclash.de/feed/AAC/" einen 404 liefert. Ihr könntet aber mit Podlove in "Podlove -> Expert Settings -> Redirect" einen entsprechenden Redirect einrichten oder den Feed Slug auf "AAC" ändern. Ich würde die Lösung mit dem Redirect empfehlen. Wenn ihr einen "Permanent Redirect" von "http://coffeeclash.de/feed/AAC/" auf "http://coffeeclash.de/feed/aac/" einrichtet, ändert sich in der Folge auch die URL im iTunes Verzeichnis und alles ist gut.

**Comment by doublest** [comment]
klasse, es funktioniert, vielen Dank für den Tip mit dem Redirect. Wird noch es empfohlen bzgl. des HTTP Returncodes? 307 o. 301 ??

**Comment by timpritlove** [comment]
Wie meinen? Permanent Redirect ist 301 und das solltest Du nehmen.

Das Update im iTunes Verzeichnis wird eine Weile auf sich warten lassen. Wenn der Crawler das nächste Mal vorbeikommt ist die URL geändert. Wann das stattfindet hängt von Deinem Releasezyklus ab und was iTunes sich daraus zusammendenkt.

**Comment by doublest** [comment]
alles klar, das meinte ich und hab es geändert. Danke ...

**Comment by doublest** [comment]
kleine Dankesspende an das Podlove Projekt ist raus .... vielen Dank auch an Eric für den Support.

**Comment by doublest** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/4710533/6079006/fd7a7218-adff-11e4-82c8-ddc318df07ea.jpg)

schade
