### ISSUE TITLE
Characters ' and " cause many backslahes in subtitle

### ISSUE THREAD

**Issue by David1701** [podlove/podlove-publisher#651]
When using the characters ' or " in the subtitle field somehow backslashes are inserted magically just before these characters.
![magic backslashes](https://cloud.githubusercontent.com/assets/5114568/6194675/a2465584-b3c6-11e4-9a5e-1491e2d53cda.png)

Website             http://www.schwarmtaler.de
PHP Version         5.5.21
WordPress Version   4.1
Publisher Version   2.0.0
Web Player Version  2.0.17
curl Version        7.35.0
iconv               available
allow_url_fopen     1
simplexml           ok
max_execution_time  1800
upload_max_filesize 16M
memory_limit        256M
disable_classes     
disable_functions   
permalinks          ok
podcast_settings    
web_player          ok
podlove_cache       on
assets              
	mp3    audio/mpeg
	m4a    audio/mp4
	opus   audio/opus
	psc    application/xml
	jpg    image/jpeg
	mp3    audio/mpeg

0 errors
0 notices
Nice, Everything looks fine!

**Comment by eteubert** [comment]
Thanks, will be fixed soon.
