### ISSUE TITLE
"Debug Tracking"-Fehler

### ISSUE THREAD

**Issue by nitramred** [podlove/podlove-publisher#652]
Hallo,
unter "Expert Settings" – "Tracking" – "Debug Tracking" habe ich folgenden Eintrag gefunden:
![debug_trecking](https://cloud.githubusercontent.com/assets/4311852/6199501/1b07c490-b448-11e4-8680-4f4dd2218771.png)
Könnt ihr sagen, woher diese Fehlermeldung kommt bzw. was man dagegen tun kann / muss?
Ich verwende den Publisher in Version 2.0.1
Beste Grüße
Martin

**Comment by eteubert** [comment]
Hilft der Reparatur-Button unter "Support"?

**Comment by nitramred** [comment]
Nach dem Knopf-Drücken erschien dieser Fehler:
```Fatal error: Class 'Symfony\Component\Yaml\Yaml' not found in /homepages/35/d28027874/htdocs/staatsbuergerkunde/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/lib/modules/social/social.php on line 83```
Wenn ich danach zurück gehe und die Support-Seite neu lade, erscheint zwar das hier:
![repair_done](https://cloud.githubusercontent.com/assets/4311852/6199545/b40776f2-b44a-11e4-98b2-ba5afeaf0086.png)
aber der Debug-Tracking-Error bleibt erhalten.

**Comment by eteubert** [comment]
Danke für den Yaml-Hinweis. Hat nichts mit deinem Problem zu tun, wird aber auch behoben :)

Ggf. liegt das Problem lediglich beim Publisher in der Auswahl der Test-Datei (ich vermute, das Bild-Asset ist als nicht herunterladbar konfiguriert). Generell scheint SKB ja zu laufen.

**Comment by nitramred** [comment]
Na immerhin ein Teilerfolg. Wenn nicht sogar ein ganzer. Du hast recht, Coverbilder sind bei mir nicht herunterladbar. Da der Rest wunderbar funktioniert, würde ich sagen, Du kannst den Issue schließen. Dankeschön und beste Grüße!
