### ISSUE TITLE
Moving podlove results in 404 with episodes

### ISSUE THREAD

**Issue by nielsk** [podlove/podlove-publisher#655]
I moved my wordpress-installation according to http://codex.wordpress.org/Moving_WordPress from http://niels.kobschaetzki.net/podcast to http://emui.kobschaetzki.net. That was easy. Then I changed all the URLs I could find in the podlove publisher.
I can open http://emui.kobschaetzki.net and everything looks fine, the webplayer works etc. But opening the permalink of an episode like http://emui.kobschaetzki.net/emui014-linux-desktopumgebungen/ results in a 404. What do I have to do?

**Comment by eteubert** [comment]
http://emui.kobschaetzki.net/emui014-linux-desktopumgebungen/ works for me

**Comment by nielsk** [comment]
oO 
Now it works for me, too. What the…
Thanks for having a look.
