### ISSUE TITLE
Seite funktioniert nach Podlove-Update nicht mehr

### ISSUE THREAD

**Issue by gamepaddy** [podlove/podlove-publisher#656]
Laut Hoster läuft auf meinem Server PHP Version 5.4.34, trotzdem erscheint die Meldung 
"Podlove Podcasting Plugin requires PHP 5.4 or higher.
You are running PHP 5.3.28-nmm1",
wenn ich die Seite aufrufe.

**Comment by eteubert** [comment]
Entweder irrt sich dein Hoster oder du hast mehrere PHP-Versionen laufen und dein Apache/nginx benutzt die alte. Ggf. musst du auch nur deinen Apache/nginx neu starten, um das aktuelle PHP Modul zu laden.

**Comment by gamepaddy** [comment]
Lässt sich irgendwo noch eine ältere Podlove-Version downloaden?

**Comment by eteubert** [comment]
https://downloads.wordpress.org/plugin/podlove-podcasting-plugin-for-wordpress.1.12.1-alpha.zip

**Comment by gamepaddy** [comment]
Apache neustarten funktioniert leider nicht.

**Comment by eteubert** [comment]
Dann solltest du deinen Support noch mal anschreiben. Ich benutze zum Anzeige/Vergleichen der PHP-Version die PHP-eigene Funktion `phpversion()` und die lügt nicht :)
