### ISSUE TITLE
Failed update -> everything gone

### ISSUE THREAD

**Issue by shinske** [podlove/podlove-publisher#657]
Hi guys,

I just logged into my wordpress, saw that there was a podlove update available, and installed it. There was some sort of error message that I can't recall (something about being unable to access/read a file maybe?). Unfortunately, I didn't really notice the message until it was too late and didn't do a screenshot. 

I figured I needed to do the update again, but the Podlove plugin now does not appear in my Wordpress plugins anymore. 

Next, I tried to reinstall the plugin. This resulted in a completely blank (white) page and nothing else. And now, the install button for the plugin has disappeared:
![unbenannt](https://cloud.githubusercontent.com/assets/6576680/6203648/b0317ca2-b52c-11e4-81d2-e93e8c7c628b.PNG)

Worst of all, this failed update resulted in every podcast episode completely disappearing. All episode posts made with the Publisher are gone from the site.

Cheers,
Jonas

**Comment by eteubert** [comment]
You can get the old version here: https://downloads.wordpress.org/plugin/podlove-podcasting-plugin-for-wordpress.1.12.1-alpha.zip Upload it via (s)FTP to your plugin folder and the Publisher should be working again.

It's hard to help without knowing the exact error message, though :)

**Comment by shinske** [comment]
I updated again to see if I could reproduce the error, but no such luck. This time, I just got a blank screen and a deactivated plugin. And my PHP was out of date, not sure if this was related to the error. Anyways, everything seems to be working again now, thanks!

**Comment by eteubert** [comment]
Ok, good, glad it works now! :)
