### ISSUE TITLE
Template kann nicht mehr gespeichert werden

### ISSUE THREAD

**Issue by benhartwich** [podlove/podlove-publisher#658]
Hallo,

ich nutze die aktuelle Podlove Version und möchte gern zwei deprecated shortcodes durch die neuen Template Tags ersetzen, allerdings werden die Änderungen nicht gespeichert. Das Rädchen dreht sich ewig, aber nichts passiert - also ich kann keine Template Änderungen mehr speichern.

Hier meine System Report:
Website             http://www.benjaminhartwich.de
PHP Version         5.5.21-1~dotdeb.1
WordPress Version   4.1
Publisher Version   2.0.2
Web Player Version  2.0.17
curl Version        7.26.0
iconv               available
simplexml           ok
max_execution_time  240
upload_max_filesize 200M
memory_limit        256M
disable_classes     
disable_functions   pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,
permalinks          ok
podcast_settings    
web_player          ok
podlove_cache       on
assets              
	mp3    audio/mpeg
	m4a    audio/mp4
	ogg    audio/ogg

0 errors
0 notices
Nice, Everything looks fine!

**Comment by eteubert** [comment]
Drehendes Rädchen heißt, dass irgendwo das Script stirbt; mit einem Fehler. Kannst du einen Blick ins PHP Error Log werfen?

**Comment by benhartwich** [comment]
Ich habe einen 403 sobald ich auf Speichern gehe, was allerdings nur in der Chrome Error Log zu sehen ist: http://www.benjaminhartwich.de/wp-admin/admin-ajax.php?id=1&title=Standard&content=%5Bpodlove-web-player%5D%3Cbr%3E%0D%0A%5Bpodlove-episode-downloads%5D%0D%0A%0D%0AVer%C3%B6ffentlicht+von+%3Ca+href%3D%22%5Bpodlove-podcast+field%3D%22publisher_url%22%5D%22+target%3D%22_blank%22%3E%5Bpodlove-podcast+field%3D%22publisher_name%22%5D%3C%2Fa%3E+unter+%3Ca+href%3D%22%5Bpodlove-podcast+field%3D%22license_url%22%5D%22+target%3D%22_blank%22%3E%5Bpodlove-podcast+field%3D%22license_name%22%5D%3C%2Fa%3E.%0D%0A%7B%23+iterating+over+a+list+of+contributors+%23%7D%0D%0A%7B%25+for+contributor+in+episode.contributors+%25%7D%0D%0A++++%7B%7B+contributor.name+%7D%7D%0D%0A++++%7B%25+if+not+loop.last+%25%7D%2C+%7B%25+endif+%25%7D%0D%0A%7B%25+endfor+%25%7D&action=podlove-template-updat

**Comment by benhartwich** [comment]
Es liegt an iThemes security sobald ich anhake, dass verdächtige URL Strings geblockt werden.

**Comment by eteubert** [comment]
Ich konnte das Verhalten bisher nicht reproduzieren, habe aber zumindest das Stück Code des Settings im Plugin gefunden. 

Ist mir unklar, wie ich das umgehen kann. Irgendwie muss ich den Template-Inhalt an den Server senden. Und wenn da irgendwas drin steht, das dem Security Plugin nicht gefällt, meckert es. 

Im Moment kann ich dir nur empfehlen, das Setting zu deaktivieren.

**Comment by benhartwich** [comment]
Ich kenne mich zwar nicht so gut aus, aber kannst du die Daten nicht via Post-Method schicken? Oder verwechsle ich da was?

**Comment by chemiker** [comment]
@eteubert Können wir das nicht einfach per POST statt per GET machen?

**Comment by eteubert** [comment]
Jetzt komme ich mir ziemlich blöd vor :expressionless:
Ja, natürlich geht das per POST. POST sollte ohnehin benutzt, werden, da GET nur für das Abholen von Daten gedacht ist, nicht für das Ändern.

Danke euch ^^
