### ISSUE TITLE
statistics about 20% higher than expected

### ISSUE THREAD

**Issue by leitmedium** [podlove/podlove-publisher#659]
Hey,

thanks for the great statistics feature. I checked the numbers against my basic log analysis and come to the conclusion that podlove statistics are about 20% higher than I expected. 

562 (log analysis) => 726 (podlove) … +29%
2.556 (log analysis) => 3.176 (podlove) … +24%
1.711 (log analysis) => 2.024 (podlove) … +18%

I checked what I did: I just do a dump oneliner that catches all GET requests for a media file (the real GETs not redirecting ones), sorts them by requesting ip address and counts how many different ips have been issuing this request:

```$ zgrep MEDIAFILE PATH/TO/LOGFILES/* | awk '{print $1}' | awk -F":" '{print $2}' | sort | uniq | wc -l```

So the main difference is probably that I count requests from the same ip as one. I checked my logfiles and guess it's not a bad idea as I see typical dial up adresses requesting the same file multiple times.

Am I calculating wrong here? Should I just think "stats are about 20% too high" or s this something that needs and can be adressed technically?

**Comment by eteubert** [comment]
From http://docs.podlove.org/guides/download-analytics/#data-cleanup

> - Based on the UA analysis bots are filtered out.
> - Duplicate requests are filtered out. A request is considered a duplicate if it contains
>   - the same File ID
>   - and the same Request ID
>   - and was made within the same hour

We just have different definitions for what a _duplicate request_ is. It's arguable how IPs should be handled:

- counted once per media file, as you are doing
- counted multiple times, but only once in a certain time frame (1h in our case, but arguments for larger time frames can be made)

**Comment by leitmedium** [comment]
Thanks for the reply. I assume there is no golden way, so I see the point of the decisions made. 

Best.

**Comment by timpritlove** [comment]
There are two ideas that come to my mind how this could be handled

- make the timeframe within duplicates are detected as such configurable
- generally count all downloads but also list the number of duplicate downloads (redownloads)
