### ISSUE TITLE
Feature Request: Editors can view the statistics/analytics

### ISSUE THREAD

**Issue by boderhamster** [podlove/podlove-publisher#660]
As dicussed on Twitter with @podlove_org it is currently not possible to share your statistics with editors or contributors on your blog.
When I mentioned this, I was aked to open this request on Github.

yours
Dominik

**Comment by timpritlove** [comment]
This is about WordPress capabilities. 

Can you describe scenarios how you'd like to configure the system in order to give proper permissions to users?

**Comment by eteubert** [comment]
We will probably offer some kind of UI in the future.
But for now, you can use a code snippet. See https://community.podlove.org/t/release-2-0-3/55
