### ISSUE TITLE
Episode Cover Art URL wird nicht gespeichert

### ISSUE THREAD

**Issue by benhartwich** [podlove/podlove-publisher#661]
Hallo,

immer wenn ich bei einer Episode eine URL für das Episodenbild eingebe, wird es beim Aktualisieren nicht gespeichert. Die URL lautet z.B. http://www.benjaminhartwich.de/podcast/24.jpg

In der nginx error log steht nichts und auch sonst kommt kein Error. Woran könnte das liegen?

**Comment by eteubert** [comment]
Funktioniert bei mir. 
Kannst du die alte URL nicht ersetzen oder stand vorher nichts drin?

**Comment by benhartwich** [comment]
Seit der 2er Version habe ich einen neuen Podcast produziert, d.h. das Feld war vorher und seitdem geht es auch nicht mehr. Bei allen bestehenden Podcasts sind die Links noch drin.

**Comment by katrinleinweber** [comment]
Gleiches Problem hier:  Recording Date, License Name und License URL werden ebenfalls nicht gespeichert. Außerdem verschwinden aus den  Chapter Marks alle links, sodass die Zeilen mit einem Leerzeichen enden, anstatt mit `<http://www....>`. Vielleicht mir seit https://github.com/podlove/podlove-publisher/commit/c966c364fd46dfd84009f918963b0ec2ddc208df etwas zu aggressiv gesäubert?

Habe Repair und das Anlegen einer neuen Episode schon probiert, sowie Entfernung aller Sonderzeichen aus den Kapiteltiteln.

**Comment by eteubert** [comment]
Danke @katrinleinweber, das ist exakt der schuldige commit :)

Wird im nächsten Hotfix behoben.

**Comment by katrinleinweber** [comment]
Bitteschön :-)

**Comment by katrinleinweber** [comment]
Das Hauptproblem ist gelöst, aber speziell aus der Summary verschwinden `<a href=""></a>`-Links immer noch.

**Comment by eteubert** [comment]
HTML in der summary? Hm. Sollte das nicht ohnehin plaintext sein @timpritlove?

**Comment by katrinleinweber** [comment]
Zumindest hat es vor dem 2er-Update funktioniert. Hm.

**Comment by timpritlove** [comment]
Summary is explizit plain text. HTML is nicht garantiert zu überleben.
