### ISSUE TITLE
Tracking URLs in Templates

### ISSUE THREAD

**Issue by carlito** [podlove/podlove-publisher#662]
Hi,

I build a custom web player (and a custom UI for download links) and these components are getting their files from a template. That's working fine. Now I'd love to use the new analytics magic but the twig variable `file.url` gives only the original location. Is there another template tag or twig variable to get the tracking URL? Couldn't find anything in the docs about that.

Thanksalot.

**Comment by eteubert** [comment]
Whoops, that was missing from the docs. I added it, but what you are looking for is `file.publicUrl`

http://docs.podlove.org/reference/template-tags/#file

**Comment by carlito** [comment]
Great, thanks!

**Comment by carlito** [comment]
I replaced `file.url` with `file.publicUrl` in my templates but now I get errors:

>Warning:  Missing argument 1 for Podlove\Template\File::publicUrl() in /path/to/plugin/lib/template/file.php on line 75

>Notice:  Undefined variable: source in /path/to/plugin/lib/template/file.php on line 76

**Comment by eteubert** [comment]
More missing documentation. The method expects one or two parameters: `$source` and `$context`. Since you are building a web player, the source (first parameter) should be "webplayer". 
The context (second parameter) ist optional. The core only differs between "home" and "episode" here.

**Comment by carlito** [comment]
Works, thanks! 

What are all predefined values for `$source`? What should I use for download links?

**Comment by carlito** [comment]
I figured out that the parameters `source` and `context` are part of the rewritten URL (/s/download/c/episode/). So I use 'download' as source for my download links now.
