### ISSUE TITLE
Episodes not yet available will be displayed as 160 bytes

### ISSUE THREAD

**Issue by jthoenes** [podlove/podlove-publisher#663]
When I add an episode - but have not uploaded it to podseed.org - I get a green mark and it claims to have 160 bytes.

![screen shot 2015-02-17 at 08 02 12](https://cloud.githubusercontent.com/assets/15578/6224384/5ba795cc-b67b-11e4-853e-c68e24157b46.png)

What is worse is, that once I do upload it to podseed.org and try to re-validate the size by clicking 'update all media files', I do not get the correct size.

This can be fixed by removing/commenting out the line 186 in lib/ajax/ajax.php:

````php
                header("Etag: $etag");
````

To me it seems, that the publisher stores the wrong etag, because of the redirects podseed.org does before it returns a 404.

````bash
~ $ curl -I http://cdn.podseed.org/alltaegliche/whatever.mp3
HTTP/1.1 302 Moved Temporarily
Server: nginx/1.6.0
Date: Tue, 17 Feb 2015 07:08:23 GMT
Content-Type: text/html
Content-Length: 160
Connection: keep-alive
Location: http://master.podseed.org/alltaegliche/whatever.mp3
Content-Disposition: attachment; filename="whatever.mp3"

~ $ curl -I http://master.podseed.org/alltaegliche/whatever.mp3
HTTP/1.1 404 Not Found
Server: nginx/1.6.0
Date: Tue, 17 Feb 2015 07:08:49 GMT
Content-Type: text/html
Content-Length: 168
Connection: keep-alive
````

Note: No etag is returned, therefore it should not store one.

**Comment by eteubert** [comment]
I can reproduce the podseed redirect with curl but my Publisher behaves differently from yours. Are you on the latest version?

`l.186 in lib/ajax/ajax.php` sets an etag, but for the `analytics_episode_downloads_per_hour` method. This has nothing to do with media file validation. Validation is located at https://github.com/podlove/podlove-publisher/blob/master/lib/ajax/file_controller.php#L19 and nothing is cached. I also resolve all curl redirects before I look at the returned `Content-Length`.

So ... ¯\\_(ツ)_/¯

**Comment by jthoenes** [comment]
Hi,

it seems like I'm on the latest version:

````
Website             https://der-alltaegliche.de
PHP Version         5.5.9-1ubuntu4.6
WordPress Version   4.1.1
Publisher Version   2.0.3
Web Player Version  2.0.17
curl Version        7.35.0
iconv               available
simplexml           ok
max_execution_time  30
upload_max_filesize 2M
memory_limit        256M
disable_classes     
disable_functions   pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,
permalinks          ok
podcast_settings    
web_player          ok
podlove_cache       on
assets              
	mp3    audio/mpeg
	chapters.txttext/plain
	m4a    audio/mp4
	oga    audio/ogg
	opus   audio/ogg;codecs=opus
	mp3.zip application/zip

0 errors
0 notices
Nice, Everything looks fine!
````

The request issued when I click the 'update' button in ''post.php?post=1311&action=edit' goes to https://der-alltaegliche.de/wp-admin/admin-ajax.php?action=podlove-file-update&file_id=339&slug=test

The response is:
````
{"file_url":"http:\/\/cdn.podseed.org\/alltaegliche\/test.mp3","file_id":339,"reachable":false,"file_size":160}
````

Still, I get a green checkmark - although the ``reachable: false``

The logging says:

````
[2015-02-25 10:03:06] Media file mime type does not match expected asset mime type.	/MP3 Audio Expected: audio/mpeg, but found: text/html
[2015-02-25 10:03:06] --- # Can't reach http://cdn.podseed.org/alltaegliche/test.mp3 --- # Please include this output when you report a bug url: http://cdn.podseed.org/alltaegliche/test.mp3 content_type: text/html http_code: 302 header_size: 275 request_size: 221 filetime: -1 ssl_verify_result: 0 redirect_count: 0 total_time: 0.096458 namelookup_time: 0.060383 connect_time: 0.078544 pretransfer_time: 0.078585 size_upload: 0 size_download: 0 speed_download: 0 speed_upload: 0 download_content_length: 160 upload_content_length: 0 starttransfer_time: 0.096418 redirect_time: 0 redirect_url: http://master.podseed.org/alltaegliche/test.mp3 primary_ip: 31.172.8.116 certinfo: Array ( ) primary_port: 80 local_ip: 85.214.76.49 local_port: 41741 php_open_basedir: /srv/der-alltaegliche/wordpress/:/tmp php_safe_mode: php_curl: 1 curl_exec: 1
````

Does this help?

**Comment by eteubert** [comment]
Interesting. Setting up my Publisher to look for the identical file I get

```
{"file_url":"http:\/\/cdn.podseed.org\/alltaegliche\/test.mp3","file_id":3703,"reachable":false,"file_size":0}
```

So the same, but the correct file size (0). I will fix the faulty green checkmark by checking the returned `reachable` parameter.

But the main bug is that the Publisher does not update correctly if the file is actually there?

**Comment by jthoenes** [comment]
Hi Eric,

yes, that's true. I was (wrongly?) assuming, the two bugs are connected.

**Comment by eteubert** [comment]
I have a feeling I fixed it with the commit above but I can't be sure because I wasn't able to reproduce it. Once the next patch is released, I'd love to hear if it helped.

**Comment by jthoenes** [comment]
I'll come back and confirm once the new version is out.

**Comment by jthoenes** [comment]
Hi Eric, the problem is now different - but not gone away. I need to dig a little deeper, to find what is causing it. Once I know, I'll re-open this issue or open another one. Whatever is appropriate

**Comment by eteubert** [comment]
Thanks for your help! :) Continuing in this issue is fine.
