### ISSUE TITLE
Podcast Feeds Episode Slug?

### ISSUE THREAD

**Issue by alexridley** [podlove/podlove-publisher#665]
I've been trying to figure this out myself and have decided to turn here!

I've figured out how to set everything up, up until the point in the Podcast Feeds section where I need to enter the Slug. I've set it up before where it was one of my Episode Slugs (just like I had put when I set up the Episodes), and had minimal success as only that episode was uploaded and it wasn't a true feed, and was just the one episode.

What do I put in the Slug section for my feed to work? I feel like I'm missing something simple here. :(

**Comment by eteubert** [comment]
Anything unique, but for an mp3 feed "mp3" is a common choice. Then your feed will be available at `/feed/mp3`

**Comment by alexridley** [comment]
Perfect! Solved the issue, thank you very much!
