### ISSUE TITLE
Podcast image in RSS feed

### ISSUE THREAD

**Issue by ofadam** [podlove/podlove-publisher#667]
Could the iTunes artwork be used for the following proposed RSS tag? This will let Stitcher pull artwork.

```xml
<image>
<title>PODCAST_TITLE_GOES_HERE</title>
<url>PODCAST_ITUNES_ARTWORK_GOES_HERE</url>
<link>PODCAST_LINK_GOES_HERE</link>
</image>
```

**Comment by eteubert** [comment]
Specification: http://cyber.law.harvard.edu/rss/rss.html#ltimagegtSubelementOfLtchannelgt

@timpritlove Was there any reason not to support this?

**Comment by timpritlove** [comment]
No there is no good reason. I must admit I thought we actually support the tag but apparently we don't. I consider this a bug which should be fixed asap.
