### ISSUE TITLE
episode summary verwirft HTML tags

### ISSUE THREAD

**Issue by tompson** [podlove/podlove-publisher#671]
bisher habe ich immer den HTML source aus dem Episoden Body in die Summary gegeben, jetzt werden plötzlich nach dem speichern alle HTML tags entfernt - mache ich was falsch oder ist das ein Fehler? 

Ich bekomme so keine Links mehr die Summary

**Comment by timpritlove** [comment]
Summary ist by design ein Plaintextfeld

**Comment by tompson** [comment]
hm, wie bekomme ich dann jetzt HTML in meine Episode? 

bisher hat das via Summary so funktioniert: http://dtr.fm/episode-42-nasodren/

ich hab das in Auphonic in das Summary (Description) Feld gegeben, dann via "Import Episode Metadata" importiert und in der Episode im Web Player und in den diversen Playern ist das HTML korrekt erschienen.

**Comment by timpritlove** [comment]
HTML muss in das "Content" Feld von WordPress. In der Summary gibt es (noch) kein Markup in irgendeiner Form. Wenn wir das mal ändern, dann nur um Formate in der Machart von Markdown.

Dass das bisher funktioniert hat wundert mich und ich bin mir auch nicht sicher, durch welche technische Änderung das auf einmal sich geändert hat. Aber beabsichtigt war das nie.

**Comment by tompson** [comment]
und wie bekomme ich dann HTML in die <description> im RSS feed? das nimmt er ja aus der Summary, oder?

**Comment by tompson** [comment]
hab den commit gefunden der das geändert hat:

https://github.com/podlove/podlove-publisher/commit/c966c364fd46dfd84009f918963b0ec2ddc208df

**Comment by tompson** [comment]
ok, ich sehe dass da bei unserem Podcast etwas falsch läuft, bei uns im feed fehlt das element content:encoded

**Comment by tompson** [comment]
ok, problem gefunden, in den Podcast Feed settings war "Include HTML Content" nicht an, schon seit über einem Jahr   m(
