### ISSUE TITLE
HTTPS URLs in Feeds bei Self-Signed Setup

### ISSUE THREAD

**Issue by saerdnaer** [podlove/podlove-publisher#672]
Wir haben bei http://podcast.openstreetmap.de folgendes Setup: 
Die normalen Nutzer benutzten die Webseite nur per HTTP, nur wir als Admins der Seite benutzen HTTPS. Ich hab dann z.B. das entsprechende Zertifikat bei mir im Rechner gepinnt.

Jetzt ist inzwischen das Podlove Tracking Feature aktiviert. Dadurch landen jetzt plötzlich auch https URLs im Feed, das ich gerne abstellen würde. Ja ich weiß mit HTTPS wäre cooler, aber wir haben für diese Subdomain halt aktuell einfach kein Zertifikat, das von einer offiziellen CA unterschrieben wurde.

Wie bzw. wo kann ich die URL anpassen?

**Comment by eteubert** [comment]
Es gibt dafür kein Setting aber dieses Snippet erzwingt HTTP für Links in Podcast-Feeds:

```php
add_filter( 'set_url_scheme', function($url, $scheme, $orig_scheme) {

	if (@is_feed() && @get_post_type() === 'podcast') {
		$url = preg_replace( '#^\w+://#', 'http://', $url );
	}

	return $url;
}, 10, 3 );
```

Das Snippet kannst du mit https://wordpress.org/plugins/code-snippets/ benutzen.

**Comment by saerdnaer** [comment]
Ich hätte das oben wohl besser erklären sollen. Ich meinte vor allem die URL im enclosure-Tag. Vorher stand da
```
<enclosure url="https://podcast.openstreetmap.de/podlove/file/1320/s/feed/c/mp3/OSMDE040.mp3" length="41709131" type="audio/mpeg"/>
```
Inzwischen hab ich den Publisher auf die 1.2.4 geupdated und den Tracking-Mode von "Tracking URL Parameters & Analytics" auf "Tracking URL Parameters" umgestellt. Jetzt steht da seltsamer weise folgendes im Feed: 
```
<enclosure url="http://podcast.openstreetmap.de/podlove/file/1320/s/feed/c/mp3/OSMDE040.mp3" length="41709131" type="audio/mpeg"/>
```

**Comment by eteubert** [comment]
> Ich meinte vor allem die URL im enclosure-Tag.

Mein Snippet sollte auch enclosure URLs beeinflussen.
Nach dem Einfügen des Snippets musst du ggf. im Support-Bereich die Repair-Funktion verwenden, um zu garantieren, dass du einen frisch generierten Feed erhältst.

**Comment by saerdnaer** [comment]
Gibts irgendwo eine Erklärung was das Code-Snippets Plugin technisch macht? Er wollte bei mir das Snippet irgendwie nicht akzeptieren bzw. ich konnte einfach keine neuen Snippets anlegen. Jetzt hab ich das Plugin für die Seite in der Mulitsite-Instanz deaktiviert, habe aber trotzdem wie gewünscht http:// enclosure URLs....

**Comment by saerdnaer** [comment]
Da es bei uns jetzt funktioniert schließe ich das Ticket einfach mal.
