### ISSUE TITLE
shortcode geht nicht

### ISSUE THREAD

**Issue by versicherungs-vergleicher** [podlove/podlove-publisher#673]
Hallo zusammen, ich hatte bereits im sendegate mal herumgefragt, dort konnte keiner helfen.

- Ich habe alle Plugins bereits deaktiviert gehabt - ohne Änderung
- habe child theme deaktiviert und das richtige DIVI theme aktiviert - ohne Änderung
- habe ein standard Wordpress theme ausprobiert - ohne Änderung
- ich bilde mir ein, dass im Oktober/November ein test mit demPlayer, den Player anstandslos angezeigt hat

Zugriff auf Dashboard könnt ihr zu Testzwecken gern bekommen, vielleicht habt ihr ja eine Idee, was ich vielleicht noch machen kann

Ich habe mit Elegant Themen geschrieben (Theme Entwickler) die haben in meinem Dashboard getestet und folgendes geschrieben:

Hey,

I did and checked it.
It's the plugin, I tried it on a normal page (no page builder) and it's not working: http://versicherungs-vergleicher.com/testing-podcasts/ (you can remove this page once you check it as well)

You can take this even further by testing it on the WordPress default theme, just so you can see it's not the theme.

My guess is the shortcode is only working on podcast post type, it probably has a conditional tag to only allow it there.

I can only suggest you to open a new issue on the plugin GitHub page.
Xxxxxxxx

Website             http://versicherungs-vergleicher.com
PHP Version         5.4.4-14+deb7u12
WordPress Version   4.1.1
Publisher Version   2.0.3
Web Player Version  2.0.17
curl Version        7.26.0
iconv               available
simplexml           ok
max_execution_time  600
upload_max_filesize 64M
memory_limit        256M
disable_classes     
disable_functions   
permalinks          ok
podcast_settings    
web_player          ok
podlove_cache       on
assets              
	mp3    audio/mpeg

0 errors
0 notices
Nice, Everything looks fine!

Vielen Dank für Eure Hilfe

Grüße

Carsten

**Comment by timpritlove** [comment]
Von welchem Shortcode sprichst Du? Wir haben da so einige im Angebot.

**Comment by versicherungs-vergleicher** [comment]
ja, klar sorry, also erstmal vom Player [podlove-web-player] 

Ich habe sowohl im Text Reiter als auch visuell das mal getestet.... Obwohl ihr ja irgendwo geschrieben habt es darf nur in Text - glaube ich.

Es ging auch schonmal - allerdings mal irgendwann im Herbst, als ich das erste mal geübt habe.



Aus Episode heraus funktioniert es, da habe ich es auch in den Texteditor zusätzlich eingebunden und da wird er dann auch 2xangezeigt siehe hier:
http://versicherungs-vergleicher.com/0000-folge-null/

Und im normalen Text, müsste er auch 2x kommen und zwar wenn du ganz runter scrollst dann kommt unten "Hier gibts was auf die Ohren" da müsste er erscheinen und im Text drüber am Ende dieses Bereiches - siehe hier:
http://versicherungs-vergleicher.com/

Ich hatte das Diivi Theme im Verdacht, weil das mit so einem Pagebuilder arbeitet, allerdings habe ich auch eine Testeite ohne diesen Builder ausprobiert. Im normalem Editor.

Wie gesagt, wenn du möchtest darfst du auch mal wenn Euch das hilft in mein dashboard gucken, da lege ich dich mal an.

Ich habe ebenfalls im Sendegate mal eine Anfrage gepostet.
https://sendegate.de/t/podlove-webplayer-wird-nicht-angezeigt-sprungmarken-hakeln/1079
Da hat ein "Micha" geschrieben er nutzt DIVI und da gehts.... :-(

Das mit den Sprungmarken was ich da geschrieben habe hatte sich erledigt.

Wen Du eine Idee hast was ich machen kann wäre das hilfreich -  in meinem Terminkalender steht ja der PPW15 drin,  da darf ich mich sowieso mal für die Arbeit von Euch persönlich bedanken.....;-)

Können auch telefonieren, wie auch immer - will nur nicht lästig sein, was ich ja jetzt schon bin ;-)

Grüße

Carsten

**Comment by timpritlove** [comment]
Den Shortcode gibt es nicht mehr. Benutze {{ episode.player }}

Siehe: http://docs.podlove.org/reference/template-tags/

**Comment by versicherungs-vergleicher** [comment]
Ich stell mich wahrscheinlich zu blöd an...geht nicht aber jetzt wird wenigstens der Text ausgegeben.
Ich habe einfach {{ episode.player }} eingegeben oder muss ich das jetzt noch spezifizieren

http://versicherungs-vergleicher.com/?preview=true&preview_id=415&preview_nonce=e39309b2f2

**Comment by timpritlove** [comment]
Preview Links funktionieren nur mit Login, den wir nicht haben. 

Werde mal ein wenig genauer: was gibst du genau wo ein und was ist Deine Erwartung, was passieren sollte und was passiert stattdessen?

**Comment by eteubert** [comment]
> Den Shortcode gibt es nicht mehr. Benutze {{ episode.player }}

Tatsächlich gibt es den noch und er _sollte_ auch funktionieren. Aber der Template Tag ist zukunftssicherer. Allerdings funktioniert der nur im Template, d.h. du musst unter `Podlove ➜ Templates` ein Template mit dem Inhalt `{{ episode.player }}` anlegen und dieses Template in der Episode benutzen. Das Standard-Template von frischen Installationen sieht so aus, und ist ein guter Startpunkt:

```jinja
{% if not is_feed() %}

	{# display web player for episode #}
	{{ episode.player }}
	
	{# display download menu for episode #}
	{% include "@core/shortcode/downloads-select.twig" %}

{% endif %}
```

**Comment by timpritlove** [comment]
@eteubert: Wenn es den Shortcode noch gibt, dann sollten wir ihn aber auch mal auf http://docs.podlove.org/reference/shortcodes/ dokumentieren. Da steht er nämlich nicht drin.

Davon abgesehen: warum funktioniert ausgerechnet ein Shortcode nur im Template und nicht im Content? Macht wenig Sinn, oder?

**Comment by eteubert** [comment]
> @eteubert: Wenn es den Shortcode noch gibt, dann sollten wir ihn aber auch mal auf http://docs.podlove.org/reference/shortcodes/ dokumentieren

Tja, er ist deprecated. Ich bin mir immer noch nicht sicher, was es als Shortcode geben sollte und was nur als Template Tag.

> Davon abgesehen: warum funktioniert ausgerechnet ein Shortcode nur im Template und nicht im Content?

Der Shortcode funktioniert überall. Template Tags funktionieren nur in Templates. Können wir auch hinterfragen, ob das geändert werden sollte.

**Comment by versicherungs-vergleicher** [comment]
Ok, kommt gleich ich Nehmerinnen kurzen screencast auf,

Kurz gesagt, ich will innerhalb meines zukünftigen blogs, mittendrin im Text den Podcast-Player angezeigt sehen, was ich wo eingebe und probiert habe zeige ich Euch gleich....

**Comment by versicherungs-vergleicher** [comment]
Oder soll ich euch schnell per Teamleiter zuschalten?

**Comment by versicherungs-vergleicher** [comment]
Habe gerade screencast aufgenommen, 7 min. Wird gespeichert und in meine Dropbox geladen, kann etwas dauern. Sitze hier gerade bei 600er upload.

Ab 15:30 Uhr bin ich unterwegs und wäre erst wieder ab ca. 18.15 Uhr erreichbar, falls ich mich melden soll ist eine sms oder whats hilfreich 0173-5379696 heute Abend bin ich verfügbar nur zwischen  20:00-20:30Uhr nicht.... Da bringe ich meine Jungs ins Bett ;-)

**Comment by versicherungs-vergleicher** [comment]
7min https://www.dropbox.com/s/yah2rqasbivkz1s/Podlove-Player-fehlerbeschreibung.mp4?dl=0

**Comment by timpritlove** [comment]
Ja, wie oben von @eteubert schon ausgeführt hatte ich mich geirrt: [podlove-web-player] gibt es noch (wird es aber irgendwann nicht mehr geben) und funktioniert im "Content"-Feld. "{{ episode.player }}" funktioniert dort nicht (das halte ich aber für einen Fehler, sollten wir ändern).

Dass sowohl " [podlove-web-player]" als auch  "{{ episode.player }}"  nicht in deiner anderen Seite funktionieren liegt schlicht daran, dass es genau das ist - eine Seite. Keine Episode. Es gibt den Kontext "aktuelle Episode" nicht. 

Frage an @eteubert : haben wir schon eine Möglichkeit, direkt auf eine bestimmte Episode zu verweisen, so dass man einen Player für eine beliebige Episode auf irgendeiner Seite einblenden könnte?

**Comment by versicherungs-vergleicher** [comment]
Hm, Danke Schade, @timpritlove, genau das wäre das was ich mir wünsche(glaube ich), am besten dann noch über die Kapitelmarken anspringbar, sodass man vielleicht einen längeren Podcast hat und wenn ich zum Thema x,y im Blog  schreibe, könnte ich ja auf diese Stelle verweisen und dann hinspringen, indem man den Player im "normalem" Content einblendet. Danke für Eure Ausführungen.

also dann übe ich mich in Geduld und freu mich mal Euch beide zum #PPW15a zu treffen, ist das alles schon amtlich? Start 01.05....oder 30.04. abends... Vielen Dank Grüße Carsten 

Vielleicht kann ich ja die Divi-Entwickler dazu bringen, ein Modul zu bauen welches Episoden einbindet.... Mals schauen, da haben wir bloß 2 Probleme, mein Englisch und mein Einfluss auf Amis.... ;-) also Danke Euch Grüße aus Ilmenau in Thüringen

**Comment by eteubert** [comment]
> Frage an @eteubert: haben wir schon eine Möglichkeit, direkt auf eine bestimmte Episode zu verweisen, so dass man einen Player für eine beliebige Episode auf irgendeiner Seite einblenden könnte?

Per Template Tags:

```jinja
{{ podcast.episodes({slug: 'myslug'}).player }}
```

Das geht mit Templates auch dynamisch:

```jinja
{% template "episode-player" %}
{{ podcast.episodes({slug: slug}).player }}

{% Aufruf per Shortcode %}
[podlove-template id="episode-player" slug="myslug"]
```

**Comment by versicherungs-vergleicher** [comment]
Das klingt gut, nur bin ich jetzt ausgestiegen, jetzt muss ich mich mit Templates auseinander setzen, besser gesagt mal einen Freak anschleppen. Habe mal versucht ganz naiv auf meiner Seite das einzufügen per Shortcode.... Siehe www.versicherungs-vergleicher.com ganz unten im blauen Kästchen 

Ist mir echt unangenehm, Euch hier so zu belasten.... Ich halte es mal mit Loriot: "Ich will doch einfach nur hier sitzen..."
;-) 

Danke Euch
