### ISSUE TITLE
Fehlende Angaben in den Analytics

### ISSUE THREAD

**Issue by 18zehn** [podlove/podlove-publisher#674]
Hallo, 

in meiner Installation (Version 2.0.3) werden in den Analytics keine Detail-Werte angezeigt, obwohl es schon eine ganze Weile läuft. 
![screenshot 2015-02-26 09 20 07](https://cloud.githubusercontent.com/assets/4332976/6388317/e2ccc2a6-bd98-11e4-818a-b6fb5a312a90.png)

Fehlerkonsole:
Website             http://nerdhoert.de
PHP Version         5.4.36-0+deb7u3
WordPress Version   4.1.1
Publisher Version   2.0.3
Web Player Version  2.0.17
curl Version        7.26.0
iconv               available
simplexml           ok
max_execution_time  60
upload_max_filesize 50M
memory_limit        256M
disable_classes  
disable_functions  
permalinks          ok
podcast_settings  
web_player          ok
podlove_cache       on
assets  
    mp3    audio/mpeg
    m4a    audio/mp4
    txt    text/plain
    png    image/png
    json   application/json

0 errors
0 notices
Nice, Everything looks fine!

**Comment by carlito** [comment]
Same here (in zwei verschiedenen Installationen).

**Comment by eteubert** [comment]
Ist ein Problem, das (meines Wissens) vor allem Episoden haben, die schon lange vor dem Tracking veröffentlicht wurden. Ich arbeite an einem Fix.

**Comment by timpritlove** [comment]
Besteht bei Euch dieses Problem noch?

**Comment by carlito** [comment]
Scheint behoben.
