### ISSUE TITLE
Tracking aktiviert - Folgen können nicht abgespielt werden

### ISSUE THREAD

**Issue by kleinesp** [podlove/podlove-publisher#675]
ich habe folgendes Problem. 
Wenn Tracking aktiviert ist können die Folgen nicht wiedergegeben werden. Weder auf der Homepage noch in einem Podcast Client

Im Moment ist es deaktiviert. Sonst können die Leute ja nichts hören. 

Wie gewünscht ist der Screenshot dabei. 
![image](https://cloud.githubusercontent.com/assets/11211156/6391599/4037b6ca-bdb8-11e4-8229-4f35c5cc17c6.jpg)
![image](https://cloud.githubusercontent.com/assets/11211156/6391600/4060a5ee-bdb8-11e4-9679-4791b6a9df7c.jpg)

**Comment by timpritlove** [comment]
Kannst Du es mal einschalten und genau schauen (am besten mit einem Command Line Tool), was auch den Fehlercode richtig liefert (curl oder wget), wenn Du die Tracking URL auflöst? Ohne das Testen zu können, können wir da nichts zu sagen.

**Comment by kleinesp** [comment]
Ich bin ganz ehrlich. Ich habe kein Wort verstanden. 
Ich habe es nun aktiviert. Wenn ihr nun auf kleinesp.de geht und die Folge abspielen wollt geht das nicht. Wenn ihr den Cast abonniert könnt ihr das aber die Folge nicht im Client abspielen.

**Comment by eteubert** [comment]
Es ist merkwürdig. Beim Direkt-Download macht dein Server die Füße hoch (HTTP 500), andere Wege (z.B. via curl Tool) lösen die URL korrekt auf. Die Art des Fehlers lässt ein Problem in deiner Server-Konfiguration vermuten. Es ist aber leider schwer nachvollziehen, wo genau die Ursache liegt.

**Comment by kleinesp** [comment]
Also muss ich es deaktiviert lassen?

**Comment by kleinesp** [comment]
Vor 
✔ URL resolves correctly
war gerade ein X konnte aber kein Foto machen. Zu spät bemerkt.

**Comment by kleinesp** [comment]
Was würde euch weiterhelfen um das Problem zu lösen?

**Comment by eteubert** [comment]
Du kannst nur deinen Administrator/Support bitten, herauszufinden, wieso ein Zugriff auf z.B. http://www.kleinesp.de/podlove/file/85/s/download/c/select-show/LC017.mp3 einen HTTP 500 verursacht.

**Comment by kleinesp** [comment]
Ok. Ihr sollt mal prüfen ob die Specs stimmen und es wurde von PHP 5.6 auf 5.5 geändert.

**Comment by eteubert** [comment]
Kannst du bitte noch den Text von der Seite `Podlove ➜ Support` hier posten?

**Comment by kleinesp** [comment]
Folgendes Problem- 
![image](https://cloud.githubusercontent.com/assets/11211156/6412103/01e9bb7a-be80-11e4-9257-736300a1fce3.jpg)

**Comment by eteubert** [comment]
Ein Problem im Archivist Plugin. Das kannst du deaktivieren, indem du auf Dateiebene den Plugin-Ordner löschst oder umbenennst; z.B. via. FTP. Dann sollte der Login wieder funktionieren.

**Comment by kleinesp** [comment]
Danke 

Support
![image](https://cloud.githubusercontent.com/assets/11211156/6418333/a7bf3fbe-beb4-11e4-9218-7cd61924b743.jpg)

**Comment by kleinesp** [comment]
Nur noch Probleme. Wollte updaten. Jetzt ist das Plugin Komplet verschwunden. Ich kann mir nicht vorstellen das es daran liegt das ich Tracking aktiviere. 
PHP hab ich jetzt auf 5.4 gestellt da der Support meinte das es vielleicht an 5.6 liegt. 
Podlove wurde einmal komplet neu installiert. 

Gäbe es noch irgendwelche Infos die euch helfen könnten? Ich bin mit meinem Latein am Ende

**Comment by eteubert** [comment]
Tja, mein einziger Ansatz für ein Problem auf unserer Seite ist Speicher-Anspruch. Aber ich habe eben den Profiler angeworfen und der ganze Aufruf eines Tracking-Links erfordert PHP-seitig knapp 500kB. Das ist gewiss mehr, wenn mehr Plugins aktiv sind, aber weit entfernt von kritischen Größenordnungen.

**Comment by kleinesp** [comment]
Ok. Dann hau ich mal ein paar Plugins raus. Kann ich sonst noch irgendetwas liefern. Ich möchte helfen das Problem zu lösen und podlove weiter verwenden.
