### ISSUE TITLE
Podlove Subscribe Widget und Feed URLs

### ISSUE THREAD

**Issue by malexmave** [podlove/podlove-publisher#676]
Moin moin,

folgendes Problem: Wir nutzen das Podlove Subscribe button widget auf unserer Podlove-Installation (aktuellste Version). Die Feeds sind auf `http://plaintext.velcommuta.de/feed/[slug]` eingestellt, wie üblich. Die Seite verwendet SSL mit dem Wordpress-https-Plugin (das Problem existiert aber auch ohne das Plugin, ich habe die Anweisungen aus dem "How to report a bug" befolgt).

Aus irgendeinem Grund verlinken die URLs beim Podlove Subscribe Button widget jetzt immer auf https://..., was ja bekanntlich für Probleme mit iOS / Webkit sorgt (wird zu `itpc://https://...` und dann dank bug zu `itpc://https//...` (ohne den Doppelpunkt beim https)).
![screenshot from 2015-02-27 14 46 34](https://cloud.githubusercontent.com/assets/1688580/6413410/73f0e11c-be8f-11e4-875e-314da7675aee.png)

Das ist jetzt natürlich doof, weil das bedeutet, dass iOS- / Safari-Nutzer unseren Podcast nicht abonieren können. Daher meine Frage: Gibt es eine möglichkeit, den Podlove Subscribe Button dazu zu bringen, die http://-Variante der Feeds zu verwenden, ganz egal, ob man die Webseite gerade per HTTPS aufruft? Wir würden nur ungerne SSL für die gesamte Seite abschalten, nur weil Apple verbuggte Programme schreibt...

Hier der Output der Support-Seite:
```
Website             https://plaintext.velcommuta.de
PHP Version         5.5.22-1+deb.sury.org~trusty+1
WordPress Version   4.1.1
Publisher Version   2.0.4
Web Player Version  2.0.17
curl Version        7.35.0
iconv               available
simplexml           ok
max_execution_time  30
upload_max_filesize 2M
memory_limit        256M
disable_classes     
disable_functions   pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,
permalinks          ok
podcast_settings    
web_player          ok
podlove_cache       off
assets              
	mp3    audio/mpeg
	opus   audio/ogg;codecs=opus
	ogg    audio/ogg

0 errors
0 notices
Nice, Everything looks fine!
```

Danke im Voraus,
malexmave

**Comment by eteubert** [comment]
Eventuell hilft ein Workaround aus einem anderen issue weiter: https://github.com/podlove/podlove-publisher/issues/672#issuecomment-76116228 Nur, dass du die condition etwas anpassen musst. Ggf. so? (ungetestet)

```php
add_filter( 'set_url_scheme', function($url, $scheme, $orig_scheme) {

    if (@get_post_type() === 'podcast' && stristr($url, '/feed/') !== false) {
        $url = preg_replace( '#^\w+://#', 'http://', $url );
    }

    return $url;
}, 10, 3 );
```
