### ISSUE TITLE
Problem with cursor positioning within podlove templates

### ISSUE THREAD

**Issue by David1701** [podlove/podlove-publisher#678]
It seems that there is a problem with positioning a cursor within the podlove templates editor in Safari. Safari uses bold characters for displaying twig tags or functions. Somehow that seems to confuse the ability to position a curse in lines after bold characters.

This problem does not appear in Chrome because bold characters are not used for code formatting in Chrome.

Here's an example. You can see the cursor at the end of the line. But obviously it blinks right before the last character.
![boldfont](https://cloud.githubusercontent.com/assets/5114568/6427042/71458bbc-bf74-11e4-9966-d520873d256c.png)

**Comment by eteubert** [comment]
I'd say it's a Safari bug. It's a monospace font, but if you apply "bold", it's getting bigger and isn't monospace any more. Chrome, for example, handles this correctly.

Anyway, I fixed it by switching to a color theme that doesn't use bold styles.

**Comment by David1701** [comment]
Great, thanks a lot...
