### ISSUE TITLE
Feed Header anpassen

### ISSUE THREAD

**Issue by saerdnaer** [podlove/podlove-publisher#679]
Aktuell werden wir im iTunes Repository mit unserem MP3 Feed gelistet, ich würde das gerne auf den M4A bzw. MP4 Feed umstellen. 
Soweit ich das sehe wäre das am einfachsten möglich, wenn man für ein paar Wochen ```<itunes:new-feed-url ...>``` in der Header (aller) Feeds schreibt. 

Was ist dazu der einfachste Weg? Ich kann auch damit leben einfach den entsprechenden PHP Code anzupassen...

**Comment by timpritlove** [comment]
Noch einfacher: einen entsprechenden Redirect einrichten. Entweder generell die Feeds tauschen oder eben nur auf den iTunes Store user agent reagieren.

**Comment by timpritlove** [comment]
Muss natürlich ein 301 Moved Redirect sein.

**Comment by saerdnaer** [comment]
Dazu muss ich halt den User Agent kennen. Ich hätte halt gerne einfach alle Clients die itunes:new-feed-url kennen, permanent auf den M4A Feed umgeleitet. (Ich nehme an das alle Clients die dieses Attribute kennen auch AAC können und würde denen halt auch gerne die Kapitel zur Verfügung stellen.)

**Comment by timpritlove** [comment]
Wenn du alle Clients umleiten willst ist ein im HTTP-Server eingerichteter 301 immer noch die bessere Lösung. Das funktioniert dann auch für Clients, die mit <itunes:new-feed-url> nichts anfangen können. Die Annahme, dass alle Clients, die m4a spielen können, das Element kennen, ist mit Sicherheit nicht richtig.

**Comment by saerdnaer** [comment]
Meine Annahme war ja auch genau anders rum: Alle Clients die itunes:new-feed-url können auch m4a. Aber eigentlich will ich nur die URL im iTunes Podcast Verzeichnis ändern. Ich muss mal bei uns in die Logs schauen, ob ich da den entsprechenden User-Agent finde.

**Comment by timpritlove** [comment]
Vielleicht nicht die falscheste Annahme, stimmt.

So oder so: wir unterstützen derzeit <itunes:new-feed-url> noch nicht, auch wenn das schon seit Ewigkeiten im Trello steht. Wir wollten das einbauen, wenn wir expliziten "leite diesen Feed auf einen anderen weiter" Support reinkommt, aber dafür gibt es generell wenig Nachfrage. Beim nächsten Meeting mal diskutieren, wie man das elegant machen kann.

Ich habe mal etwas recherchiert wg. iTunes User Agent und bin leider nicht fündig geworden. Vielleicht weiß @eteubert, welchen User Agent String der iTunes Podcast Directory Update Bot verwendet?

**Comment by eteubert** [comment]
> Vielleicht weiß @eteubert, welchen User Agent String der iTunes Podcast Directory Update Bot verwendet?

Nein, den haben wir auch erst in der Datenbank, sobald wir Feedstats tracken.

**Comment by timpritlove** [comment]
User Agent String vom Podcastverzeichnis ist "iTMS"
