### ISSUE TITLE
Workflow für das Anzeigen von Bildern

### ISSUE THREAD

**Issue by modnerd** [podlove/podlove-publisher#68]
Während des Podcast-Workshops vor der re:publica habe ich mit einigen von euch gesprochen um mal eine Übersicht zu bekommen, was derzeit noch fehlt, um Podcasts mit Bildern sinnvoll zu unterstützen. Der ganze Bereich ist ziemlich "interdisziplinär" und umfasst Anpassungen in Auphonic und Podlove Publisher/Player und ggf. später auch in Instacast, aber ich lege den Gesamtkomplex erstmal hier ab.

## Ziel
Für Podcasts mit eingebetteten Bildern, die derzeit ausschließlich via M4A angeboten werden können, soll sowohl ein sinnvoller Workflow für die Produktion von Folgen, die Migration alter Folgen sowie eine Darstellung der Inhalte gefunden werden.

### Darstellung/Player
Für die Darstellung werden folgende Erweiterungen im Player benötigt (teilweise wohl schon vorgesehen):
- Anzeige von Kapitelbildern in der Kapitelliste (quadratisch neben dem Namen, verkleinert)
- Anzeige des Bildes des jeweils gespielten Kapitels an geeigneter Stelle (Kopfzeile)
- Bildergalerie in der die Bilder in angenehmer oder maximaler Größe (Vollbild?) angezeigt werden. Hier gab es schon die Idee, das mit dem Video-View zu verbinden. Evtl. macht es aber Sinn, zusätzlich noch einen View zu definieren (etwa als Overlay) in dem ich quasi eine Diashow sehe, die von der Abspielposition in der Folge gesteuert wird. Sinnvoll wäre auch, dabei zu vorherigen Bilder zurück gehen zu können, da zuweilen Fotos aufgrund der Struktur der Folge nur sehr kurz erscheinen können und man während des Weiterhörens vielleicht noch mal einen Blick auf das was vorher zu sehen war, werfen will.

## Workflow/Verwaltung der Assets
Wichtiges Ziel eines zukünftigen Produktionsworkflows wäre mir (derzeit noch), mit M4A-Dateien als Ausgangsmaterial arbeiten zu können. Auch wenn das nicht die Zukunft ist, brauchen wir bis auf weiteres die "Abwärtskompatibilität" für Apples Podcast-Player und iTunes. Das größere Problem ist jedoch, dass es derzeit neben GarageBand kein brauchbares Authoring-Tool gibt, dass sowohl Apple-kompatibel Bilder einfügen kann und dann auch ein halbwegs angenehmes Authoring ermöglicht. Daher schlage ich vor, hier bis auf weiteres mit M4A-Dateien aus GB zu arbeiten und dem Workflow die Bilder aus der M4A einzuflössen. Parallel können natürlich auch andere Wege angeboten werden - das manuelle  Bereitstellen der Assets existiert ja sowieso. Das Handling von M4A-Dateien brauchen wir aber in jedem Fall für die Migration alter Folgen, da die Dateien oftmals der einzige Ort sind, in den die benötigten Informationen vollständig vorliegen.

### normale Produktion
- Media-Sets in Assets definieren: Beim Verwalten von Assets muss es (zumindest für Bilder) die Möglichkeit geben, nicht nur ein Bild sondern Bilderserien abzulegen. Dies müsste entsprechend in der Pfad-Konvention berücksichtigt werden. Es ist zu überlegen, ob die Kapitel-Nr./ID im Namen verankert sein muss (evtl. problematisch, falls Podcasts mehr Fotos zu einer Folge in den Assets haben, die jedoch nicht alle in den Kapiteln auftauchen oder wenn Bilder unabhängig von Kapiteln angezeigt werden sollen).
- Auphonic: Es muss ein Workflow definiert werden, wie Auphonic sowohl Informationen über Kapitel und den zugehörigen Bildern sowie ggf. die Bild-Assets selbst (falls diese aus einer Datei extrahiert werden können) liefern kann. Notfalls kann der Transfer der Dateien manuell erfolgen, das müsste man mal schauen.

### Migration
Für die Migration muss eine Möglichkeit existieren, entweder automatisch während der Migration oder zumindest später manuell via Auphonic durch das nochmalige Produzieren/Parsen alter Dateien die Bildern/Kapitel-Daten nachträglich zu extrahieren (auch incl. URL).

### Auphonic

- Erkennen von Kapitelmarkern innerhalb von M4A-Dateien und Übernahme in den weiteren Workflow
- Erkennen und Extrahieren von Bildern in M4A-Dateien und ablegen als Media-Set
- Übernahme von URLs zu Kapiteln
- Automatisierung der obigen Funktionen bei der Migration

### Instacast
- Darstellung von Fotos anhand von Media-Assets statt aus der M4A-Datei, sofern vorhanden

### Test mit Schöne Ecken
Der Podcast Schöne Ecken, den ich produziere, könnte hier Testbed für diese Änderungen werden. Ich würde gerne mit euch die Spzifikationen für diese Art des Podcastens festklopfen und testen.
Wenn wir hier weiterkommen, würde ich parallel auch die Entwickler anderer Podcatcher (gerade auf Android) ansprechen, um Darstellung von Bildern auch dort zu ermöglichen. Wenn wir das schaffen, sind wir einen ganzen Schritt weiter und haben ein plattformunabhängiges Feature-Set, wie es Apple und auch sonst niemand hinbekommen hat.
Und wenn wir das geschafft haben, erzähle ich euch, welche Ideen ich für Podcasts mit Geodaten ich noch habe ;)

**Comment by eteubert** [comment]
Feature-Diskussionen ab sofort nur noch in [Trello](//trello.com/b/zB4mKQlD/podlove-publisher) oder [Podlove Community](//community.podlove.org).

Diskussion ist hier verlinkt: https://trello.com/c/0494rGGZ/323-episoden-fotoalbum
