### ISSUE TITLE
Zeilenumbrüche weden bei der Verwendung von {{ episode.summary }} nicht angezeigt.

### ISSUE THREAD

**Issue by Jagdfunk** [podlove/podlove-publisher#681]
Moin, ich verwende im Template das Tag {{ episode.summary }}. Aus unbekannten Gründen schmeißt es mir die Zeilenumbrüche raus. Wenn´s ein Feature ist, wo kann ich das abstellen?! ;o)
http://jagdfunk.de

![image](https://cloud.githubusercontent.com/assets/4698188/6459816/5e072aae-c192-11e4-836e-1e990d5971ce.png)

```
Website             http://jagdfunk.de
PHP Version         5.5.22
WordPress Version   4.1
Publisher Version   2.0.4
Web Player Version  2.0.19
curl Version        7.26.0
iconv               available
simplexml           ok
max_execution_time  60
upload_max_filesize 50M
memory_limit        256M
disable_classes     
disable_functions   
permalinks          ok
podcast_settings    
web_player          ok
podlove_cache       on
assets              
	mp3    audio/mpeg
	m4a    audio/mp4
	opus   audio/ogg;codecs=opus
	jpg    image/jpeg
	psc    application/xml
	json   application/json
	chapters.txttext/plain
	ogg    audio/ogg

0 errors
0 notices
Nice, Everything looks fine!
```

**Comment by timpritlove** [comment]
Das ist derzeit noch grundsätzlich so. Eigentlich ist die Summary als "ein Absatz" definiert, aber ich gebe zu, dass das so in der Form nicht dokumentiert ist.

@eteubert Vielleicht sollten wir einen Filter bereitstellen a la "{{ episode.summary|html }}", um eine entsprechende Konversion für HTML vorzunehmen, der dann auch Absätze umwandelt? In dem Zusammenhang könnte man auch noch mal über Markdown nachdenken, dass allerdings dann in normalen Referenzen wie  "{{ episode.summary }}" zu plain text gefiltert werden müsste (kein Bold, kein Kursiv, keine Headlines, plain ascii lists etc.).

**Comment by Jagdfunk** [comment]
Das scheint ein größeres Fass zu sein. Ich hatte die Hoffnung, dass es nur ein kleines Töpfchen ist. z.B., dass nur das Zeichen ASCII CODE 13 in der Summary verbleibt. Mit dem Shortcode war das ja noch der Fall.

Wenn die Summary HTML formatierbar wird, dürfte die Schnittstelle zu Auphonic wohl auch deutlich komplexer werden. Auphonic muss die Formatierung ja wieder entfernen.

**Comment by timpritlove** [comment]
An Auphonic würde das ja nicht als HTML übergeben werden, sondern man könnte das eben nur mit den Podlove Templates in der Webseite machen. Genau aus diesem Grund ist das Feld ja ein Plain Text Feld und als "ein Absatz" definiert.

Wäre zu überlegen, ob man die Newlines nicht als solches beibehält. Mir ist derzeit auch nicht ganz klar, warum sie eigentlich verschwinden.

**Comment by eteubert** [comment]
Newlines (Im Sinne von `\n`) sind für Browser irrelevant, die interessieren sich nur für HTML-Linebreaks (`<br>`), darum wird das als ein Absatz gerendert.

Versuch mal {{ episode.summary|nl2br }} (http://twig.sensiolabs.org/doc/filters/nl2br.html)

**Comment by Jagdfunk** [comment]
Danke Eric! Das hilft.
