### ISSUE TITLE
Feature Request: Twitch TV Social Service for Contributors

### ISSUE THREAD

**Issue by JoeyTheHobbes** [podlove/podlove-publisher#683]
Hi!

I have a small and simple request:
Could someone please add a Contributor Social Service for Twitch TV? 
A small icon that links to https://twitch.tv/USERNAME would be nice!

Thanks in advance!

**Comment by timpritlove** [comment]
Yes, no problem. I just submitted a pull request. You might need to wait until the next update cycle though. Initial code in #684 (needs migration code)

**Comment by chemiker** [comment]
Twitch was added to the services in the recent 2.1 update (even if it is not listed in the readme).

**Comment by JoeyTheHobbes** [comment]
Thank you for your effort. Unfortunately the Twitch service is not present in the (my?) 2.1 release.
![twitch not in 2-1](https://cloud.githubusercontent.com/assets/11300164/7372525/868f21a0-edc7-11e4-9ce1-801777cad0aa.png)

**Comment by timpritlove** [comment]
Try hitting the repair button in "Podlove -> Support". This should help.

**Comment by JoeyTheHobbes** [comment]
Thanks for the quick response! Tim the hero - it did help! ;)
