### ISSUE TITLE
Episode Unavailable

### ISSUE THREAD

**Issue by tijander** [podlove/podlove-publisher#685]
hallo,

habe seit heute morgen das problem, dass ich im IOS podcastclient keine Epsisoden mehr abspielen kann.

Folgende Meldung kommt.
 
![fehler](https://cloud.githubusercontent.com/assets/10337611/6480015/23a0cf60-c24f-11e4-812d-01a3af375ab2.png)

Fehler:
- der client läd komplett runter alles gut. dann der fehler

Kontrolle:
- Webplayer läuft
- im RSS läuft
- in Itunes läuft

Ich habe:
- bei meinem Provider nachgefragt da ist Serverseitig alles i.o.
- im podlove publisher den repair knopf gedrückt
- podcast episode guid regeneriert bei einer folge

hat noch wer den fehler oder kann vielleicht helfen?

vielen dank
tias

Website             http://nachtkantine.org
PHP Version         5.4.38-nmm1
WordPress Version   4.1.1
Publisher Version   2.0.4
Web Player Version  2.0.17
curl Version        7.22.0
iconv               available
simplexml           ok
max_execution_time  30
upload_max_filesize 200M
memory_limit        256M
disable_classes     
disable_functions   
permalinks          ok
podcast_settings    
web_player          ok
podlove_cache       on
assets              
	mp3    audio/mpeg

0 errors
0 notices
Nice, Everything looks fine!

**Comment by tijander** [comment]
achso gerade noch getestet, wenn ich die epsisoden im ios client nicht runterlade sondern
gestreamt anhöre geht das ohne probleme.

achso iOS 8.1.3

**Comment by tijander** [comment]
ok weiter rum getestet.

wenn ich das Tracking ausschalte geht es wunderbar.

komisch. da es auf jeden fall bis vor paar tagen ohne probleme lief.

was könnte man denn machen? 

klingt etwas nach issue #675 , wie ich gelesen habe.

mit dem unterschied das es auf meiner seite und in itunes lief....

**Comment by eteubert** [comment]
Wir sind etwas ratlos.

Andere Podcasts mit aktivem Tracking funktionieren in der Podcasts.app. Wenn ich dem Request folge, sieht alles ok aus — was nicht verwundert, da die Episode auf vielen Wegen korrekt abgespielt werden kann. Völlig unklar, woran sich die Podcasts.app stört :-/

**Comment by tijander** [comment]
gerad instacast ausprobiert da geht es auch :(

habe das tracking ausgeschaltet nochmal neu geladen das gleiche problem. 

also am tracking scheind es nicht zuliegen.

daher hatte ich den anderen post auch gelöscht. war ich zu voreilig..

**Comment by timpritlove** [comment]
Wenn ich das richtig sehe hast Du jetzt den Tracking Mode "Tracking URL Parameters" angeschaltet und hattest vorher "Tracking URL Parameters & Analytics" an, richtig?

Das Problem mit der Podcast.app besteht noch, Grund weiter unklar. Allerdings ist es mir (bislang nicht reproduzierbar) gelungen, die Podcast.app durch Löschen der Mediendatei in einem interessanten Zustand zu bekommen, wo das Download-Logo keine Wolke, sondern ein normaler Kreis ist:

![img_4050](https://cloud.githubusercontent.com/assets/119680/6483322/81dd9410-c267-11e4-9069-bed06f40031d.PNG)

Und siehe da: einmal auf diesem Wege geladen spielt die Episode auch problemlos ab.

Meine Vermutung: irgendwas mit den Tracking Parametern. Wir hatten deren Aufbau schon mal wg. iTunes geändert. Kann gut sein, dass es hier auch noch was gibt, was die Podcast.app stört.

**Comment by tijander** [comment]
nein hatte die ganze zeit auf "Tracking URL Parameters & Analytics"...

das hatte ich dann mal ausgeschaltet, aber gleiches problem.

hm...

hatte es noch mit den kollegen iphones ausprobiert unterschiedlich provider unterschiedliche generationen von phones. 

aber schön das es bei dir geht Tim :)

dann hoffe ich einfach mal das es bei anderen auch geht. und nicht alles die podcast.app nutzen sondern auf anderen wegen hören.

komisch.

aber danke!

ich berichte falls es wieder geht.

falls ihr nur tipps habt nur zu

**Comment by eteubert** [comment]
Uns fiel gerade auf, dass ihr in euren Episoden die duration nicht gesetzt habt, so dass die mit `<itunes:duration>00:00:00</itunes:duration>` im Feed steht. Vielleicht stört sich die Podcasts.app daran? Es schadet auf keinen Fall, wenn ihr die nachtragt.

**Comment by tijander** [comment]
ok hab sie überall eingetragen. leider keine besserung.

**Comment by timpritlove** [comment]
Okay, das scheint es nicht zu sein. Allerdings habe ich zwischendurch immer wieder Erfolg mit der Episode und Podcast.app. Allerdings immer noch nicht reproduzierbar.

Seht allerdings so aus, als ob auch Castro ein ähnliches Problem hat. Nach dem Download wird die Episode als "ungültig" verworfen. Ich werde mal bei denen nachfragen, was es sein könnte. Bitte nichts am Setup ändern, wir sind dran.

**Comment by tijander** [comment]
DANKE!

**Comment by timpritlove** [comment]
Noch eine Frage. Der "Episode Media File Slug" der Datei scheint "episode-04-usm-haller-" zu sein. Habt ihr da wirklich ein "-" am Ende eingegeben oder ist das vielleicht ein Space am Ende?

**Comment by tijander** [comment]
das ist ein "-"

und nochmal zum verständnis. es ging ja schon alles. das problem ist erst seit gestern denke ich.

habe samstag die letzte folge hochgeladen und alles war schick und ging. seit dem hatte ich nichts geändert.

also nichts am tracking das läuft seit version 2.0 

das komische ist ja das das problem auch mit alten folgen auftritt...

**Comment by timpritlove** [comment]
Sieht so aus, als hätten wir den Bug gefunden. Update kommt...

**Comment by timpritlove** [comment]
Update ist draussen. Bitte mal einspielen und dann neu testen.

**Comment by tijander** [comment]
he ihr seit echt super! danke für die arbeit...

aber leider keine besserung in sicht. habe auch noch mal:

- die podcast episode guid regeneriert bei einer folge
- den repairknopf gedrückt

**Comment by timpritlove** [comment]
Hm, die URLs, die wir im Verdacht hatten, sind jetzt aber in Ordnung. Dann müssen wir noch weitersuchen. Grumpf.

**Comment by hohse** [comment]
Huhu! Habe gerade diesen Thread gefunden und wollte nur sagen, dass wir bei unserem Podcast von Hörern das gleiche Problem geschildert bekommen haben: siehe hier Kommentar 1 http://www.flachbereich.de/?podcast=episode68#comments

**Comment by eteubert** [comment]
Danke für die Meldung. Interessant, dass ihr genauso keine "pretty permalinks" verwendet, was nahelegt, dass es etwas damit zu tun hat. Wir sind weiter dran.

**Comment by eteubert** [comment]
@timpritlove Vielleicht hilft ein vierter Modus "Tracking, aber hänge beim Redirect keine ptm-Parameter an die Ziel-URL"?

**Comment by timpritlove** [comment]
wäre es vielleicht wert, das mal auszuprobieren

**Comment by line-o** [comment]
> Interessant, dass ihr genauso keine "pretty permalinks" verwendet, was nahelegt, dass es etwas damit zu tun hat.
Nicht das da am Ende "nur" 2 Fragezeichen in der URL sind.

**Comment by eteubert** [comment]
> Nicht das da am Ende "nur" 2 Fragezeichen in der URL sind.
> Oder, WP verbockt da was beim (um)interpretieren von URLs.

Nein, prinzipiell passt das schon. Es macht ja auch nur der Podcasts.app Download Probleme.

```
➜ curl -IL "http://www.flachbereich.de/?download_media_file=270&ptm_source=download&ptm_context=buttonlist&ptm_file=FlachbereichEpisode68.m4a"
HTTP/1.1 301 Moved Permanently
Location: http://www.flachbereich.de/wordpress/wp-content/uploads/podcast/FlachbereichEpisode68.m4a?ptm_source=download&ptm_context=buttonlist&ptm_file=FlachbereichEpisode68.m4a

HTTP/1.1 200 OK
```

**Comment by line-o** [comment]
Dann sollte man doch mal einen Testfeed mit direkten Links mit angehängten PTM-Parametern erstellen und den dann "abonnieren". Dann ist klar, ob es die Parameter alleine sind oder nur in Verbindung mit dem Redirect.

**Comment by timpritlove** [comment]
Good point. Mal ohne den ganzen Publisher- und WP-Kram drumrum probieren und das Problem isolieren. Es muss ja einen Grund geben, warum NSURLSession auf iOS es ablehnt einen Typ festzustellen.

Noch ein Hinweis zum Testen: kann es sein, dass hier bisher nur MP3-Quellen das Problem aufweisen? Es wäre interessant, dass mal mit MP4 gegenzulesen, da es hier ja offenbar um ein Nichtfeststellen des Dateitypes handelt. Vielleicht verhält sich iOS mit MP4-Medien anders. Würde mich nicht überraschen.

**Comment by tijander** [comment]
@eteubert  steige gerade aus :) was sind "pretty permalinks"  soll ich mal was bei den permalinks ändern

@hohse danke für die meldung

@timpritlove ich habe das gerade mal mit einer m4a datei ausprobiert. also mein feed mal umgestellt. und mit einer kleinen 10mb datei ausprobiert. läd er ios runter und gleich fehlermeldung.

@ all wenn ich die episode manuel über itunes sync. dann gehts. 

da reicht es technisch bei mir nicht. aber noch mal kurz das tracking hatte ich auch mal ausgeschaltet und neu runtergeladen ging aber trotzdem nicht. nur zur info

**Comment by eteubert** [comment]
> @eteubert steige gerade aus :) was sind "pretty permalinks" soll ich mal was bei den permalinks ändern?

Alles außer der ersten Option in den Permalink-Einstellungen. Das sinnvollste ist häufig das schlichte "Post Name". Es ist möglich, dass die Umstellung das Problem löst (weil dann auch die Download-Links anders aussehen).

**Comment by tijander** [comment]
ok.  probiere ich aus.

**Comment by timpritlove** [comment]
okay, wenn es mit mp4 das gleiche ist bestärkt das mein Gefühl, dass es wirklich "nur" an den URLs liegt.

**Comment by timpritlove** [comment]
Ihr könntet als  Fix wohl die Permalink-Settings ändern. Die Wahrscheinlichkeit, dass es dann geht, ist wohl recht hoch. Allerdings bedeutet das auch, dass alle Episoden-Links und (!) auch alle Feed-URLs sich ändern. D.h. ihr könnt das nur machen, wenn ich gleichzeitig die alte Feed-URLs auf die neue umleitet (Werkzeug dafür gibt es in Expert Settings -> Redirects). Das ist zwar viel Maschinenöl, aber es würde vermutlich helfen.

Das gilt wohl auch für Dich @hohse.

So oder so würden wir das Problem natürlich gerne bei der Wurzel packen. Wenn ihr es also noch ein wenig ertragt, würden wir gerne noch ein paar Versuche starten.

**Comment by eteubert** [comment]
> Allerdings bedeutet das auch, dass alle Episoden-Links und (!) auch alle Feed-URLs sich ändern. D.h. ihr könnt das nur machen, wenn ich gleichzeitig die alte Feed-URLs auf die neue umleitet 

Es ist richtig, dass sich alle URLs änder, _aber_ sie sind weiterhin unter den alten URLs erreichbar und werden korrekt umgeleitet. Die Standard-"Parameter-URLs" funktionieren immer, unabhängig von den Permalink-Einstellungen.

D.h. die Umstellung ist höchstwahrscheinlich schmerzlos.

**Comment by hohse** [comment]
Hui - so viele Antworten...:)
Okay, ich werde bei Gelegenheit mal mit den Permalink-Einstellungen rumspielen und testen und berichten. Vielen Dank alle!

**Comment by tijander** [comment]
"So oder so würden wir das Problem natürlich gerne bei der Wurzel packen. Wenn ihr es also noch ein wenig ertragt, würden wir gerne noch ein paar Versuche starten."

da unsere hörerschaft denke ich recht überschaubar ist und gerad etwas die zeit fehlt. werden wir wohl den weg des "ertragen" einschlagen.  

ich schaue hier weiter fleißig rein. falls wir was testen sollen oder helfen können sagt bescheid.

erstmal vielen vielen dank an euch! 

tias

**Comment by timpritlove** [comment]
Sehr hilfreich, danke. Wenn @hohse umstellt und schon mal Erfolge erzielt hätten wir schon mal einen guten Vergleich.

**Comment by tijander** [comment]
ok irgendwie läst mir das auch keine ruhe :)

also ich habe mal umgestellt auf 

![bildschirmfoto 2015-03-07 um 01 07 52](https://cloud.githubusercontent.com/assets/10337611/6538760/98d922be-c466-11e4-9ad4-f728a8d84252.JPG)

das war wirklich schmerz frei. alles ist gut. der feed funktioniert weiter. sieht jetzt so aus.
also gleich nur ohne frage zeichen
![bildschirmfoto 2015-03-07 um 01 07 18](https://cloud.githubusercontent.com/assets/10337611/6538744/7d46079c-c466-11e4-8619-e82764c8423a.JPG)

kann ohne probleme runterladen. muss nichts bei redirect einstellen. das geht wirklich automatisch.

aber leider keine änderung in sicht. IOS bringt die gleich fehlermeldung.

----

was komischer weise geht ist wenn ich die datein von itunes aus auf das phone schiebe geht es...

das nur zur info...

---

**Comment by timpritlove** [comment]
Hm. ich sehe die neue Feed-Adresse nicht. Hast Du schon wieder zurückgestellt?

Und pack doch mal den Subscribe Button auf die Seite.

**Comment by tijander** [comment]
ja ich hatte das die nacht ausprobiert und hatte sich nichts geändert. feed sah dann so aus siehe oben. das 2. bild.

der download hatte auch funktioniert. ohne das ich was im redirect einstellen musste...


hm :( ...

ja button mach ich drauf.


komm aber erst die nacht wieder dazu.


was wäre hilfreicher feed mit "?" so wie jetzt oder ohne...

**Comment by hohse** [comment]
Soooo! Ich hatte nun endlich Zeit, unsere neue Episode fertig zu basteln und habe im Zuge dessen gleich mal die Permalinks in "pretty" umgewandelt - in der Tat erstaunlich problemlos. Die einzelnen Folgen sind nun mehr über Fragezeichen und Zahlen zu erreichen, sondern über den Episodentitel. Also beispielsweise so: http://www.flachbereich.de/episode69/

Und siehe da! Die besagte Episode69 lässt sich problemlos in Apples Podcast App (auf iPad Air 2) runterladen und abspielen. Auf meinem Android-Telefon mit Antenna-Pod geht auch alles einwandfrei wie vorher. Habe aber noch keine früheren Folgen ausprobiert.

**Comment by hohse** [comment]
Kleine Ergänzung: Interessanterweise scheint nun auch der Subscribe-Button zu funktionieren. Mit dem hatten wir zuvor auch immer Probleme (sprich: er erschien gar nicht) und ich habe ihn nicht benutzt. Den habe ich jetzt in den Widgets noch mal versucht und siehe da: funktioniert einwandfrei. :)

**Comment by hohse** [comment]
Und noch eine kleine Ergänzung: offenbar müssen ältere Episoden, bei denen der Fehler vor der Perma-Link-Umstellung auftrat, erneut heruntergeladen werden. Eine Freundin hatte mit unserer Episode 68 ausprobiert. Von der ließ sich die schon in der Podcast-App befindliche Episode nicht abspielen, nachdem sie die aber gelöscht und erneut heruntergeladen hatte, ging es. Es scheint also in der Tat irgendwie an den Links gelegen zu haben...?

**Comment by line-o** [comment]
Das hört sich so an als sollte diese Einstellung der Default-Wert sein.

**Comment by timpritlove** [comment]
Sollte er, ist er aber nicht (ist ja kein Podlove-Setting, sondern WP), da er Rewrite-Mechanismen voraussetzt und da muss man beim guten alten Apache-Server ja noch ein Modul zuschalten. Deswegen ist es so.

Wir könnten aber überlegen, im Publisher das nahezulegen, das zu ändern.

**Comment by line-o** [comment]
Hach, Apache. Das waren noch Zeiten, Eine Warnung wäre schon sehr hilfreich.

**Comment by tijander** [comment]
@hose du hast jetzt die permalinks umgestellt und gut?  auf was hast du sie umgestellt?

hast du noch was an dem feed angepasst?

**Comment by hohse** [comment]
@tijander Ja, genau. Ich hab's auf den Beitragsnamen gestellt und sonst nichts weiter.

![screenshot 2015-03-07 19 26 29](https://cloud.githubusercontent.com/assets/9248259/6542669/fb856ac8-c4ff-11e4-9921-fde544cf2f28.png)

Ach! Und ich habe im Zuge meiner verzweifelten und von Unwissenheit geleiteten Versuche von Aktionismus auch noch in den "Expert Settings" des Podlove-Plugins dieses Häkchen entfernt (siehe Bild unten), das da vorher aus irgend einem Sinn drin war - ohne zu wissen, was konkret das bedeutet. Weiß ich auch immer noch nicht. Aber es funktioniert alles, es kann also nicht so schlecht gewesen sein...:D 

![screenshot 2015-03-07 19 29 19](https://cloud.githubusercontent.com/assets/9248259/6542674/4cd07c10-c500-11e4-8d4d-03972b197f44.png)

**Comment by tijander** [comment]
so habe bei mir auch die permalinks auf beitragsname umgestellt und nun geht alles.

habe bei einer folge noch mal die GUID neu generiert. aber das hätte ich wohl gar nicht machen müssen.

habe die anderen folgen nochmal runtergeladen und die gingen alle ohne probleme.

danke noch mals für die hilfe!

spende ist raus!

vg
tias

**Comment by eteubert** [comment]
Ok, danke euch, dann werden wir eine entsprechende Warnung einbauen, wenn Tracking aktiv ist aber die "falsche" Permalinkstruktur aktiv ist.
