### ISSUE TITLE
Can't find podlove in dashbord anymore!

### ISSUE THREAD

**Issue by stuttboksa** [podlove/podlove-publisher#686]
Hi!
The podlove is found in the ftp directory but I can't find it on the dashboard anymore. When i try to instal it it says that the target file is already there or something like that. Any idea what the problem is? I've deleted plugins that perhaps could cause the problem but it didn't work. The plugin directory is the same as all my other working plugins. I'm using the 4.1.1 wordpress.
www.elimtistedal.no

**Comment by eteubert** [comment]
Did you try to deactivate/deinstall the Publisher? (warning: deinstalling also removes all Publisher-related data. You didn't mention if this is a fresh install, so be careful with this advice :))
You can also try to delete the Publisher plugin files via FTP and then try to install it again.

**Comment by stuttboksa** [comment]
Thanks for the reply. This is not a fresh install. I have not tried that and I hope I don't have to...

**Comment by eteubert** [comment]
Deleting the files via FTP doesn't delete the data. It's safe :) Just don't _deinstall_ the plugin via the plugin menu.

**Comment by stuttboksa** [comment]
Now the plugin is found in the dashboard but when I try to add new episodes the "Media files" line only says mp3_fil. I've copied the file name from the ftp directory but it only says mp3_fil. Any suggestions?
![skjermbilde 2015-03-06 kl 12 26 35](https://cloud.githubusercontent.com/assets/11311162/6524655/60c01e1a-c3fc-11e4-94f4-1d450f6293a1.png)
