### ISSUE TITLE
WebPlayer immer on top (auch wenn Bottom geklickt ist sowie "manuell einfügen")

### ISSUE THREAD

**Issue by AlexKug** [podlove/podlove-publisher#687]
Leider ist der Webplayer immer on top des Postings, auch wenn ich in den Setting "on bottom" markiert habe. Was kann ich tun? Danke und viele Grüße!
Alexander

**Comment by eteubert** [comment]
Ich vermute, du beziehst dich auf die "Put player to bottom of post" Option? Die gilt nur für WordPress enclosures.

Gehe stattdessen in `Podlove ➜ Templates`, dort ist vermutlich ein Template, das den Player beinhaltet, bei "Insert at top", ausgewählt. Das musst du stattdessen bei "Insert at bottom" eintragen.

**Comment by AlexKug** [comment]
Klasse, das war die Lösung! Vielen Dank für die schnelle Hilfe...
Bis bald,
Alexander
