### ISSUE TITLE
Play-Button auslagern oder zugänglich machen

### ISSUE THREAD

**Issue by 18zehn** [podlove/podlove-publisher#688]
Hallo,

vielleicht ist es auch meinen fehlenden Programmierkenntnissen geschuldet, aber gibt es eine Möglichkeit, den Webplayer auch von anderer Stelle aus zu starten, sprich also, den Klick auf den Play-Button zu simulieren?

**Comment by eteubert** [comment]
So zum Beispiel:

```js
jQuery(".podlovewebplayer_wrapper .bigplay").click()
```

**Comment by 18zehn** [comment]
Und genau das habe ich an den unterschiedlichsten Stellen versucht, aber der Player startet nicht.
Kann es damit zusammenhängen, dass der Player bei der Erstellung des "Seitenquelltexts" noch gar nicht vorhanden ist?

**Comment by line-o** [comment]
Am Besten Skripte ans Ende der Seite packen.

**Comment by 18zehn** [comment]
Sind das letzte Element der Seite vorm </body>

**Comment by 18zehn** [comment]
Ich habe das Ganze auch mal im Sendegate angesprochen: https://sendegate.de/t/ansprechen-des-webplayers-von-anderer-stelle/1131
