### ISSUE TITLE
Wordpress Theme 2015 übernimmt Metadaten zum Episoden-Posting (Podlove) nicht

### ISSUE THREAD

**Issue by AlexKug** [podlove/podlove-publisher#689]
Hallo nochmal,
Metadaten zum Posting, wie auch Angaben zur Lizenz etc. werden nicht in das Posting übernommen, Datum und Veröffentlicher z. B. fehlen auch. Liegt das am Theme oder ist das eine Einstellungsfrage des Podlove Publishers?
www.psychcast.de

Vielen Dank,
Alexander

**Comment by timpritlove** [comment]
Liegt einerseits am Thema (Veröffentlichungsdatum wird bei den Twenty*-Themes bei Custom Posts einfach weggelassen - warum auch immer) , kann man aber wie auch die Episoden-spezifischen Metadaten einfach per Template leicht hinzufügen.

http://docs.podlove.org/reference/template-tags/

**Comment by AlexKug** [comment]
Lieber Tim, alles klar, vielen Dank!!
