### ISSUE TITLE
Nginx Errors

### ISSUE THREAD

**Issue by benhartwich** [podlove/podlove-publisher#692]
Hi,

ich habe folgende Errors in meiner Nginx Log und der Podcast Player scheint auch keinen Podcast zu starten, was ich an meinem PC leider nicht nachvollziehen kann. 
[error] 24603#0: *40572 open() "/var/kunden/web1423/www/benj                      aminhartwich.de/httpdocs/podlove/file/278/s/webplayer/c/episode/27.mp3" failed (                      2: No such file or directory), client: 94.217.129.139, server: benjaminhartwich.                      de, request: "GET /podlove/file/278/s/webplayer/c/episode/27.mp3 HTTP/1.1", host                      : "www.benjaminhartwich.de", referrer: "http://www.benjaminhartwich.de/wp-conten                      t/plugins/podlove-podcasting-plugin-for-wordpress/lib/modules/podlove_web_player                      /player/podlove-web-player/static/flashmediaelement.swf"

Upload Location ist: http://www.benjaminhartwich.de/podcast/. Ich verstehe nicht ganz, warum von Podlove dieses Verzeichnis geöffnet wird.
Wie kommt dieser Fehler zustande, wie kann ich ihn beheben?

Weiterer Error:
1050 open() "/var/kunden/web1423/www/benjaminhartwich.de/httpdocs/freak-wenkuemmerts/flashmediaelement.swf" failed (2: No such file or directory), client: 95.91.236.158, server: benjaminhartwich.de, request: "GET /freak-wenkuemmerts/flashmediaelement.swf HTTP/1.1", host: "www.benjaminhartwich.de", referrer: "http://www.benjaminhartwich.de/freak-wenkuemmerts/"

Server-Umgebung:
Website             http://www.benjaminhartwich.de
PHP Version         5.5.22-1~dotdeb.1
WordPress Version   4.1.1
Publisher Version   2.0.5
Web Player Version  2.0.17
curl Version        7.26.0
iconv               available
simplexml           ok
max_execution_time  320
upload_max_filesize 500M
memory_limit        256M
disable_classes     
disable_functions   pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,
permalinks          ok
podcast_settings    
web_player          ok
podlove_cache       on
assets              
	mp3    audio/mpeg
	m4a    audio/mp4
	ogg    audio/ogg

0 errors
0 notices
Nice, Everything looks fine!

**Comment by eteubert** [comment]
Ich vermute eine Fehlkonfiguration deines nginx, so dass mp3s nicht erreichbar sind:

m4a wird korrekt aufgelöst:
```
➜ curl -IL http://www.benjaminhartwich.de/podlove/file/279/s/download/c/select-show/27.m4a
HTTP/1.1 301 Moved Permanently
Location: http://www.benjaminhartwich.de/podcast/27.m4a?ptm_source=download&ptm_context=select-show&ptm_file=27.m4a

HTTP/1.1 200 OK
```

mp3 wird nicht aufgelöst:
```
➜ curl -IL http://www.benjaminhartwich.de/podlove/file/278/s/download/c/select-show/27.mp3
HTTP/1.1 404 Not Found
```

Wäre es ein Problem des Publishers/WordPress, käme der 404 auch von WordPress. Aber hier sieht es für mich aus, als lässt dein nginx den Request gar nicht zu WordPress durch.

**Comment by benhartwich** [comment]
OK, danke. Ich habe allerdings keine Regel für die Domain in NGinx für Podlove definiert. Hat jemand Erfahrung damit? Oder gibt es eine Nginx Podlove Anleitung?

Ich wüsste auch erstmal gar nicht, wo ich da jetzt suchen könnte.

**Comment by benhartwich** [comment]
Ich habe mich nochmal umgesehen in den Podlove Einstellungen. Könnte es sein, dass es ein Tracking-Bug ist? Ich nutze die Funktion Tracking Parameter & Analytics und unten steht: URL does not resolve correctly.

**Comment by eteubert** [comment]
> Ich habe mich nochmal umgesehen in den Podlove Einstellungen. Könnte es sein, dass es ein Tracking-Bug ist?

Wie gesagt, ich denke nicht, dass es mit WordPress oder Podlove zu tun haben kann, da die mp3-URLs einen nginx-404 auslösen.

![nginx 404](http://cl.ly/image/2u0f2l0G172N/Screen%20Shot%202015-03-11%20at%2018.17.43.png)

**Comment by benhartwich** [comment]
Ja schon klar, aber warum gehen dann die anderen Dateien alle (m4a und ogg)? Wenn es ein Nginx Problem wäre, würde es meiner Erfahrung nach überhaupt nicht gehen oder eben komplett gehen. Ich habe auch im Forum etwas gelesen und das Problem scheint ja auch anderweitig aufzutreten in Zusammenhang mit dem Tracking. 

Gibt es ein Debug Logging für Podlove oder irgendetwas das ich neben den Standardverfahren auswerten kann?

Ich würde ja für die Problemlösung auch 15€ an euer Projekt dann spenden (=> Student).

**Comment by eteubert** [comment]
Schwierig. Ich würde als erstes nginx configs nach Regeln durchsuchen, die "mp3" enthalten.
Ansonsten würde ich schrittweise debuggen: prüfen, ob die mp3-Requests in WP ankommen, falls ja, dann tiefer im Stack debuggen, usw. Aber da ich von dem Problem noch nie gehört habe (nur mp3 funktioniert nicht, alle anderen Formate problemlos), kann ich leider keine weiteren "guck mal hier und leg mal den Schalter um"-Hinweise geben.

Wenn du vollkommen ratlos bist, kannst du mich per mail mit Zugängen kontaktieren (siehe github Profil).

**Comment by benhartwich** [comment]
Ach fuck, eine Caching Regel bei nginx scheint Probleme gemacht zu haben. Nun gehts wieder. Danke! Ich schick euch ne Spende.

**Comment by eteubert** [comment]
:)

**Comment by bitnapper** [comment]
Hallo @benhartwich , ich habe das selbe Problem beim Umzug meiner Seite auf einen Nginx. Welche Caching-Regel hat bei dir das Problem verursacht?

**Comment by benhartwich** [comment]
Hatte das Problem bis gerade eben immer noch. Es scheint am Caching von mp3 Dateien generell zu liegen, warum auch immer:

location ~* \.(?:jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogv|webm|htc|woff)$ {
  expires 1M;
  add_header Pragma public;
  add_header Cache-Control public;
  add_header Vary Accept-Encoding;
  access_log off;
}

Ich habe einfach alle Audiodateien aus der location entfernt. Wenn jemand weiß, wie ich das Caching effektiv anschalten kann, ohne dass ein 404 Error kommt, gern!

**Comment by bitnapper** [comment]
Schade, das macht bei uns leider keinen Unterschied.

**Comment by benhartwich** [comment]
Einfach mal alles schrittweise deaktivieren. Ich kann euch auch meine nginx conf zuschicken.

**Comment by 2ndkauboy** [comment]
Ich hatte gerade das gleiche Problem. Ich habe nun folgende location vor der mit dem Caching für statische Dateien eingebaut:

```
# dynamic Podlove assets cache paths
location ~ /podlove/ {
        try_files $uri $uri/ /index.php?$query_string;
}
```
