### ISSUE TITLE
Episodes are not shown in Divi Elegant Theme Blog Module

### ISSUE THREAD

**Issue by Nefariuscipher** [podlove/podlove-publisher#693]
Hey there!

I thought Podlove Episodes are handled the same way as blog articles. However when I want to show my latest articles in the Divi Elegant Theme with the Blog Module, it tells me "nothing is found". 

Is there any way to work around this?

**Comment by timpritlove** [comment]
Episodes are not posts, but "custom" posts named "podcast". Your theme needs to be able to deal with more than just the standard "post" type. If nothing shows up, it is explicitly filtering non-"post" elements. 

There is nothing we can do against this. Podlove Publisher just follows standard WP rules. Your theme developer either needs to support specific post types or stop filtering our "post" items.

**Comment by Nefariuscipher** [comment]
Thx timpritlove. 

But sorry to hear that. I was afraid it is something a developer needs to be hired ;-)
