### ISSUE TITLE
Audio-Dateien werden nicht gefunden (0 Bytes)

### ISSUE THREAD

**Issue by versicherungs-vergleicher** [podlove/podlove-publisher#696]
Hallo zusammen, ich habe bei o.g Dingen Probleme, habe ein Screencast aufgenommen der alle Einstellungen zeigt. Vielleicht könnt ihr helfen, Danke, hier mein Supportdatensatz:

Nicht erschrecken, zwischendurch wenn ich den Podcast anspiele wird's laut...;-)
http://goo.gl/HleJM2

hier der Link - 6 min - 

Website             http://versicherungs-vergleicher.com
PHP Version         5.4.4-14+deb7u12
WordPress Version   4.1.1
Publisher Version   2.0.5
Web Player Version  2.0.17
curl Version        7.26.0
iconv               available
simplexml           ok
max_execution_time  600
upload_max_filesize 64M
memory_limit        256M
disable_classes     
disable_functions   
permalinks          ok
podcast_settings    
web_player          ok
podlove_cache       on
assets              
	mp3    audio/mpeg
	m4a    audio/mp4
	m4a    audio/mp4
	flac   audio/flac
	oga    audio/ogg

0 errors
0 notices
Nice, Everything looks fine!

**Comment by eteubert** [comment]
Deine Dateien müssen alle per HTTP erreichbar sein. Das kannst du ganz einfach testen, indem du die erwartete URL in einem Browser ansurfst.

`http://www.versicherungs-vergleicher.com/wp-content/Podcast/0000-Folge-Null.m4a` leitet weiter auf `http://versicherungs-vergleicher.com/wp-content/Podcast/0000-Folge-Null.m4a`, was eine WordPress 404 ausspuckt.

Warum das so ist, weiß ich nicht (Ein Plugin, das mit Redirects spielt, .htaccess Einträge, ...). Aber so lange die Dateien nicht erreichbar sind, sind sie auch für den Publisher nicht erreichbar.

Thema erzwungener Download: Gleicher Stand wie bisher: muss im Apache/nginx konfiguriert werden.

**Comment by Erdebene** [comment]
Carsten, überprüfe bitte, ob die Dateinamen Deiner Audio-Dateien exakt mit dem "Episode Media File Slug" in der Episode übereinstimmen. Das ist nach Deinem Screencast lediglich bei der mp3- und der flac-Version der Fall. Das sollte Dir zusätzliche grüne Haken unter Status bescheren. Vielleicht heilt das sogar den Feed.

Den Feed prüfen kannst Du mit dem [W3C Feed Validation Service] (http://validator.w3.org/feed/).

Mein m4a-Feed sieht im Validator z.B. so aus:
![zwischenablage01](https://cloud.githubusercontent.com/assets/11456963/6643115/1de140ac-c9aa-11e4-8fee-3f2e8f6ee230.jpg)

Ganz ohne Schmerzen ist der auch nicht (Tips nehme ich gern entgegen), aber er tut was er soll. ;o)

**Comment by versicherungs-vergleicher** [comment]
OK Danke Euch erstmal, das schaue ich mir dann an - war ja klar, ich hab mir eingebildet alles verglichen zu haben....  die Versicherungen fordern ihren Tribut... ;-)
Vielen Dank für Eure Mühe, gebe Bescheid,

Werde auch das w3 plugin austauschen....

Danke Erik & Danke Jochen, musste doch jetzt mal gucken wie der hilfreiche Jäger mit Vornamen heisst ;-)

**Comment by versicherungs-vergleicher** [comment]
So alle Plugins abgeschaltet, ich bin mir jetzt keiner Schuld mehr bewusst, Jochen, hast du im Screencast Fehler gesehen oder vermutest du die Fehler. Ich weiss nicht mehr was ich einstellen soll.

Bin für jeden Hinweis dankbar, hier auf meiner Testseite ist auch zu sehen - dass die fehlenden Dateien mit "0" Bytes angezeigt werden: http://versicherungs-vergleicher.com/podcarsten/
![bildschirmfoto 2015-03-14 um 00 11 48](https://cloud.githubusercontent.com/assets/7683773/6648832/f914744e-c9de-11e4-9a52-d9ed9a61c887.png)

![bildschirmfoto 2015-03-14 um 00 07 32](https://cloud.githubusercontent.com/assets/7683773/6648772/49248b0a-c9de-11e4-9ff3-0ec4938e69b7.png)

Also wie gesagt - ALLE Plugins deaktiviert, ich nutze DIVI-Theme als Childtheme

hier ein Auszug aus dem PP Loging:

[2015-03-13 22:19:19] --- # Can't reach http://www.versicherungs-vergleicher.com/wp-content/Podcast/0000-Folge-Null.m4a --- # Please include this output when you report a bug url: http://www.versicherungs-vergleicher.com/wp-content/Podcast/0000-Folge-Null.m4a content_type: text/html; charset=UTF-8 http_code: 301 header_size: 425 request_size: 256 filetime: -1 ssl_verify_result: 0 redirect_count: 0 total_time: 1.89099 namelookup_time: 0.00016 connect_time: 0.000263 pretransfer_time: 0.000343 size_upload: 0 size_download: 0 speed_download: 0 speed_upload: 0 download_content_length: -1 upload_content_length: 0 starttransfer_time: 1.890946 redirect_time: 0 certinfo: Array ( ) primary_ip: 94.102.220.48 primary_port: 80 local_ip: 94.102.220.48 local_port: 34318 redirect_url: http://versicherungs-vergleicher.com/wp-content/Podcast/0000-Folge-Null.m4a php_open_basedir: /var/customers/webs/adminvv/:/var/customers/tmp/adminvv/:/usr/share/php/:/usr/share/php5/:/tmp/ php_safe_mode: php_curl: 1 curl_exec: 1


Und hier mein Setup:

Website             http://versicherungs-vergleicher.com
PHP Version         5.4.4-14+deb7u12
WordPress Version   4.1.1
Publisher Version   2.0.5
Web Player Version  2.0.17
curl Version        7.26.0
iconv               available
simplexml           ok
max_execution_time  30
upload_max_filesize 64M
memory_limit        256M
disable_classes     
disable_functions   
permalinks          ok
podcast_settings    
web_player          ok
podlove_cache       on
assets              
	mp3    audio/mpeg
	m4a    audio/mp4
	m4a    audio/mp4
	flac   audio/flac
	oga    audio/ogg

0 errors
0 notices
Nice, Everything looks fine!

**Comment by timpritlove** [comment]
Das Problem liegt in Deiner Webserver-Konfiguration. Ich sehe da gleich mehrere Probleme.

1. www.versicherungs-vergleicher.de vs. versicherungsvergleicher.de

Du solltest Dich mal für eines der beiden URL-Schemas entscheiden. Sie sind nämlich gemixt und so wird z.B. die URL

http://www.versicherungs-vergleicher.com/wp-content/Podcast/0000-Folge-Null.m4a

weitergeleitet auf

http://versicherungs-vergleicher.com/wp-content/Podcast/0000-Folge-Null.m4a

Letztere erzeugt ein 404, warum auch immer. Du hast da irgendwie total obskure Redirects konfiguriert, die dem Publisher da nachhaltig in die Parade fahren.

Mein Tip: www.versicherungs-vergleicher.de per CNAME DNS Eintrag auf versicherungs-vergleicher.de zeigen lassen und alles nur über versicherungs-vergleicher.de laufen lassen. Jeglicher Konfigurationseintrag im WP und im Publisher sollte kein "www." sehen.

2. MIME Types

Deine MIME-Types sind im Argen. So wird für eine .mp3 Datei der MIME-Type "application/octet-stream" geliefert. Richtig wäre "audio/mpeg". Das muss geändert werden.


3. Doppeltes Asset

Du bietest ALAC und M4A Episode Assets unter der selben Extension an. Beide Dateien seien unter <episode-media-file-slug>.m4a  zu erreichen. Kann ja nicht sein. Du musst hier einen entsprechend unterschiedlichen Suffix konfigurieren.

**Comment by eteubert** [comment]
Und, wie @Erdebene schon richtig anmerkte, sind deine Dateien schlicht falsch benannt. Du hast gar keine "0000-Folge-Null.m4a"
Das Problem der ogg Datei: Der Publisher erwartet eine .oga extension. Entweder erzeugst du .oga, oder du änderst die extension im Publisher in `Expert Settings → File Types`

**Comment by versicherungs-vergleicher** [comment]
@Erik - Danke - tausendmal draufgeschaut und nicht gesehen
Das mit den FileTypes, die Dateien kommen so aus Auphonic, das muss ich dann korrigieren

@Tim  wo regelt man das mit dem url Schema - ok da hab ich jemanden den ich da fragen kann

weiterhin gehe ich davon aus Timm dass du dich nur vertippt hast und sich lles auf "com" bezieht aber es geht ja um den Rest nicht um de oder com

Auch das mit den MIme Types schaue ich mir an - muss erstmal verstehen was da los ist

vielen Dank, bin jetzt unterwegs und heut Nachmittag gehts los.... Danke für Eure nächtliche Unterstützung, als Vera F. Birkenbihl noch gelebt hat, vielleicht kennt ihr sie, war die nächtliche Kommunikation ein Herausforderung, sie hatte einen verschobenen Tag/Nacht Rhythmus - sie war genial und mit ihr zu arbeiten war riesig ;-)

**Comment by eteubert** [comment]
Zum Thema Downloads und mime types habe ich einen Screencast veröffentlicht. Vielleicht hilft der dir ja weiter :)

https://community.podlove.org/t/podlove-publisher-how-to-enable-force-downloads/78/1

**Comment by versicherungs-vergleicher** [comment]
Mime-Types - das habe ich nie angefasst und irgendwie scheint da alles so zu sein wie es Original war
![bildschirmfoto 2015-03-14 um 15 26 09](https://cloud.githubusercontent.com/assets/7683773/6653917/a93de92a-caa4-11e4-9d2f-6b63b337a90d.png)

**Comment by versicherungs-vergleicher** [comment]
das mit den Downloads am Download Button habe ich in der .htaccess eingebettet

**Comment by versicherungs-vergleicher** [comment]
zum Url Schema - schau mal am Server habe ich 2 Möglichkeiten, Möglichkeit 1 - ist nicht das was du meinst oder hilft das auch(?) da was einzustellen... Ich hab aber das in Bild 2 (2.Zeile)umgesetzt --> CName 
Habe ich das so richtig verstanden...?

![bildschirmfoto 2015-03-14 um 18 27 51](https://cloud.githubusercontent.com/assets/7683773/6653938/e7bc6ee6-caa5-11e4-817a-d7c81785463a.png)
![bildschirmfoto 2015-03-14 um 21 29 52](https://cloud.githubusercontent.com/assets/7683773/6653940/f5e0e6c8-caa5-11e4-887f-9cc1fd8b2ea1.png)

**Comment by versicherungs-vergleicher** [comment]
Hallo zusammen,

fast alles gelöst, nachdem die Assets alle da waren, waren die Feeds defekt.
Curl Error - das habt ihr aber schon einige Male behandelt und ich habe dann bemerkt, dass Tim mir oben schrieb, dass bei mir falsche Formate (MIME Types) geliefert werden-war aber alles richtig eingetragen. Der selbe Fehler wurde irgendwo in Issues erwähnt, also könnte jetzt nur ein Plugin Schuld sein. Alle ausgeschaltet, es ging - dann ZenCache ermittelt als Ursache ....  Dort kann man aber GZIP konfigurieren, was ich in den anderen Issues als  Lösung erkannt habe.... Mach ich noch.

@Erik blieb noch die Frage für mich warum in den File Types  Ogg zwar drin steht, nachdem du aber gesagt hättest dass er oga erwartet hätte ich die Dateiendung umbenannt und dann gings.... Die Ogg Datei fällt ja so aus Auphonic raus und ich hatte die FileTypes bis dahin nicht berührt

Da ich Opus auch teste und das Opus-Asset nicht erkannt wird, vermute ich ein ähnliches Problem wie muss denn dort die " Endung' sein, wollte ich gern wissen welche Dateiendung er in diesem Fall erwartet oder ob es dort was besonderes zu beachten gilt - allerdings ist das jetzt nicht Kriegsentscheident, das Format kann ich auch weglassen, aus Auphonic kommt "Opus" Format Extensions,

Herzlichen Dank für Eure tolle Unterstützung

**Comment by eteubert** [comment]
> warum in den File Types Ogg zwar drin steht

Es gibt zwei File Type Einträge für ogg, einen für jede Dateiendung. Ich sehe nur gerade, dass das bei der Auswahl nicht ersichtlich ist. Das muss ich anpassen.

> Da ich Opus auch teste und das Opus-Asset nicht erkannt wird, vermute ich ein ähnliches Problem

Die Endung (opus) stimmt. Aber schau dir bitte den oben genannten Screencast an, der löst auch dein Mime-Type-Problem (das ist bei dir bei m4a immer noch audio/mpeg und opus hat gar keinen Mime-Type) https://community.podlove.org/t/podlove-publisher-how-to-enable-force-downloads/78/1
