### ISSUE TITLE
Podcast Publisher breaks site search functionality

### ISSUE THREAD

**Issue by accozzaglia** [podlove/podlove-publisher#698]
The following error is generated when performing a routine search using the theme's search tool:

`[12-Mar-2015 22:26:35 UTC] PHP Fatal error:  Call to undefined method wpdb::esc_like() in /home2/toronua0/public_html/accozzaglia/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/includes/search.php on line 28`

The theme in use: Pinboard 1.06.

I commented out the following line in plugin.php in order to restore theme search functionality:
`// require_once \Podlove\PLUGIN_DIR . 'includes/search.php';`

For the short term, I can live without Episode posts being included in search results.

**Comment by eteubert** [comment]
I see you are running WordPress 3.6.1. The missing method was introduced in WordPress 4.0. I changed it so it's compatible to your Version.
You can leave the line commented out. Once I release the next version, it should reactivate automatically.

**Comment by timpritlove** [comment]
We also recommend you to upgrade to WordPress 4.1. There are many reasons to do so, security being one of them. We still support older versions of WordPress in general but soon raise the limit.

**Comment by accozzaglia** [comment]
Replying to eteubert: 
That is correct. At this time, I do use 3.6.1. The 8-line code fix you supplied does work, and I have uncommented-out the aforementioned line of code in plugins.php.

To both eteteubert and timpritlove: 

When I last tried to update to a current WP release a few months ago, there were simply too many issues which, even with all plug-in updates applied (including those which conflicted with the newest WP build), could not mend the functionality problems which emerged from updating; worse, there were a couple of plug-ins whose code had not been updated to work with the current release and with no functional equivalent found in any other plug-in available. 

What I ended up having to do was restore everything from backup. (At the time, I was using 3.5.1 and the current release was 3.9.3.) To describe having to do this as an inconvenience would be an incredible understatement.

Where I'm going with this aside:

I do understand how from a developer's angle, you're focussed on supporting the latest version of WP and operating ideally with the hope that everyone who uses your project for their end-needs only do so with the current version of software (the same premise is probably valid with reference to even what OS an end user has installed versus what OS is the latest). I understand how the motivation for this is, often above everything else, related to patching security holes in the source code as well as controlling the direction and usability of that software across the greatest number of environments (and why push-updating on mobile devices has become a routine way of doing things).

In real-world situations, however, the assumption that every WP admin is updating compliantly at the very moment a new WP update is released is neither workable nor tenable for reasons both practical and situational. Some of those may be related to maintaining compatible functionality for their specific needs; unfortunately, they cannot be faulted for that necessarily. Others are probably less technically inclined and are intimidated by tinkering with anything beyond style sheets. Others still may not be doing administration professionally (i.e., for pay) and are only doing so on an informal or casual basis.

The point I hope to convey is thus: whenever a WP plug-in release is specified for compatibility with earlier WP builds (as is the case with the current build of Podlove Publisher listed as "compatible with" from WP 3.6 onward), the understanding — the covenant, even — from an end-user's understanding is that that plug-in *should* work seamlessly with their legacy WP build (assuming that this plug-in is the only one they have as "active"; beyond that, plug-in conflicts are generally beyond your control as developers).

To admonish, however, end-users who reach out to you for support (in a developer-oriented environment such as github) by effecting the message, "You *should* update to the latest WP build if you want our stuff to work," is a wilful break of that covenant by the developer. Should a plug-in no longer work as intended for a legacy WP build, then this needs to be reflected plainly in the compatibility field on the WP plug-in page where an end-user found your plug-in.

That said, I like Podlove Publisher's potential enough to a) keep trying to make it work with my own setup, despite the issues which have arisen; b) take the initiative to communicate with you two, the developers, on issues which arise from using the plug-in; and c) do what I can as a non-developer to keep up with the developers. I do this, however, with an understanding that the developers prefer that end-users come to where *they* feel most at home (i.e., github/stackexchange/stackoverflow/etc. ), rather than meet with end-users in a more accessible general support setting (such as the native WP support forums for plug-ins).

Thanks for reading and thanks for your understanding.

**Comment by timpritlove** [comment]
Well that is all understood and a valid point. But I can only hope the same level of feedback goes to plugin developers who do not care so much about current versions of WordPress as the main reason to stay current is not to be the first or most modern or whatever but to keep up with the enormous security threat that bugs in WordPress pose. And every single release patches a lot of them.

As you have seen, we have already applied a patch to restore compatibility and we have not problem supporting old versions as long as it makes sense technically and considering the work load associated with doing so.

But we are also open to cut the cord on outdated versions that shouldn't be in use anyway (for security reasons) that prohibit us from moving ahead because of missing features or intrinsic bugs.
