### ISSUE TITLE
Using uploads from Wordpress to host a m4a file

### ISSUE THREAD

**Issue by jm-berthelot** [podlove/podlove-publisher#699]
Hey,

I got a problem, I can't use a m4a file uploaded in the uploads from wordpress (at this adresse : http://www.example.com/wp-content/uploads/xxx.m4a) for a podcast episode.

Despite the upload location in the pocast settings is http://www.example.com/wp-content/uploads/ and the media file slug in the podcast episode is xxx.m4a, it's still written "file not found".

Can you help me please ?

Thanks

**Comment by timpritlove** [comment]
What is the real URL? example.com URLs don't help us much.

**Comment by jm-berthelot** [comment]
suckitandlisten.com

The file is http://www.suckitandlisten.com/wp-content/uploads/Victory-_-by-PDM.m4a

**Comment by timpritlove** [comment]
Your web server delivers a "text/plain" MIME type for the file. That's something you should fix.

**Comment by jm-berthelot** [comment]
Ok. Thanks for your answer, but I'm a noob... Do you know a tool that can fix this ?

**Comment by eteubert** [comment]
Please doublecheck:

- in `Podcast Settings → Media → Upload Location` is `http://www.suckitandlisten.com/wp-content/uploads/`
- in your episode, the Media File Slug is _exactly_ `Victory-_-by-PDM` (capitalization matters)

You can find a tutorial for mime types here https://community.podlove.org/t/podlove-publisher-how-to-enable-force-downloads/78 but it's not the cause for a "file not found" warning.

**Comment by jm-berthelot** [comment]
![edit episode suck it and listen wordpress](https://cloud.githubusercontent.com/assets/11519554/6687452/6d6facae-ccab-11e4-9682-9af73781c981.png)

@eteubert, doublechecked, still didn't work...

**Comment by timpritlove** [comment]
The MIME Types are part of the web server configuration. So whoever is in charge and/or control of that got the job. When you are not self-hosting, talk to your webhoster's administrators. Not much we can do about that.

However, the 404 seems to be unrelated to that particular bug.

**Comment by eteubert** [comment]
Can you please copy & paste the output from `Podlove → Support` menu?

**Comment by jm-berthelot** [comment]
Website             http://www.suckitandlisten.com
PHP Version         5.4.38
WordPress Version   4.1.1
Publisher Version   2.0.5
Web Player Version  2.0.17
curl Version        7.21.0
iconv               available
simplexml           ok
max_execution_time  300
upload_max_filesize 64M
memory_limit        256M
disable_classes     
disable_functions   _dyuweyrj4,_dyuweyrj4r,dl
permalinks          ok
podcast_settings    
web_player          ok
podlove_cache       on
assets              
	m4a    audio/mp4

0 errors
0 notices
Nice, Everything looks fine!

**Comment by eteubert** [comment]
Strange, that looks ok.
One more thing to try: In `Podlove → Dashboard` look for the logging area. Are there any red entries "Can't reach ..."?

**Comment by jm-berthelot** [comment]
Thanks for your answers guys, i finally found it by just clicking on "attempt repair" in the podlove > support ! It worked well after that.

**Comment by eteubert** [comment]
Ah, great :)
