### ISSUE TITLE
Add chapters to the player

### ISSUE THREAD

**Issue by jm-berthelot** [podlove/podlove-publisher#700]
Hey,

I don't know how to cut the podcast episode in chapters in the player. 

I looked at http://podlove.org/simple-chapters/ and http://docs.podlove.org/podlove-web-player/ but i don't know where i can change the shortcode options...

My dream is to change the player like the image without using (and paying) audiophonic. I'm sure there is a free option to do that.

Thanks for your help !
![pwp_chapters](https://cloud.githubusercontent.com/assets/11519554/6689840/1ecc6e36-ccbd-11e4-9952-cea9ab6f8685.jpg)

**Comment by eteubert** [comment]
Watch this: https://community.podlove.org/t/podlove-publisher-how-to-enable-chapter-marks/75

**Comment by jm-berthelot** [comment]
Thanks !

**Comment by jm-berthelot** [comment]
Thanks ! Do you know how to add covert art per chapter (like the image i posted) ? 

Plus, if you know how to hide these buttons below the podcast player, it would be great !!! 

Thanks for your help !

[episode 11 pirate des mers by gilles suck it and listen](https://cloud.githubusercontent.com/assets/11519554/6691351/63d79da8-ccc6-11e4-9db7-f7b060800f5f.png)

**Comment by eteubert** [comment]
> how to add cover art per chapter

Only by using a more complex chapter format: http://podlove.org/simple-chapters/

> how to hide these buttons below the podcast player

Go to `Podlove → Templates` and edit the default template.

PS: For questions, https://community.podlove.org is a better place to ask. More people are hanging around there than here. github is mainly for bug reports.
