### ISSUE TITLE
Add Episodes on Homepage

### ISSUE THREAD

**Issue by jm-berthelot** [podlove/podlove-publisher#701]
Hey,

I got a problem : I don't know how to put Episodes on the Homepage of my blog. As you can see : http://www.suckitandlisten.com, there is a "latest posts" section that display only "posts" and not "episodes" (as it is a custom type posts). Do you know how to put posts and episodes in this section ?

Other problem : the theme i'm using is hickory. And the lasts article are put on the front page with a Featured Area Layout like this example : http://www.mumblr.fr, and i wanted to put the episodes and posts at this place. I guess that's the same problem...

Thanks for your help !

**Comment by eteubert** [comment]
Unfortunately, many themes have limited support for CPTs. Your best bet is to ask the theme developer, or ask someone who can handle HTML/PHP to adjust your theme.
