### ISSUE TITLE
Parts of episodes as separate entities

### ISSUE THREAD

**Issue by mtrgt** [podlove/podlove-publisher#703]
I’m producer of a show featuring several sections in each episode. I’d like to make each of these sections downloadable, subscribable and linkable. Ideally, each section would be part of on episode but would also have a separte page (or a page with the rest of the episode hidden which you could bring up front if you want to). Is there a way to make the publisher support this?

**Comment by eteubert** [comment]
The only thing you can do is use chapter marks for the sections. That way, you can jump to the sections within he web player. Other Han that, the scenario described by you is not something we ever thought of and I don't think it's possible.

**Comment by mtrgt** [comment]
Ok, I’ll see what I can achieve using the Publisher’s built in features and Javascript and if I get to a convincing result, I’ll show up again at this spot.
If by any chance, you plan on intergrating such a feature, I would be very glad to help within my limited capacities.
