### ISSUE TITLE
Episode Title in Social Media Share

### ISSUE THREAD

**Issue by bsardin** [podlove/podlove-publisher#704]
Love your plugin. However, I do want to let you know about a small bug. When I share an episode page on Facebook, the title of the episode does not appear. Before it showed as the file name, now it shows as no title. Thank you for this fantastic plugin!

Website             http://www.gracegonewild.net
PHP Version         5.4.37
WordPress Version   4.1.1
Publisher Version   2.0.5
Web Player Version  2.0.17
curl Version        7.38.0
iconv               available
simplexml           ok
max_execution_time  120
upload_max_filesize 32M
memory_limit        256M
disable_classes     
disable_functions   
permalinks          ok
podcast_settings    
web_player          ok
podlove_cache       on
assets              
	mp3    audio/mpeg

0 errors
0 notices
Nice, Everything looks fine!

**Comment by eteubert** [comment]
When I check http://www.gracegonewild.net/podcast/the-hair-committee-with-rev-natasha-murray-norman/ using the [Facebook Debugger](https://developers.facebook.com/tools/debug/) it looks good. Did you find the issue?
