### ISSUE TITLE
das summary wird nicht mehr im post angezeigt

### ISSUE THREAD

**Issue by mrchaosbude** [podlove/podlove-publisher#706]
ich hatte mir ein template angelegt wo alles wichtige eigentlich drin ne war nun wird anstelle des summarys nur noch [podlove-episode field="summary"] im post angezeigt. ich habe nun ein wenig herum probiert aber irgendwie will es gerade nicht. vielleicht könnt ihr mir ja helfen was ich ändern muss damit es wieder funktioniert 

so sied mein template aus : 

`<h2><p style="text-align: right;">[podlove-subscribe-button size="medium" width="medium"]</p></h2>
[podlove-episode field="summary"]
<h2></h2>
[podlove-web-player]

[podlove-episode-downloads style=""]

<h6 style="text-align: right;"><em><a href="http://www.jamendo.com/en/artist/338779/ton">Ton</a> <a href="http://www.jamendo.com/en/track/1095717/like-a-boy">like a boy</a>@<a href="http://www.jamendo.com">jamendo</a></em></h6>

[podlove-episode-contributor-list donations="yes"]`

ach so bei den alten folgen sieht es nun leider genauso aus :(

**Comment by eteubert** [comment]
Schau mal ins Podlove Dashboard. Da sollten Upgrade-Informationen zu finden sein. (Seit 2.0 sind einige Daten nur noch per Template Tag erreichbar, nicht mehr per shortcode)
