### ISSUE TITLE
possible problem with new Jetpack

### ISSUE THREAD

**Issue by leitmedium** [podlove/podlove-publisher#708]
Hey,

today the complete episodes stream disappeared from my podcast homepage. The feeds were fine and the episodes could be viewed when episodes urls were directly accessed. After some trial & error I assume the issue is related to Jetpack's new security features. After disabling Jetpack, clearing caches and creating and deleting a post the homepage with episode feed is back.

Sadfully I cannot give you any further error messages, but maybe this helps for tracking similar errors.

Best.

**Comment by eteubert** [comment]
Can you verify that it is related to the "Protect". There is another Jetpack issue in the Site Icon module (see #711) but that should not affect your homepage results, just the feeds.

**Comment by leitmedium** [comment]
Hey,

I sadfully cannot reproduce the bug. Re-enabling all of Jetpack's features did not empty the home page results again. Though disabling them was definitely fix. Maybe the bug only occurs when activacting some of Jetpack's features for the first time.

I'll keep an eye on this. You can close the report for now if you prefer.

**Comment by eteubert** [comment]
Ok, thanks for your help :)
