### ISSUE TITLE
Cover Bild wird nicht ordentlich skaliert

### ISSUE THREAD

**Issue by DamageIncorporated** [podlove/podlove-publisher#710]
Beim Einrichten auf der Seite *Podcast Settings* empfielt der Publisher für das Cover eine Bildgröße von *At least 1400 x 1400 pixels*. Dem habe ich natürlich Folge geleistet und mein Cover entsprechend gebaut und hochgeladen.

Allerdings nahm ich an, dass Wordpress oder der Publisher das Bild je nach Anwendungsfall (Webplayer, Subscribe-Button, etc) **serverseitig passend skaliert**, bevor es an den Benutzer ausgeliefert wird. 
Das scheint nicht der Fall zu sein, denn bei meiner hiesigen 2 MBit-Anbindung erzeugt das Cover in beiden genannten Fällen sehr lange Ladezeiten. Bei jetzt 1600x1600px kann ich zuschauen, wie sich das Bild aufbaut. Fühlt sich an wie früher(tm) ;-)

Danke und Gruß, Markus

**Comment by timpritlove** [comment]
Ja so ist das leider derzeit. Es empfiehlt sich, eine brauchbare Kompression zu wählen. Allerdings ist für eine der nächsten Versionen Abhilfe geplant: wir werden das Bild dann lokal cachen und für den jeweiligen Einsatz skalieren. Dann entfällt das Problem. Bis dahin musst Du das noch aushalten :)

**Comment by DamageIncorporated** [comment]
Alles klar, danke!
...dann also besser vorerst kein PNG ;-)

**Comment by Erdebene** [comment]
Ich reduziere die Farbtiefe aller Cover auf 256 Farben. Das fällt wenigstens mir optisch nicht auf, spart eine Menge Dateigröße und bringt somit Geschwindigkeit.

**Comment by eteubert** [comment]
Kommt mit Release 2.2.
