### ISSUE TITLE
RSS Feed is invalid

### ISSUE THREAD

**Issue by saschafoerster** [podlove/podlove-publisher#711]
I tried to play with the options, but I don't get the feed to validate. Do you have other hints what I need to change?
http://feedvalidator.org/check.cgi?url=http%3A%2F%2Fpodcast.saschafoerster.de%2Ffeed%2Fm4a%2F
Kind regards, Sascha

**Comment by eteubert** [comment]
Looks like a plugin incompatibility. See attached screenshot.

![feed_validator_results__http___podcast_saschafoerster_de_feed_m4a_](https://cloud.githubusercontent.com/assets/235918/6955251/8d5815c4-d90d-11e4-90e7-104af406f57d.png)

**Comment by saschafoerster** [comment]
I found the evil plugin: it's Jetpack Site-Icon functionality: http://jetpack.me/support/site-icon/ Thank you for your help!
