### ISSUE TITLE
Custom Post Type "Episodes" not shown in several themes

### ISSUE THREAD

**Issue by Nefariuscipher** [podlove/podlove-publisher#712]
Hey there!

Just curious if there's a workaround of what I am intending to do.

I successfully implemented podlove for different installations, that use different themes.

However I encounter problems when it comes to actually displaying them in the "Blog" View of the site. E.g. some "build your own" themes just offer me the option to show posts with certain categories. However the custom post type "episodes", provided by Podlove has no categories. 

Therefore my podcast episodes are simply not shown.

Apparently this has something to do, with the theme developer, who is not using the Wordpress Codex standards. I am guessing I am not the only one, who has this problem. Is there a workaround to fix this?

**Comment by timpritlove** [comment]
You can enable categories as a module within Podlove. It is not on by default. Not sure this already solves the problem. The theme in general has to be able to deal with custom post types, specifically "podcast" which we use.

**Comment by Nefariuscipher** [comment]
Okay great. I am going to try this and check if that works. Anyway your plugin is extremely awesome. If only the theme designers would code that stuff correctly ... ;-)
