### ISSUE TITLE
Podlove Import auf einem HHVM Server

### ISSUE THREAD

**Issue by ugoArangino** [podlove/podlove-publisher#713]
Ich habe einen frisch aufgesetzten **Debian Server** mit **nginx** und **hhvm**. Ein aktuelles Wordpress ohne weitere Plugins ist installiert. Wenn ich die alten Podlove Einstellungen importieren möchte wird mir eine weiße Seite angezeigt.

Im HHVM Error Log steht folgendes (/var/log/hhvm/error.log):

```
Fatal error: Uncaught exception 'BadMethodCallException' 
with message 'Call to a member function registerXPathNamespace() on a non-object (boolean)' 
in /var/www/html/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/lib/modules/import_export/import/podcast_importer.php:84
Stack trace:
#0 /var/www/html/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/lib/modules/import_export/import/podcast_importer.php(40): Podlove\\Modules\\ImportExport\\Import\\PodcastImporter->import()
#1 /var/www/html/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/lib/modules/import_export/import_export.php(14): Podlove\\Modules\\ImportExport\\Import\\PodcastImporter::init()
#2 /var/www/html/wp-includes/plugin.php(496): Closure$Podlove\\Modules\\ImportExport\\Import_Export::load()
#3 /var/www/html/wp-admin/admin.php(145): do_action()
#4 {main}
```

**Comment by eteubert** [comment]
An der Stelle fehlt error-handling. Was das heißt, ist, dass PHP die export-Datei nicht lesen kann. Lädst du die XML hoch oder die komprimierte Datei (und versuch mal das andere)?
Ich kann aber eine hhvm-Kompatibilität auch nicht ausschließen, da ich damit nicht teste.

**Comment by ugoArangino** [comment]
Ich habe jetzt auf einer neuen Instanz beides ausprobiert. Der gleiche Fehler taucht noch immer auf. 
Wenn ich den SQL Dump importiere und die Dateien manuell überspiele funktioniert alles, auch mit hhvm.

**Comment by timpritlove** [comment]
Besteht dieses Problem noch?

**Comment by ugoArangino** [comment]
Weiß ich nicht. Könnte sich inzwischen geändert haben. 
Ich hatte es damals manuell (SQL) importiert.
