### ISSUE TITLE
Strange length of one episode in episode list

### ISSUE THREAD

**Issue by GoetzMueller** [podlove/podlove-publisher#715]
In the episode list there a strange length given http://www.geemco.de/kaizen-2-go-podcast/ (# 010) see also attached screenshot.

The length in the episode itself looks ok and it plays without any issue. Any idea about that?

![bildschirmfoto 2015-04-04 um 17 44 53](https://cloud.githubusercontent.com/assets/10376917/6993372/5c2e394c-daf2-11e4-9603-994a4683bd1c.png)

**Comment by timpritlove** [comment]
What does the duration setting in the Episode itself say?

**Comment by GoetzMueller** [comment]
In the episode (after loading the file) it said 0:40:... However, in the backend the information was lost for whatever reason. After a re-loading and storing the episode it looks good now.
