### ISSUE TITLE
Inkompatibilität mit Parallax Theme

### ISSUE THREAD

**Issue by Raintrader** [podlove/podlove-publisher#718]
Ich benutze das Podlove Plugin innerhalb des Parallax Theme von Themefy.
Dieses Theme verwendet Custom Postypes für Portfolio, Highlights und Team Posts.
Auch Design Templates innerhalb des Themes verden mit CPT´s verwaltet (Builder Layouts).
Diese werden standardmässig nicht mit im Kategorien Index ausgegeben (http://sugartweaks.de/diabetes-blog/).

Bei aktivierten Podlve Plugin, tauchen jedoch im Index der Kategorie "diabetes-blog" ein paar (nicht alle )Post´s des CPT "Builder Layout" des Themes auf.

Ebenso tauchen die Podcast Episoden des Poldlove Plugins im Kategorien Index auf, obwohl die Option **"Include episode posts on the front page and in the blog feed" nicht Aktiviert ist.**
 Im Normalen standard Blog Loop von WP tauchen die CPTs nicht auf.
Dies passiert **nur innerhalb eines Kategorien Index.** Merkwürdiger Weise werden nur 3  (von 12) Posts der Theme CPT´s dargestellt und nur 2 Episode CPTs obwohl insgesamt drei vorhanden sind.

Deaktiviere ich das Podlove Plugin verschwinden sowohl die CPT des Plugins als auch die des Themes wieder aus dem Kategorien Index.

Ich habe schon Konatkt mit dem Themefy Support aufgenommen,(http://themify.me/forum/topic/custom-post-types-show-up-in-a-category-index) diese verweisen mich jedoch nach Prüfung auf den Podlove Support.

Hier ein paar Screenshots die das Problem darstellen.

![Podlove CPT in Cat index](http://sugartweaks.de/Pics/Parallax-A.png)
![Parallax Theme CPT in Cat index](http://sugartweaks.de/Pics/Parallax-B.png)
![Admin Page Theme CPT](http://sugartweaks.de/Pics/Parallax-C.png)

**Comment by eteubert** [comment]
Haben sie mehr gesagt als "frag mal die anderen"? Denn die Theme Entwickler sind im Gegensatz zu mir in der Lage, das Problem zu debuggen. Der Publisher ist kostenlos verfügbar. Ich kann nur rätselraten, da ich das Theme nur debuggen kann, wenn ich es kaufe.

Theme-Inkompatibilitäten fallen eher in die Support-Kategorie als Bug-Report. Daher verweise ich dich mal in die Community (https://community.podlove.org), ggf. hat dort jemand das gleiche Plugin im Einsatz.

**Comment by Raintrader** [comment]
Sie sagten " frag mal die anderen und wenn die nichts tun können, schauen wir noch mal".
Was mich allerdings glauben lässt das es doch eher ein Bug ist, ist die Tatsache dass die Podcast Episoden im Blog auftauchen obwohl die Option "Include episode posts on the front page and in the blog feed" nicht aktiviert ist.

**Comment by eteubert** [comment]
Ich schließe nicht aus, dass es ein Bug auf unserer Seite ist :) Ich habe nur keine Möglichkeit, es zu überprüfen. Du bist auch der erste seit Monaten, der ein Problem mit dem von dir genannten Setting hat, woraus ich schließe, dass es ein Spezialfall im Zusammenspiel mit dem Theme ist.

**Comment by Raintrader** [comment]
Hab nun mal das Theme gewechstelt. Auch dort tritt das Problem auf. Im Blog feed der Startseite werden die Episoden nicht angezeigt. Allerdings im Index einer Kategorie. Es scheint als seinen die Episoden dieser Kategeroie zugeordnet worden. Kann ich das irgendwo überprüfen, bzw ändern ?

**Comment by eteubert** [comment]
Du kannst in `Podlove > Modules` prüfen, ob das "Categories" Modul aktiv ist. Das aktiviert Kategorien für Episoden.
Aber selbst dann sind diese Kategorien *eigentlich* getrennt von denen für Posts.
