### ISSUE TITLE
Podlove & Ozh' Admin Drop Down Menu

### ISSUE THREAD

**Issue by riggie11** [podlove/podlove-publisher#719]
Hi all, 

If you're using the Ozh' Admin Drop Down Menu plugin in your Wordpress admin, Podlove causes the menu to create blank spaces beneath the drop down menu.

Is there any way to solve this?

thanks,
Riggie
![podlove](https://cloud.githubusercontent.com/assets/11852880/7044667/3c676e42-ddf6-11e4-9e9c-53ac32ee56ee.jpg)

**Comment by riggie11** [comment]
It should look like this below...
![podlove2](https://cloud.githubusercontent.com/assets/11852880/7044719/c6739200-ddf6-11e4-9d75-75b53861d96d.jpg)

**Comment by timpritlove** [comment]
Looks like the plugin has problems with SVG Icons. Have you reported this to the author of the "Ozh' Admin Drop Down Menu" plugin?

**Comment by riggie11** [comment]
I have now reported to Ozh' Admin's author.

Podlove is the only plugin I've ever had causing this problem, so I assumed it could be fixed by you guys...

**Comment by timpritlove** [comment]
Podlove might be the only plugin using SVG for the menu graphics until now but given the fact that SVG is now an established internet standard I assume there is really nothing to "fix" here. I think it's just an unexpected "new" image file format for some who think the web is still JPG and PNG only.

However, I can not exclude that any errors were made here. Let's see what the Ozh' Admin's author is saying about this. We are happy to change everything that makes sense. However, the logos work fine within WordPress so I would not know where to start.

Can you provide a link to that report? Is it a GitHub issue too?

**Comment by riggie11** [comment]
Tim, it just seems to be an issue with SVG not displaying properly in Ozh Admin.

I submitted the issue here:
https://wordpress.org/support/topic/podlove-icon-problem?replies=2#post-6800297

**Comment by riggie11** [comment]
Hi Tim,
Ozh Admin have a solution to the SVG problem, so no worries to take action with Podlove :-)

https://wordpress.org/support/topic/please-add-width-value-to-the-wp-menu-image-css

**Comment by timpritlove** [comment]
Great. I consider this a solved problem then.
