### ISSUE TITLE
Social Media Dienste: Spreaker.com?

### ISSUE THREAD

**Issue by DamageIncorporated** [podlove/podlove-publisher#720]
Die Liste der Social Media Dienste ist ja bereits sehr lang, aber da ich nicht weiß, welches die Aufnahmekriterien für neue Dienste in dieser Liste sind: Wie wäre es mit Spreaker.com?

Die gibt es auch bei den "Auphonic external services", sonst wäre mir der Dienst wahrscheinliech bisher nie begegnet 

Danke und Gruß, Markus

**Comment by katrinleinweber** [comment]
Hi Markus,

es wurden schon einige [von Nutzern vorgeschlagene Dienste aufgenommen](https://github.com/podlove/podlove-publisher/pulls?q=service). Der beste Weg zum Erfolg ist [das Forken dieses Repos](https://github.com/podlove/podlove-publisher#fork-destination-box), gefolgt vom Einpflegen des gewünschten Dienstes mit Logo, und des abschließenden Pull Requests. Vorlagen findest du in den `Files changed`-Tabs der alten Pull Requests.

Viele Grüße!

**Comment by chemiker** [comment]
Added with #912.
