### ISSUE TITLE
Analytics not showing up

### ISSUE THREAD

**Issue by sftsk** [podlove/podlove-publisher#721]
Hello,

we are using the Publisher since a few months (probably starting with 1.12-alpha) and have activated the analytics. Everything shows up as being set up the right way, but unfortunately it still shows the following message: `Still crunching the numbers. The first time it may take up to an hour until you see analytics.`.

We have just published the second episode (the first one was published before the analytics were released). Do you have any idea what might be wrong?

Thanks and all the best, keep up the great work!

Lukas

attached here some screenshots and the debug info:
![screen shot 2015-04-09 at 14 54 00](https://cloud.githubusercontent.com/assets/646910/7067028/6434d9b4-dec8-11e4-9747-9980d823c181.png)
![screen shot 2015-04-09 at 14 53 53](https://cloud.githubusercontent.com/assets/646910/7067030/68fe26f8-dec8-11e4-807d-02e3e22350c9.png)

```
Website             https://booncon.com/wp
PHP Version         5.5.9-1ubuntu4.6
WordPress Version   4.1.1
Publisher Version   2.0.4
Web Player Version  2.0.17
curl Version        7.35.0
iconv               available
simplexml           ok
max_execution_time  30
upload_max_filesize 2M
memory_limit        256M
disable_classes     
disable_functions   pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,
permalinks          ok
podcast_settings    
web_player          ok
podlove_cache       on
assets              
	m4a    audio/mp4
	mp3    audio/mpeg
	opus   audio/ogg;codecs=opus
	chapters.txttext/plain

0 errors
0 notices
Nice, Everything looks fine!
```

**Comment by sftsk** [comment]
Investigating a little more shows, that there are around 60 entries in the `wp_podlove_downloadintent` table but 0 in the `wp_podlove_downloadintentclean` table.
It seems like there is something wrong with filtering them? Or is there a critical mass that needs to come through?

Thanks!

**Comment by eteubert** [comment]
Analytics are processed hourly in a background WP-Cron job. You can use a plugin like https://wordpress.org/plugins/wp-crontrol/ to see if they are running properly. The important cron identifier to look for is "podlove_cleanup_download_intents".

**Comment by sftsk** [comment]
Thank you for the comment, the cron does not show up in the list:
![screen shot 2015-04-10 at 10 31 27](https://cloud.githubusercontent.com/assets/646910/7084375/cfaaaf44-df6c-11e4-9dcf-a86c0fa2dbb4.png)

I just tried deactivating & activating the publisher plugin, didn't help.

**Comment by timpritlove** [comment]
Can you check the web servers error log for any PHP errors that might be related?

**Comment by eteubert** [comment]
And can you try to disable w3tc and see if that helps?

**Comment by sftsk** [comment]
Nothing in the error log.
Turned off w3tc and deactivated/ activated the publisher again. No luck :(
When should the cronjob get "registered", is there any way for me to try triggering that?

**Comment by eteubert** [comment]
> When should the cronjob get "registered"

On every request. You trigger it by ... loading any admin-site ;) That's why I suspect some other plugin interfering in the cron system, especially w3tc since it's the only one that registered crons on your system.

**Comment by sftsk** [comment]
The triggering I understand,  but when does it get registered? When activating the plugin?
From what I understand the cronjob should show up in the crontrol screen, right?
I have very little plugins activated, I attached a screenshot.

![screen shot 2015-04-10 at 13 30 36](https://cloud.githubusercontent.com/assets/646910/7086860/eacc8bc6-df85-11e4-8b6f-470b5de9955a.png)

**Comment by sftsk** [comment]
I now tried calling the cron through wp-cli, I get the following error:
```
PHP Fatal error:  Class 'Monolog\Logger' not found in /var/www/bc-new/releases/20150302074145/web/app/plugins/podlove-podcasting-plugin-for-wordpress/lib/log.php on line 33
Fatal error: Class 'Monolog\Logger' not found in /var/www/bc-new/releases/20150302074145/web/app/plugins/podlove-podcasting-plugin-for-wordpress/lib/log.php on line 33
```
will try to do a little more debug, thanks for pointing me to the right direction

**Comment by eteubert** [comment]
> The triggering I understand, but when does it get registered? When activating the plugin?

No, it really is registered on every request (if it's not already known to WordPress): https://github.com/podlove/podlove-publisher/blob/master/lib/analytics/download_intent_cleanup.php#L18

> I now tried calling the cron through wp-cli

I'm not sure how that works internally but it looks like the class autoloading is not functioning that way.

**Comment by sftsk** [comment]
Solved it, we are using [Bedrock](https://github.com/roots/bedrock) as the base of our Wordpress project and I just discovered that it disables the Wordpress Cron.

Reading their [documentation](https://roots.io/bedrock/docs/) helps:

```
wp-cron

Bedrock disables the internal WP Cron via define('DISABLE_WP_CRON', true);. If you keep this setting, you'll need to manually set a cron job like the following in your crontab file:

*/5 * * * * curl http://example.com/wp/wp-cron.php
```

I hope this is useful to somebody else, thanks for the help!

**Comment by eteubert** [comment]
Wow. Yeah I've heard about it before. But why would they disable it? Sure, running a real cron is the better way but silently disabling core functionality seems plain wrong. Gheez.

Thanks for coming back to report your findings :)
