### ISSUE TITLE
Webplayer wird doppelt angezeigt

### ISSUE THREAD

**Issue by chmock** [podlove/podlove-publisher#722]
Hi.
Nach einem (zunächst) fehlgeschlagenem Pluginupdate wird mir jetzt der Player doppelt angezeigt.
Ich hatte nach dem fehlgeschlagenem Update, das Plugin manuell geladen und per FTP in der entsprechende Verzeichnis kopiert. 
Hat jemand eine fixe Idee, wo ich das Problem finde?

Hat es was damit zu tun, dass mir in den Podlove Web Player Options folgendes angezeigt wird?

Notice: Undefined offset: 1 in D:\is\www\podcast.sbk-rlp.de\wp-content\plugins\podlove-podcasting-plugin-for-wordpress\lib\modules\podlove_web_player\player\podlove-web-player\settings.php on line 246

Notice: Undefined offset: 1 in D:\is\www\podcast.sbk-rlp.de\wp-content\plugins\podlove-podcasting-plugin-for-wordpress\lib\modules\podlove_web_player\player\podlove-web-player\settings.php on line 247

Gruß
Chris

**Comment by eteubert** [comment]
Wie bindest du den Player denn ein? Template, Shortcode oder automatisches Einfügen am Anfang/Ende des Posts?

**Comment by chmock** [comment]
Automatischen Einfügen am Anfang.

**Comment by eteubert** [comment]
Dann schau mal bitte in `Podlove > Templates`, ob auch ein Template, das den Player enthält, automatisch eingefügt wird.

**Comment by chmock** [comment]
Oh je, das ist mir jetzt schon echt peinlich. Ich habe noch nie mit einem Template gearbeitet, deshalb war mir diese Funktion unbekannt. Es stand auf "default"... daher der zweite Player. Muss irgendwie mit den Update gekommen sein.
Jetzt schaut optisch alles gut aus, aber der Player lädt die Datei zum abspielen nicht mehr... ich werd erstmal weiter suchen, außer du, oder sonst jemand, weiß grad, woran das liegen könnte.

Danke schonmal! 
LG
Chris

**Comment by chmock** [comment]
Aha:
Bei einem versuchten Download erhalte ich folgendes:

Fatal error: Call to undefined function openssl_digest() in D:\is\www\podcast.sbk-rlp.de\wp-content\plugins\podlove-podcasting-plugin-for-wordpress\includes\downloads.php on line 62

**Comment by eteubert** [comment]
> Fatal error: Call to undefined function openssl_digest()

Das wird nur im Tracking verwendet, d.h. wenn du das ausschaltest, geht es erstmal wieder.

Besser wäre, openssl Support in PHP anzuschalten (was je nach System/Konfiguration unterschiedlich funktioniert).
