### ISSUE TITLE
Mein Feed ist leer

### ISSUE THREAD

**Issue by bameier** [podlove/podlove-publisher#723]
Seit der Veröffentlichung meiner aktuellen Episode IP027 Psychoanalyse ist mein feed leer und ich kann den Fehler nicht finden. Ich bin schon etwas verzweifelt. 
Sowohl 
http://www.indyacapunk.de/feed/mp4/ 
als auch der mp3 feed zeigen rein gar nichts an. 
Ich hatte ein paar Plugins aktualisiert, die ich nun bereits deaktiviert habe. Vorher hatte ich einen Beitrag gelöscht, den ich auch wieder aus dem Papierkorb genommen habe. Ich habe sonst weiter nichts gemacht heute.

Website             http://www.indyacapunk.de/wordpress
PHP Version         5.3.28-nmm2 (upgrade to 5.4 or higher recommended)
WordPress Version   4.1.1
Publisher Version   1.12.1-alpha
Web Player Version  2.0.17
curl Version        7.22.0
iconv               available
allow_url_fopen     1
simplexml           ok
max_execution_time  30
upload_max_filesize 200M
memory_limit        256M
disable_classes     
disable_functions   
permalinks          ok
podcast_settings    
web_player          ok
podlove_cache       on
assets              
	mp3    audio/mpeg
	m4a    audio/mp4
	png    image/png

0 errors
1 NOTICE (no dealbreaker, but should be fixed if possible): 
- Official support for PHP 5.3 ends 14 August 2014. We will require PHP 5.4 once we reach Publisher 2.0. Feel free to upgrade to a higher version like 5.5.

**Comment by bameier** [comment]
Ich habe gerade einen Hinweis bekommen, dass der Feed eventuell schon ein paar Tage länger leer ist. Seit dem Blogpost, dass ich über Ostern keine Episode veröffentliche. Ich habe den Post gelöscht. Kann das daran liegen, dass ich noch die alte Podlove Version 1.12.1-alpha benutze. Ich muss noch auf einen Server umziehen, der das geforderte neue PHP hat.

**Comment by eteubert** [comment]
Schwer zu sagen. Ich kann dir nur empfehlen, so viele Plugins wie möglich zu deaktivieren, da es grundsätzlich ja noch funktioniert (auf der Webseite). Ggf. auch kurz auf ein Standardtheme wechseln, falls das Theme aktualisiert wurde und jetzt ein anderes Feedverhalten hat.

**Comment by bameier** [comment]
Ich habe wieder ein Standardtheme geladen. Dies war es anscheinend, denn nun ist der Feed wieder da. Danke.
