### ISSUE TITLE
Can't add contributors

### ISSUE THREAD

**Issue by Nefariuscipher** [podlove/podlove-publisher#726]
hey there!

I am running the latest version of wordpress and podlove but for some reasons I can't add contributors at "episodes". It only shows me to look for them, but not actually adding them.

How can I troubleshoot this?

**Comment by eteubert** [comment]
It's a bit hard to find, it's in a separate menu :)

![episodes_ _newz_of_the_world_ _wordpress](https://cloud.githubusercontent.com/assets/235918/7318527/5f3f243e-eabf-11e4-888d-017499ca86ec.png)

**Comment by Nefariuscipher** [comment]
Hah! ;-)
Can't believe it ... 
Missing the forest for the trees.

Thanks @eteubert
