### ISSUE TITLE
Kein Zugriff auf Netzwerkverwaltung Podlove Dashboard + Podlove Templates

### ISSUE THREAD

**Issue by mysharepoint** [podlove/podlove-publisher#727]
Wenn ich die beiden Links Netzwerkverwaltung Podlove Dashboard + Podlove Templates anklicke, bekomme ich nur eine Fehlermeldung

Du hast nicht die erforderlichen Rechte, um auf diese Seite zuzugreifen.

Bin als SuperAdmin angemeldet, Problem auf 2 verschiedenen WordPress-Installationen (Version 4.2)

**Comment by eteubert** [comment]
Spannend, kann ich nicht nachvollziehen.

- Ist das Plugin "Netzwerkweit aktiviert" oder separat pro Blog?
- Falls nicht, ist es im "Haupt-Blog" (Blog 1) aktiv? (wobei das Podlove-Menü gar nicht erscheinen sollte, wenn das Plugin weder netzwerkweit aktiviert noch im Haupt-Blog aktiv ist)

**Comment by mysharepoint** [comment]
Hallo danke für dien Hinweis mit 2 hat es funktioniert Haupt-Blog" (Blog 1) aktiv

**Comment by eteubert** [comment]
Ah, jetzt weiß ich, unter welche Konstellation das Problem auftritt: Du hast die Plugins einzeln aktiviert und siehst dann die Netzwerk-Links im Admin-Menü. Die zeigen aber ins Leere, wenn im Haupt-Blog kein Publisher aktiv ist. Danke! :)
