### ISSUE TITLE
Webplayer automatisch einfügen nicht aktivierbar

### ISSUE THREAD

**Issue by pixelsophie** [podlove/podlove-publisher#728]
Hallo,
ich wollte gerade (nach dem Update) mal wieder testen ob der Webplayer jetzt mit meinem Theme funktioniert. Und weil ihr so tolle Arbeit leistet funktioniert es tatsächlich.

Nun wollte ich die Option aktivieren: automatisch am Ende einfügen. Leider erhalte ich dann aber folgende Fehlermeldung:
FEHLER: Die Einstellungsseite wurde nicht gefunden.
und kann diese Option nicht aktivieren. Hat Jemand eine Idee wie ich das lösen könnte?

**Comment by chemiker** [comment]
@pixelsophie Besteht das Problem noch?

**Comment by pixelsophie** [comment]
Nein, das ist auch gelöst worden und funktioniert.
Danke euch!
