### ISSUE TITLE
Webplayer not rendering on website & Can't save Expert Settings

### ISSUE THREAD

**Issue by Nefariuscipher** [podlove/podlove-publisher#729]
Hey there!

On this site for a client I am using WP 4.2.2. and the latest version of Podlove.

For some odd reason the Webplayer is not rendering, although the media is found. 

Here is an affected episode: http://www.florians.eu/2015/03/ziele/

How can I debug this?
Sebastian

**Comment by eteubert** [comment]
Check your templates. There's one prepended by default and it should include the web player.

**Comment by Nefariuscipher** [comment]
found the settings, but here happens something funny, too.

When I want to activate the settings the following error is returned:
FEHLER: Die Einstellungsseite wurde nicht gefunden.

How is that possible?

The same happens, when I would like to activate Tracking functionality in settings.

There seems to be something affecting the behaviour of the plugin ...

**Comment by eteubert** [comment]
> On this site for a client I am using WP 4.2.2

Is this a typo? The most recent version is 4.2. In any case, it might help if you paste the contents of `Podlove > Support` menu.

> > FEHLER: Die Einstellungsseite wurde nicht gefunden.
> How is that possible?

Not sure, I'm not able to reproduce it. Can you temporarily deactivate all plugins except the publisher?
And does this happen on all Publisher Settings pages or just Templates and Expert Settings?

**Comment by Nefariuscipher** [comment]
Hey @eteubert !

Yeah this was a typo ;-)

Website             http://www.florians.eu
PHP Version         5.6.8
WordPress Version   4.2
Publisher Version   2.1.0
Web Player Version  2.0.17
open_basedir        /home/.sites/907/site199/web:/home/.sites/907/site199/tmp:/usr/share/pear
curl Version        7.15.5
iconv               available
simplexml           ok
max_execution_time  25
upload_max_filesize 200M
memory_limit        128M
disable_classes     
disable_functions   
permalinks          ok
podcast_settings    
web_player          ok
podlove_cache       on
assets              
	mp3    audio/mpeg

1 ERROR: 
- The PHP setting "open_basedir" is not empty. This is incompatible with curl, a library required by Podlove Publisher. Please ask your hoster to unset "open_basedir".
0 notice

Could this be caused through some kind of Firewall or Access restrictions (htaccess)? I am trying to think outside the box

**Comment by eteubert** [comment]
Seems to be related to #739.

**Comment by Nefariuscipher** [comment]
Hey there!

Found a "solution" I wanted to share with you. Basically I deleted the entire plugin and installed it new. Then it worked for me. I am not sure if this is suitable for everyone and I am also not sure WHY it worked ...

**Comment by eteubert** [comment]
Interesting. Well. Glad it works for you now :)
