### ISSUE TITLE
Kann keine Podcastlisten anlegen

### ISSUE THREAD

**Issue by mysharepoint** [podlove/podlove-publisher#730]
Über Netzwerkverwaltung -> Podcast Dashboard möchte ich eine neue Podcastliste anlegen.

Kann das Formular auch ausfüllen und die beiden Podcasts in meinem Netzwerk hinzufügen, Liste speichern - aber erscheint danach nicht in der Übersicht. Liste wird nicht angelegt.

Zusatzfrage: was gebe ich unter ListURL ein ?

**Comment by timpritlove** [comment]
List URL ist quasi die "Landing Page" - eine URL die Du quasi als Home Page für diese Liste ansiehst. Das ist in der Regel eine entsprechende Übersichtsseite auf Deiner Website.

**Comment by mysharepoint** [comment]
Danke das mit der List URL habe ich verstanden, aber ich kann keine Listen erstellen

**Comment by timpritlove** [comment]
Ja, da müssen sich die anderen mal zu äussern

**Comment by eteubert** [comment]
Kannst du auf der Modul-Seite bitte einmal abspeichern (keine Module ändern) und dann noch mal versuchen?

**Comment by mysharepoint** [comment]
meinst du mit Modul plugin?

**Comment by timpritlove** [comment]
Podlove -> Modules

**Comment by mysharepoint** [comment]
ok Modules gefunden, gespeichert, Liste anlegen funktioniert - gibt es auch eine Anleitung wie man die Liste jetzt verwendet über Shortcode oder templates? Wäre für einen Tipp dankbar

**Comment by eteubert** [comment]
Danke, jetzt weiß ich was das Problem ist :)

> gibt es auch eine Anleitung wie man die Liste jetzt verwendet über Shortcode oder templates? Wäre für einen Tipp dankbar

Einen Shortcode haben wir nicht, aber du kannst dieses Template als Basis benutzen und nach deinen Wünschen anpassen:

```jinja
{% set list = network.lists({id: "foo"}) %}
{% set icon_size = 64 %}

<h2>{{ list.title }}</h2>
<p>{{ list.subtitle }}</p>
<p><small>{{ list.description }}</small></p>

<table class="podcast-list">
  <tbody>
	{% for podcast in list.podcasts %}
    <tr>
      <td>
        <a href="{{ podcast.landingPageUrl }}" title="{{ podcast.title }}">
					<img height="{{ icon_size }}" width="{{ icon_size }}" class="icon64" src="{{ podcast.imageUrl({size: icon_size}) }}">
				</a>
      </td>
      <td>
        <span class="title"><a href="{{ podcast.landingPageUrl }}" title="{{ podcast.title }}">{{ podcast.title }}</a></span><br>
        <span class="subtitle">{{ podcast.subtitle }}</span><br>

        <span class="links">
			{% for service in podcast.services({category: "social"}) %}
            <a title="{{ podcast.title }} bei Twitter" href="{{ service.profileUrl }}" target="_blank">
                <img width="16" height="16" src="{{ service.logoUrl }}" class="podlove-contributor-button" alt="{{ service.title }}" />
            </a>&nbsp;
		    {% endfor %}
        </span>
        <br/>

        {{ flattr.button({ user: 'timpritlove', url: podcast.landingPageUrl }) }}
        {{ podcast.subscribe_button({size: 'small', width: ''}) }}
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
```

Liste aller Template Tags: http://docs.podlove.org/reference/template-tags/
