### ISSUE TITLE
Shortcode "id" deprecation warning from content automatically added at the top

### ISSUE THREAD

**Issue by jthoenes** [podlove/podlove-publisher#732]
Hi,

I just upgraded to 2.1. I have a template called 'start' to be 'Insert at top' configured from the templates configuration. It does not contain references to other templates.

On my pages (e.g. http://der-alltaegliche.de/2015/02/16/switch-wie-man-dinge-veraendert-wenn-es-schwer-faellt-dap-059/), I get the following warning:

````
Notice: Podlove\template_shortcode wurde mit einem Parameter oder Argument aufgerufen, der seit Version 2.1.0 veraltet ist! The "id" attribute for [podlove-template] shortcode is deprecated. Use "template" instead.start in /srv/der-alltaegliche/wordpress/wp-includes/functions.php on line 3508
````

Any ideas?

**Comment by eteubert** [comment]
Fill be fixed in next patch.

Until then, you can hide PHP notices by putting this at the end of your `wp-config.php`: `define('WP_DEBUG_DISPLAY', false);`

**Comment by jthoenes** [comment]
OK, thanks!
