### ISSUE TITLE
Flattr Javascript lässt sich nicht deaktivieren

### ISSUE THREAD

**Issue by ulikoenig** [podlove/podlove-publisher#734]
Hallo,

ich habe keine Möglichkeit gefunden, das Javascript, das direkt vom Flattr-Server eingebunden wird, abzuschalten.
Durch das einbinden dieses Skriptes von einem Drittserver, werden alle Besuche auf der eigenen Webseite an einen Fremden Server signalisiert. Dies macht das Erstellen einer korrekten Datenschutzerklärung auf der eigenen Webseite unnötig komplex. Ich sparen mir die detaillierten Ausführungen. 

Ich bitte darum, das Javascript nur einzubinden, wenn der Flattr-Button explizit aktiviert wird.

Ich habe meine Installation aktuell von Hand angepasst, indem ich in der Datei: 
```
includes/flattr.php 
```
die folgende Zeile entfernt habe:
```
add_action('wp_head', 'podlove_flattr_script_head');
```
Viele Grüße

Uli

**Comment by katrinleinweber** [comment]
+1 Habe das mal als [feature request eingereicht](https://community.podlove.org/t/fr-mirror-button-style-from-flattr-plugin/105).

**Comment by eteubert** [comment]
Wir haben vor, die ganze Flattr-Funktionalität in ein Modul zu kapseln.

Bis dahin empfehle ich folgendes:

https://wordpress.org/plugins/code-snippets/ installieren und folgendes Snippet einfügen:

```php
add_action('plugins_loaded', function() {
	remove_action('wp_head', 'podlove_flattr_script_head');
});
```

Das übersteht auch Publisher-Updates :)
