### ISSUE TITLE
2.1.1 apple Podcast App 

### ISSUE THREAD

**Issue by nikor30** [podlove/podlove-publisher#737]
Die Podcast App läd zwar aber dann sagt sie Podcast nicht verfügbar !
![](http://i.imgur.com/9qm4stx.jpg)
Auch hier erst seit der 2.1.1

**Comment by tijander** [comment]
hi ich hatte vor paar wochen auch dieses problem....

schau mal hier

https://github.com/podlove/podlove-publisher/issues/685#issuecomment-78224627

**Comment by eteubert** [comment]
Ändern der Permalinks sollte mit großer Wahrscheinlichkeit helfen.
