### ISSUE TITLE
Move existing podcast to another multisite

### ISSUE THREAD

**Issue by DerDiemen** [podlove/podlove-publisher#738]
Is there a way of migrating an existing podcast into a new subdomain? The idea is having a podcast for every subdomain and one subscription list for the main site (which is holding the podcast yet) - Or will it be necessary to do this manually - which will probably cause troubles for everyone who subscribed the old feed, right? 

Thanks in advance

**Comment by eteubert** [comment]
Hey there. Sorry for shooing you around but GitHub is just our bug tracker :)

Please head over to https://community.podlove.org/ for community support or http://publisher.podlove.org/support/ for professional support.

Thanks!
