### ISSUE TITLE
Cannot save changes in Expert Settings

### ISSUE THREAD

**Issue by rehbergadam** [podlove/podlove-publisher#739]
I am able to save changes everywhere within the plugin, except the Expert Settings panel.  When I hit the save changes button under Expert Settings, I ma taken to the following URL and error message.

www.mywebsite.com/wp-admin/options.php

...which displays this message:  ERROR: options page not found.

Do you have any suggestions on debugging issues on my end.  I temporarily deactivated all plugins except Podlove and this issue still persists.

Any help would be appreciated.

**Comment by eteubert** [comment]
Can you save normal WordPress settings, like at `/wp-admin/options-general.php`? 
Because they also use `/wp-admin/options.php` as the target for saving settings. This file *must* exist.

**Comment by rehbergadam** [comment]
Hello and thank you for the reply.

I do have a /wp-admin/options-general.php page that will save successfully.  I also went into /wp-admin/options.php and that also saved successfully as well.
