### ISSUE TITLE
Multisite: Episode Assets Dropdown Empty

### ISSUE THREAD

**Issue by DerDiemen** [podlove/podlove-publisher#740]
When I try to create a new Episode Asset on a multisite, the dropdown menu is empty.

<img src="http://war-klar.de/PicShare/Episode%20Assets.png"></img>

**Comment by timpritlove** [comment]
please try the repair button in Podlove -> Support

**Comment by eteubert** [comment]
I think there's a bug when creating new sites while the plugin is network enabled: the plugin activation hook does not get fired, so a lot of data is missing.

Workaround:

1. In network plugins, _deactivate_ Podlove Publisher
2. In the new site plugins, _activate_ Podlove Publisher, then _deactivate_ 
3. In network plugins, _activate_ Podlove Publisher

**Comment by DerDiemen** [comment]
Thanks @eteubert - This fixed it!
