### ISSUE TITLE
Episodes are not treated like normal Posts

### ISSUE THREAD

**Issue by boderhamster** [podlove/podlove-publisher#741]
Hi,
I'm not sure if this is a bug, an intended feature or a problem with certain templates. But here is something odd that I encountered:

When using the feature slide on my blog (nerdmeetsyou.de) or including some plugin that automatically gets successful posts with thumbnails to display them in the menu on the right, the Episode Posts from Podlove are not included.

(I activated the feature slide with a single post, so you can see what I mean. As my latest post would actually be a Podcast, but instead a normal post is shown there.)

Thanks for your help in advance.
yours
Dominik

**Comment by eteubert** [comment]
Episodes are what WordPress calls [Custom Post Types](https://codex.wordpress.org/Post_Types). Your theme or widget needs to support these. Please ask the feature slide developer about this.
