### ISSUE TITLE
Flattr Button nur laden, wenn er auch benutzt wird

### ISSUE THREAD

**Issue by tautologe** [podlove/podlove-publisher#744]
Ghostery (Firefox Addon zum Blockieren von Trackern) meldet mir, dass auf jeder Seite der Flattr Button geladen wird, obwohl dieser nicht benutzt wird und ich auch keinen Flattr-Account angegeben habe. 

Dafür ist wohl dieser HTML/JS-Schnipsel verantwortlich:
```
<script type="text/javascript">
	/* <![CDATA[ */
	(function() {
	    var s = document.createElement('script');
	    var t = document.getElementsByTagName('script')[0];

	    s.type = 'text/javascript';
	    s.async = true;
	    s.src = '//api.flattr.com/js/0.6/load.js?mode=auto&popout=0';

	    t.parentNode.insertBefore(s, t);
	 })();
	/* ]]> */
	</script>
```

Aus Privatsphäre-Sicht wäre es wünschenswert, wenn der Code nur geladen wird, wenn auch ein Account angegeben ist.

Danke!

**Comment by timpritlove** [comment]
Auf welcher Seite ist das so?

Derzeit ist die Flattr-Funktionalität noch nicht in ein separates Modul ausgelagert, was vermutlich dieses Verhalten hervorruft.

**Comment by eteubert** [comment]
Bekanntes Problem, siehe https://github.com/podlove/podlove-publisher/issues/734#issuecomment-99279662 für vorübergehenden Workaround.

**Comment by tautologe** [comment]
Danke für die schnelle Antwort, das hilft mir fürs erste!
