### ISSUE TITLE
Error: link must be a full and valid URL, line XX in Feed

### ISSUE THREAD

**Issue by sftsk** [podlove/podlove-publisher#748]
Just realised I am getting a lot of these since quite some time in the dashboard.

Checking the feed, the links are relative `<link>/podcast/bp003-travellers/</link>`. Any idea what could be wrong?

**Comment by katrinleinweber** [comment]
Hi!

Can you please post the exact URL of this feed? I'm getting `Error establishing a database connection` for all the booncon.com-URLs wanted to check.

Once that problem is resolved, I would check the `Podlove >  Podcast Settings > Upload Location` and Wordpress' `Settings > Permalinks`. If everything seems OK there, I guess it could also be a problem with the HTTPS redirect.

**Comment by sftsk** [comment]
Hey,

sorry there was a problem with the host before.
The upload location is working fine, it is on s3.
Also the permalinks should be ok, they are set to `http://booncon.com/%postname%/`.

HTTPS is active but not enforced in any way, the siteurl is `http://booncon.com`.
The podcast works just fine, only the feed does not put the full path where it should.

Thank you for your help!

**Comment by eteubert** [comment]
What did you configure as "Podcast landing page" in `Podlove > Expert Settings > Website`?

**Comment by sftsk** [comment]
Episode pages which is at `/podcast/`

**Comment by eteubert** [comment]
Ah, too quick. I realized that question doesn't matter. Please see my edited comment :)

**Comment by sftsk** [comment]
They are both set in code and work just fine:
https://booncon.com/urltest/

(just created this tiny demo page)
```
<?php
  echo 'Site url: ' . WP_SITEURL . '<br>';
  echo 'Home url: ' . WP_HOME;
?>
```

We are using https://github.com/roots/bedrock and the urls are set in an `.env` file

**Comment by sftsk** [comment]
Uhh, and I see that function is returning a different output. It's showing the url with `https://` instead of reading it from the settings file.
Will look into this myself, thank you for the help!
