### ISSUE TITLE
bug: Creating podcast lists doesn't work

### ISSUE THREAD

**Issue by timbuchwaldt** [podlove/podlove-publisher#751]
Moin!
I'm currently installing Holgis (wrint.de) new mulitsite system and noticed some strange behaviour: Upon creating a "List" in the network-wide podlove panel I just doesn't do anything. No error upon creation, but also there is no list being created. 
We are running on a freshly installed wordpress, default themes and no changes whatsoever:

```
Website             http://wrint.buchwaldt.ws/kombuese
PHP Version         5.5.9-1ubuntu4.9
WordPress Version   4.2.2
Publisher Version   2.1.3
Web Player Version  2.0.17
Twig Version        1.18.1
open_basedir        ok
curl Version        7.35.0
iconv               available
simplexml           ok
max_execution_time  30
upload_max_filesize 2M
memory_limit        256M
disable_classes     
disable_functions   pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,
permalinks          ok (/%year%/%monthnum%/%day%/%postname%/)
podlove_permalinks  ok
podcast_settings    ok
web_player          ok
podlove_cache       on
assets              
    mp3    audio/mpeg
network module      ok

0 errors
0 notices
Nice, Everything looks fine!
```

**Comment by eteubert** [comment]
This probably means that the networks module wasn't initialized properly and the database tables are missing. I will look into it.

Workaround:

1. Go to the main blog
2. In Podlove > Modules, activate any module that is currently off, and save
3. Turn the module off again and save, to restore the previous configuration
4. Check if you can now manage Network Lists

**Comment by timbuchwaldt** [comment]
Hey,
soo.. nope. Didn't work :( Would giving you access help?

**Comment by eteubert** [comment]
Sure, just create an account for eric@podlove.org.

**Comment by eteubert** [comment]
Also, please check the PHP error log for any suspicious entries.

**Comment by timbuchwaldt** [comment]
Password came via the support system, mail is currently not fully set up. I'll check the PHP log.

**Comment by timbuchwaldt** [comment]
```
Table 'wrint.wp_global_podlove_modules_networks_podcastlist' doesn't exist für Abfrage SELECT * FROM wp_global_podlove_modules_networks_podcastlist
```

Jaaaaa gut... :D das sieht nach dem Problem aus

**Comment by eteubert** [comment]
Hm, werde ich mir morgen noch mal ansehen müssen.
Aber das sollte wirklich funktionieren:

```php
add_action('plugins_loaded', function() {
	\Podlove\Modules\Networks\Networks::instance()->was_activated();
});
```

Einmal ausführen, z.B. mit https://wordpress.org/plugins/code-snippets/

**Comment by timbuchwaldt** [comment]
Dat ging :) :+1:
