### ISSUE TITLE
Player generated link broken

### ISSUE THREAD

**Issue by treintje** [podlove/podlove-publisher#756]
A link generated by the sharing function of the webplayer appears to be broken:
http://mypodcast.com/episode1/%23t%3D40:59.359
While the URL above leads to a 404 Error site (in both Firefox and Safari), the following URL works fine:
http://mypodcast.com/episode1/#t=40:59.359

**Comment by eteubert** [comment]
Can you explain how you got that link? In my experiments the share link never contains the timecode.
Are you using the Player that comes with the Publisher or do you have the separate Player Plugin installed?

**Comment by treintje** [comment]
I clicked on the share button, then on the link button in the player to get the link.
Yes, I had the player plugin installed. Now deactivated it and indeed, links come without the timecode. Would be nice to have it as an option, though.

**Comment by eteubert** [comment]
I created a bug report in the player project.
