### ISSUE TITLE
App.net authorization doesn't work

### ISSUE THREAD

**Issue by jonasschoen** [podlove/podlove-publisher#758]
Hello,

I just set up a new wordpress with the Podlove Publsiher and I wanted to connect an app.net account. It was also created just minutes ago. The authorization process didn't work; I didn't get the auth code. 
![bildschirmfoto 2015-06-10 um 00 00 47](https://cloud.githubusercontent.com/assets/9519201/8070763/37045b9c-0f04-11e5-8f47-ec1e70b3b977.png)

I think this is a bug within the publisher or at ADN.

Regards,
Jonas

**Comment by eteubert** [comment]
Thanks for reporting. We are looking into it.

**Comment by timpritlove** [comment]
Tested our authorization backend, seems to work. Is this bug still reproducible?

**Comment by jonasschoen** [comment]
Hi Tim,

I tried to authorize the publisher again and it still doesn't work. Tested it with Chrome and Firefox.

**Comment by eteubert** [comment]
Also working for me. No idea what causes that problem for you :/

**Comment by jonasschoen** [comment]
Hmm strange. Still doesn't work here. But it is not very important for me so ok. Thank you for investigating :)

**Comment by katrinleinweber** [comment]
Have you tried resetting your ADN password, revoking the app authorisation for PPP or something like that?

**Comment by katrinleinweber** [comment]
I de-authorised PPP in the ADN-account to test this and now get the same error => ADN backend seems to be the problem.

**Comment by jonasschoen** [comment]
Hmm ok.

**Comment by katrinleinweber** [comment]
PS: On the other hand, de- and re-authorising Cauldron worked fine. Do we consider ADN as deprecated or not, is maybe a question that this problem (wherever the cause) highlights.

**Comment by timpritlove** [comment]
I would suggest contacting the official ADN support on this and see what they think the error message means.

**Comment by jonasschoen** [comment]
I contacted the support on sunday but didn't get a response until now. I'll post it here when they respond.

**Comment by chemiker** [comment]
Any update here?

**Comment by jonasschoen** [comment]
I didn't get an answer from the ADN support.

**Comment by eteubert** [comment]
> Do we consider ADN as deprecated or not

I think we've reached that point.

Closing.
