### ISSUE TITLE
Podlove Publisher und Social Media Auto-Publisher

### ISSUE THREAD

**Issue by Meiky** [podlove/podlove-publisher#759]
Hallo ich teste derzeit das Plugin Social Media Auto Publish. Es teilt Beiträge in den entsprechenden Netzwerken. Das Plugin ist unter den Beitragsseite, wenn man seinen Artikel schreibt zu sehen und einzustellen. Beim Veröffentlichen stellt es die entsprechende Texte in die Sozialen Netzwerke.

Leider aber sind die Felder NICHT unter denen bei NEUE EPISODE, nur bei einem WP-Beitrag.
Kann man da was machen?

**Comment by timpritlove** [comment]
Das Plugin muss Custom Post Types unterstützen. Ggf. gibt es da eine Stelle, wo man es für den Typ "podcast" aktivieren kann. Falls nicht, bitte den Autor entsprechend treten.

Da es sich hier nicht um einen Fehlerreport handelt, schließe ich das Ticket. Ansonsten gerne auch weiter auf http://community.podlove.org/ diskutieren.
