### ISSUE TITLE
Einzelne Episode bearbeiten - Buttons von Wordpress funktionieren nicht

### ISSUE THREAD

**Issue by 404Keneth** [podlove/podlove-publisher#760]
Hallo, 

ich habe Podlove installiert und bis jetzt finde ich das Plugin echt klasse! Danke dafür!

Doch trotzdem habe ich ein kleines Problem. Wenn ich beim Bearbeiten einer Episode bin, dann kann ich mehrere Sachen von Wordpress nicht machen.

1. Ich kann Reiter wie Wordpress Seo by Yoast, Podcast Episode, Revisionen und andere Reiter nicht öffnen oder schließen. Ich klicke zwar auf den Pfeil der rechts am Reiter ist doch nichts passiert. Bei normalen Beiträgen oder anderen Seiten funktioniert es.

2. Ich kann den Podcast keine Schlagworte hinzufügen. Ich kann zwar welche eingeben, aber sobald ich den Button drücke zum hinzufügen von Schlagworten passiert nichts, weil der Hinzufügen Button nicht funktioniert. Bei normalen Beiträgen funktioniert es.

Ich glaube beide Sachen sind Ursache des gleichen Problems, weiß einer woran es liegen kann?

Danke für die Hilfe
Keneth

**Comment by katrinleinweber** [comment]
Hallo!

2. liegt vermutlich an einem der Plugins. In der WP+Podlove-Instanz in die ich reingucken kann, sind relativ wenige installiert und Schlagworte funktionieren für Episoden ganz normal. Bitte probier' mal, eines dieser Plugins (und dann der restlichen) nach dem anderen abzuschalten, und überprüfe 1. und 2. zwischendurch.

**Comment by eteubert** [comment]
> Ich glaube beide Sachen sind Ursache des gleichen Problems, weiß einer woran es liegen kann?

Korrekt. Vermutlich ein JavaScript-Fehler oder Konflikt.
Am einfachsten ist es, wenn du in die JavaScript Konsole schaust. Siehe http://webmasters.stackexchange.com/a/77337

**Comment by 404Keneth** [comment]
@katrinleinweber und @eteubert  Vielen dank für eure Hilfe! Habe das Problem endlich gefunden. Und zwar gab es ein Problem mit dem Plugin "Ultimate Addons for Visual Composer". Ohne euch hätte ich den Fehler wahrscheinlich nie gefunden! Nochmal vielen Dank!

Beste Grüße
Keneth

**Comment by katrinleinweber** [comment]
Gern geschehen :-)
