### ISSUE TITLE
Podlove Publisher 2.2.4 erkennt die neuste Episode nicht

### ISSUE THREAD

**Issue by jackermonkey** [podlove/podlove-publisher#761]
Hi,

bis jetzt gab es mit dem Publisher nie Probleme, ich hoste zu jeder Episode ein MPEG-4 AAC Audio und ein mp3 Asset. Beim erstellen der neusten Episode bekomme ich aber kontinuierlich den Status "File not found" für beide Assets, obwohl beide Files korekt benannt sind (slug und name stimmen sicher überein) und im gleichen Ordner wie alle älteren Episoden auf dem Server liegen. Per manueller Eingabe in die Adresszeile sind sie erreichbar:

http://enoughtalk.de/podcast/diverse-talk-001-max-is-lost-on-the-fury-river.m4a
http://enoughtalk.de/podcast/diverse-talk-001-max-is-lost-on-the-fury-river.mp3

Gehe ich im Podlove Dashboard auf "Revalidate Assets" werden die 20 Files der vorherigen 10 Episoden gefunden, die 2 neusten aber nicht.

Das Log meldet zudem erstmalig:
"[2015-06-24 07:39:22] Media file mime type does not match expected asset mime type. diverse-talk-001-max-is-lost-on-the-fury-river/MPEG-4 AAC Audio Expected: audio/mp4, but found: audio/mpeg"
Allerdings wurden die Dateien genau wie vorher erstellt, auch Mediainfo zeigt keine Unterschiede der Codecs, etc.

Ich kann mich nicht entsinnen in den Einstellungen irgendetwas geändert zu haben.
Ideen?

Vielen Dank,
jackermonkey

**Comment by timpritlove** [comment]
Noch keinen konkreten Hinweis zur Ursache, aber was mir spontan auffällt ist, dass Dein Varnish für die Medien-Dateien keinen "Content-Length"-Header mitliefert. Das solltest Du auf jeden Fall schon mal abstellen.

**Comment by eteubert** [comment]
Ja, daran liegt es. Für den Publisher heißt fehlende "Content Length", dass die Datei nicht existiert. Das sollten wir mal unterscheiden (HTTP200 und Length 0 vs. HTTP404) aber dennoch solltest du deinen Varnish fixen :)

```
› curl -IL http://enoughtalk.de/podcast/diverse-talk-001-max-is-lost-on-the-fury-river.m4a
HTTP/1.1 200 OK
Server: Apache
Last-Modified: Tue, 23 Jun 2015 20:58:32 GMT
ETag: "7e3ae076-2eb8781-51935a72b3439"
Cache-Control: max-age=1209600
Expires: Wed, 08 Jul 2015 08:29:54 GMT
Vary: Accept-Encoding
Content-Type: audio/mpeg
Date: Wed, 24 Jun 2015 08:29:58 GMT
X-Varnish: 4272324922
Age: 3
Via: 1.1 varnish
Connection: keep-alive
```

**Comment by jackermonkey** [comment]
Danke :) Dann weiß ich ja jetzt woran es liegt, aber nicht, wie ich es fixen kann (Podlove ist schließlich so toll, weil jeder noob damit Podcasts veröffentlichen kann). Lese mich mal schlau.
Aufgrund des obigen Auszugs gehe ich davon aus, dass es ne Server Einstellung ist, die von WP/Podlove unabhängig ist? Wieso trifft das denn dann aber eigentlich nur für die neuste Episode zu?

**Comment by eteubert** [comment]
Hier ist ein Thread zu dem Thema: https://stackoverflow.com/questions/23643233/how-do-i-disable-transfer-encoding-chunked-encoding-in-varnish
Wenn das bei dir nur Fragezeichen im Kopf generiert, kontaktiere bitte deinen Hoster :)

**Comment by jackermonkey** [comment]
Hab jetzt einen Haufen Dinge getan:

- Serverseitig SSL aktiviert (weil es bei one.com scheinbar nicht automatisch an war)
- Nochmal durch die WP Plugins gegangen und "Autoptimize", sowie "WP Performance Booster" raus geschmissen (die hatte ich zwischen Veröffentlich der vorherigen und der aktuellen Episode installiert - evtl. haben die reingepfuscht?)
- in die .htaccess im root-Verzeichnis aufgrund dieser Anleitung (http://thebot.net/threads/disable-varnish-cache-fix-wordpress-login-503-one-com-etc.245260) die genannte Zeile eingefügt.

Was den Bug gefixt hat, versteht ihr wohl besser, auf jeden Fall werden die Files jetzt erkannt :) 
Danke euch!

**Comment by timpritlove** [comment]
Na prima :)
