### ISSUE TITLE
Contributor list in Edit Episode view too large

### ISSUE THREAD

**Issue by katrinleinweber** [podlove/podlove-publisher#763]
![podlove-contributor-list-ui-overflow](https://cloud.githubusercontent.com/assets/9948149/8391616/8ee23f78-1cc9-11e5-9844-5ff296a9de65.png)

Tested in both Safari 7.1.6 and Firefox 38.0.5 on a 13'' 1280x800px MacBook Pro screen (larger overflow on a 1080x1920 pivot display. No sidebars or any other window-modifying extensions are installed.

It seems to me that the three drop-down menus are too wide, although there are no long `Group`, `Role` or other names. Only the `Choose...` and `Add New Contributor` options fill out the 1st column, but all other entries have plenty of whitespace.

Potentially, a longer name I added some time ago caused this, but I didn't check or notice back then, sorry. Even so, the column width should be updated or limited somehow.

**Comment by eteubert** [comment]
I improved it a bit. At least Roles & Groups don't use up so much space any more. But to be usable at all resolutions,  need to find a responsive layout that is flexible enough to switch to more than a single row when width becomes scarce (which is hard right now because it's a table).
