### ISSUE TITLE
Der Feed geht seit dem letzten Update nicht mehr, brauch Hilfe

### ISSUE THREAD

**Issue by Meiky** [podlove/podlove-publisher#767]
Hallo hab nun schon viel probiert, aber seit dem letzten Podlove Update geht der Feed nicht mehr

http://www.meikys-podcast.de/wordpress/feed/mp3/

Allerdings auch der Feed von Wordpress ist kaputt.

An was kann das liegen hab schon soviel probiert, kenne mich da zu wenig aus.

http://www.meikys-podcast.de/wordpress/feed/

Hab mit dem Serverbetreiber getestet. Andere Plugins, Server und htaccess kein Verursacher, 

Der Fehler im Feed lautet so
ERR_CONTENT_DECODING_FAILED

Danke schon mal für die Hilfe

**Comment by eteubert** [comment]
Feed sieht von hier aus korrekt aus. Hast du etwas geändert?
Meine Vermutung wäre gewesen, dass ein Caching Plugin einen Konflikt erzeugen könnte.

**Comment by funkenstrahlen** [comment]
Der Feedvalidator ist auch zufrieden: http://feedvalidator.org/check.cgi?url=http%3A%2F%2Fwww.meikys-podcast.de%2Fwordpress%2Ffeed%2Fmp3%2F
