### ISSUE TITLE
incompatibility with WP to diaspora*

### ISSUE THREAD

**Issue by katrinleinweber** [podlove/podlove-publisher#768]
When [Podlove Publisher v2.2.4](https://github.com/podlove/podlove-publisher/tree/2.2.4) and @gutobenn's [WP to diaspora* v1.4.0](https://github.com/gutobenn/wp-to-diaspora/tree/v.1.4.0) are both active, only the 1st `Contributor` is shown in the list in `Edit Episode`, and clicking `+` does nothing. Firefox' JavaScript console reports `TypeError: $select.attr(...) is undefined` [at `chosenImage.jquery.js`](https://github.com/podlove/podlove-publisher/blob/master/js/admin/chosen/chosenImage.jquery.js#L23) upon loading an episode draft. This is how the broken state looks:

![podlove-contributors-incompatible-with-wp-to-d-2](https://cloud.githubusercontent.com/assets/9948149/9303819/f4fe98f2-44e1-11e5-976b-494b39fa8070.png)

And below is the normal state once WP to D* is deactivated.

![podlove-contributors-incompatible-with-wp-to-d-1](https://cloud.githubusercontent.com/assets/9948149/9303813/eb442264-44e1-11e5-917c-5d030a48a853.png)

**Comment by noplanman** [comment]
Hi @katrinleinweber 
As far as I can see, this is not a WP to diaspora* problem. I've installed the Podlove plugin and tested it myself.
I got the error you mentioned when I had the EDD (Easy Digital Downloads) plugin installed. Do you have that active too by any chance?
Also, have you tried to deactivate each plugin one-by-one to see which one the "culprit" is?

**Comment by katrinleinweber** [comment]
No, in my setup, WP-to-D* is the culprit: If every other plugin is deactivated, activating this one starts the problem in the Podlove Publisher.

**Comment by noplanman** [comment]
Ah, right, now I saw it.
It's due to both plugins using the **chosen** library.
I'll investigate further to see if there's a solution I can add to the WP2D plugin, to prevent the breakage.

Thanks for finding this one! These are the little nasty ones that stay pretty well hidden ;-)

**Comment by katrinleinweber** [comment]
You're welcome! Thanks for investigating a solution :-)

**Comment by noplanman** [comment]
Ok, the problem was the old version of chosen that is being used.
I've provided a fix here: #770 
@katrinleinweber As a temporary fix, until the changes get merged, you can simply copy the files from my PR to your plugin directory.
Please let me know if this fixes it for you :smiley:

**Comment by katrinleinweber** [comment]
Merci :-) I'll wait for the official update, though.

**Comment by noplanman** [comment]
:+1:
