### ISSUE TITLE
Feed doesn't validate due to favicon since WP4.3

### ISSUE THREAD

**Issue by katrinleinweber** [podlove/podlove-publisher#772]
Since [Wordpress 4.3](https://github.com/WordPress/WordPress/tree/4.3-branch) one can add a favicon via the Design menu. Unfortunately, the [PPP 2.2.4](https://github.com/podlove/podlove-publisher/releases/tag/2.2.4) writes this into the feeds, which may cause validation problems: `[channel contains more than one image](http://feedvalidator.org/check.cgi?url=http%3A%2F%2Fwww.konscience.de%2Ffeed%2Fmp3%2F#l27)`.

Before, I used [All in One Favicon plugin](https://wordpress.org/plugins/all-in-one-favicon/) without this problem. Is it maybe possible to filter out WP's favicon?

**Comment by eteubert** [comment]
Yes, we should handle this, good catch :)

 - [ ] In Publisher feeds: If a channel image exists, remove WordPress generated favicon
