### ISSUE TITLE
Kein Bild neben dem Episodentitel

### ISSUE THREAD

**Issue by pixelsophie** [podlove/podlove-publisher#774]
Hallo,
hat Jemand eine Idee, wieso bei mir kein Bild angezeigt wird? Sowohl bei der Episode nicht, als auch im Archiv: http://www.pixelsophie.de/2015/09/ppe18-warum-ich-gern-fotomedienlaborantin-bin/
![screenshot](https://cloud.githubusercontent.com/assets/8769076/9837200/a0caba8e-5a37-11e5-82a7-b0dd76c9335d.png)

**Comment by katrinleinweber** [comment]
Das Sonderzeichen ツ im Dateinamen würde ich als Hauptverdächtigen vermuten ;-)

**Comment by pixelsophie** [comment]
Ich danke dir. ich verabeite die Episoden mit Auphonic und vermute das daher das Bild kommt: Ich habe es dort geändert. Weißt du ob es eine Möglichkeit gibt das Podcastbild nachträglich zu ändern?

**Comment by katrinleinweber** [comment]
Bin mir nicht sicher. Ich werfe bei sowas immer die Auphonic-Produktion neu an.

**Comment by pixelsophie** [comment]
Danke für deinen Tipp, hat leider nicht geholfen. Hat noch Jemand eine Idee?

**Comment by chemiker** [comment]
@pixelsophie Besteht das Problem noch?

**Comment by pixelsophie** [comment]
Nein, ich meine nicht. Es erscheint meist eines. Wieso fragst du?

**Comment by chemiker** [comment]
@pixelsophie Dann kann ich das Ticket schließen :)
