### ISSUE TITLE
Audio Content Dir - WordPress Mediathek

### ISSUE THREAD

**Issue by benhartwich** [podlove/podlove-publisher#777]
Hallo,

mich würde interessieren, ob es Ansätze gibt, Podcastdateien mithilfe der internen WordPress Mediathek zu verwalten? Bisher muss man ja ein Verzeichnis setzen, in dem alle Dateien drin sind, aber gibt es auch eine Möglichkeit das mit der WordPress Mediathek zu verbinden?

Liebe Grüße

**Comment by eteubert** [comment]
Hi,

wir sprechen gelegentlich darüber, es hat aber derzeit keine Priorität.

Feature-Diskussionen der Art bitte lieber ins https://sendegate.de oder https://community.podlove.org. Hier werden nur noch issues verwaltet.
