### ISSUE TITLE
Buggy download button display on Windows/Chrome

### ISSUE THREAD

**Issue by germanstudent** [podlove/podlove-publisher#779]
With the current Podlove Publisher version (2.2.4), download buttons won't show the arrow symbol (css used by pp should be ul.episode_download_list by https://github.com/samcollins/css-social-buttons/blob/master/css/zocial.css)

Screenshot Windows 10 / Chrome 45.0.2454.99 m

![111](https://cloud.githubusercontent.com/assets/3316382/10019875/1c19a3ee-6140-11e5-8be9-5a6d5e5e5365.png)

Screenshot Windows 10 / Internet Explorer 11.0.10240.16431
![222](https://cloud.githubusercontent.com/assets/3316382/10019885/2f0107fe-6140-11e5-9e44-333f4a5cac34.png)

Template code used

```
{# @core/shortcode/downloads-buttons.twig #}

<ul class="episode_download_list">
    {% for file in episode.files %}
        {% set asset = file.asset %}
        {% if asset.downloadable %}
            <li>
                <a href="{{ file.publicUrl("download", "buttonlist") }}">{{ asset.title }}<span class="size">{{ file.size|formatBytes }}</span></a>
            </li>
        {% endif %}
    {% endfor %}
</ul>
```

**Comment by eteubert** [comment]
Hm, maybe we should simplify here and go to a rather unstyled simple link-list.

I looked at the "css social buttons" project and they now use an icon font. I don't think it's reasonable for us to use this just for those icons.

**Comment by eteubert** [comment]
Something like this:

<img width="579" alt="screen shot 2015-09-25 at 13 14 26" src="https://cloud.githubusercontent.com/assets/235918/10093612/613342b6-6387-11e5-82d4-d4ad36a0d54b.png">

Simple, very few CSS required and adjusts to the theme used because it's just HTML links.
