### ISSUE TITLE
Get Podlove episode template object within wordpress loop

### ISSUE THREAD

**Issue by Dreamfish19** [podlove/podlove-publisher#780]
Hi,

ich stehe gerade etwas auf dem Schlauch ...

Wenn ich nach der Podlove - Dokumentation gehe, kann ich in Wordpress mit dem untenstehenden Code auf Daten aus der Episode zugreifen.

<?php
/**
 * .
 * 
 * @param  int|WP_Post $post          Optional. Post ID or post object. Defaults to global $post.
 * @return \Podlove\Template\Episode
 */
function \Podlove\get_episode($id = null);

// example
$episode = \Podlove\get_episode();
echo $episode->player(['context' => 'episode']);
?>

Wenn ich unter Wordpress ein neues PHP-Template erstelle, und innerhalb der Loop (<?php while (have_posts()) : the_post(); ?> den obenstehende Code nutze, bekomme ich eine Fehlermeldung 

Parse error: syntax error, unexpected '\' (T_NS_SEPARATOR), expecting '(' in /www/htdocs/w01397ed/team-act.de/wp-content/themes/teamactTheme/template-podcast.php on line 37

Ist dies überhaupt die richtige Vorgehensweise? Mir werden alle Episoden innerhalb der Loop korrekt ausgegeben, aber ich möchte Zusatzsinfos mit ausgeben (bspws. die Download-URL für die MP3-Datei).

Danke!

**Comment by eteubert** [comment]
`\Podlove\get_episode()` etc. gibt es erst ab Version 2.3. Aber da du mir Code-Doku zeigst, nehme ich an, du hast die 2.3 Beta installiert?

Aber einen *Syntax* Fehler finde ich an der Stelle merkwürdig. Zeig doch mal bitte, wie du es konkret verwendest.

**Comment by Dreamfish19** [comment]
Danke für die schnelle Antwort! Nein, ich habe die 2.2.4 installiert .. ganz normal aus dem Wordpress-Verzeichnis. Könnte es daran liegen?

**Comment by eteubert** [comment]
Du kannst die Funktion selbst implementieren. z.B. so:

```php
<?php
function dreamfish_get_episode($id = null) {
	
	$post = get_post($id);

	if (!$post)
		return null;

	$episode = \Podlove\Model\Episode::find_one_by_property('post_id', $post->ID);

	if (!$episode)
		return null;

	return new \Podlove\Template\Episode($episode);
}
```

Und dann so benutzen:

```php
<?php
$episode = dreamfish_get_episode();
echo $episode->subtitle();
```

**Comment by timpritlove** [comment]
Bis zum Release der 2.3 wird aber auch nicht mehr viel Zeit vergehen...

**Comment by Dreamfish19** [comment]
Eric, vielen Dank für die schnelle Antwort! An die Grunddaten der einzelnen Episode komme ich jetzt schon mal. Verrätst du mir noch, wie ich dann beispielsweise an die FileUrls der einzelnen Episoden komme ?

**Comment by eteubert** [comment]
Da musst du dich durch die API hangeln. Siehe doc: http://docs.podlove.org/reference/template-tags/
Als Beispiel ggf. auch http://docs.podlove.org/reference/templates/#downloads-buttons

Alle Docs/Beispiele sind in Twig-Syntax. Das musst du dir umdenken. Sonst ist alles identisch mit der PHP API.

**Comment by Dreamfish19** [comment]
Danke für den Hinweis!
Ich habe es jetzt so gelöst:
<?php
    $episode_files = $episode->files();
    foreach ($episode_files as $episode_file) {
        $mp3_link = '<a href="'.$episode_file->url().'">Folge herunterladen</a>';
   }; ?>

**Comment by eteubert** [comment]
:+1: 

Release 2.3 ist nun auch verfügbar, d.h. du kannst ab sofort die dokumentierte API benutzen: https://community.podlove.org/t/release-2-3-0/412
