### ISSUE TITLE
Im Player wird die Gesamtlaufzeit nicht angezeigt?

### ISSUE THREAD

**Issue by JehuJaanai** [podlove/podlove-publisher#781]
Hi,

ich habe bei einigen Episoden das die Gesamtlaufzeit im Player und bei iTunes nicht angezeigt werden. 
Ich nutzte Auphonic für das Tagging und dann füge ich die Daten (mp3,aac. psc) in den Podlove Publisher. 

Das heißt auch, dass für das letzte Kapitel der Episode auch keine Zeitangabe zu sehen ist.

Woran könnte das liegen! In Auphonic schiebe ich eine Textdatei mit folgenden Angaben rein:

00:00:00.000 Intro und Begrüßung
00:03:09.000 Was ist Leberwurst?
00:14:38.598 Warum gibt es Leberwurst?
00:20:15.703 Drei Tipps für Leberwurst-Genießer

**Comment by timpritlove** [comment]
Die Kapitelinformationen müssen im Publisher auch noch eingetragen werden. Wenn Du die Auphonic-Integratino benutzt, kannst Du die Daten direkt aus der Produktion übernehmen.

**Comment by JehuJaanai** [comment]
Ich nutze Auphonic separat und bekomme dann die o.g. 3 Dateien um sie bei mir in WordPress in die Episode einzufügen neben Titel, Subtitle, Summery etc. Im Player kann ich keine Kapitelinformationen mehr eingeben. Da wird nur per ftp der psc hochgefahren. Auf der Website werden die einzelnen Kapitel bzw. die Marker ordentlich angezeigt. Du die Gesamtlaufzeit von z.b. 43:03 bleibt bei mir 00:00 und das letzt Kapitel ist "..." - auch keine Zeitangabe..

**Comment by timpritlove** [comment]
Ich vermute, du verwendest derzeit das PSC als Quelle für die Kapitel via Assets. Du kannst das auch umstellen, so dass die Kapitel direkt in WP eingegeben werden, das ist auch die von uns empfohlene Methode. Dann gibt es ein entsprechendes Eingabefeld.

So oder so würde ich Dir raten auf das Publisher-Auphonic-Modul umzustellen, das macht einiges einfacher. Vor allem kannst Du dann alle Metadaten im Publisher eingeben und die Aufträge direkt von dort erzeugen und starten. Dann kriegst du auch die Gesamtzeit mit übergeben und alles. Macht das Leben einfacher.

Warum die Kapitel in iTunes nicht erscheinen muss Auphonic beantworten. Das liegt nicht in unserem  Bereich.

Ansonsten mache ich da Ticket hier mal zu, da es sich nur um Support handelt, den wickeln wir über die Podlove Community ab: https://community.podlove.org/

**Comment by JehuJaanai** [comment]
Tim, ich habe meinen Fehler gefunden. Es lag einfach an dem fehlenden Eintrag unter Duration. Alles gut und Danke für Deine schnelle Reaktion.
