### ISSUE TITLE
Datei wird nicht gefunden obwohl vorhanden

### ISSUE THREAD

**Issue by pixelsophie** [podlove/podlove-publisher#783]
Hallo,

meine Podcast Datei wird nicht gefunden obwohl sie im FTP-Verzeichnis liegt. Ich meine alles richtig eingestellt zu haben. Hat Jemand eine Idee woran das liegen kann? So kann man den Podcast leider auch nicht hören oder herunterladen.

**Comment by eteubert** [comment]
Was steht unter `Podlove > Support`?
Findet sich etwas im `Podlove > Dashboard` Logging Bereich?

**Comment by pixelsophie** [comment]
Website             http://www.pixelsophie.de
PHP Version         5.6.13
WordPress Version   4.3.1
Publisher Version   2.2.4
Web Player Version  2.0.17
Twig Version        1.18.1
open_basedir        /home/xogdjphu/pixelsophie.de:/home/xogdjphu/.fpp/pixelsophie.de/tmp:/home/xogdjphu/.fpp/pixelsophie.de/session:/home/xogdjphu/.fpp/pixelsophie.de/webredirect:/home/xogdjphu/phpinclude:/usr/share/php5.6/lib/php:/home/logdateien/stats
curl Version        7.26.0
iconv               available
simplexml           ok
max_execution_time  180
upload_max_filesize 256M
memory_limit        152M
disable_classes     
disable_functions   exec, system, shell_exec, popen, pclose, proc_open, proc_close, proc_get_status, proc_nice, proc_terminate, show_source, escapeshellcmd, escapeshellarg
permalinks          ok (/%year%/%monthnum%/%postname%/)
podlove_permalinks  ok
podcast_settings    ok
web_player          ok
podlove_cache       on
assets              
	mp3    audio/mpeg
	jpg    image/jpeg

1 ERROR: 
- The PHP setting "open_basedir" is not empty. This is incompatible with curl, a library required by Podlove Publisher. Please ask your hoster to unset "open_basedir".
0 notices

**Comment by timpritlove** [comment]
There we have it: "Please ask your hoster to unset "open_basedir"

**Comment by pixelsophie** [comment]
Vielen Dank. Ich werde es versuchen. Was genau ist das und kann das Auswirkungen auf meine Wordpress Installation haben?

**Comment by timpritlove** [comment]
Das erlaubt den Zugriff auf externe URLs und es könnte die Auswirkungen haben, dass der Podlove Publisher funktioniert.

**Comment by pixelsophie** [comment]
Ich danke sehr! Meinst du das löst auch das Problem mit dem fehlenden Bild? https://github.com/podlove/podlove-publisher/issues/774

**Comment by eteubert** [comment]
Das wird auch dein Bild-Problem lösen, da du Bilder per Assets verwaltest (wie Audiodateien). Allerdings halte ich die Chance, dass dein Hoster das Setting entfernt, für gering. Die benutzen das, um mehrere Benutzer auf einem System unterzubekommen und diese rechtlich voneinander zu trennen.

Es ist auch nicht sicher, dass es daran liegt. Ich muss die Nachricht mal von "ERROR" auf "WARNING" ändern, da ich dafür mittlerweile einen Workaround habe.

Es ist auf jeden Fall hilfreich, wenn du in dein PHP Error Log schaust und ins Dashboard Log.

**Comment by pixelsophie** [comment]
Danke! Und wieso ging es früher mal?

**Comment by pixelsophie** [comment]
Hallo, 
mein Hostet hat mir geantwortet, die Funktion kann nicht deaktiviert werden. Kann ich Podlove jetzt nicht mehr nutzen? Schade, ich mochte es sehr.

**Comment by timpritlove** [comment]
Tja, ich würde im Zweifel lieber mich auf die Suche nach einem kompetenten Webhoster machen.

**Comment by pixelsophie** [comment]
Wieso ging es denn früher einmal und gibt es irgendwie eine Möglichkeit Podlove trotzdem zu nutzen? Welcher Hoster wäre denn kompetent?

**Comment by eteubert** [comment]
> Wieso ging es denn früher einmal und gibt es irgendwie eine Möglichkeit Podlove trotzdem zu nutzen? 

Was sich geändert hat, kann ich dir ohne weitere Infos nicht beantworten. Ich schrieb weiter oben, wie du uns bei der Suche nach der Ursache helfen kannst:

> Es ist auf jeden Fall hilfreich, wenn du in dein PHP Error Log schaust und ins Dashboard Log.

**Comment by pixelsophie** [comment]
Hallo, tut mir leid, aber ich weiß nicht wie ich diese Log-Dinge einsehen kann. Schade, dennoch vielen Dank für deine Mühe.

**Comment by Webmeteor** [comment]
Eine Aussage, wie ich würde leiber einen anständigen Hoster suchen, ist nicht gut. Als Entwickler gerade für Wordpress muss man damit rechnen, dass solche Funktionen nicht zur Verfügung stehen. Denn wieviele haben einen eigenen Server, um Wordpress für ein Hobby laufen zu lassen?

So als Programmierer dieses Addons, müsst ihr doch wissen, wo ihr den cURL Request drin habt. Es ist dann also ein leichtes dieses dann für Euch zu finden und zu debuggen auf einem Shared Server.

**Comment by eteubert** [comment]
> So als Programmierer dieses Addons, müsst ihr doch wissen, wo ihr den cURL Request drin habt. Es ist dann also ein leichtes dieses dann für Euch zu finden und zu debuggen auf einem Shared Server.

Der Fehler ist bekannt, aber nicht behebbar. Wenn `open_basedir` gesetzt ist, funktioniert ein wesentliches Feature von cURL nicht: http://stackoverflow.com/a/10138396 

Tatsächlich gibt es dafür seit Version 2.1.1 einen Workaround. Ich habe nur die Fehlermeldung noch nicht angepasst.

D.h. ich _vermute_, es liegt nicht daran. Aber mehr kann ich nicht sagen und da @pixelsophie keinen Log-Zugriff hat, ist es mir unmöglich, den Fehler zu orten.

**Comment by pixelsophie** [comment]
Ich habe nie gesagt keinen Zugriff zu haben. Ich weiß nicht wo ich log Angaben finde. 
Einen Hoster mit genannter Funktion zu finden ist sehr schwer. Wenigstens wenn man keinen Server anmieten will.

**Comment by eteubert** [comment]
Hast du eine Lösung für das Problem gefunden?

**Comment by pixelsophie** [comment]
Ich dachte ihr habt eines gefunden. Seit dem Update nach meiner Anfrage geht es wieder.

**Comment by eteubert** [comment]
Oh, okay. Cool :)
