### ISSUE TITLE
Social service "YouTube (Channel)" URL structure

### ISSUE THREAD

**Issue by Inrumpo** [podlove/podlove-publisher#784]
With release 2.3.0 social service support for YouTube channels was introduced.
This creates a URL structure as follows:
```
https://www.youtube.com/c/individualvaluehere
```
But shouldn't it be like:
```
https://www.youtube.com/channel/individualvaluehere
```
The /c/ doesn't work for me.

**Comment by timpritlove** [comment]
This sure looks like a genuine bug.

**Comment by Inrumpo** [comment]
I guess I have to come back to this one.
I just found out that there are in fact YouTube URLs that do work like:
`https://www.youtube.com/c/individualvaluehere`

Example: https://www.youtube.com/c/zsleyerlp
