### ISSUE TITLE
player not visible without javascript

### ISSUE THREAD

**Issue by xenDE** [podlove/podlove-publisher#785]
Hi,

please add a `<audio/>` Player for disabled javascript.

You can replace it with the fancy javascript player.

Thanks for making Podcast life easier!

best regards

**Comment by eteubert** [comment]
The player is based on `<audio/>`. However, it's width is set to `auto` which seems to default to 0. You can fix it with some css: `audio { width: 300px }` but I will also include that in a future patch.

**Comment by xenDE** [comment]
Thanks!
