### ISSUE TITLE
Problem nach Update

### ISSUE THREAD

**Issue by PsychCast** [podlove/podlove-publisher#786]
Guten Tag, ich wollte heute den Podlove Podcast Publisher auf 2.4.4 updaten, dabei hängte WP sich auf und liess sich nur noch starten nach Löschen der .maintenance und verschieben des Podlove-Plugins. Kanns jetzt immer noch nicht updaten und es kommt eine Fehlermeldung. Kann ich es jetzt neu Installieren ohne dass ale Daten weg sind? www.psychcast.de
Vielen Dank!

**Comment by timpritlove** [comment]
Die aktuelle Version des Publishers ist 2.3.0. Die 2.4.4 wird sicherlich noch eine Weile dauern :)

Welche Version war denn vorher installiert? Welche PHP-Version setzt Du ein?

**Comment by PsychCast** [comment]
Vielen Dank für Deine Antwort!
PHP4.2.12, mySQL 5.5.45

Das automatische Update hing sich auf, dann erstmal nur weisse Seite. Wenn ich das Plugin jetzt starten will angehängte Fehlermeldung. Bei Update-Versuch unendliche Zeitdauer, bis ich dann wieder abbrechen muss, jetzt habe ich gesehen ist das Plugin bei WP gar nicht mehr in der Liste, im Order per FTP ist es aber noch zu sehen.
Ich hoffe, das ist noch zu lösen…

Danke vielmals jedenfalls.
VG
Alexander


Am 07.10.2015 um 22:16 schrieb Tim Pritlove <notifications@github.com>:

**Comment by PsychCast** [comment]
Sorry, mit Vorversion bin ich nicht ganz sicher, aber ich denke die davor, wurde regelmäßig geupdated…

Was passiert, wenn ich das ganze Plugin neu installiere? Alles bisherigen EPisoden etc. weg?

VG
Alexander

Am 07.10.2015 um 22:16 schrieb Tim Pritlove <notifications@github.com>:

**Comment by timpritlove** [comment]
Dein PHP ist nicht alt, es ist totale Steinzeit und wird seit vielen, vielen Jahren nicht mehr unterstützt. Ein Wunder, dass das überhaupt lief. Bitte aktualisiere auf PHP 5.6.

**Comment by PsychCast** [comment]
Das sind die Infos, die ich habe. Das kann man nicht updaten, da macht glaube ich STrato zentral. Sind leider noch bei Strato..
Ich dachte, das wäre nicht so alt.
Und nach dem eventuellen Update, muss ich dsa Plugin dann neu installieren?
Danke




Am 07.10.2015 um 23:17 schrieb Tim Pritlove <notifications@github.com>:

**Comment by timpritlove** [comment]
Ich zitiere: https://faq.strato.de/article/2264/So-wechseln-Sie-in-Ihrem-Webhostingpaket-die-PHP-Version-von-5.3-auf-5.5.html

"Einen Wechsel zwischen den PHP Versionen 5.3, 5.5 und 5.6 können Sie mit wenigen Klicks in Ihrem STRATO Kundenservicebereich vornehmen."

Ich vermute allerdings auch, dass Du von PHP 5.4 sprichst und nicht 4.4. Die Version 4.4 ist seit DREIZEHN JAHREN nicht mehr supported. Den Schuss hat auch Strato schon gehört :)

**Comment by timpritlove** [comment]
Ich mache jetzt das Ticket hier zu, da es sich ja nicht um einen Bug handelt. Support erhältst Du aber weiterhin in der Podlove Community: https://community.podlove.org/c/podlove-publisher

**Comment by PsychCast** [comment]
Alles klar, danke Dir vielmals!

Am 07.10.2015 um 23:35 schrieb Tim Pritlove <notifications@github.com>:
