### ISSUE TITLE
Seasons-list with English entries in a German Wordpress-installation

### ISSUE THREAD

**Issue by David1701** [podlove/podlove-publisher#787]
The list of all seasons contains English written statements within a German Wordpress-installation: The total number of episodes in a season is listed in English as well as the starting dates of the seasons. It isn't quite dramatic - but we strive for perfection. :)

![denglish](https://cloud.githubusercontent.com/assets/5114568/10412875/65d27de6-6f94-11e5-98d8-a90d4eea4388.png)

**Comment by eteubert** [comment]
We haven't even started with translations yet. Whatever _seems_ to be translated (like some dates or buttons) is based on WordPress translation tables, not ours :)
