### ISSUE TITLE
enhance avatar image handling

### ISSUE THREAD

**Issue by leitmedium** [podlove/podlove-publisher#788]
For every episode I do the following:
- create contributor profile
- upload avatar image to media library
- copy image url from media library
- paste url to contributor avatar field

What I'd love to see here is an easier solution, e.g.:
- integration with media library (e.g. "upload" button close to avatar field)
- possibility to always display current avatar image from social media account (twitter, instagram, facebook)

**Comment by timpritlove** [comment]
Upload button for contributors is planned for the next release.

Showing the Avatar of social media sites is complicated as it needs API access which needs a developer key which we can't distribute as an open source project.

**Comment by timpritlove** [comment]
> integration with media library (e.g. "upload" button close to avatar field)

This feature has been added in Publisher 2.5.0

> possibility to always display current avatar image from social media account (twitter, instagram, facebook)

This is can't be done.

I am closing this issue now.
