### ISSUE TITLE
Export Analytics Data

### ISSUE THREAD

**Issue by dirkprimbs** [podlove/podlove-publisher#789]
Ich versuche derzeit die Download-Statistiken meines Podcasts zu analysieren und würde gerne regelmäßig einen Schnappschuss davon in einem Excel Sheet haben. 
Der Versuch via "Export Tracking Data" die Daten zu bekommen funktioniert aber leider nicht. Der Text "Export: starting ..." taucht auf und dann tut sich weiter nichts mehr.

Bekanntes Problem?

Thx! //D

**Comment by eteubert** [comment]
Findest du Fehler in der JS Console? (Wie du die findest steht [hier](https://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers))

**Comment by dirkprimbs** [comment]
Danke, dass Du den Ball aufgenommen hast! Ich habe seitdem nicht mehr getestet und der Fehler tritt jetzt nicht mehr auf. Leider weiß ich auch nicht ob das vielleicht am letzten Update liegt oder ich etwas falsch gemacht hatte...

viele Grüße,
Dirk
