### ISSUE TITLE
Template-Tag {{file.publicUrl}} verlinkt zu Original-Datei obwohl Tracking aktiv ist

### ISSUE THREAD

**Issue by svenwiegand** [podlove/podlove-publisher#791]
Ich habe in den Expert-Settings die Option `Tracking URL Parameters & Analytics` aktiviert und nutze in meinen Templates das Template-Tag `{{ file.publicUrl }}`. Laut [Dokumentation](http://docs.podlove.org/reference/template-tags/#file) soll das Tag bei aktiviertem Tracking auf die Tracking-URL verweisen. Bei mir wird aber ein Link direkt zur Original-Audio-Datei generiert.

**Comment by eteubert** [comment]
Du musst mindestens den source Parameter mit angeben: `{{ file.publicUrl({ source: "website" }) }}`

**Comment by svenwiegand** [comment]
Vielen Dank. Mit `{{ file.publicUrl({ source: "download" }) }}` scheint es zu klappen. Das hatte sich mir so aus der [Doku](http://docs.podlove.org/reference/template-tags/#file) nicht erschlossen.
