### ISSUE TITLE
Chapters visibility settings does not work für Podlove Webplayer 3

### ISSUE THREAD

**Issue by funkenstrahlen** [podlove/podlove-publisher#799]
![screen shot 2015-11-14 at 14 47 18](https://cloud.githubusercontent.com/assets/144173/11163851/aa80f3e0-8ade-11e5-8b50-d385bfe69970.png)
This has no effect.

**Comment by line-o** [comment]
Related https://github.com/podlove/podlove-web-player/issues/286
