### ISSUE TITLE
Multisite Aktivierung erstellt keine Tabellen

### ISSUE THREAD

**Issue by open-dev** [podlove/podlove-publisher#800]
Ich aktivierte den Publisher netzwerkweit und lief in das Problem, dass die Tabellen für den Publisher (zB File Types) nicht erstellt wurden. Auf den Sites, in denen bereits ein Podcast integriert ist, waren die Tabellen selbstverständlich schon vorhanden. In allen anderen frischen Sites waren diese nicht vorhanden.
Einerseits ganz charmant, da die Datenbank so nicht um alle Tabellen für jede Sites aufgeblasen wird (wenn man netzwerkweit aktiviert, jedoch den Publisher nur bei 9/10 nutzt), andererseits sollte dann eine Möglichkeit bestehen, diese Tabellen dann an entsprechender Site bei Wunsch erstellen zu lassen.
Als Workaround konnte ich netzwerkweit deaktivieren und im Nachgang bei allen Sites einzeln aktivieren (Tabellen wurden erstellt), deaktivieren und dann wieder nertzwerkweit einschalten.
Für Fragen, etc., stehe ich zur Verfügung.

Grüße

**Comment by svenwiegand** [comment]
Das scheint nicht nur Multi-Site, sondern die aktuelle Version insgesamt zu betreffen. Habe im September auf einer Seite ohne Probleme erfolgreich einen Podcast in Betrieb genommen. Wollte das gleiche gestern in einem anderen Podcast machen (keine Multi-Site-Installation) und dort geht nichts, da die File-Type-Tabelle leer ist und ich somit keine Assets definieren kann...

**Comment by eteubert** [comment]
@svenwiegand Hilft ein Deaktivieren & Aktivieren des Plugins? Wenn nicht, kannst du bitte ins PHP Error Log schauen?

Generell fällt es mir schwer, die Probleme nachzuvollziehen. Works for me :-/

**Comment by svenwiegand** [comment]
@eteubert Vergiss meinen Kommentar. Das war ein sehr spezielles Problem: Die Web-Site lief noch unter PHP 5.3. Als ich podlove installierte brachte WordPress korrekterweise die Meldung, dass dieses Plug-In 5.4 (oder 5.5?) benötigt. Die Installation lief aber trotzdem durch. Ich habe danach die Web-Site auf 5.6 umgestellt und dann Podlove aktiviert (installiert war es ja nun schon). Die fehlenden Tabellen scheinen ein Resultat davon zu sein, dass zum Zeitpunkt der Installation die PHP-Version zu alt war. Mit einem Reinstall funktioniert nun wieder alles wie gewollt. 

Entschuldige die unnötige Panik... ;-)

**Comment by eteubert** [comment]
@svenwiegand Ah, aber trotzdem ein Pfad, den ich bisher nicht bedacht habe. Ich mache dazu aber ein separates issue auf.

**Comment by chemiker** [comment]
Sollte mit #806 behoben worden sein.
