### ISSUE TITLE
Wrong release date in Podlove Web Player 3

### ISSUE THREAD

**Issue by dnebannoS** [podlove/podlove-publisher#801]
Hey,

After updating to Podlove Publisher 2.3.4 this morning I activated the web player 3 beta and noticed a wrong release date displayed within it.

My template gets the date via "episode.publicationDate" and is correct. The new web player seems to always be off by one month .. for all released episodes.

Here's an example:
![podlove-webplayer3-date](https://cloud.githubusercontent.com/assets/4618869/11196649/920b8790-8cb8-11e5-85b9-bae4e3db9037.png)

**Comment by timpritlove** [comment]
Looks like an off-by-one error. Web Player decrements month number by 1.

**Comment by timpritlove** [comment]
Ich schließ mal das Ticket, denn einerseits betrifft das den Web Player und andererseits wurde der Bug soeben im Code behoben
