### ISSUE TITLE
Übersetzung

### ISSUE THREAD

**Issue by benhartwich** [podlove/podlove-publisher#802]
Hallo,

ich habe bereits gegooglet und mich bei translate.podlove.org umgesehen, aber ich finde nirgends die ganze po. bzw. Übersetzungsmöglichkeit für alle Strings in Podlove. Wie kann das Plugin übersetzen?

LG

**Comment by eteubert** [comment]
Noch gar nicht, da müssen wir mehr Vorarbeit leisten.
