### ISSUE TITLE
Image folder in Web Player v3.0 distribution is missing

### ISSUE THREAD

**Issue by plutonik-a** [podlove/podlove-publisher#803]
The podlove-podcasting-plugin-for-wordpress.zip file doesn't include the image folder `/img/*` for the Web Player v3.0, so that a background-image for the download dropdown is missing.

Related https://github.com/podlove/podlove-web-player/issues/269
https://trello.com/c/1RVLPgEV

**Comment by eteubert** [comment]
was fixed in a previous release
