### ISSUE TITLE
Horizontal Scrolling with Webplayer 3 and Firefox

### ISSUE THREAD

**Issue by pommes** [podlove/podlove-publisher#808]
Hi there, 

I tried out the Webplayer 3 Beta and I like it a lot.
With Firefox (42, OSX) the player does not fit exactly in horizontal direction.
I have to scroll left/right a little bit in the player itself and the chapter list.
Maybe this especially caused by my layout but it works well in Safari and Chrome.

My Site: http://zahlensender.net

Kind regards, 

  Tim

**Comment by eteubert** [comment]
Scrolling issues are known and tracked in the web player project, like here https://trello.com/c/qAuohJtf/213-scroll-bars-am-ende-der-folge-sichbar
