### ISSUE TITLE
PPP und der "erweiterte Layout Editor" des Enfold Theme

### ISSUE THREAD

**Issue by Erdebene** [podlove/podlove-publisher#810]
Ich benutze zunehmend das [Enfold Theme](http://themeforest.net/item/enfold-responsive-multipurpose-theme/4519990?ref=Kriesi). Mir ist aufgefallen, dass der im Enfold Theme enthaltene "erweiterte Layout Editor" im Editor der Podlove-Episoden nicht angeboten wird. Kann man dasermöglichen? das wäre eine feine Sache.

**Comment by eteubert** [comment]
Feature-Vorschläge bitte nur im Forum diskutieren https://sendegate.de/c/podlove
Hier werden nur noch Bugs verwaltet.
