### ISSUE TITLE
All my podlove instances stopped working 

### ISSUE THREAD

**Issue by hugonz** [podlove/podlove-publisher#811]
I'm getting the same problem that [has been reported](https://github.com/podlove/podlove-publisher/issues/542) with the importing on libraries from PHP, but in my case, Podlove is the only plugin on my Wordpress install! no conflicting Piwik here. 

I'm getting internal server error on several sites using Podlove. The problem just started showing about a week ago.This is the actual error:

```
Fatal error: Cannot redeclare class Spyc in
/home/estupidoninja/estupido.ninja/site/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/vendor/mustangostang/spyc/Spyc.php
on line 57
```
I've tried downgrading the PHP version even down to 5.3 with no luck. 
Anyone has an idea what could be going wrong? The only help the host is offering is to remove the plugin (no good, since these sites are podcast sites)

**Comment by eteubert** [comment]
PHP 5.4 is the minimum requirement. I recommend 5.6. Actually, we have also tested with the most recent PHP 7.0 and that works too.

If you don't have any plugins installed, it might be the theme that is in conflict. Have you tried switching to a default theme like twentyfifteen?

**Comment by hugonz** [comment]
Thanks for your quick response.

Yes, I just found about the PHP version after the changes took effect. I'll be moving the installation back to the latest PHP then, no point in having them run on old PHP, thanks.

I hadn't thought about the theme, I will change it to a default one and see if it solved the problem. As I understand it, if the theme uses the Spyc libraries, then I'd be getting the same error, is that correct?

**Comment by eteubert** [comment]
> Spyc libraries, then I'd be getting the same error, is that correct?

Yes. It's a library to read configuration files, so it is possible themes might use this.

**Comment by hugonz** [comment]
Update:

One of the sites is consistently giving the premature end of header in the /podcast url, the other is giving the error on and off and in random urls even after using the 2014 theme for Wordpress, so there isn't really a library conflict. but something else.

All of this stopped working for no reason, and not after any upgrade or plugin addition. I'll be moving these sites to a virtual server that I can troubleshoot, as I think there is something seriously  wrong with my webhost. 

Thanks for your help in finding what these errors meant. If I keep finding the problem even when I control the stack, I will continue trying to find the root cause and report back if I can relate it to anything in Podlove's code or the PHP libraries. 

Thanks again,

Hugo

**Comment by eteubert** [comment]
Did you manage to trace the issue?

**Comment by hugonz** [comment]
I was able to trace the issue with the webhost, it was related to the PHP
limits: both execution time and memory use. They changed the php.ini for
the site and added

max_execution_time = 60
memory_limit = 128M

It got much better and I was getting the error once every 10/12 times. My
conclusion was that I had to move the site out of the shared hosting and
into a VPS, the limits seems way too high and rather the server load was to
blame. I did move the site into a 512MB VPS with lighttpd and I've had no
problems since.

I guess this could happen more and more with shared hosts as Podlove gets
more feature-rich and they keep cramming too many sites on a single server.

**Comment by eteubert** [comment]
Still strange that you got the mentioned error and not a) a timeout or b) an out of memory exception. But I guess strange things happen when a system is crammed with sites until it barely can handle the load.

I guess we need something like this: :P

```php
if (is_cheap_shared_hosting()) {
  display_warning("Please spend at least 5$/month on a VPS for the best Publishing experience.");
}
```

Thanks for taking the time to reply and happy podcasting :)
