### ISSUE TITLE
Podlove Publisher and Markdown Plugins don't play nice together

### ISSUE THREAD

**Issue by klaustopher** [podlove/podlove-publisher#815]
Hi,

I just set up a new Wordpress installation. The only plugins that are active are the current version of the publisher and [WP Markdown Editor](https://wordpress.org/plugins/wp-markdown-editor/) that brings the JetPack Markdown Parser.

Markdown works for Posts, Pages but not for Episodes.

URL is: http://abends-im-wald.de

I think it might have something to do with the fact, that the markdown plugin does not register itself for the custom post type, but that's just a guess. I don't really know what more information I can give you, so you can debug this, but if you tell me what information you need to debug this, I'm more than happy to provide it.

Other info:
* No cache-plugin enabled
* Disabled the podlove cache

**Comment by eteubert** [comment]
You need to enable markdown support for custom post types, see http://jetpack.me/support/markdown/

You need to add this snippet:

```php
add_action('init', 'podlove_jetpack_enable_markdown');
function podlove_jetpack_enable_markdown() {
    add_post_type_support( 'podcast', 'wpcom-markdown' );
}
```

You can add this snippet with https://wordpress.org/plugins/code-snippets/.

**Comment by klaustopher** [comment]
Thanks, this works now ... ;) Maybe it could be added to a documentation somewhere ;)

**Comment by eteubert** [comment]
We could even make this work out-of-the box. I created a task: https://trello.com/c/gWKapB6M/466-jetpack-support
