### ISSUE TITLE
Escaping in social media links

### ISSUE THREAD

**Issue by eteubert** [podlove/podlove-publisher#817]
From Slack: 

> Da gibt es noch einen Bug bei den Social Media Links.
> 
> Wenn ich als URL für eine Website "https://de.wikipedia.org/wiki/Nikolaus_Forg%C3%B3” angebe, steht da nach dem Speichern https://de.wikipedia.org/wiki/Nikolaus_Forg%252525C3%252525B3 drin. D.h. das Encoding-EscapeZechen “%” wird selbst escaped.
> 
> Das selbe übrigens wenn ich eine Unicode URL nehme: https://de.wikipedia.org/wiki/Nikolaus_Forgó

**Comment by Erdebene** [comment]
Passt gleube ich in den Zusamenhang. Domains mit Umlauten werden noicht ordentlich angezeigt/verarbeitet.
Aus http://www.försterkinder.de/ wird http://www.xn--frsterkinder-4ib.de/
Der Link führt zum Ziel, ist aber unsexy

**Comment by chemiker** [comment]
Fixed with #915
