### ISSUE TITLE
Media file exists, but podlove cannot detect file

### ISSUE THREAD

**Issue by doctarock** [podlove/podlove-publisher#819]
I am implementing the podlove system on a wordpress site.

When attempting to set up a test episode the plugin was trying to load the mp3 from / (webroot) despite having the Episode Asset URL Template set as the default: %media_file_base_url%%episode_slug%%suffix%.%format_extension%

To fix this issue I installed the plugin "Custom Upload Dir" which allowed me to set all media files to be uploaded to /wp-content/uploads/everyting/[file], I then changed the Episode Asset URL Template to this folder.

This is working mostly as expected, the episode links directly to the file and will play the podcast when viewed from the episode page, however the backend is unable to detect the file and so does not pick up the episode filesize.

EDIT: it can detect the duration when "detect duration" is pressed

Of particular note is that the backend still indicates a base url of /, despite generating the correct filename for the episode (wp-content/uploads/everything/test-podcast-episode-ajfp.mp3)

The "asset file name" is also cleared when you click "update" under edit episode, for it to regenerate the correct file URL I need to uncheck and then recheck "enable".

**Comment by eteubert** [comment]
Did you fill out the "Upload Location" in `Podcast Settings > Media`? It should be the full URL (starting with "http", not "/").

**Comment by doctarock** [comment]
I just gave that a go, that explains the base URL, I assumed the "Asset URL Template" served this purpose. Unfortunately this did not resolve the issue however.

I have implemented a workaround using XHR in episode.js to get the filesize for now, I will retry setting this up this properly when I get a chance.

**Comment by eteubert** [comment]
Feel free to reopen when you get more details. I'll close until then.

**Comment by markusvoelter** [comment]
I have the same issue. I did fill in the base URL, as you can see in the screenshot. If I manually concatenate the base url and the slug (and add .mp3) it works. But the publisher cannot resolve it.

![screen shot 2016-06-17 at 19 59 05](https://cloud.githubusercontent.com/assets/592330/16159996/0a60bcd2-34c6-11e6-8bba-9ca64ee22551.png)

**Comment by markusvoelter** [comment]
Additional info: I just tried to do a wget from the command line to download the media file from the actual (remote) Wordpress server. It works. But the publisher cannot resolve it.

**Comment by markusvoelter** [comment]
I found this in the log:

[2016-06-17 21:28:36] --- # Can't reach http://traffic.libsyn.com/omegataupodcast/omegatau-207-airbusMontageInHamburg.mp3 --- # Please include this output when you report a bug certinfo: php_open_basedir: php_safe_mode: php_curl: curl_exec:
