### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by partnerwerk** [podlove/podlove-publisher#820]
I am missing the possibilities to contribute translations. It seems that the plugin is not fully supporting the WordPress standards for localization. That is a pity - even more so as now http://translate.wordpress.org/ offers a wonderful platform for people from all over the world to contribute their translation into any language you can think of. So this is not filing a bug but a request to make this great development usable for many more people. 

Da dieses Plugin bis auf die Sprache ja deutsche Wertarbeit ist, würde ich gerne meinen Beitrag leisten, es ins Deutsche zu übersetzen :-)

**Comment by eteubert** [comment]
I made some changes to the plugin. The warning at https://translate.wordpress.org/projects/wp-plugins/podlove-podcasting-plugin-for-wordpress disappeared, so we are at least one step closer to a translation :)

**Comment by partnerwerk** [comment]
Thank you. I checked in with https://translate.wordpress.org/projects/wp-plugins/podlove-podcasting-plugin-for-wordpress/dev/de/default and can access the files now. I will add translations the coming days.

**Comment by partnerwerk** [comment]
Stelle beim Übersetzen fest, dass ich keine vernünftige Übersetzung für Asset habe. Mal bedeutet es Datei, mal Dateityp. Ich habe versucht, das mit Posten zu übersetzen - ist solala. irgendein Vorschlag?

**Comment by partnerwerk** [comment]
Wie unterscheide ich also File Format und Asset Type? Technisch ist das klar, aber ich stehe etwas auf dem Schlauch, wie es auf Deutsch gehen würde...

**Comment by partnerwerk** [comment]
Ich bekomme die Übersetzungen im Publisher nicht angezeigt. *.mo und *.po heruntergeladen in /wp-content/languages. Weder die Umbenennung in podlove-de_DE.* noch in podlove-podcasting-plugin-for-wordpress-de_DE.* bringt Übersetzungen im Backend zum Vorschein.

**Comment by eteubert** [comment]
Ich würde dich gerne zu Slack einladen, unserem Chat. Ich vermute, es gibt immer mal wieder etwas zu den Übersetzungen zu diskutieren und da ist das vermutlich die bessere Plattform. Dazu brauche ich deine email. Kannst du die bitte hier schreiben oder an eric@ericteubert.de senden?
