### ISSUE TITLE
Podcasts as Social Service

### ISSUE THREAD

**Issue by HerrvonSpeck** [podlove/podlove-publisher#821]
I was wondering if it would be possible to add a specific Icon for Podcasts as a social service for contributors. Since it's possible to add websites it's possible to add them already, but I guess it would be nice to have a specific icon for this.

**Comment by funkenstrahlen** [comment]
+1

**Comment by eteubert** [comment]
We tend to only support "social" services that have a user profile page that can be linked to — with the exception of the website. I feel like this is enough for now.

Please discuss feature ideas at https://community.podlove.org rather than here, in the bug tracker.
