### ISSUE TITLE
Add Audio Example to Contributor

### ISSUE THREAD

**Issue by HerrvonSpeck** [podlove/podlove-publisher#822]
While setting up a new public page for the contributors of a new project, I wondered if it would be possible to add an audio example for each contributor to that list. I imagine a simple play button derived from the regular Podlove web player which appears in the table of global contributors, if an Admin added a speech example to the contributor in the backend.

It would be totally nice to greet new listeners with a "Hello! My name is Blurb McFork! Welcome to the PooPod!" when they are looking for the people behind a podcast.

Especially podcasts with many male and similar sounding contributors would profit from this feature.

**Comment by eteubert** [comment]
Interesting idea :)
Please discuss feature ideas at community.podlove.org rather than here, in the bug tracker.
