### ISSUE TITLE
Speichern von Episoden führt zu Fehlermeldung

### ISSUE THREAD

**Issue by partnerwerk** [podlove/podlove-publisher#825]
Beim Abspeichern von neuen Episoden bekomme ich einen Fehler 500 und diesen Log-Eintrag:
`*260 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot use object of type WP_Error as array in /var/www/clients/client1/web119/web/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/lib/http/curl.php on line 104" while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: meineseite.de, request: "GET /wp-admin/admin-ajax.php?action=podlove-file-create&episode_id=1&episode_asset_id=2&slug=meineseite-testaufnahme HTTP/1.1", upstream: "fastcgi://unix:/var/lib/php5-fpm/web119.sock:", host: "meineseite.de", referrer: "http://meineseite.de/wp-admin/post.php?post=12&action=edit"`
Ist das ein Serverfehler oder ein Pluginfehler?

**Comment by timpritlove** [comment]
Was sagt das Support-Menü?

**Comment by partnerwerk** [comment]
`1 NOTICE (no dealbreaker, but should be fixed if possible): 
- The PHP setting "open_basedir" is not empty. This is incompatible with curl, a library required by Podlove Publisher. We have a workaround in place but it is preferred to fix the issue. Please ask your hoster to unset "open_basedir".`

Alles andere ist ok.
Ist das die Erklärung...?

**Comment by partnerwerk** [comment]
Das war eine Spezialität von ISPConfig. Die entsprechende Servereinstellung hat den Fehler beseitigt.
