### ISSUE TITLE
Meta Key / Custom Fields value für Podlove Episode Media File Slug

### ISSUE THREAD

**Issue by benhartwich** [podlove/podlove-publisher#828]
Hallo,

ich teste gerade Front-End Upload / Publishing Systeme für WordPress und das Frontend Upload Plugin kann Meta Keys aus den Custom Fields ansteuern, aber nach meiner bisherigen Recherche platziert Podlove die Episode Media File Slug z.B. nicht als Meta Key Value oder?

Im Grunde wäre das der einzig wichtige Knackpunkt, damit ein rudimentäres Uploadtool Sinn machen würde. Kann mir hier jemand etwas dazu sagen oder mir Tipps / Hilfe geben?

**Comment by eteubert** [comment]
Korrekt, der Slug steht in der Tabelle `wpprefix_podlove_episode`. 

Hier bitte nur Bugs melden. Fragen / Anregungen sind besser auf https://community.podlove.org/ oder https://sendegate.de/ aufgehoben.
