### ISSUE TITLE
Lokalisierung für Buttons

### ISSUE THREAD

**Issue by partnerwerk** [podlove/podlove-publisher#829]
In der Template-Datei für die Player-Buttons fehlt die Lokalisierungsfunktion:
[https://github.com/podlove/podlove-publisher/blob/release-2-3-8/templates/shortcode/downloads-select.twig](https://github.com/podlove/podlove-publisher/blob/release-2-3-8/templates/shortcode/downloads-select.twig)

**Comment by partnerwerk** [comment]
Ebenfalls in den Tabellen-Überschriften hier:
[https://github.com/podlove/podlove-publisher/blob/release-2-3-8/templates/shortcode/episode-list.twig](https://github.com/podlove/podlove-publisher/blob/release-2-3-8/templates/shortcode/episode-list.twig)

**Comment by chemiker** [comment]
Wird mit #919 zugefügt.
