### ISSUE TITLE
Contributor names

### ISSUE THREAD

**Issue by partnerwerk** [podlove/podlove-publisher#830]
[/wp-admin/admin.php?page=podlove_contributor_settings&action=edit&contributor=1 ](#)

> The Public Name will be used for public mentions. E.g. the Web Player. If left blank, it defaults to the "real name"

steht auf der Seite, auf der man die Contributors einträgt. Das wird allerdings so nicht ausgeführt. Es erscheint mit dem template-Tag `{{ contributor.publicname }}` nichts im Frontend, es sei den man trägt explizit einen Namen in das Feld ein

**Comment by chemiker** [comment]
@eteubert Was muss geändert werden? Die Beschreibung oder das Verhalten?

**Comment by eteubert** [comment]
@chemiker Die Beschreibung sollte gekürzt werden auf "The Public Name will be used for public mentions." 

In Templates sollte generell `{{ contributor.name }}` verwendet werden, wenn Fallback-Funktionalität gewünscht ist. Das muss an der Stelle aber nicht erwähnt werden.

**Comment by chemiker** [comment]
Resolved with #914
