### ISSUE TITLE
Podlove not compatible with AGP Font Awesome Collection WordPress Plugin

### ISSUE THREAD

**Issue by hellojed** [podlove/podlove-publisher#832]
Hi,

today I wanted to install the Podlove Plugin to my WordPress installation but, after installing, while trying to activate it, received the following error:

Fatal error: Cannot redeclare class Spyc in /www/htdocs/v145731/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/vendor/mustangostang/spyc/Spyc.php on line 57

Some googling led me to a possible conflict with my Font Awesome plugin, so I noticed that I'm able to activate the Podlove plugin when the Font Awesome plugin is deactivated but stumble across a nearly identical (changed folders) error when trying to re-activate the Font Awesome plugin whole Podlove is still active.

My WordPress version is 4.4.2, it runs on PHP Version 5.5.31 and MySQL Version 5.6.27 on a shared server at All-Inkl.

**Comment by eteubert** [comment]
Same issue as #542

WordPress still provides no way to deal with dependency management.

I plan to wrap the dependency in a `class_exists` somehow which will help in _some_ cases (only when the Publisher is loaded later than the other plugin using the same dependency).
