### ISSUE TITLE
[Bug] Social Services Google+ URL structure

### ISSUE THREAD

**Issue by Inrumpo** [podlove/podlove-publisher#833]
Wenn I add a Google+ account (let's call it `testuser` for now) to one of my contributors and klick the icon, a URL with the following structure gets created:
`http://mywebsite.com/wp-admin/testuser`

The working URL should look like:
`https://plus.google.com/+testuser/`

Workaround: Add the complete Google+ URL
I guess it's intended to be done that way. Just entering the username would still be more consistent though.

**Comment by chemiker** [comment]
The publisher expects you to enter a whole URL what also indicated by the placeholder (see screenshot)
![screen shot 2016-05-09 at 15 54 30](https://cloud.githubusercontent.com/assets/4408941/15127901/6f864d52-15fe-11e6-8aea-8054fac95eab.png)

The reason for this is that for a long time the identifier in the URL was a cryptic string. As it is unknown whether all google+ accounts feature a short URL, I would suggest to stay with the current behavior. /cc @eteubert
