### ISSUE TITLE
No way to change title assigned to feeds in podcast network 

### ISSUE THREAD

**Issue by ofadam** [podlove/podlove-publisher#836]
After reviewing instructions for setting up a podcast network (http://docs.podlove.org/podlove-publisher/guides/podcast-network.html), I've decided to use Option 2: Category based feeds. All is working well, except that each category's RSS feed contains the same overall title and podcast logo.

Is there a way to make those unique while retaining all of the podcasts in the same WordPress installation?

**Comment by eteubert** [comment]
This is a bug tracker. Please use the community forum (https://community.podlove.org) or professional support (http://publisher.podlove.org/support/).

To give a quick answer to your question: Categories are basically just filters on the main feed. You can change their data only by writing code and looking for the right hooks. If you have separate podcasts, a network is the recommended way.
