### ISSUE TITLE
Spaces in filenames

### ISSUE THREAD

**Issue by tautologe** [podlove/podlove-publisher#838]
Hi, 
when I import a production from auphonic that processed a filename with spaces, the publisher does not find the processed file. 

I know that one could just use files without spaces, but most times a friend cuts the file and uploads it to auphonic. And when I get the success mail, I publish the file when I have the time. When he forgot to rename the file I have to find out what went wrong (there is no meaningful error message), login to auphonic myself, fix the filename, reprocess and tell him to not forget to remove the space next time. This is a suboptimal workflow ;)

Also if podlove is going to enable automated publishing, this issue will probably break the workflow or publishing empty episodes. I did not try what happens, if I enable "Publish episode when done".

Thank you very much for this awesome piece of software and even more if you fix this issue :-)

**Comment by timpritlove** [comment]
Can you tell me what you have entered as the episode media flie slug and what the file was actually named? can you provide a URL to test?

**Comment by tautologe** [comment]
After transmitting via FTP auphonic says: "External service result file URLs: http://hostname/podcast/2016-04-03 Test1.mp3"

The episode media file slug is "2016-04-03 Test1" as it is seems to be transmitted by auphonic. I did not edit it. 

When I first click "Import Episode Metadata" after selecting the auphonic production, the space seems to be replaced by a hyphen ("http://hostname/podcast/2016-04-03-Test1.mp3") in the column "Asset File Name" below. The column file size says "File not found!". After clicking around the asset file name soon disappears. The media slug keeps the same.

**Comment by eteubert** [comment]
It's worth discussing how we should treat spaces in filenames. Replacing them with a "-" is definitely wrong. Maybe replacing with `%20` would make more sense?

**Comment by tautologe** [comment]
Yes, `%20` is the correct way to escape spaces in URLs. You will often see `+` as a replacement for spaces, but only when used in queries, it does not work for paths/filenames.
