### ISSUE TITLE
Player/download wird in leerer Episode angezeigt.

### ISSUE THREAD

**Issue by erdebene** [podlove/podlove-publisher#839]
Ich richte gerade eine neue Serie in meiner WP-Multisite-Umgebung ein.
So sieht die Einstellung für den Web-Player aus:
![image](https://cloud.githubusercontent.com/assets/11456963/14325502/e86ab8d2-fc29-11e5-8c9c-2053d7622168.png)

Ich habe eine Episode angelegt und außer dem Titel der Episode **nichts** eingetragen, dennoch werden mir schon die Downloads in der Vorschau angezeigt.
![image](https://cloud.githubusercontent.com/assets/11456963/14325562/31232500-fc2a-11e5-97da-527554d7d010.png)

Sobald etwas in _Episode Media File Slug_ eingetragen ist, wird der Player angezeigt. Wie gesagt, immer noch kein anderer Inhalt und kein Template-Aufruf.
![image](https://cloud.githubusercontent.com/assets/11456963/14325948/0b15a944-fc2c-11e5-8bef-bf21e3fa5276.png)

ein gültiger Eintrag in _Episode Media File Slug_ läßt das Episoden-Cover erscheinen. Außerdem funktionieren dann Player und Download:
![image](https://cloud.githubusercontent.com/assets/11456963/14325624/7332dfc6-fc2a-11e5-9609-289b01e0ccd2.png)

Üblich wäre, dass alles leer ist, weil noch nichts in der Episode steht und kein Template aufgerufen wird. Kann ich noch was probieren?

Die Support-Informationen:
```
Website             http://erdradio.de
PHP Version         5.6.20
WordPress Version   4.4.2
Publisher Version   2.3.9
Web Player Version  2.0.19
Twig Version        1.24.0
open_basedir        ok
curl Version        7.38.0
iconv               available
simplexml           ok
max_execution_time  60
upload_max_filesize 50M
memory_limit        256M
disable_classes     
disable_functions   
permalinks          ok (/%postname%/)
podlove_permalinks  ok
podcast_settings    ok
web_player          ok
podlove_cache       off
assets              
	m4a    audio/mp4
	mp3    audio/mpeg
	opus   audio/ogg;codecs=opus
	ogg    audio/ogg
	jpg    image/jpeg
	json   application/json
	chapters.txttext/plain
	psc    application/xml
network module      ok

0 errors
0 notices
Nice, Everything looks fine!
```

**Comment by erdebene** [comment]
In der Multisite-Umgebung wird bei Einrichtung einer neuen Seite mit der Podlove-Instanz ein Template  per default installiert. Als ich das entdeckte, habe ich es gelöscht und die Welt war in Ordnung. Man muss eben nur darauf kommen ...
Dennoch danke.

**Comment by eteubert** [comment]
Das Standard-Template sollte eigentlich helfen, nicht verwirren. Vielleicht wäre es generell gut, auch in der Episodenansicht einen Indikator zu haben, ob und welches Template automatisch eingebunden wird.
