### ISSUE TITLE
Incomplete installation after php version warning

### ISSUE THREAD

**Issue by tautologe** [podlove/podlove-publisher#840]
I just installed podlove on a fresh wordpress installation (Strato shared hosting). 
After the installation I get warned that the php version is outdated and that podlove cannot be activated. 

Indeed: Strato has a very old php version activated by default (I think it was 5.3), but you can also choose 7.0. After I did that podlove was somehow activated, but incomplete. Some menu items were missing, e.g. the Podlove Dashboard and it was not possible to add any assets. I got podlove working by deactivating and then activating it again and now everything seems to be ok. But maybe there is an error in the php version check routine which could potentially cause some more trouble.

**Comment by eteubert** [comment]
Yeah, that's bad. When the PHP version is outdated I only show that message but leave the plugin activated. When the version is fixed, none of the "activation" hooks are executed. I guess I shouldn't leave the plugin activated.

**Comment by eteubert** [comment]
fixed here: 33edde660ecf691885ca7d157452f7a3b4dc6ed3
