### ISSUE TITLE
HHVM Segmentation fault: htmlspecialchars()

### ISSUE THREAD

**Issue by ugoArangino** [podlove/podlove-publisher#841]
Bei mir stürzt mein **HHVM** immer ab, wenn ich meine **Podlove Publisher** Daten **exportieren** möchte.. Anbei sind Warnungen und der Stacktrace.
Als Grund wird angegeben, dass `htmlspecialchars()` ein `Array` übergeben wird, aber diese Funktion `Strings` erwartet. 
Ich habe mir mal den Code von `podcast_exporter.php` angeschaut. Dort werden ja Arrays mit einer for-Schleife durchlaufen. Bei Nested-Arrays stützt das Programm aber sofort ab.

### journalctl -fu hhvm.service
	hhvm[16259]: Warning: htmlspecialchars() expects parameter 1 to be string, array given in /var/www/podcast/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/lib/modules/import_export/export/podcast_exporter.php on line 102

### PHP Stacktrace:

	#0  htmlspecialchars(Array) called at [/var/www/podcast/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/lib/modules/import_export/export/podcast_exporter.php:102]
	#1  Podlove\Modules\ImportExport\Export\PodcastExporter->exportOptions() called at [/var/www/podcast/wp-includes/plugin.php:525]
	#2  do_action(podlove_xml_export, ) called at [/var/www/podcast/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/lib/modules/import_export/export/podcast_exporter.php:181]
	#3  Podlove\Modules\ImportExport\Export\PodcastExporter->getXml() called at [/var/www/podcast/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/lib/modules/import_export/export/podcast_exporter.php:47]
	#4  Podlove\Modules\ImportExport\Export\PodcastExporter->download() called at [/var/www/podcast/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/lib/modules/import_export/export/podcast_exporter.php:18]
	#5  Podlove\Modules\ImportExport\Export\PodcastExporter::init() called at [/var/www/podcast/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/lib/modules/import_export/import_export.php:13]
	#6  Closure$Podlove\Modules\ImportExport\Import_Export::load() called at [/var/www/podcast/wp-includes/plugin.php:525]
	#7  do_action(admin_init) called at [/var/www/podcast/wp-admin/admin.php:168]

---

## System

	HipHop VM 3.13.0 (dbg)
	Compiler: tags/HHVM-3.13.0-0-g5b0e52b83f1dc0aa0c1dfe3a5687995c9693f5a6
	Repo schema: 5fa42b79ea61b0af8d3fe1af48e0308a834bd224

	nginx version: nginx/1.9.10

	Website             https://komfortrauschen.com
	PHP Version         5.6.99-hhvm
	WordPress Version   4.5
	Publisher Version   2.3.9
	Web Player Version  no web player found
	Twig Version        1.24.0
	open_basedir        ok
	curl Version        7.38.0
	iconv               available
	simplexml           ok
	max_execution_time  0
	upload_max_filesize 
	memory_limit        256M
	disable_classes     
	disable_functions   
	permalinks          ok (/%postname%/)
	podlove_permalinks  ok
	podcast_settings    ok
	web_player          ok
	podlove_cache       on
	assets              
		m4a    audio/mp4
		mp3    audio/mpeg
		ogg    audio/ogg
		jpg    image/jpeg
		psc    application/xml
	network module      ok

	0 errors
	0 notices
	Nice, Everything looks fine!

**Comment by eteubert** [comment]
Thanks for the report and sorry for not replying earlier. Will be fixed in the following release.
