### ISSUE TITLE
podlove webplayer 3: how can I deactivate the Share option

### ISSUE THREAD

**Issue by Lillieleen** [podlove/podlove-publisher#842]
HI there,

I just switched to the podlove webplayer 3 very recently. Before it was possible to modify the settings of it but now I am not able to do so any more ... However, since German authorities seem to become more strict on the sharing buttons these days I'd like to switch the share function off - at least for a while. How can I do so?
Would love to hear back from you!
Lilli

**Comment by timpritlove** [comment]
Can you explain what you mean by "German authorities seem to become more strict" and how this should affect simple sharing links?

**Comment by Lillieleen** [comment]
Hey, 
Sorry for the delay. What I was referring to is this: https://www.e-recht24.de/artikel/facebook/10081-urteil-abmahnung-facebook-like-button.html
With regard to the Podlove Media Player it would mean that I'd like to be able to disable the share function, which to my knowledge was possible before but now I cannot find where to disable it anymore.

**Comment by eteubert** [comment]
(I think) this does not apply to the web player since we don't include any of the tools provided by the social media plattforms. The image ships with the web player and no third party scripts are loaded. No data is sent to Facebook or other platforms on page load.

**Comment by Lillieleen** [comment]
Are you sure? Cause in order to share the podcast by i.e. Twitter or Facebook etc. I have to log in – which is the problem as I understood it. 
However, before it was possible to disable and enable functions of the Webplayer - why did you remove that posibility?

**Comment by timpritlove** [comment]
Of course you have to log in to a system when you want to post something on that system. But our player does simply provide a link to do this easily. Not more not less. The sharing function is simply a shortcut. As Eric explained, we are do not load anything from Twitter/Facebook so no automatic tracking is enabled.

Regarding the missing functions: please note that Web Player 3 is in BETA. Nothing is finished or set in stone.
