### ISSUE TITLE
Subscribe Button shortcode attributes have no effect with new subscribe button

### ISSUE THREAD

**Issue by funkenstrahlen** [podlove/podlove-publisher#843]
The Podlove Subscribe Button was updated recently. Im embed the subscribe button via shortcode into my wordpress: 

`[podlove-podcast-subscribe-button size="big"]`

However after the update the attribute option `size=big` does not have any effect any more. The button is displayed like it was configured with big + auto as it displays the coverart image.

![screen shot 2016-05-04 at 15 29 46](https://cloud.githubusercontent.com/assets/144173/15015578/0f74a868-120d-11e6-9208-109cd6f8c77f.png)

I want to see only the button **without** the coverart. I assume this happens due to a change in the button API.

**Comment by eteubert** [comment]
The shortcode is updated but I forgot to update the documentation.

What you need is this: `[podlove-podcast-subscribe-button size="big" format="rectangle"]`
For other parameters have a look at the button doc here: http://docs.podlove.org/podlove-publisher/reference/template-tags.html#podcast. The parameters for templates and shortcodes are identical.

**Comment by funkenstrahlen** [comment]
Thank you. I updated the shortcode and it is fixed now.
