### ISSUE TITLE
Episode image url sometimes wrong

### ISSUE THREAD

**Issue by johannes-mueller** [podlove/podlove-publisher#846]
As just shown on #sub7 ...

I have a theme on http://kern.punkto.info that uses episodes image urls by `$episode->image()->html( array( "width" => 160 ) )`

Sometimes some image urls are rendered in a wrong way like this:
```
<img class="episode-tile-image" width="160" height="160" src="http://kern.punkto.info/bildoj/kp045-unujarigxo.jpg" srcset="http://kern.punkto.info/bildoj/kp045-unujarigxo.jpg 1x, http://kern.punkto.info/bildoj/kp045-unujarigxo.jpg 2x, http://kern.punkto.info/bildoj/kp045-unujarigxo.jpg 3x">
```

where as the correct way would be the cached urls for the demanded resolution like this:
 ```
<img class="episode-tile-image" width="160" height="160" src="https://kern.punkto.info/wp-content/cache/podlove/56/3f717f0cf638df942a6791c61f1fb2/kp010-ccc_160x160.jpg" srcset="https://kern.punkto.info/wp-content/cache/podlove/56/3f717f0cf638df942a6791c61f1fb2/kp010-ccc_160x160.jpg 1x, https://kern.punkto.info/wp-content/cache/podlove/56/3f717f0cf638df942a6791c61f1fb2/kp010-ccc_320x320.jpg 2x, https://kern.punkto.info/wp-content/cache/podlove/56/3f717f0cf638df942a6791c61f1fb2/kp010-ccc_480x480.jpg 3x">
```

This occurs sometimes, mostly all the image urls are rendered correctly. When it occurs, reloading the page a couple of times usually works around the issue.

**Comment by eteubert** [comment]
Fixed in https://github.com/podlove/podlove-publisher/commit/8dc9b04a7a46166cd0d93de2b366c30d02998ac5
