### ISSUE TITLE
Media can't be found

### ISSUE THREAD

**Issue by 343max** [podlove/podlove-publisher#849]
I just wanted to publish a new podcast episode but when I enter the media file slug I only get a "File not found!" message for all files. I double checked that the files are there and everything is fine. Also when I edit an old episode the error message is the same, even the files are definitely there.

Any ideas? What's the best way to debug this?

**Comment by timpritlove** [comment]
some associated URLs would be helpful

**Comment by 343max** [comment]
What kind of URLs do you mean? Media URLs? http://podcasts.343max.de/wmr/wmr102.m4a

**Comment by 343max** [comment]
Turns out a system update had uninstalled the php-curl module. After reinstalling and restarting the http server everything works fine again.
