### ISSUE TITLE
WP Backend broken after PP installation & activation

### ISSUE THREAD

**Issue by JaegersNet** [podlove/podlove-publisher#850]
Hi there,

i just made a fresh installation of podlove publisher. After enabling it the WP backend is stuck. Only the left menu is visible, the right area is grey - for every tested menu entry. 

Frontend seems to work fine, except the WP menu bar, which is missing.

After deactivating Podlove Publisher everything's fine again.

PP Version 2.3.12 
WP Version 4.5-3 DE

I switched to the TwentySixteen Template - without any effect
I checked apache error logs - without any relevant error messages 
I checked wp-debug.log - two other plugins have issues, I disabled them without effect

Until I start disabling plugin by plugin... any idea?

Michael

**Comment by eteubert** [comment]
Never heard of that issue before. Symptoms suggest a PHP error but that should appear in wp-debug.log when logging is enabled. Can you inspect the generated HTML of a broken page? Maybe it could be helpful to see where exactly it stops rendering.

Try setting both `define( 'WP_DEBUG', true );` and `define( 'WP_DEBUG_DISPLAY', true );`.

**Comment by JaegersNet** [comment]
Ok, did it.

`Notice: Undefined index: nofollow_blogroll in /xxx/wordpress/wp-content/plugins/nofollow/nofollow.php on line 230

Strict Standards: Redefining already defined constructor for class SocialAuthorBio in /xxx/wordpress/wp-content/plugins/social-autho-bio/social_author_bio.php on line 56

Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /xxx/wordpress/wp-content/plugins/nofollow/nofollow.php:230) in /xxx/wordpress/wp-content/plugins/wordpress-social-login/wp-social-login.php on line 64

Notice: Undefined index: updated in /xxx/wordpress/wp-content/plugins/gp-premium/addons/generate-hooks/functions/functions.php on line 412

Warning: Cannot modify header information - headers already sent by (output started at /xxx/wordpress/wp-content/plugins/nofollow/nofollow.php:230) in /xxx/wordpress/wp-includes/pluggable.php on line 1167

Warning: Cannot modify header information - headers already sent by (output started at /xxx/wordpress/wp-content/plugins/nofollow/nofollow.php:230) in /xxx/wordpress/wp-includes/pluggable.php on line 1167`

After disabling the two plugins "nofollow and Socialauthorbio"

`Notice: Undefined index: updated in /xxx/wordpress/wp-content/plugins/gp-premium/addons/generate-hooks/functions/functions.php on line 412

Notice: Undefined index: pretty-link/pretty-link.php in /xxx/wordpress/wp-content/plugins/pretty-link/classes/models/PrliUpdate.php on line 288


Fatal error: Cannot redeclare class Spyc in /xxx/wordpress/apps/piwik/vendor/mustangostang/spyc/Spyc.php on line 57`

**Comment by eteubert** [comment]
> Fatal error: Cannot redeclare class Spyc in /xxx/wordpress/apps/piwik/vendor/mustangostang/spyc/Spyc.php on line 57`

Ah, that's the one. Piwik is using the Spyc library, which the Publisher is also using. The Publisher is already patched to handle this. You can replace the file above manually with a recent one and the issues should go away: https://github.com/mustangostang/spyc/blob/master/Spyc.php

**Comment by JaegersNet** [comment]
Ok, fixed it. At least the backend is working again. Now I'll give Podlove Publisher a try;

Thanks!
