### ISSUE TITLE
Feed Problems on iTunes

### ISSUE THREAD

**Issue by tasovi** [podlove/podlove-publisher#852]
Hi,
since I am using podlove, somehow there is a problem with the feed.
iTunes or the Podcast app on iOS cancels the download of episoes and shows an exclamation mark.
I don't know what is wrong?
The feed is here:
http://pendler-podcast.de/feed/mp3/

can someone please help me?
What did I do wrong?
 am using the latest podlove version.
Danke Euch/ thx

**Comment by timpritlove** [comment]
Can't find anything wrong with the feed and download behaviour. Subscribing and downloading in iTunes works fine for me.

Also: this is not a support forum. Please use https://community.podlove.org/ instead
