### ISSUE TITLE
Feature request: Custom "Social" contacting possibility for contributors

### ISSUE THREAD

**Issue by johannes-mueller** [podlove/podlove-publisher#853]
## Problem

There's often the problem, that a podcast guest speaker wants to give contact data for a social network, messaging network, or something similar, which is not in the "Service" dropdown in the "Social" section of the contributor editing page. Examples are Wikipedia, Telegram and probably lots of subculture specific niche social networks.
## Proposed solution

So please consider adding the possibility of custom services. To add a custom service the user has to provide
- the name of the service
- a favicon of the service
- an url scheme

As soon as the custom service is added, it should be available for future added contributors.

Thanks for considering this

Johannes

**Comment by chemiker** [comment]
I'm closing this ticket since it is basically a dublicate of #776.
