### ISSUE TITLE
Don't Rely On Cross-Domain Content

### ISSUE THREAD

**Issue by ilf** [podlove/podlove-publisher#854]
Apparently the plugin requires user agents to fetch content from other domains than the website where it's installed. After enabling JavaScript on Podlove-enabled sites, it wants to fetch content from at least:

https://cdn.podlove.org/subscribe-button/button.html?id=*
https://cdn.podlove.org/subscribe-button/fonts/roboto_medium/Roboto-Medium-webfont.woff
https://cdn.podlove.org/subscribe-button/javascripts/app.js
https://cdn.podlove.org/subscribe-button/stylesheets/app.css

I propose to **disable all cross-domain-content by default**.

If that's not possible, please provide an **option to disable all cross-domain content**.
Unfortunately, that's a show-stopper for our site to install this otherwise awesome plugin.

**Comment by eteubert** [comment]
If you don't use the Podlove Subscribe Button, no third party files are fetched.
You can ensure that by disabling the "Subscribe Button" module in "Podlove > Modules".

**Comment by ilf** [comment]
Thanks, that's at least an option to disable cross-domain-content.

Would it also be possible to disable all cross-domain-content by default? Those files can also be delivered from the local Wordpress instance with the plugin, no?

**Comment by eteubert** [comment]
The button is CDN-hosted and not delivered with the Publisher plugin. If you like, you can host the button yourself. See https://github.com/podlove/podlove-subscribe-button#self-hosted.

**Comment by ilf** [comment]
Thanks, but that still doesn't answer my two questions:

1. Why not deliver the button with the plugin by default?
2. If there is a valid reason to decide against [1], please disable the button by default.

**Comment by timpritlove** [comment]
1. The button is centrally hosted because it needs to be easily integrated and updated frequently
2. the button is not enabled by default

**Comment by eteubert** [comment]
I will close this since we prefer to leave it as it is for now, reasons stated above.

**Comment by eteubert** [comment]
Starting with Release 2.6 the button can now optionally be delivered locally.

**Comment by ilf** [comment]
Yay, thanks!
