### ISSUE TITLE
Problems with feed validation (Hueman Theme)

### ISSUE THREAD

**Issue by boderhamster** [podlove/podlove-publisher#856]
Hallo Leute,

ich benutze seit langem Podlove, doch als ich letztens mal wieder überlegt hatte wieder eine Episode für meinen Podcast zu produzieren, ist mir aufgefallen, dass mein Feed nicht mehr richtig funktioniert. (nerdmeetsyou.de) (nerdmeetsyou.de/feed/nmy/)

Ich kann es leider nicht mehr validieren. Siehe Bild.
Weil es scheinbar fehlerhaft ist, wurde deshalb mein Podcast auch bei iTunes schon rausgenommen.
Jetzt ist die Frage: Wisst ihr vielleicht, woran das liegen könnte, dass mein Feed nicht mehr funktioniert?
(Ich habe bereits versucht alle Plugins zu deaktivieren. Daran lag es wohl nicht.)

![unbenannt](https://cloud.githubusercontent.com/assets/8282516/17082527/2d160e3e-5182-11e6-990a-539731b2fa9d.PNG)

Website             http://nerdmeetsyou.de
PHP Version         5.4.45
WordPress Version   4.5.3
Publisher Version   2.3.12
Web Player Version  2.0.19
Twig Version        1.24.0
open_basedir        ok
curl Version        7.37.1
iconv               available
simplexml           ok
max_execution_time  180
upload_max_filesize 8M
memory_limit        256M
disable_classes     
disable_functions   
permalinks          ok (/%postname%/)
podlove_permalinks  ok
podcast_settings    ok
web_player          ok
podlove_cache       on
assets              
	mp3    audio/mpeg
	jpg    image/jpeg

0 errors
0 notices
Nice, Everything looks fine!

**Comment by eteubert** [comment]
Using http://castfeedvalidator.com/ I get:

> Error resolving feed address.
> http://nerdmeetsyou.de/feed/nmy
> Unable to do basic feed validation...(http://nerdmeetsyou.de/feed/nmy)
> This feed validated in 30.1541650295 seconds

Which suggests that your server takes longer than 30 seconds to render the feed. This can be solved in various ways:

- Limit the items in the feed (to, for example, 10)
- Update PHP to a version with better performance (5.6 or 7)
- upgrade your hosting package

**Comment by boderhamster** [comment]
Thanks for the help.
I changed to php 5.6
And also limited the feed size to 10.
But nothing changed.
I assume its not the speed of my hosting package. As it isn't that bad I think, and also it worked in the past without me adding episodes to the feed.

Is there anything else I could try?

Thanks again for the help.
yours
Dominik

**Comment by eteubert** [comment]
I can now fetch your feed in my browser with only 1 second of latency (from Japan, so this is more than acceptable).
http://castfeedvalidator.com/ validates within 17 seconds.

What is it that's not working for you now?

**Comment by boderhamster** [comment]
Hi eteubert,

thanks for helping me.
If I click on validating feed in backend it doesn't validate. Instead it shows the following error:
<img width="946" alt="bildschirmfoto 2016-07-27 um 21 29 27" src="https://cloud.githubusercontent.com/assets/8282516/17189335/4b8308a6-5441-11e6-9001-469dd6d1b1f1.png">

**Comment by eteubert** [comment]
Hi,

Just saw you're using the Hueman theme. I should include that in the support output. I remembered from another user that this theme is misbehaving and breaks all feeds. I reported it to them now: https://wordpress.org/support/topic/bug-reportrequest-please-dont-break-rss-feeds?replies=1#post-8743789

Until then, you could use a plugin like https://wordpress.org/support/plugin/code-snippets to add a fix:

```
remove_filter('feed_link', 'alx_feed_link', 10);
```

**Comment by boderhamster** [comment]
Hallo eteubert,

danke, dass dir das aufgefallen ist. Echt super nett, dass du dir das nochmal näher angeschaut hast.
Das mit dem einfügen des Codes über Code Snippet ist mir leider nicht gelungen.
Hoffe das wird einfach mit dem nächste Update des Themes behoben. Scheint ja kein größerer Fehler zu sein.

**Comment by eteubert** [comment]
Here's the Hueman issue: https://github.com/presscustomizr/hueman/issues/256
