### ISSUE TITLE
Feed with free AND protected podcasts

### ISSUE THREAD

**Issue by davidzack** [podlove/podlove-publisher#859]
Looking for some guidance on how to configure a feed. I'd like to have a single feed that protects certain podcasts.  I had first created multiple feeds:

http://mysite.com/feed/free
http://mysite.com/feed/premium

and protected the second feed.  But it looks like I can only assign the Podlove web player to one feed. 

Is it possible to have just a single feed:
http://mysite.com/feed/all-podcasts

which protects only some podcasts?  Perhaps by assigning categories to the podcasts?

**Comment by eteubert** [comment]
Hi David,

you may have more luck finding answers to your questions at https://community.podlove.org/. GitHub Issues are for bug reports only.

I can still give you some pointers here:

- Category based feeds: http://docs.podlove.org/podlove-publisher/guides/podcast-network.html#option-2-category-based-feeds
- An article on protected feeds in general: https://community.podlove.org/t/un-protected-feeds-publisher-weekly-9/610
