### ISSUE TITLE
Feed funktioniert nicht mehr

### ISSUE THREAD

**Issue by jandreher** [podlove/podlove-publisher#860]
Hi !

Unsere Podcast-Seite läuft von Anfang an mit Podlove. Vor drei Tagen, wir haben nichts aktualisiert, keine neue Folge eingestellt und nichts geändert, können keine Eppisoden mehr angehört oder geladen werden. Scheinbar funktioniert die Feed-Validierung unseres Feeds

http://psychcast.de/feed/mp3/

nicht mehr. 
Wir haben bereits das neueste Podlove-publisher per FTP in unsere Wordpress Installation geladen und alles mögliche versucht, aber ohne Erfolg. Wo liegt der Fehler, was können wir machen?
![voila_capture 2016-08-07_11-39-04_pm](https://cloud.githubusercontent.com/assets/20893114/17465476/2e19bce6-5cf8-11e6-960d-34cf7e9e9496.png)

**Comment by eteubert** [comment]
Bitte http://castfeedvalidator.com/ benutzen, der eingebaute Validator ist leider nicht verlässlich. Den wollte ich schon lange mal entfernen.

Laut castfeedvalidator ist alles in Ordnung und er zeigt auch korrekte Episoden an.

**Comment by jandreher** [comment]
Hi!
Ja, das stimmt, auch castfeedvalidator stellt keinen Fehler des feeds fest. Dennoch ist es weiterhin unmöglich, eine Episode im Podlove-Player zu hören oder als Datei zu laden, auch iTunes und andere Podfetcher laden keine Episoden mehr. Mit dem Webhoster scheint es auch keine Probleme zu geben. Über FTP geladene Episoden kann man hören.
Hast Du eine Idee, woran es noch liegen könnte? Wir sind ziemlich verzweifelt und kriegen die Seite im Moment seit zwei Tagen einfach nicht mehr ans laufen...!

**Comment by eteubert** [comment]
Hilft es, Analytics auszuschalten?

**Comment by jandreher** [comment]
Hi !
Vielen Dank für Deine Hilfe! Habe das Google-analytics Plugin deaktiviert. Nach Browserneustart keine Änderung; audiofeeds sind weiterhin nicht ladbar. 
Andere Optionen?
jan

Am 11. August 2016 um 13:21 schrieb Eric Teubert <notifications@github.com>:

Hilft es, Analytics auszuschalten?

**Comment by eteubert** [comment]
Sorry, ich meinte Podlove Analytics :) Das geht in Podlove > Expert Settings > Tracking.

**Comment by jandreher** [comment]
Hi Eric!
WOW! Das hat funktioniert! Ich habe unter Podlove > Expert Settings > Tracking das Tracking auf Disabled gestellt, und nun klappt es wieder! Das ist großartig ! Vielen Dank für Deine erfolgreiche Hilfe! 
Gibt das einen Hinweis auf die Ursache des Fehlers, oder lassen wir das Tracking jetzt in Zukunft einfach aus?
Dankbarste Grüße,
Dein Jan

Am 11. August 2016 um 15:49 schrieb Eric Teubert <notifications@github.com>:

Sorry, ich meinte Podlove Analytics :) Das geht in Podlove > Expert Settings > Tracking.

**Comment by eteubert** [comment]
Ich habe eine Vermutung. Lass das Tracking erst mal aus bis das nächste Publisher Update kommt. Versuch's dann noch mal anzustellen.

**Comment by jandreher** [comment]
OK, machen wir gerne! Danke vielmals nochmal!
jan

Dr. Jan Dreher
