### ISSUE TITLE
Excerpt für den Posttype Episode

### ISSUE THREAD

**Issue by different-thinking** [podlove/podlove-publisher#861]
Guten Morgen,

ich versuche gerade dem Podlove Post Type "Episode" einen Excerpt zu verpassen. Ich habe als Vorlage eine Plugin genommen, was dem Page Post Type einen Excerpt (https://de.wordpress.org/plugins/page-excerpt/) spendiert und den Code geändert:

`<?php
/*
*/

add_action( 'edit_episode_form', 'pe_add_box');
add_action('init', 'pe_init');

function pe_init() {
	if(function_exists("add_post_type_support")) //support 3.1 and greater
	{
		add_post_type_support( 'episode', 'excerpt' );
	}
}

function pe_episode_excerpt_meta_box($post) {
?>
<label class="hidden" for="excerpt"><?php _e('Excerpt') ?></label><textarea rows="1" cols="40" name="excerpt" tabindex="6" id="excerpt"><?php echo $post->post_excerpt ?></textarea>
<p><?php _e('Excerpts are optional hand-crafted summaries of your content. You can <a href="http://codex.wordpress.org/Template_Tags/the_excerpt" target="_blank">use them in your template</a>'); ?></p>
<?php
}

function pe_add_box()
{
	if(!function_exists("add_post_type_support")) //legacy
	{		add_meta_box('postexcerpt', __('Episode Excerpt'), 'pe_episode_excerpt_meta_box', 'episode', 'advanced', 'core');
	}
}`

Leider funktioniert das nicht. Es gibt keine Excerpt-Box, wenn ich eine Episode editiere.

Ich brauche das für ein Plugin, welches mir eine Übersicht der Posts wunderhübsch aufbereitet.

Was mach ich falsch?

robert

**Comment by eteubert** [comment]
Excerpts müssen für den Post Type aktiviert werden:

```
add_filter('podlove_post_type_args', function($args) {
	$args['supports'][] = 'excerpt';
	return $args;
});
```
