### ISSUE TITLE
Maybe a fallback without flash is more usefull

### ISSUE THREAD

**Issue by vasilisvg** [podlove/podlove-publisher#864]
I noticed that a fallback with Flash is generated when an audio file is served with MP3. [Support for MP3 nowadays is great](http://caniuse.com/#search=mp3). The only browsers that don’t support MP3 are Opera Mini and IE8, and these browsers also [don’t support the audio element](http://caniuse.com/#feat=audio). 
I think today a more sensible and a more safe fallback would be to offer a simple download link instead. The code in [lib>modules>podlove_web_player>player_v3>html5printer](https://github.com/podlove/podlove-publisher/blob/master/lib/modules/podlove_web_player/player_v3/html5printer.php#L61) would have to be slightly adjusted to fix this. From line 61 on it would now read this:

``` PHP
$flash_fallback_func = function(&$xml) use ($file) {
    $flash_fallback = $xml->addChild('a','Download this episode');
    $flash_fallback->addAttribute('href', $file['url']);
};
```

As a detail, an optional line for non-english people can be added.

``` PHP
$flash_fallback->addAttribute('lang', 'en');
```

**Comment by eteubert** [comment]
I agree with you, however the PWP3 is deprecated and this is so far down the priority list that it's likely to never be implemented.
