### ISSUE TITLE
Authorization mit Auphonic funktioniert nicht

### ISSUE THREAD

**Issue by Matth3s** [podlove/podlove-publisher#867]
Ich hab Podlove 2.3.17 auf einem Wordpress 4.6.1 laufen. Wenn ich Auphonic aktiviere und anschließend auf "Authorize now" klicke, werde ich zwar zu Auphonic weitergeleite, aber wenn ich anschließend auf "Allow" (auf der Webseite von Auphonics) komme ich zu meiner Wordpress Instanz und Auphonic ist nicht autorisiert.

Im Log steht zwar das es aktiviert wurde, ich kann aber nicht in Podlove darauf zugreifen.
Ist das ein Bug der aktuellen Version oder sitzt der Bug vor de Rechner?

**Comment by eteubert** [comment]
Wir hatten ein https-Problem auf dem Auth-Server. Sollte seit einiger Zeit wieder funktionieren. Falls nicht, bitte Issue wieder öffnen.
