### ISSUE TITLE
Can't find file (capital letter / lowercase letter)

### ISSUE THREAD

**Issue by Inrumpo** [podlove/podlove-publisher#869]
I just found that Podlove will not be able to find a podcast file if the capital / lowercase letters don't match those on the FTP server. That's tedious.

Example:
File on server is called `GT033-2016-09-27.m4a`.
If I enter the `Episode Media File Slug` like this: `gt033-2016-09-27` the file will not be found. `GT033-2016-09-27` works fine.

**Comment by timpritlove** [comment]
That's how the Web work since the beginning. It's not "Podlove" that does this, it's how web servers work for 25 years now.
