### ISSUE TITLE
https episode feed

### ISSUE THREAD

**Issue by shasycouk** [podlove/podlove-publisher#871]
Hey everyone,

thanks for this amazing plugin!

I am hosting my wordpress on SSL only and I am using the statistic tool. However, the feed does not validate because it's a https url to the episodes - can I change that somewhere? My nginx settings would redirect the http request to https either way, but at least the feed won't have a problem.

I have changed my wordpress installation to http (since it redirects it to https either way; dirty fix!) but the episodes are still linked to https://. Is this maybe a fixed variable somewhere in podlove now since when I've installed the plugin, my wordpress URL was https?

I did everything: Change the podlove url to http, the wordpress url to http, deleted the episode and the feed, recreated both, both are still linked as https.

I guess that's the reason why iTunes is also not able to read my feed.

Best,
Benedikt

**Comment by shasycouk** [comment]
Alright, case closed. It's most probably my Let's Encrypt Certificate that iTunes won't accept (see https://itunespartner.apple.com/en/podcasts/news/19855810 and https://community.letsencrypt.org/t/itunes-rejecting-le-certs/11486/4). Don't really want to change the certificate right now, so looking for a solution!

**Comment by eteubert** [comment]
Yes, the culprit here it iTunes for rejecting Lets Encrypt.

We are planning to add options to the Publisher to force http for feeds.

> I have changed my wordpress installation to http (since it redirects it to https either way; dirty fix!) but the episodes are still linked to https://.

Maybe Caching? Try Podlove > Support > Repair to clear the cache.

**Comment by shasycouk** [comment]
> Maybe Caching? Try Podlove > Support > Repair to clear the cache.

Nope, does not work. All parameters are changed to http (wordpress & site address) but yet the Publisher puts the https links in the feed.

> We are planning to add options to the Publisher to force http for feeds.

sounds good! Can't wait for it 👍

**Comment by shasycouk** [comment]
Got myself a cheap Comodo certificate, so iTunes works fine now. Thanks a lot, and hopefully I will be able to go back to Let's Encrypt next year.

**Comment by shasycouk** [comment]
Got myself a cheap Comodo certificate, so iTunes works fine now. Thanks a lot, and hopefully I will be able to go back to Let's Encrypt next year.
