### ISSUE TITLE
Referenzierung auf episode slug in shortcode nicht wirksam

### ISSUE THREAD

**Issue by ducatimaus** [podlove/podlove-publisher#872]
Ich versuche auf einer Seite einen Player für eine Episode aufzurufen, wie hier beschrieben:
[https://github.com/podlove/podlove-publisher/issues/673#issuecomment-76331184](https://github.com/podlove/podlove-publisher/issues/673#issuecomment-76331184)
Leider geht das nicht wie beschrieben. Wenn ich meinen episode slug direkt ins Template _episode-player_ eingebe, funktioniert es:
`{{ podcast.episodes({slug: 'ep022'}).player }}`

Der shortcode auf der Seite sieht dann so aus:
`[podlove-template id="episode-player"]`

Wenn ich versuche, den slug wie beschrieben beim Aufruf per shortcode in der Seite mitzugeben, also per:
`[podlove-template id="episode-player" slug="ep022"]`
(im Template steht dann `{{ podcast.episodes({slug: slug}).player }}` )
erscheint gar kein Player.

**Comment by eteubert** [comment]
Template Shortcode Parameter sind in einem `options` Objekt, siehe http://docs.podlove.org/podlove-publisher/guides/understanding-templates.html#shortcode-options.

D.h. das sollte funktionieren:

```
[podlove-template id="episode-player" slug="ep022"]
```
```
{{ podcast.episodes({slug: option.slug}).player }}
```

**Comment by ducatimaus** [comment]
Funktioniert! Vielen Dank!
