### ISSUE TITLE
Darstellung von episode.content / episode.summary ohne Zeilenumbrüche

### ISSUE THREAD

**Issue by ducatimaus** [podlove/podlove-publisher#873]
Wenn ich über Templates Texte aus den Episoden mit {{ episode.summary }} und {{ episode.content }} einbinde, werden die Zeilenumbrüche ignoriert und die Infotexte somit falsch formatiert.

**Comment by timpritlove** [comment]
Probier mal `{{ episode.summary|nl2br }}`. Ansonsten ist das hier kein Supportsystem. Bitte auf https://community.podlove.org/ weiterfragen

**Comment by ducatimaus** [comment]
Hallo Tim,

On 10/10/16 3:48 PM, Tim Pritlove wrote:
>
> Probier mal |{{ episode.summary|nl2br }}|.
>
Vielen Dank! Die Zeilenumbrüche funktionieren damit, allerdings werden
Links im Content Feld nun als html Quelltext dargestellt, also so:
<a href="http://wordpress.p116814.webspaceconfig.de/?p=1172">Link zum in
der Predigt erwähnten Strategiepapier</a>

> Ansonsten ist das hier kein Supportsystem. Bitte auf
> https://community.podlove.org/ weiterfragen
>
Ich hatte dort vor Tagen ein Thema dazu eröffnet. Da überhaupt kein
Feedback kam, und ich auch unter
http://docs.podlove.org/podlove-publisher/reference/template-tags
keine weiteren Infos gefunden habe, ging ich davon aus, dass es sich um
einen Bug handelt.

|nl2br| ist doch eine PHP Funktion nicht? Lt. php.net macht diese aus
Text-Zeilenumbrüchen HTML-Zeilenumbrüche. Wenn hier also HTML
berücksichtigt wird, verwundert es mich um so mehr, dass der Link oben
nicht korrekt dargestellt wird. Kannst Du Dir das erklären?

LG
Lilly

**Comment by ducatimaus** [comment]
Das hat leider den Link nicht zurecht gezaubert. Dass wir da Links haben und somit HTL benötigen ist eigentlich eher eine Ausnahme, im Summary Feld kommt das gar nicht vor.
Danke trotzdem!
