### ISSUE TITLE
Cannot validate Feed (error 60)

### ISSUE THREAD

**Issue by boderhamster** [podlove/podlove-publisher#874]
Hi Guys,

thanks again for helping to find the bug with my feed when using the Hueman Theme. The developers of the theme fixed the bug in the next update.
So now i tried to reactivate my podcast project as my feed seemed to be working. But right after adding a new episode, I'm unable to validate the feed.
The following error shows when I'm trying:
"Unable to download image. cURL error 60: SSL certificate problem: self signed certificate." 
Can you tell me, what this means? Or how I could fix this. 

Thanks again for all the help I got from you guys until now!
I tried to add all the needed information below.

 [2016-10-13 10:06:02] Validate episode Was bedeutet Ubisofts Geburtstagsvideo für den Videospiele-Journalismus?
[NMY Talk – Folge 1]	
[2016-10-13 10:06:02] Begin scheduled asset validation.
[2016-10-13 09:06:09] End scheduled asset validation.
[2016-10-13 09:06:09] Begin scheduled asset validation.
[2016-10-13 08:49:10] Unable to download image. cURL error 60: SSL certificate problem: self signed certificate. 

Website             http://nerdmeetsyou.de
PHP Version         5.6.12
WordPress Version   4.6.1
WordPress Theme     Hueman v3.2.9
Publisher Version   2.3.18
Web Player Version  2.0.19
Twig Version        1.24.2
open_basedir        ok
curl Version        7.37.1
iconv               available
simplexml           ok
max_execution_time  180
upload_max_filesize 8M
memory_limit        256M
disable_classes     
disable_functions   
permalinks          ok (/%postname%/)
podlove_permalinks  ok
podcast_settings    ok
web_player          ok
podlove_cache       on
assets              
  - mp3    audio/mpeg http://nerdmeetsyou.de/feed/nmy/
  - jpg    image/jpeg no feed

0 errors
0 notices
Nice, Everything looks fine!

**Comment by eteubert** [comment]
Your feed looks flawless http://castfeedvalidator.com/?url=http://nerdmeetsyou.de/feed/nmy/

Please only report bugs here. For support, use http://publisher.podlove.org/support/ or https://community.podlove.org/c/podlove-publisher. Thank you.
