### ISSUE TITLE
Change iframe of Webplayer v3 to 100%?

### ISSUE THREAD

**Issue by TheLux83** [podlove/podlove-publisher#875]
Hey there,

I'm trying to implement Podlove-Publisher to our website, but I have a problem with the webplayer.
As you can see in this picture, the iframe of the player uses a width of 104%
![2016-10-17 16_48_35-neue benachrichtigung](https://cloud.githubusercontent.com/assets/20551716/19442555/f5bf044a-9489-11e6-85ee-eda554322549.jpg)

I don't know why and I don't know how to change it. Is this a bug, or a feature? ;) 
Do you know how I can change it?

**Comment by eteubert** [comment]
Not sure. I checked another site (http://www.radionukular.de/ankuendigung-tourtagebuch-im-autokino/) with the player in Chrome, Safari and FF and the width there is always 100%.

You could try switching to a default theme to find out if your theme is responsive.

**Comment by TheLux83** [comment]
Hey @eteubert,
Thanks for the suggestion. I've tried a standard theme and as you said. The iframe has a width of 100%.
But now I don't know why my theme is creating a width of 104% for an iframe of a plugin o.O

**Comment by TheLux83** [comment]
I've used a little CSS Hack to get the width back to 100%
I've used my normal CSS file and inserted 
.podlove-player-wrapper code iframe {
		width:100% !important;
}
It's quick and dirty but for the moment, it's okay.

Thanks for your help @eteubert!

**Comment by eteubert** [comment]
I'm also not sure how this can happen. But I'm happy you found a solution :)
