### ISSUE TITLE
Sending Trackbacks to URLs from within the PSC-file (Chapters)

### ISSUE THREAD

**Issue by OleAlbers** [podlove/podlove-publisher#877]
It would be nice if the URLs that are within the chapter-file would create a Trackback/Pingback to that URLs.

Reason: We (like a lot of other podcasts) talk about stuff that was mentioned in another podcast. It would be nice if a standard-Wordpress Trackback would be created OR these URLs just appear inside the "Trackback"-Filed of the current episode

**Comment by OleAlbers** [comment]
An alternative could be that the chapters information are displayed in the episodes description which sould then trigger wordpress itself to send a pingback

**Comment by OleAlbers** [comment]
Ok. I was to impatient. Created a WordPress-PlugIn for that purpose myself:
https://github.com/OleAlbers/psc

Anybody feel free to use it :)

**Comment by eteubert** [comment]
Thanks for sharing your plugin with everyone :)
