### ISSUE TITLE
Adding Claim-Codes for Fyyd Podcast search into RSS-Feed

### ISSUE THREAD

**Issue by bitnapper** [podlove/podlove-publisher#880]
It would be nice to have an option to add a claiming code from the [fyyd podcast searchengine](https://fyyd.de/) into ones RSS-Feed. 

Example:
`<fyyd:verify xmlns:fyyd="https://fyyd.de/fyyd-ns/">auWqos76gbs1lmdpshd525hDoUocdPu1c7Yqzxm</fyyd:verify>`

**Comment by eteubert** [comment]
That module already exists [in the 2.4 beta](https://github.com/podlove/podlove-publisher/blob/release-2-4-0/readme.txt#L167).

**Comment by bitnapper** [comment]
Cool. Thx.
