### ISSUE TITLE
Plugin gone?

### ISSUE THREAD

**Issue by mburn0403** [podlove/podlove-publisher#886]
### Expected behavior
Update to 2.4 
### Actual behavior
After update the plugin is no longer present in the web interface
not even under "installed plugins"

is there a easy fix - otherwise i have to go back to a backup

**Comment by eteubert** [comment]
Download zip from https://wordpress.org/plugins/podlove-podcasting-plugin-for-wordpress/ and upload either via FTP or "Install Plugin" interface.

Not sure what went wrong there but data shouldn't be affected. I don't think you need to use that backup.

**Comment by mburn0403** [comment]
did not work - using the backup - not sure what went wrong either

**Comment by mburn0403** [comment]
done - backup works - closing issue

**Comment by eteubert** [comment]
Thanks for following up 👍
