### ISSUE TITLE
episode.publicationDate returns date twice

### ISSUE THREAD

**Issue by oliverlampert** [podlove/podlove-publisher#887]
### Expected behavior
Using episode.publicationDate within podlove templates should return date only once.
for example: 20. November 2016 Sonntag

### Actual behavior
episode.publicationDate returns date twice:
example: 20. November 2016 Sonntag, 20. November 2016 

Can be reproduced by using Standard-Tag:
`[podlove-episode-list]`

Or Template Code snippet:
`{% for episode in podcast.episodes %}
                    {{ episode.publicationDate }}
    {% endfor %}
`
 
Example on GUI:
[http://katharina-dill.de](url)
column: "Datum"

### System information
Website             http://katharina-dill.de
PHP Version         5.6.27
WordPress Version   4.4.2
WordPress Theme     Rosemary v1.2
Publisher Version   2.4.0
Web Player Version  no web player found
Twig Version        1.28.1
open_basedir        ok
curl Version        7.50.3
iconv               available
simplexml           ok
max_execution_time  0
upload_max_filesize 32M
memory_limit        256M
disable_classes     
disable_functions   
permalinks          ok (/%year%/%monthnum%/%postname%/)
podlove_permalinks  ok
podcast_settings    ok
web_player          ok
podlove_cache       on
assets              
  - mp3    audio/mpeg http://katharina-dill.de/feed/mp3/
cron                ok

0 errors
0 notices
Nice, Everything looks fine!

**Comment by eteubert** [comment]
Please check the Date/Time Settings in Settings / General:

<img width="838" alt="screen_shot_2016-12-08_at_12_03_18" src="https://cloud.githubusercontent.com/assets/235918/20997207/69d50bcc-bd3e-11e6-84b4-92bd99ba88b5.png">

**Comment by oliverlampert** [comment]
Thank you very much! There was a strange adjusted time format of wordpress settings that lead to it.

**Comment by eteubert** [comment]
Glad I could help :)
