### ISSUE TITLE
Make Transcripts available

### ISSUE THREAD

**Issue by mburn0403** [podlove/podlove-publisher#888]
### Feature Request
Make transcripts available to tick in the _Expert Settings -> Web Player_ menue for Podigee Web Player
### Example
As seen here, scroll to Example 1: https://auphonic.com/blog/2016/12/02/make-podcasts-searchable-speech-to-text/

**Comment by eteubert** [comment]
Please use https://community.podlove.org/c/podlove-publisher for feature requests (but it's already on my todo list :)).
