### ISSUE TITLE
[Request] Advanced configuraton for Podigee Podcast Player

### ISSUE THREAD

**Issue by Inrumpo** [podlove/podlove-publisher#890]
2.4 introduced the (very nice) Podigee Podcast Player. Thanks for that!

Unfortunately, configuration options are very limited. But: The Podigee team [already offers advanced configuration options](https://www.podigee.com/changelog/podigee-podcast-player-advanced-configuration).

**My request:**
Please make those available for Podlove users too.

**Comment by eteubert** [comment]
Please use the forums (https://community.podlove.org) for feature requests. Github should be used for bugs only.
