### ISSUE TITLE
Podlove-Player 2.1 gives incorrect links to timestamps

### ISSUE THREAD

**Issue by dieterbethke** [podlove/podlove-publisher#892]
### Expected behavior
When creating a share-link, it should look like this:
http://fotophonie.de/fotophonie-070-hello-again/?t=19:51.548

### Actual behavior
But all i get is this:
http://fotophonie.de/fotophonie-070-hello-again/%23t%3D19:51.5483

There seems to be a problem with encoding of "/?t="

### System information (see `Podlove > Support` menu)

Website http://fotophonie.de1
PHP Version 5.5.38-nmm2
WordPress Version 4.6.1
WordPress Theme Twenty Twelve v2.1
Publisher Version 2.4.0
Web Player Version 2.1.0
Twig Version 1.28.1
open_basedir ok
curl Version 7.22.0
iconv available
simplexml ok
max_execution_time 300
upload_max_filesize 200M
memory_limit 268435456
disable_classes 
disable_functions 
permalinks ok (/%postname%/)
podlove_permalinks ok
podcast_settings ok
web_player ok
podlove_cache on
assets 
- mp3 audio/mpeg http://fotophonie.de/feed/mp3/
- m4a audio/mp4 http://fotophonie.de/feed/m4a/
- ogg audio/ogg http://fotophonie.de/feed/ogg/
- opus audio/ogg;codecs=opushttp://fotophonie.de/feed/opus/
- psc application/xmlno feed
- chapters.txttext/plain no feed
- jpg image/jpeg no feed
- json application/jsonno feed
cron ok

0 errors
0 notices
Nice, Everything looks fine!

**Comment by timpritlove** [comment]
Yes, it's a long standing bug and should be fixed asap. Thanks for reporting.

**Comment by dieterbethke** [comment]
Thanks for ACK. Any idea how long it will take to fix it ASAP?
Is it a good idea to patch the file podlove-web-player.min.js on my own in the meantime, as a hotfix?

**Comment by timpritlove** [comment]
If you can do a patch, please consider submitting it as a pull request against this repo: https://github.com/podlove/podlove-web-player/commits/version-2.x-master (this issue is actually in the wrong repo and should probably be moved)
