### ISSUE TITLE
Fatal error when opening backend - somewhere in lib/settings/podcast.php

### ISSUE THREAD

**Issue by Hossi81** [podlove/podlove-publisher#893]
### Expected behavior

Entering backend via .../wp-admin should work.

### Actual behavior

Error Message: "Fatal error: Call to undefined function Podlove\Settings\register_setting() in /www/htdocs/w01400c7/follow-up.fm/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/lib/settings/podcast.php on line 35"

### System information (see `Podlove > Support` menu)

Can't access the menu right now - I suspect there is some interaction with W3 total cache. That crashed and I had to delete it completely. My front end is now working again. At least that works :)

**Comment by timpritlove** [comment]
Looks like some misconfiguration of your web server. Please check you have the right components installed. 

Closing this as GitHub is for bug reports and code fixes only. Please turn to https://community.podlove.org/ for help or professional support at https://publisher.podlove.org/
