### ISSUE TITLE
Podlove Web Player 2 doesn't work - infinite loading

### ISSUE THREAD

**Issue by koeniglicher** [podlove/podlove-publisher#896]
### Expected behavior
Hi,

I reinstalled Wordpress and PodLove-Publisher and PodLove-Web-Player.
Since now, the player seems to buffer infinitly. The Error appears in every episode.

http://vomwindeverwirrt.de/vom-winde-verwirrt-episode-1-9-weihnachtscast/
http://vomwindeverwirrt.de/vom-winde-verwirrt-episode-1-8-info-der-infocast/
http://vomwindeverwirrt.de/vom-winde-verwirrt-episode-1-7-konzertliebe/

If you use the direct link to the mp3-file (vomwindeverwirrt.de/PodcastUpload/VWV9.mp3) it works. 

Also the Download button doesnt work and the duration detection throws error 3.

I am new to the PodLove Plugin and maybe I made a simple mistake in the options or the installation.

Could anybody just give me support, tips or help? Thank you

Regards,
Kay

### System information (see `Podlove > Support` menu)

> Website             http://vomwindeverwirrt.de
> PHP Version         5.6.29-nmm1
> WordPress Version   4.7
> WordPress Theme     Verbosa v0.9.7
> Publisher Version   2.4.0
> Web Player Version  2.1.0
> Twig Version        1.28.1
> open_basedir        ok
> curl Version        7.35.0
> iconv               available
> simplexml           ok
> max_execution_time  30
> upload_max_filesize 200M
> memory_limit        256M
> disable_classes     
> disable_functions   
> permalinks          ok (/%postname%/)
> podlove_permalinks  ok
> podcast_settings    ok
> web_player          ok
> podlove_cache       on
> assets              
>   - mp3    audio/mpeg http://vomwindeverwirrt.de/feed/mp3/
> cron                ok
> 
> 0 errors
> 0 notices
> Nice, Everything looks fine!

**Comment by timpritlove** [comment]
The URL that is accessed is `http://vomwindeverwirrt.de/vom-winde-verwirrt-episode-1-7-konzertliebe/vomwindeverwirrt.de/PodcastUpload/VWV7.mp3` so it looks you have failed to provide a proper protocol when entering the media file base. Please add "http://" to it.

Also, we do not use GitHub for support. Please report future problems at https://community.podlove.org/
