### ISSUE TITLE
Analytics All Time / Last Month not working

### ISSUE THREAD

**Issue by meszner** [podlove/podlove-publisher#897]
### Expected and actual behavior
Analytics worked just fine, but since February the numbers for January are gone. 
<img width="249" alt="bildschirmfoto 2017-02-02 um 16 09 04" src="https://cloud.githubusercontent.com/assets/3786431/22554863/fc73fad4-e961-11e6-812c-d031832f23ea.png">
At the same time, the total number of downloads decreased by the January figures.

But the analytics for single episodes and the chart are still working and presenting the expected figures. 
Do you know what the problem might be?

Daniel

### System information (see `Podlove > Support` menu)
Website             http://www.zeitsprung.fm
PHP Version         5.5.9-1ubuntu4.20
WordPress Version   4.7.2
WordPress Theme     Fruitful v3.3.1
Publisher Version   2.4.1
Web Player Version  no web player found
Twig Version        1.30.0
open_basedir        ok
curl Version        7.35.0
iconv               available
simplexml           ok
max_execution_time  30
upload_max_filesize 100M
memory_limit        256M
disable_classes     
disable_functions   pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,
permalinks          ok (/%postname%/)
podlove_permalinks  ok
podcast_settings    ok
web_player          ok
podlove_cache       on
assets              
  - mp3    audio/mpeg http://www.zeitsprung.fm/feed/mp3/
  - m4a    audio/mp4  http://www.zeitsprung.fm/feed/mp4/
  - ogg    audio/ogg  http://www.zeitsprung.fm/feed/ogg/
cron                ok

0 errors
0 notices
Nice, Everything looks fine!

**Comment by eteubert** [comment]
Should be fixed in 2.4.2.
