### ISSUE TITLE
Normal characters become encoded

### ISSUE THREAD

**Issue by defycgn** [podlove/podlove-publisher#898]
### Expected behavior
Title of the episode link in Facebook should be "17x01 - Thema".

### Actual behavior
If you copy the link to facebook it becomes: "17&#215;01 &#8211; Thema"

We guess the problem is that the normal characters e.g. 'x' becomes html encoded ('×'). 

### System information (see `Podlove > Support` menu)

PHP Version         7.0.13-0ubuntu0.16.04.1
WordPress Version   4.7.2
WordPress Theme     Sparkling v2.3.2
Publisher Version   2.4.3
Web Player Version  2.1.1
Twig Version        1.30.0
open_basedir        ok
curl Version        7.47.0
iconv               available
simplexml           ok
max_execution_time  30
upload_max_filesize 2M
memory_limit        256M
disable_classes     
disable_functions   pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wifcontinued,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,
permalinks          ok (/%postname%/)
podlove_permalinks  ok
podcast_settings    ok
web_player          ok
podlove_cache       on

Tested using open graph enabled and disabled.

**Comment by eteubert** [comment]
Please provide your website so I can look at the live data.

**Comment by defycgn** [comment]
https://serienrepublik.de

Tim Hartung



Viele Grüße, 
Tim Hartung
- mobil -

**Comment by defycgn** [comment]
Ich habe inzwischen festgestellt, dass man hier auch Deutsch schreiben kann. :) Das Problem der Umkodierung tritt immer auf, wenn jemand ein Episodenposting mit z. B. einem Bindestrich beinhaltend bei Facebook verlinkt. Ist also kein Problem, das nur wir haben.

**Comment by defycgn** [comment]
Gibr es bereits Lösungsansätze dazu?

**Comment by eteubert** [comment]
Ich vermute dass es am Theme oder einem Plugin liegt. Hier siehst du dass an einer anderen Stelle im Publisher (Widget) der Titel "normal" ist, aber sogar der Episoden-Titel im Artikel, der von WordPress bzw. vom Theme kommt, in Sonderzeichen gesetzt ist.

Sollte leicht zu prüfen sein indem du kurz ein Standardtheme wie twentysixteen aktivierst.

![sonderzeichen](https://cloud.githubusercontent.com/assets/235918/22855531/ab361c44-f0bc-11e6-8b6c-a7c5b408e654.png)

**Comment by oglimmer** [comment]
I reproduced the issue with a default installation of wordpress and the podlove-publisher plugin.

```
Setup Ubuntu 16.04.1

Log in as root to server and execute:

  * apt-get install apache2 php-mysql libapache2-mod-php python-pip
  * apt-get install mysql-server python-mysqldb
  * mysql
  * apt-get install libao-common libao4 libcurl3-gnutls libflac8 libgd3 libjbig0 libjpeg-turbo8 libjpeg8 * ogg0   libphp-phpmailer librtmp1 libspeex1 libtiff5 libvorbis0a libvorbisenc2 libvorbisfile3 libvpx3 * x11-6   libx11-data libxau6 libxcb1 libxdmcp6 libxpm4 vorbis-tools unzip tar gzip php-curl php-xml php-gd * -getid3 php-twig php-mbstring
  * cd /var/www/
  * curl "https://wordpress.org/latest.tar.gz" >latest.tar.gz
  * gzip -d latest.tar.gz 
  * tar xf latest.tar 
  * rm latest.tar 
  * chown -R www-data:www-data wordpress/
  * vi /etc/apache2/sites-enabled/000-default.conf (change the DocumentRoot to /var/www/wordpress)
  * service apache2 restart
  * mysql -uroot -p
    # create database wordpress;
    # create user wordpress identified by 'wordpress';
    # grant all on wordpress.* to wordpress@'%';

Visit your server at port 80

- install wordpress with mysql user 'wordpress' / pass: wordpress
- Install wordpress plugin `Podlove Podcast Publisher` and activate it
- Create an episode with the title `17x01 - The first test` and publish it

=> while the title in the admin area is still shown as `17x01 - The first test`, the index.php shows it as `17×01 – The first test` (the x and the - are replaced)
```

**Comment by eteubert** [comment]
After some digging: It's a native WordPress functionality called [wptexturize](https://codex.wordpress.org/Function_Reference/wptexturize) and it's applied automatically to all titles.

You can deactivate it globally with a snippet like this:

```php
add_action('init', function () {
	remove_filter('the_title', 'wptexturize');
});
```

Please read the documentation though because it does much more than just the "x".
