### ISSUE TITLE
Support upper case and lower case file suffix

### ISSUE THREAD

**Issue by koko-joe** [podlove/podlove-publisher#899]
Hi, I am trying to migrate our old blog/podcast to Podlove.
Some of our files have the suffix ".mp3" and some of them have the suffix ".MP3".
I can add all .mp3 to one feed and all .MP3 to another feed but I can't mix them.
Reuploading files isn't an option because we only have a limited upload volume per month.
If the demand for this feature is too low and/or the implementation would be too complex I will probably find a warkaround for this.

**Comment by eteubert** [comment]
Maybe you can ask your host to rename all extensions to `.mp3`?

I don't think the Publisher will ever support a case like this. It wouldn't be trivial so support.
