### ISSUE TITLE
Analytics stopped displaying numbers for specific time-frames

### ISSUE THREAD

**Issue by stormgrass** [podlove/podlove-publisher#901]
### Expected behavior

Display of download numbers per episode for specific time-frames.

### Actual behavior

Numbers stopped being displayed for specific time-frames, total numbers are displayed only.
![screenshotanalytics](https://cloud.githubusercontent.com/assets/16881520/23945637/87f36d4e-0977-11e7-8ad7-103cb12e54cb.png)

### System information (see `Podlove > Support` menu)

```
Website             http://www.zeitsprung.fm
PHP Version         5.5.9-1ubuntu4.20
WordPress Version   4.7.3
WordPress Theme     Fruitful v3.3.1
Publisher Version   2.4.7
Web Player Version  no web player found
Twig Version        1.30.0
open_basedir        ok
curl Version        7.35.0
iconv               available
simplexml           ok
max_execution_time  30
upload_max_filesize 100M
memory_limit        256M
disable_classes     
disable_functions   pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,
permalinks          ok (/%postname%/)
podlove_permalinks  ok
podcast_settings    ok
web_player          ok
podlove_cache       on
assets              
  - mp3    audio/mpeg http://www.zeitsprung.fm/feed/mp3/
  - m4a    audio/mp4  http://www.zeitsprung.fm/feed/mp4/
  - ogg    audio/ogg  http://www.zeitsprung.fm/feed/ogg/
cron                ok

0 errors
0 notices
Nice, Everything looks fine!

```

**Comment by eteubert** [comment]
Go to "Podlove > Tools" and check if your background jobs/crons work properly ("Run WP Cron Diagnostics" button).

**Comment by stormgrass** [comment]
Cron seems to be running properly.
![cronanalytics](https://cloud.githubusercontent.com/assets/16881520/23989249/14ac29dc-0a32-11e7-9633-c87dbf45c930.png)

**Comment by stormgrass** [comment]
_**Update:**_ For some reason, we're getting the daily/weekly/etc. numbers again. Maybe due to my checking whether cron services work? 

Anyway, I think the issue can be closed.
