### ISSUE TITLE
revisiting episodes changes "&" in new chapters UI

### ISSUE THREAD

**Issue by Inrumpo** [podlove/podlove-publisher#903]
This was introduced with the new chapters UI in `2.5`.

### Expected behavior

A chapter title with a `&` character in it should stay that way.

### Actual behavior

Revisiting the episode changes all `&` characters in chapter titles to `&amp;`.

### System information
```
Website             https://GameTalk.FM
PHP Version         5.6.30
WordPress Version   4.7.3
WordPress Theme     Joeys Twenty Fifteen Child v1.0
Publisher Version   2.5.0
Web Player Version  no web player found
Twig Version        1.32.0
open_basedir        ok
curl Version        7.36.0
iconv               available
simplexml           ok
max_execution_time  50
upload_max_filesize 150M
memory_limit        256M
disable_classes     
disable_functions   exec, shell_exec, system, dl, passthru, proc_open, proc_close
permalinks          ok (/%postname%/)
podlove_permalinks  ok
podcast_settings    ok
web_player          ok
podlove_cache       on
assets              
  - mp3    audio/mpeg https://GameTalk.FM/feed/mp3/
  - m4a    audio/mp4  https://GameTalk.FM/feed/m4a/
cron                ok

0 errors
0 notices
Nice, Everything looks fine!
```

**Comment by Inrumpo** [comment]
In addition: 
Importing a character such as `ä` turns it into a `�` during the import. (UTF-8 .txt)

On a side note:
The `URL Title`, used by mp4chaps, is not used in the new chapters UI.

**Comment by eteubert** [comment]
I fixed the `&` issue.

I can't reproduce `ä` turning to `�`. Importing Umlauts works for me. It might help if you could attach the txt you are using. Ideally in a separate issue since it's unrelated to the `&` issue.

> The URL Title, used by mp4chaps, is not used in the new chapters UI.

You are referring to the format Hindenburg is using, which is non-standard.

**Comment by Inrumpo** [comment]
Thanks for fixing this in 2.5.1. 
I have not been able to reproduce the Umlaut issue again. So it might be gone (or whatever). Thanks for your efforts!
