### ISSUE TITLE
After Update Podlove Podcast Publisher produces syntax error

### ISSUE THREAD

**Issue by netzfeuilleton** [podlove/podlove-publisher#905]
### Expected behavior
Should run as expected.
### Actual behavior
Parse error: syntax error, unexpected T_FUNCTION in .../wp-content/plugins/podlove-podcasting-plugin-for-wordpress/podlove.php on line 62
### System information (see `Podlove > Support` menu)
Run in a Werdpress MU Setup, on its on Subdomain, with Domainmapping.
Website             http://gucken-trinken.netzfeuilleton.de
PHP Version         5.4.45
WordPress Version   4.7.3
WordPress Theme     Tonal v1.1.2
Publisher Version   2.5.0
Web Player Version  no web player found
Twig Version        1.32.0
open_basedir        ok
curl Version        7.37.1
iconv               available
simplexml           ok
max_execution_time  180
upload_max_filesize 8M
memory_limit        256M
disable_classes     
disable_functions   
permalinks          ok (/%year%/%monthnum%/%day%/%postname%/)
podlove_permalinks  ok
podcast_settings    ok
web_player          ok
podlove_cache       on
assets              
  - mp3    audio/mpeg http://gucken-trinken.de/feed/mp3/
cron                ok
network module      ok

0 errors
0 notices
Nice, Everything looks fine!
<img width="1646" alt="bildschirmfoto 2017-03-28 um 19 18 41" src="https://cloud.githubusercontent.com/assets/10114998/24421724/7365baa0-13f7-11e7-8e8c-6da6b2806430.png">

**Comment by timpritlove** [comment]
Not sure what the problem is but you should really upgrade your PHP to at least version 5.6 (PHP 7 recommended).

**Comment by eteubert** [comment]
Are you sure this subdomain is using the same PHP version as the rest of your network? The syntax error would occur in a PHP 5.2 environment.

**Comment by netzfeuilleton** [comment]
You we're right, there we're two different versions of PHP AND it was about time to update PHP on the server. What a short visit to github gets you!
