### ISSUE TITLE
Tracking zeichnet nichts mehr auf / Tracking no longer records

### ISSUE THREAD

**Issue by Messa1** [podlove/podlove-publisher#906]
Da ich mir nicht sicher bin ob die Entwickler Deutsch oder Englisch sprechen habe ich es in beiden Sprachen erstellt.

### Expected behavior
DE: Nutzerverhalten tracken
EN: Tracking User behavior

### Actual behavior
DE: Es hat bis zu einem bestimmten Tag getrackt und seit dem nicht mehr.
Am System selber wurde nichts geändert, konnte auch nicht in den Debug Infos finden.

EN: It has been tracked up to a certain day and has not stopped since.
At the system itself nothing was changed, can not synonymous in the debug info find.

![bildschirmfoto 2017-03-29 um 11 30 34](https://cloud.githubusercontent.com/assets/3908658/24448049/352654ee-1473-11e7-8cf1-117c260459c0.png)

### System information (see `Podlove > Support` menu)

Website             http://www.georgjocham.com
PHP Version         5.6.29-nmm1
WordPress Version   4.7.3
WordPress Theme     Betheme Child v1.6
Publisher Version   2.5.0
Web Player Version  no web player found
Twig Version        1.32.0
open_basedir        ok
curl Version        7.35.0
iconv               available
simplexml           ok
max_execution_time  30
upload_max_filesize 200M
memory_limit        512M
disable_classes     
disable_functions   
permalinks          ok (/%postname%/)
podlove_permalinks  ok
podcast_settings    ok
web_player          ok
podlove_cache       on
assets              
  - mp3    audio/mpeg http://www.georgjocham.com/feed/mp3/
  - m4a    audio/mp4  http://www.georgjocham.com/feed/itunes/
cron                ok

0 errors
0 notices
Nice, Everything looks fine!

**Comment by eteubert** [comment]
de/en is fine but we try to keep the issues english :)

I suspect your tracking works fine, just the calculation of analytics got stuck.

Go to `Podlove > Tools` and check if crons are working.

<img width="363" alt="screen shot 2017-03-30 at 09 19 59" src="https://cloud.githubusercontent.com/assets/235918/24492012/1778b0ce-152a-11e7-8a17-57475676adeb.png">

Then, on the same page further down, try to manually trigger recalculations.

<img width="497" alt="screen_shot_2017-03-30_at_09_20_31" src="https://cloud.githubusercontent.com/assets/235918/24492050/3ee3ef34-152a-11e7-9548-cf8c103d7830.png">

And see if that helps.

**Comment by Messa1** [comment]
Ok then in EN :)

So i try that, but when i go to the tool page it shows me "starting" but i have no clicked the buttons. And it stokes in this status.

WP-Cron looks finde.
![bildschirmfoto 2017-03-30 um 09 23 03](https://cloud.githubusercontent.com/assets/3908658/24492211/da2f7576-152a-11e7-887b-7c426b24d5f6.png)

It stays in this status. It starts automatically when i open this page and don't stop
 
![bildschirmfoto 2017-03-30 um 09 23 23](https://cloud.githubusercontent.com/assets/3908658/24492230/ef48a1f8-152a-11e7-8dc9-24e77d328976.png)

**Comment by eteubert** [comment]
Do you have database access, like phpMyAdmin? Find the `wp_podlove_job` table and

1. export it if possible (sql/csv) so I can see why it's stuck
2. truncate/empty it/delete all entries, which should solve the "starting..." issue

**Comment by Messa1** [comment]
So I export the SQL.
[dp_podlove_job.sql.zip](https://github.com/podlove/podlove-publisher/files/881552/dp_podlove_job.sql.zip)

Next i will empty the wp_podlove_job table.
We will see, if that fix it :)

**Comment by eteubert** [comment]
Hm, looks like the jobs never get run, which would make me guess an issue with crons, however that seems to work for you—unless there's an issue in my diagnostics tool. Hard to say.

If you don't mind, you can send me login credentials to eric@ericteubert.de and I'll have a closer look.
