### ISSUE TITLE
Can't remove related episodes

### ISSUE THREAD

**Issue by Inrumpo** [podlove/podlove-publisher#907]
### Expected behavior

Removing a related episode should remove it.

### Actual behavior

They do not get removed. They are back as soon as I update the episode. 

In detail:
Podlove allows to connect episodes via choosing "related episodes". You should be able to remove them by clicking the red cross button to their right. 

What I do:
1. I click the red cross button. The related episode disappears.
2. I update (~ save) that episode.
3. The related episode that just got removed is back. 

### System information
```
Website             https://GameTalk.FM
PHP Version         5.6.30
WordPress Version   4.7.3
WordPress Theme     Joeys Twenty Fifteen Child v1.0
Publisher Version   2.5.0
Web Player Version  no web player found
Twig Version        1.32.0
open_basedir        ok
curl Version        7.36.0
iconv               available
simplexml           ok
max_execution_time  50
upload_max_filesize 150M
memory_limit        256M
disable_classes     
disable_functions   exec, shell_exec, system, dl, passthru, proc_open, proc_close
permalinks          ok (/%postname%/)
podlove_permalinks  ok
podcast_settings    ok
web_player          ok
podlove_cache       on
assets              
  - mp3    audio/mpeg https://GameTalk.FM/feed/mp3/
  - m4a    audio/mp4  https://GameTalk.FM/feed/m4a/
cron                ok

0 errors
0 notices
Nice, Everything looks fine!
```

**Comment by eteubert** [comment]
Works for me. Can you check you PHP error log for errors/warnings?

**Comment by Inrumpo** [comment]
Thanks for your response. 
I've found this:

> [29-Mar-2017 12:50:49 UTC] WordPress-Datenbank-Fehler You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'OR right_episode_id =' at line 1 fÃ¼r Abfrage SELECT * FROM wp_podlove_modules_relatedepisodes_episoderelation WHERE left_episode_id =  OR right_episode_id =  von edit_post, wp_update_post, wp_insert_post, do_action('post_updated'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, wp_save_post_revision, _wp_put_post_revision, wp_insert_post, do_action('save_post'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, Podlove\Modules\RelatedEpisodes\Related_Episodes->update_episode_relations, Podlove\Model\Base::find_all_by_where, Podlove\Model\Base::find_all_by_sql

To be honest: That sounds like Chinese to me.

**Comment by eteubert** [comment]
That is very helpful, thanks! Should be able to fix it now :)

**Comment by Inrumpo** [comment]
Did you come across unforeseen problems while fixing this one? May I be of help somehow?

**Comment by eteubert** [comment]
No problems, just forgot about it. I put it on my todo list :)

**Comment by eteubert** [comment]
Finally had a closer look at it. I fiddled with the code but I am not sure it will fix it.

Do you still have that issue now? If yes, is it only concerning a single episode or all of them? Does it only affect related episodes or other metadata as well?

**Comment by eteubert** [comment]
Oh, I realize it is currently impossible to remove _all_ relations. Is that the case for you, or is it also impossible to delete one relation with still leaving other relations in the episode?

**Comment by Inrumpo** [comment]
I've just tested this again. (WP 4.8.2 and Podlove 2.6.2 by now)

I have been able to remove relations as long as there is still one (or more?) left.
I have not been able to remove a related episode if it's the only one. In those cases where I can't remove that one related episode, both episodes are affected. I'm experiencing multiple cases of this issue. 

I can change and delete other metadata, yes.

**Comment by eteubert** [comment]
The fix is not live yet, it is in the 2.7.0 branch

**Comment by Inrumpo** [comment]
Ah.. I thought about that. My bad. I'll either install a beta and hope for the best or wait until 2.7.0 is out and then report back.

**Comment by Inrumpo** [comment]
I've tested this in 2.7 build 457 beta. My issue is fixed. I have been able to delete a related episode, even if it was the last one.
