### ISSUE TITLE
URL title used as URL when importing chapters from Hindenburg

### ISSUE THREAD

**Issue by Inrumpo** [podlove/podlove-publisher#908]
This is about the "import chapters from Hindenburg project files"-feature, introduced in 2.5.1.

### Expected behavior

URLs in chapters will be used as URLs.

### Actual behavior

The `URL title` is used instead of the URL itself.

This is what I type in Hindenburg:
![chapters in hindenburg](https://cloud.githubusercontent.com/assets/11300164/24522481/053747de-1590-11e7-9f1b-c036e57a1617.png)
(That column from left to right: Time, chapter title, URL, URL title)

It will be imported like this:
![hindenburg chapters in podlove backend](https://cloud.githubusercontent.com/assets/11300164/24522517/1b8c624e-1590-11e7-9a29-ed56561cec82.png)

### System information

> Website             https://GameTalk.FM
> PHP Version         5.6.30
> WordPress Version   4.7.3
> WordPress Theme     Joeys Twenty Fifteen Child v1.0
> Publisher Version   2.5.1
> Web Player Version  no web player found
> Twig Version        1.32.0
> open_basedir        ok
> curl Version        7.36.0
> iconv               available
> simplexml           ok
> max_execution_time  50
> upload_max_filesize 100M
> memory_limit        256M
> disable_classes     
> disable_functions   exec, shell_exec, system, dl, passthru, proc_open, proc_close
> permalinks          ok (/%postname%/)
> podlove_permalinks  ok
> podcast_settings    ok
> web_player          ok
> podlove_cache       on
> assets              
>   - mp3    audio/mpeg https://GameTalk.FM/feed/mp3/
>   - m4a    audio/mp4  https://GameTalk.FM/feed/m4a/
> cron                ok
> 
> 0 errors
> 0 notices
> Nice, Everything looks fine!

**Comment by eteubert** [comment]
Can you attach the project file here?

**Comment by Inrumpo** [comment]
This should work:
[Hindy Project File.zip](https://github.com/podlove/podlove-publisher/files/883695/Hindy.Project.File.zip)

**Comment by chemiker** [comment]
Seems like the project file is messed up:

`<Markers>    
   <Marker Id="3" Name="Test Käpitöl 1" Time="19.200" Type="Chapter" Title="https://nzz.ch" URL="NZZ Kapiteltitel"/>
   <Marker Id="4" Name="Test Käpitül 2" Time="01:09.400" Type="Chapter" Title="https://gametalk.fm" URL="GAME TALK Kapiteltitel"/>
</Markers>`

**Comment by Inrumpo** [comment]
Thanks for having a look. I see the problem.
The Podlove team might have implemented this the correct way, but the (or just my?) project file might be wrong.
I've informed the Hindenburg support about this. They are exceptionally fast and helpful. I'll report back to you as soon as I've got some new information on this topic.

**Comment by Inrumpo** [comment]
I just got a response from Hindy support. Seems they are doing everything the right way. I've tested it again. And it works just fine. Looks like I've just added the chapter information "reversed" in those columns.  Somehow. In other words: Might be stupid user error by me. Sorry for that one!
