### ISSUE TITLE
Podcast import is stuck

### ISSUE THREAD

**Issue by koko-joe** [podlove/podlove-publisher#910]
Yesterday I made a wordpress export file and podlove export file. Then I imported the wordpress file first (everything seems to be imported correctly), then I started the podlove import. I started it 22 hours ago and nothing happened since then. Literally nothing happened, the Tools page says:
Total import progress: 8/15
Currently working on: Podcast Import: Media Files
....
Podcast Import: Media Files	350/525 (66%) 	vor 22 Stunden	vor 22 Stunden

Also the question is, where do these numbers come? I have 173 episodes, so why are there 525 files to import? What does this number actually mean? Is this background job really still running? How can I stop it?

By the way, the debug logging is not very helpful:
2017-04-06 00:31:46	Importer: no matching post for (old) post_id=2137	toggle details
...
2017-04-06 00:31:48	Curl Error: malformed	toggle details
2017-04-06 00:31:48	Unexpected http response when trying to access remote media file.	HTTP Status: 0	toggle details

The details of the errors are all something like:
Curl Error: malformed	
--- 
media_file_id: "238"

and 

Unexpected http response when trying to access remote media file.	HTTP Status: 0 
---
media_file_id: "238"
http_code: 0

I included my imort files:
[import-files.zip](https://github.com/podlove/podlove-publisher/files/903867/import-files.zip)

**Comment by eteubert** [comment]
I think I found the issue and fixed it.

> I have 173 episodes, so why are there 525 files to import? What does this number actually mean?

Some file entries may be related to episode revisions.
