### ISSUE TITLE
Contributor social URLs are encoded on save

### ISSUE THREAD

**Issue by timpritlove** [podlove/podlove-publisher#913]
### Expected behavior

When adding a social link with a URL value (like "website"), the value should be stored as is and should be properly encoded when requested via the API.

### Actual behavior

When saving URLs containing non-ASCII characters and URLs containing the % escape character, Podlove Publisher does some weird (and wrong) encoding of the URL, totally garbling up the result.

**Comment by chemiker** [comment]
Dublicate of #817?
