### ISSUE TITLE
Blog does not work when Publisher is activated

### ISSUE THREAD

**Issue by nielsk** [podlove/podlove-publisher#927]
### Expected behavior
Blog works

### Actual behavior
I get only a blank page when the plug-in is activated

Errors in the nginx-error-log:
`
2017/05/10 21:58:12 [error] 950#100652: *96 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function Podlove\Modules\filter_input() in /usr/local/www/niels.kobschaetzki.net/wp-content/plugins/podlove-podcasting-plugin-for-wordpress-disabled/lib/modules/base.php:231
Stack trace:
#0 /usr/local/www/niels.kobschaetzki.net/wp-content/plugins/podlove-podcasting-plugin-for-wordpress-disabled/lib/modules/auphonic/auphonic.php(40): Podlove\Modules\Base::is_module_settings_page()
#1 /usr/local/www/niels.kobschaetzki.net/wp-content/plugins/podlove-podcasting-plugin-for-wordpress-disabled/lib/modules/auphonic/auphonic.php(35): Podlove\Modules\Auphonic\Auphonic->register_settings()
#2 /usr/local/www/niels.kobschaetzki.net/wp-content/plugins/podlove-podcasting-plugin-for-wordpress-disabled/includes/modules.php(19): Podlove\Modules\Auphonic\Auphonic->load()
#3 /usr/local/www/niels.kobschaetzki.net/wp-includes/class-wp-hook.php(298): {closure}('')
#4 /usr/local/www/niels.kobschaetzki.net/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(N" while reading response header from upstream, client: 2a02:8109:9a40:1328:523d:65c9:23d6:875e, server: niels.kobschaetzki.net, request: "GET /wp-admin/plugins.php?activate=true&plugin_status=all&paged=1&s= HTTP/2.0", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "niels.kobschaetzki.net", referrer: "https://niels.kobschaetzki.net/wp-admin/plugins.php"
2017/05/10 21:58:14 [error] 950#100652: *144 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function Podlove\Modules\filter_input() in /usr/local/www/niels.kobschaetzki.net/wp-content/plugins/podlove-podcasting-plugin-for-wordpress-disabled/lib/modules/base.php:231
Stack trace:
#0 /usr/local/www/niels.kobschaetzki.net/wp-content/plugins/podlove-podcasting-plugin-for-wordpress-disabled/lib/modules/auphonic/auphonic.php(40): Podlove\Modules\Base::is_module_settings_page()
#1 /usr/local/www/niels.kobschaetzki.net/wp-content/plugins/podlove-podcasting-plugin-for-wordpress-disabled/lib/modules/auphonic/auphonic.php(35): Podlove\Modules\Auphonic\Auphonic->register_settings()
#2 /usr/local/www/niels.kobschaetzki.net/wp-content/plugins/podlove-podcasting-plugin-for-wordpress-disabled/includes/modules.php(19): Podlove\Modules\Auphonic\Auphonic->load()
#3 /usr/local/www/niels.kobschaetzki.net/wp-includes/class-wp-hook.php(298): {closure}('')
#4 /usr/local/www/niels.kobschaetzki.net/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(N" while reading response header from upstream, client: 2003:d1:9bc4:a700:70c3:6a6b:3b99:15a2, server: niels.kobschaetzki.net, request: "GET /?feed=mp3 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "japanbezug.kobschaetzki.net"
2017/05/10 21:58:14 [error] 952#100653: *132 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function Podlove\Modules\filter_input() in /usr/local/www/niels.kobschaetzki.net/wp-content/plugins/podlove-podcasting-plugin-for-wordpress-disabled/lib/modules/base.php:231
Stack trace:
#0 /usr/local/www/niels.kobschaetzki.net/wp-content/plugins/podlove-podcasting-plugin-for-wordpress-disabled/lib/modules/auphonic/auphonic.php(40): Podlove\Modules\Base::is_module_settings_page()
#1 /usr/local/www/niels.kobschaetzki.net/wp-content/plugins/podlove-podcasting-plugin-for-wordpress-disabled/lib/modules/auphonic/auphonic.php(35): Podlove\Modules\Auphonic\Auphonic->register_settings()
#2 /usr/local/www/niels.kobschaetzki.net/wp-content/plugins/podlove-podcasting-plugin-for-wordpress-disabled/includes/modules.php(19): Podlove\Modules\Auphonic\Auphonic->load()
#3 /usr/local/www/niels.kobschaetzki.net/wp-includes/class-wp-hook.php(298): {closure}('')
#4 /usr/local/www/niels.kobschaetzki.net/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(N" while reading response header from upstream, client: 85.10.246.236, server: niels.kobschaetzki.net, request: "GET //feed/ogg HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "emui.kobschaetzki.net"
2017/05/10 21:58:15 [error] 952#100653: *132 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function Podlove\Modules\filter_input() in /usr/local/www/niels.kobschaetzki.net/wp-content/plugins/podlove-podcasting-plugin-for-wordpress-disabled/lib/modules/base.php:231
Stack trace:
#0 /usr/local/www/niels.kobschaetzki.net/wp-content/plugins/podlove-podcasting-plugin-for-wordpress-disabled/lib/modules/auphonic/auphonic.php(40): Podlove\Modules\Base::is_module_settings_page()
#1 /usr/local/www/niels.kobschaetzki.net/wp-content/plugins/podlove-podcasting-plugin-for-wordpress-disabled/lib/modules/auphonic/auphonic.php(35): Podlove\Modules\Auphonic\Auphonic->register_settings()
#2 /usr/local/www/niels.kobschaetzki.net/wp-content/plugins/podlove-podcasting-plugin-for-wordpress-disabled/includes/modules.php(19): Podlove\Modules\Auphonic\Auphonic->load()
#3 /usr/local/www/niels.kobschaetzki.net/wp-includes/class-wp-hook.php(298): {closure}('')
#4 /usr/local/www/niels.kobschaetzki.net/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(N" while reading response header from upstream, client: 85.10.246.236, server: niels.kobschaetzki.net, request: "GET //feed/opus HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "emui.kobschaetzki.net"
`
### System information (see `Podlove > Support` menu)
FreeBSD 11-RELEASE-p9
PHP 7.1.4, ZEND v3.1.0 (php-fpm)
nginx 1.12.0
According to package.json: 2.5.0

**Comment by eteubert** [comment]
See if https://github.com/podlove/podlove-publisher/issues/844#issuecomment-216931683 helps. Verify that the [PHP "filter" extension](https://secure.php.net/manual/en/book.filter.php) is enabled.

**Comment by nielsk** [comment]
That worked. Thanks a lot.
