### ISSUE TITLE
No connection to Auphonic in the episode view

### ISSUE THREAD

**Issue by jonasschoen** [podlove/podlove-publisher#931]
Hi, 
a few weeks before I first experienced an issue where the Publisher doesn't show any Auphonic productions or files. But the Publisher is connected to Auphonic at Podlove > Modules and I disabled and reenabled the connection but the problem within the edit mode of an episode remains the same. I have two productions in my Auphonic account and I asked Georg from Auphonic whether everything is okay with my account which he confirmed.

### Expected behavior
The publisher shows the latest Auphonic productions in the edit view of an episode to import the length of an episode for example.

### Actual behavior
The publisher doesn't show any Auphonic productions in the edit view of an episode and says "unable to load services/files".
![bildschirmfoto 2017-06-14 um 22 08 07](https://user-images.githubusercontent.com/9519201/27152719-11e21d88-514f-11e7-8236-fd050ea70b16.png)

### System information (see `Podlove > Support` menu)
Website                    https://technische-aufklaerung.de
PHP Version                7.0.16
WordPress Version          4.8
WordPress Theme            Twenty Thirteen v2.2
WordPress Database Charset utf8
WordPress Database Collate 
Publisher Version          2.6.0
Web Player Version         no web player found
Twig Version               1.33.2
open_basedir               ok
curl Version               7.26.0
iconv                      available
simplexml                  ok
max_execution_time         30
upload_max_filesize        70M
memory_limit               256M
disable_classes            
disable_functions          
permalinks                 ok (/%postname%/)
podlove_permalinks         ok
podcast_settings           ok
web_player                 ok
podlove_cache              on
assets                     
  - m4a    audio/mp4        https://technische-aufklaerung.de/feed/m4a/
  - mp3    audio/mpeg       https://technische-aufklaerung.de/feed/mp3/
  - ogg    audio/ogg        https://technische-aufklaerung.de/feed/ogg/
  - opus   audio/ogg;codecs=opushttps://technische-aufklaerung.de/feed/opus/
  - psc    application/xml  no feed
cron                       ok

0 errors
0 notices
Nice, Everything looks fine!

If you need further information please tell me. Thank you for having a look into this issue.
Jonas

**Comment by eteubert** [comment]
Does the issue still exist?
If yes, is there anything in the browser console (chrome example https://developers.google.com/web/tools/chrome-devtools/console/)

**Comment by jonasschoen** [comment]
I have to apologize. The error occurs because I use a browser plugin called Privacy Badger which blocked the connection to Auphonic. If I allow the connection it works perfectly. Sorry and thank you for your work, Jonas.
