### ISSUE TITLE
Text "default" in Shownotes

### ISSUE THREAD

**Issue by meszner** [podlove/podlove-publisher#932]
In the beginning of my episode shownotes, there is the text "default" and I can't figure out, where it is coming from. 

Here is the feed (https://rueckpass.zeitsprung.fm/feed/mp3/) containing "[CDATA[default<p> ...".

There are more podcasts with this issue: https://sendegate.de/t/default-taucht-in-shownotes-auf/5517

### System information (see `Podlove > Support` menu)

Website                    https://rueckpass.zeitsprung.fm
PHP Version                7.0.18-0ubuntu0.16.04.1
WordPress Version          4.7.5
WordPress Theme            Twenty Fifteen v1.8
WordPress Database Charset utf8
WordPress Database Collate 
Publisher Version          2.6.0
Web Player Version         no web player found
Twig Version               1.33.2
open_basedir               ok
curl Version               7.47.0
iconv                      available
simplexml                  ok
max_execution_time         30
upload_max_filesize        500M
memory_limit               256M
disable_classes            
disable_functions          pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wifcontinued,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,
permalinks                 ok (/%postname%/)
podlove_permalinks         ok
podcast_settings           ok
web_player                 ok
podlove_cache              on
assets                     
  - mp3    audio/mpeg       https://rueckpass.zeitsprung.fm/feed/mp3/
  - m4a    audio/mp4        https://rueckpass.zeitsprung.fm/feed/mp4/
  - opus   audio/ogg;codecs=opushttps://rueckpass.zeitsprung.fm/feed/opus/
  - chapters.txttext/plain       no feed
cron                       ok

0 errors
0 notices
Nice, Everything looks fine!

**Comment by bslinger** [comment]
I am also having this issue, and updating to 2.6.2 hasn't resolved it. My feed here: http://lamestorming.com/feed/podcast/ is printing 'default' at the start of every <content:encoded> element.

Here's my system info: 
`Website                    http://lamestorming.com
PHP Version                5.6.30
WordPress Version          4.8
WordPress Theme            Make v1.8.3
WordPress Database Charset utf8
WordPress Database Collate 
Publisher Version          2.6.2
Web Player Version         no web player found
Twig Version               1.33.2
open_basedir               ok
curl Version               7.48.0
iconv                      available
simplexml                  ok
max_execution_time         300
upload_max_filesize        1024M
memory_limit               256M
disable_classes            
disable_functions          
permalinks                 ok (/%postname%/)
podlove_permalinks         ok
podcast_settings           ok
web_player                 ok
podlove_cache              on
assets                     
  - mp3    audio/mpeg       http://lamestorming.com/feed/podcast/
  - png    image/png        no feed
  - jpg    image/jpeg       no feed
cron                       ok

0 errors
0 notices
Nice, Everything looks fine!`
