### ISSUE TITLE
No new episodes in both feeds for two days

### ISSUE THREAD

**Issue by sorcerer86** [podlove/podlove-publisher#934]
**### Expected behavior**
I am uploading a podcast episode each day. 
So far without any problems.

**### Actual behavior**
And now for two days the episodes are not shown in the feed
although I haven't changed anything. 
Could you possibly help me? Thanks in advance.

**### System information (see `Podlove > Support` menu)**
Website                    http://www.oaad.de
PHP Version                5.5.10
WordPress Version          4.8
WordPress Theme            Twenty Twelve v2.3
WordPress Database Charset utf8
WordPress Database Collate 
Publisher Version          2.6.2
Web Player Version         2.1.1
Twig Version               1.33.2
open_basedir               ok
curl Version               7.29.0
iconv                      available
simplexml                  ok
max_execution_time         30
upload_max_filesize        64M
memory_limit               268435456
disable_classes            
disable_functions          
permalinks                 ok (/%year%/%monthnum%/%day%/%postname%/)
podlove_permalinks         ok
podcast_settings           ok
web_player                 ok
podlove_cache              on
assets                     
  - mp3    audio/mpeg       http://www.oaad.de/feed/mp3/
  - m4a    audio/mp4        http://www.oaad.de/feed/oaad-m4a/
  - psc    application/xml  no feed
cron                       ok

0 errors
1 HINWEIS (no dealbreaker, but should be fixed if possible): 
- Episode Database Charset is not UTF-8! (is latin1_swedish_ci)

**Comment by eteubert** [comment]
As far as I can see there are recent episodes in the feeds now, so I'm closing this.
