### ISSUE TITLE
Analytics-Bug – Keine Download-Spaltenaufteilung bei einer Episode

### ISSUE THREAD

**Issue by HorstFrank** [podlove/podlove-publisher#937]
### Expected behavior
In Analytics wird dargestellt in welchem Zeitabschnitt (Spalte) wieviele Downloads gemacht wurden.

### Actual behavior
Bei einer Episode in unserem Podcast "Nullwert" wird immer nur die aktuelle Downloadzahl in Klammern angezeigt. Die Zahl wird über die Zeit in der richtigen Spalte angezeigt (wandert also nach links), alle vergangenen Spalten haben "-" (bekommen). 
Möglicherweise liegt es daran, dass der Episodenname "NW037-Nullwertmarketing" den Podcastnamen enthält.

### System information (see `Podlove > Support` menu)
PHP Version                7.1.8
WordPress Version          4.8.1
WordPress Database Charset utf8mb4
WordPress Database Collate 
Publisher Version          2.6.2

**Comment by eteubert** [comment]
1. Schau, ob bei Podlove > Werkzeuge > Hintergrundjobs Einträge zu finden sind, vor allem "Zusammenfassung der Downloads (Partiell)"
2. Weiter unten bei Werkzeugen bitte im Bereich "Tracking & Analyse" alle 3 Buttons von oben nach unten anklicken. Wenn die 3 so gestarteten Jobs durch sind, bitte prüfen ob die Anzeige wieder stimmt.

**Comment by HorstFrank** [comment]
AH!! toll!! Vielen Dank!
Alles wieder gut. Sorry für die Bug-Falschmeldung!

**Comment by eteubert** [comment]
Naja, irgendwo steckt ein Bug, wenn manuelles Eingreifen notwendig ist. Aber jetzt vermutlich schwer nachvollziehbar. Ich schließe hier, aber du kannst gerne wieder antworten, wenn es erneut hängen bleibt.
