### ISSUE TITLE
e-mail notifications stopped working

### ISSUE THREAD

**Issue by Inrumpo** [podlove/podlove-publisher#938]
### Expected behavior
After releasing an episode, an automatic e-mail will be sent to contributors. 

### Actual behavior
No e-mails will be sent anymore.

### Additional info
This isse is based on [this topic](https://community.podlove.org/t/automatic-e-mail-notification-stopped-working/1091) over at the Podlove community. 

This has worked for me just fine right after release of this feature in `2.6.0`. Somewhere down the road this stopped working. 

I've tried with no luck:

- tested different episode
- used different sender
- tested different recipients
- checking junk-mail folders
- changed roles and groups
- checked for PHP errors in error_log files
- checked e-maillog
- Podlove repair button & clearing caches
- deactivated and reactivated the mail notifications module

Other mail notifications are still working.
Podlove Jobs are running. 

The Podlove debug log shows me this (example with contributor named Sebastian):
`Tried sending email notification to Sebastian. wp_mail was unable to send.`

Details:
```
---
module: E-Mail Notifications
contributor_id: "19"
contributor_name: Sebastian
```

### System information (see Podlove > Support menu)

> Website                    https://GameTalk.FM
> PHP Version                7.0.23
> WordPress Version          4.8.2
> WordPress Theme            Joeys Twenty Fifteen Child v1.0
> WordPress Database Charset utf8
> WordPress Database Collate 
> Publisher Version          2.6.2
> Web Player Version         no web player found
> Twig Version               1.33.2
> open_basedir               ok
> curl Version               7.54.0
> iconv                      available
> simplexml                  ok
> max_execution_time         50
> upload_max_filesize        100M
> memory_limit               256M
> disable_classes            
> disable_functions          exec, shell_exec, system, dl, passthru, proc_open, proc_close
> permalinks                 ok (/%postname%/)
> podlove_permalinks         ok
> podcast_settings           ok
> web_player                 ok
> podlove_cache              on
> assets                     
>   - mp3    audio/mpeg       https://GameTalk.FM/feed/mp3/
>   - m4a    audio/mp4        https://GameTalk.FM/feed/m4a/
> cron                       ok
> 
> 0 errors
> 0 notices
> Nice, Everything looks fine!

**Comment by eteubert** [comment]
Likely fixed in https://github.com/podlove/podlove-publisher/commit/3a43778d3cfa96a13712d4ffe8901bd620680cbb. There was some trouble rendering the message, resulting in an empty message body, resulting in a failed attempt to send the message.

I also added more verbose debugging information should issues occur again.

**Comment by Inrumpo** [comment]
Test mails are working again. This issue seems to be fixed. Thanks!
