### ISSUE TITLE
Permalinks zerschossen

### ISSUE THREAD

**Issue by LoBodingbauer** [podlove/podlove-publisher#941]
Wir haben den Publisher hier installiert: http://wien.abendgymnasium.at
Nach einer Aktualisierung aller Plugins waren die Permalinks kaputt. Seiten wie http://wien.abendgymnasium.at/externisten/ konnten nicht angezeigt werden. 

Nachdem ich schrittweise alle Plugins ausgeschaltet habe, war dann der Podlove Publisher der letzte, den ich ausschalten musste, bis die Permalinks wieder da waren. Danach waren alle Seiten und Permalinks wieder da - und ich konnte auch wieder den Podlove Publisher anschalten.

Das selbe war auch vor einiger Zeit mit einem anderen Plugin an/aus lösbar, damals war es nicht de Podlovce Publisher, sondern "Post Snippets".

Jetzt ist also die Frage, ob der Podlove Publisher vielleicht wirklich ein Problem macht, oder ob es ein Wordpress Problem ist.

**Comment by cfoellmann** [comment]
Hast du auf "Einstellungen > Permalinks" einmal auf speichern geklickt? Das hilft oft.
Wenn du das nicht gemacht hast, ist es leider nicht mehr zu testen.
