### ISSUE TITLE
How to filter episodes from regular loop? Open a seperate loop?

### ISSUE THREAD

**Issue by derGrafiktyp** [podlove/podlove-publisher#943]
Hi.

I have a issue with the overview on my blog. I use a filter on the loop:

```
<?php $query1 = new WP_Query( array( 'author' => '-9' ) ); ?>
	<?php if ($query1->have_posts()): while ($query1->have_posts()) : $query1->the_post(); ?>
		//post
	<?php endwhile; ?>
<?php endif; ?>
```

That filter is supposed to exclude the podcast episodes from the postlist, because i want to list the podcast episodes somewhere else (on that same page).
So i made another loop, with another filter including just the post by the podcast user. Which didn't work.

Now i figured out... as soon as any filter is applied to the loop the episodes will not be shown anymore. Even if the filter would not matter to the episodes whatsoever. 
Is that a bug? Is there a workaround?

As soon as i remove the filter, episodes get shown. Applying any filter removes them... 

Please help me. :)

**Comment by eteubert** [comment]
You can use the "post_type" parameter to filter or filter out podcast episodes. The post type is called "podcast".

For future questions please use http://community.podlove.org/, we try to keep the issue tracker for bug reports only.
