### ISSUE TITLE
Experteneinstellungen Webseiten Protokoll

### ISSUE THREAD

**Issue by creabrain** [podlove/podlove-publisher#945]
### Expected behavior
Du musst Option 3 auswählen, wenn du ein Zertifikat eines Anbieters nutzt, der von iTunes nicht unterstützt wird. Der Publisher wird dann dafür sorgen, dass Feeds und Medien ausschließlich über http bereitgestellt werden.

### Actual behavior
Du musst Option 3 auswählen, wenn du ein Zertifikat eines Anbieters nutzt, der von iTunes nicht unterstützt wird (wie Let's Encrypt). Der Publisher wird dann dafür sorgen, dass Feeds und Medien ausschließlich über http bereitgestellt werden.

### System information (see `Podlove > Support` menu)
Let's Encrypt wird untersützt http://itunespartner.apple.com/en/podcasts/faq

**Comment by eteubert** [comment]
Wurde behoben in 2073f73c47803ea795f9be9f752c557ee496f5a9
