### ISSUE TITLE
Webplayer 4 vanished after update to 2.6.3

### ISSUE THREAD

**Issue by markusk** [podlove/podlove-publisher#948]
### Expected behavior
Player is visible in every episode and in the Podlove Settings under Podlove>Podcast Settings>Player

### Actual behavior
The webplaner is not displayed after updating Podlove to 2.6.3.
It worked fine at my other podcast; i.e.: https://reich-und-knapp.de/ruk020/

System information say: no web player found!? (Although web player 3 is working).

### System information
Website                    https://www.robotiklabor.de
PHP Version                7.0.25-nmm1
WordPress Version          4.9.1
WordPress Theme            Ample v1.1.7
WordPress Database Charset utf8
WordPress Database Collate 
Publisher Version          2.6.3
**Web Player Version         no web player found**
Twig Version               1.35.0
open_basedir               ok
curl Version               7.35.0
iconv                      available
simplexml                  ok
max_execution_time         30
upload_max_filesize        200M
memory_limit               512M
disable_classes            
disable_functions          
permalinks                 ok (/%postname%/)
podlove_permalinks         ok
podcast_settings           ok
web_player                 ok
podlove_cache              on
assets                     
  - mp3    audio/mpeg       http://www.robotiklabor.de/feed/mp3/
  - m4a    audio/mp4        http://www.robotiklabor.de/feed/itunes/
  - txt    text/plain       no feed
cron                       ok

0 errors
1 HINWEIS (no dealbreaker, but should be fixed if possible): 
- Episode Database Charset is not UTF-8! (is latin1_swedish_ci)

**Comment by markusk** [comment]
### Update

Still confused... It works again.

### What I did today
- Disabled and deleted all unused plugins
- Deleted all old pages
- Deleted all old users at once (role: wordpress subscribers). This resulted in this error:

> Fatal error:  Uncaught Error: Call to a member function delete() on null in /www/htdocs/xxx/robotiklabor.de/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/lib/modules/contributors/settings/generic_entity_settings.php:125Stack trace:#0
> /www/htdocs/xxx/robotiklabor.de/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/lib/modules/contributors/settings/generic_entity_settings.php(71): Podlove\Modules\Contributors\Settings\GenericEntitySettings->delete()#1
> /www/htdocs/xxx/robotiklabor.de/wp-includes/class-wp-hook.php(286): Podlove\Modules\Contributors\Settings\GenericEntitySettings->process_form('')#2
> /www/htdocs/xxx/robotiklabor.de/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)#3 /www/htdocs/xxx/robotiklabor.de/wp-includes/plugin.php(453): WP_Hook->do_action(Array)#4 /www/htdocs/xxx/robotiklabor.de/wp-admin/admin.php(156): do_action('admin_init')#5 /www/htdocs/xxx/robotiklabor.de/wp-admin/users.php(11): require_once('/www/htdocs/xxx...')#6 in /www/htdocs/w005c246/robotiklabor.de/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/lib/modules/contributors/settings/generic_entity_settings.php on line 125

Looks for me that the latter is related to [this error](https://github.com/podlove/podlove-publisher/issues/816)?

- Deleted all old users, one after another (role: wordpress subscribers). Worked fine.
- Checked all Podlove podcast settings (were okay)
- Disabled/stored/enabled the webplayer module in the podlove settings
- Tried the podlove repair button
- Tried the podlove clear caches button

### Conclusion
After all this cleanup it works again. Doesn't feel good, but so far it works... :-/

**Comment by markusk** [comment]
## Update
Looks like that this is a Safari Issue only?!

On Firefox everything looks fine - although the podlove "help" button still insists that the web player is **not found**...

Any ideas?

### Versions
macOS High Sierra, 10.13.2
Safari 11.0.2 (13604.4.7.1.3)
Firefox 57.0.1 (64-Bit)

**Comment by alexander-heimbuch** [comment]
Hey @markusk,

there is currently an issue with Safari and iOS so that in some cases the Player is not rendered. I have already a fix in place and will release this soon.

**Comment by markusk** [comment]
Many thanks!! Looking forward to the fix. Let me know if I should test it for you (although in a productive environment).

**Comment by cfoellmann** [comment]
@markusk and  @alexander-heimbuch is this closed?

**Comment by alexander-heimbuch** [comment]
yep

**Comment by markusk** [comment]
Well, since we are on Publisher Version 2.7.11 now, this is can be closed.
