### ISSUE TITLE
Letterboxd as social service for contributors

### ISSUE THREAD

**Issue by pommes** [podlove/podlove-publisher#951]
It's only a feature request. Maybe you can add [Letterboxd](https://letterboxd.com) as a social service for contributors.
I know I can achieve it selecting *Website* but showing up the Letterboxd Icon would be nice.

Or maybe - just maybe - you could add the possibility to manually overwrite the default icon for each *Website* instance in the contributors list editor. That would be a more generic approach.

**Comment by timpritlove** [comment]
Logo (taken from Twitter)

![letterboxd](https://user-images.githubusercontent.com/119680/34522156-a0798cb6-f091-11e7-81c8-775b2563aeb2.png)

**Comment by timpritlove** [comment]
Scheme: https://letterboxd.com/<username>

**Comment by IndyViduum** [comment]
+1

**Comment by pommes** [comment]
Added pull request https://github.com/podlove/podlove-publisher/pull/973.
