### ISSUE TITLE
Wordwrap issue with Webplayer 4

### ISSUE THREAD

**Issue by dpbenne** [podlove/podlove-publisher#953]
### Expected behavior
If I use wordwraps (e.g. via press ENTER) in my conclusion (Zusammenfassung) everything was fine with webplayer 2. 

### Actual behavior
With webplayer 4 the wordwrap is shown with the HTML tag "br /". 
Anyone else with the same issue? Checked it with Chrome and Opera (windows). Going back to webplayer 2 for now.

### System information (see `Podlove > Support` menu)
Website                    https://www.familieaufkurs.de
PHP Version                7.0.25-nmm1
WordPress Version          4.9.1
WordPress Theme            Avada Child v1.0.0
WordPress Database Charset utf8
WordPress Database Collate 
Publisher Version          2.6.3
Web Player Version         2.0.20
Twig Version               1.35.0
open_basedir               ok
curl Version               7.47.0
iconv                      available
simplexml                  ok
max_execution_time         30
upload_max_filesize        200M
memory_limit               256M
disable_classes            
disable_functions          
permalinks                 ok (/%year%/%monthnum%/%postname%/)
podlove_permalinks         ok
podcast_settings           ok
web_player                 ok
podlove_cache              on
assets                     
  - mp3    audio/mpeg       https://www.familieaufkurs.de/feed/mp3/
cron                       ok

0 errors
0 notices
Nice, Everything looks fine!

**Comment by mlipeck** [comment]
i have exactly the same problem. 

also with php 7.0 and with other themes.


Website                    http://nachtkantine.org
PHP Version                5.6.32-nmm1
WordPress Version          4.9.1
WordPress Theme            Arcade Basic v1.0.10
WordPress Database Charset utf8
WordPress Database Collate 
Publisher Version          2.6.3
Web Player Version         no web player found
Twig Version               1.35.0
open_basedir               ok
curl Version               7.47.0
iconv                      available
simplexml                  ok
max_execution_time         30
upload_max_filesize        200M
memory_limit               256M
disable_classes            
disable_functions          
permalinks                 ok (/%postname%/)
podlove_permalinks         ok
podcast_settings           ok
web_player                 ok
podlove_cache              on
assets                     
  - mp3    audio/mpeg       http://nachtkantine.org/feed/podcast/
cron                       ok

0 errors
0 notices
Nice, Everything looks fine!

**Comment by Inrumpo** [comment]
Should go to /podlove-web-player
cc @alexander-heimbuch

**Comment by alexander-heimbuch** [comment]
This is essentially not a bug. Web Player 4 encodes all inputs for security reasons. Allowing html allows potential cross site scripting attacks. In the next version release the player will respect control characters to format the text.

**Comment by eteubert** [comment]
@alexander-heimbuch the Publisher should convert `<br>` to `\n` then?

**Comment by alexander-heimbuch** [comment]
Yep that would be great.

**Comment by dpbenne** [comment]
He guys,

thanks for your great support. Do you know how long the adjustement of the player takes?
Greets!
Benjamin

**Comment by eteubert** [comment]
I had to publish a 2.6.4 release and included this fix instead of waiting for 2.7.0, so it is available immediately.
