### ISSUE TITLE
Download button for geolocation database doesn't work

### ISSUE THREAD

**Issue by jonasschoen** [podlove/podlove-publisher#954]
### Expected behavior
If I click the "Download now" button on the _Tracking_-Tab in the Expert Settings, I expect some kind of message that the download is ongoing or finished.

### Actual behavior
I get a blank page with the message "Forbidden" (URL: https://jonas-schoenfelder.de/wp-admin/options.php)

### System information (see `Podlove > Support` menu)
Website                    https://jonas-schoenfelder.de
PHP Version                7.0.16
WordPress Version          4.9.1
WordPress Theme            Rowling v1.11
WordPress Database Charset utf8mb4
WordPress Database Collate 
Publisher Version          2.6.3
Web Player Version         no web player found
Twig Version               1.35.0
open_basedir               ok
curl Version               7.26.0
iconv                      available
simplexml                  ok
max_execution_time         30
upload_max_filesize        50M
memory_limit               256M
disable_classes            
disable_functions          
permalinks                 ok (/%year%/%postname%/)
podlove_permalinks         ok
podcast_settings           ok
web_player                 ok
podlove_cache              on
assets                     
  - mp3    audio/mpeg       https://jonas-schoenfelder.de/feed/mp3/
  - m4a    audio/mp4        https://jonas-schoenfelder.de/feed/m4a/
  - psc    application/xml  no feed
  - jpg    image/jpeg       no feed
cron                       ok

0 errors
0 notices
Nice, Everything looks fine!

**Comment by saerdnaer** [comment]
I have the same problem at https://podcast.openstreetmap.de/

**Comment by eteubert** [comment]
I talked to the database providers and apparently some other WordPress plugin was sending them too many download requests so they were forced to block _all_ requests from WordPress plugins.

We are working on a solution. Until then, the only solution is to download it manually and upload via FTP -- or ignore it. Tracking will work just fine, only without geo data.
