### ISSUE TITLE
Podcasts nicht abspielbar (und damit auch nicht in iTunes importierbar)

### ISSUE THREAD

**Issue by schlaubumms** [podlove/podlove-publisher#961]
### Expected behavior
Nach erfolgter Episodeneinstellung sollte man auf der Seite die Datei hören können. Das ist nicht der Fall. Selbst bei der Erstellung der Episode ist es fast schon Zufall, dass er die Datei findet und die Zeit auslesen kann. Wenn es dann doch gelingt, wird eine neue URL generiert und in den Feed für iTunes gepackt.
### Actual behavior
Diese URL wie oben beschrieben enthält aber keinen Podcast. Und damit kann man den Feed auch nicht bei iTunes importieren.
### System information (see `Podlove > Support` menu)
Website                    https://nerdstar.de
PHP Version                5.6.33
WordPress Version          4.9.2
WordPress Theme            SmartMag v2.2.1
WordPress Database Charset utf8
WordPress Database Collate 
Publisher Version          2.6.4
Web Player Version         2.1.0
Twig Version               1.35.0
open_basedir               ok
curl Version               7.29.0
iconv                      available
simplexml                  ok
max_execution_time         30000
upload_max_filesize        512M
memory_limit               500M
disable_classes            
disable_functions          
permalinks                 ok (/%category%/%postname%/)
podlove_permalinks         ok
podcast_settings           ok
web_player                 ok
podlove_cache              on
assets                     
  - mp3    audio/mpeg       https://nerdstar.de/feed/radionerdstar/
cron                       ok

0 errors
0 notices
Nice, Everything looks fine!

Ein Auszug des Fehlers
2018-01-30 22:41:18 | Unexpected http response when trying to access remote media file.	radionerdstar-001-remakes/MP3 Audio HTTP Status: 404	Details ein-/ausblenden--- 
media_file_id: "2" http_code: 404
-- | --

**Comment by timpritlove** [comment]
Ihr habt offensichtlich noch keine Episode veröffentlicht. Solange es keine Episode gibt, ist sie auch nicht im Feed enthalten und so lange lässt sich bei iTunes auch nichts einreichen.

**Comment by schlaubumms** [comment]
Hallo Tim, das ist leider schon der Fall, ich hatte das nur gestern deaktiviert, weil das ja sonst öffentlich zu sehen ist. Trotz einer veröffentlichten Folge und der Tatsache, dass auch iTunes die Daten, die übertragen werden, erkennt, kann iTunes die Folge selber nicht laden:

> Es können keine Folgen Ihres Feeds geladen werden.

**Comment by timpritlove** [comment]
Tja, ohne eine Episode im Feed kann ich das nicht testen. Warum nicht eine Nullnummer einstellen, die vielleicht nicht mehr als ein Intro enthält?

**Comment by schlaubumms** [comment]
Seit heute morgen ist eine aktiv. Kann jetzt getestet werden. 

Wie gesagt, das Verzeichnis, wo sie hochgeladen werden, nutzt das Plugin garnicht sondern generiert einen neuen Link. Da ist dann aber die Datei nicht zu finden. Alles andere funktioniert einwandfrei. Wir haben auch mit unserem Empfehler für das Plugin gesprochen und die Einstellungen abgeglichen, alles gleich.

**Comment by schlaubumms** [comment]
Drei Tage testen, löschen, installieren, löschen, umstellen, basteln, genervt sein, nochmal von vorne anfangen, passt. Danke ;)
