### ISSUE TITLE
Warning: count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by tompson** [podlove/podlove-publisher#964]
bekomme seit kurzem in der Website wo der Webplayer eingebunden wird folgenden fehler:

Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/html/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/vendor/podlove/podlove-timeline/lib/Podlove/Chapters/Parser/Mp4chaps.php on line 45

Beispiel siehe https://dtr.fm/episode-147-lattenzaun/

**Comment by PeterTheOne** [comment]
Verwendest du PHP 7.2? `count()` wirft seit PHP 7.2 diese Warnung wenn nicht-zählbare Objekte gezählt werden https://wiki.php.net/rfc/counting_non_countables . Die Warnung verweist auf eine Stelle von https://github.com/podlove/podlove-timeline die es anscheinend nicht mehr gibt..

**Comment by tompson** [comment]
ja, ich verwende 

```
php --version
PHP 7.2.1 (cli) (built: Jan  8 2018 23:26:20) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.2.1, Copyright (c) 1999-2017, by Zend Technologies
```

**Comment by tompson** [comment]
ich verwende das offizielle Docker Wordpress Image und die haben scheinbar auf PHP 7.2 gewechselt, wenn ich den alten Container mit PHP 5.6 verwende habe ich das Problem nicht

**Comment by PeterTheOne** [comment]
Mit https://github.com/podlove/podlove-timeline/pull/2 sollte es dann wieder gehn.

**Comment by tompson** [comment]
Ok, sobald das released ist Versuch ich es wieder
