### ISSUE TITLE
BeyondPod can't download some podcasts

### ISSUE THREAD

**Issue by ccoenen** [podlove/podlove-publisher#967]
This behaviour started a few days ago, and it affects CRE and Raumzeit at the same time. I conclude that it might not actually be [BeyondPod](http://www.beyondpod.mobi/android/index.htm), but Podlove that may have changed (at least I did not upgrade the app in the same time frame).

It also happens on a completely unrelated device for the same podcasts (all other podcasts run fine)

### Expected behavior
Download Episodes RZ069 and RZ070 of Raumzeit

### Actual behavior
App can't download the app, this is the debug output:

```
Failed - RZ070 Weltraumrecht

    Feed Url: http://feeds.feedburner.com/raumzeit-podcast-mp3
    Episode Url: https://tracking.feedpress.it/link/13436/8271260/rz070-weltraumrecht.mp3
    Downloaded: 0, starting at position: 0 took: 0 mSec. at 0,00 KB/Sec
    Content Size: 0. Cache Size: Not Set
    Content Date: Unknown. Cache Date: Not Set
    Feed has Image: Yes, image downloaded: Yes
    Content Compression: Not Compressed
    Reason to fail: ProtocolException - Expected ':status' header not present
```

I am not sure which :status header could be missing, but sadly this is all the info I have.

### System information (see `Podlove > Support` menu)
(does not really apply, but here's a little bit of smartphone info)

Android 8
[BeyondPod](http://www.beyondpod.mobi/android/index.htm) v4.2.16m

**Comment by eteubert** [comment]
Looks fine from here. It would help to know what exactly BeyondPod does not like about the URL/file. Have you tried contacting their developer?

**Comment by ccoenen** [comment]
I will try that next. Sadly, I don't have any more detailed information at my disposal, other than the snippet I see above.

**Comment by timpritlove** [comment]
It‘s a HTTP/2 bug in BeyondPod. Developer says it will be fixed in the next Release and already is in current beta.
