### ISSUE TITLE
PHP warnings when publishing a new episode: Missing argument 2 for podlove_maybe_override_post_titles()

### ISSUE THREAD

**Issue by markusk** [podlove/podlove-publisher#970]
### Expected behavior
Returning to the published episode

### Actual behavior
Warning: Missing argument 2 for podlove_maybe_override_post_titles() in /www/htdocs/xxxxx/reich-und-knapp.de/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/includes/auto_post_titles.php on line 12

Warning: Cannot modify header information - headers already sent by (output started at /www/htdocs/xxxxx/reich-und-knapp.de/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/includes/auto_post_titles.php:12) in /www/htdocs/xxxxx/reich-und-knapp.de/wp-admin/post.php on line 198

Warning: Cannot modify header information - headers already sent by (output started at /www/htdocs/xxxxx/reich-und-knapp.de/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/includes/auto_post_titles.php:12) in /www/htdocs/xxxxx/reich-und-knapp.de/wp-includes/pluggable.php on line 1216

### System information (see `Podlove > Support` menu)
Website                    https://reich-und-knapp.de
PHP Version                5.6.32-nmm1
WordPress Version          4.9.4
WordPress Theme            Twenty Sixteen Child v1.0.0
WordPress Database Charset utf8
WordPress Database Collate 
Publisher Version          2.7.0
Web Player Version         player_v4
Twig Version               1.35.0
open_basedir               ok
curl Version               7.35.0
iconv                      available
simplexml                  ok
max_execution_time         30
upload_max_filesize        200M
memory_limit               256M
disable_classes            
disable_functions          
permalinks                 ok (/%postname%/)
podlove_permalinks         ok
podcast_settings           ok
web_player                 ok
podlove_cache              on
assets                     
  - mp3    audio/mpeg       http://reich-und-knapp.de/feed/mp3/
  - m4a    audio/mp4        http://reich-und-knapp.de/feed/m4a/
  - chapters.txttext/plain       no feed
cron                       ok

0 errors
0 notices
Nice, Everything looks fine!

**Comment by eteubert** [comment]
fixed in 19c9cd254cda8fbfe12548532df4244828f514b4

**Comment by markusk** [comment]
Many thanks!!
