### ISSUE TITLE
analytics tool seems to have issues with time zones 

### ISSUE THREAD

**Issue by leitmedium** [podlove/podlove-publisher#976]
### Expected behavior

The analytics tool should present reliable numbers for downloads per day.

### Actual behavior

I published an episode on 2018-04-15 at 0:04 in the morning. The  stacked graph shows around 100 downloads for this episode for 2018-04-14 (one day before), while the table chart starts counting on 2018-04-15. I assume the downloads for the first one or two ours are shown for the wrong day in the stacked graph. What at least bothers me is that table chart and stacked graph on the same page show different statistics.

### System information (see `Podlove > Support` menu)

Website                    https://mkl.wtf
PHP Version                7.0.25-nmm1
WordPress Version          4.9.5
WordPress Theme            Twenty Eleven v2.7
Active Plugins             
           - Antispam Bee v2.7.1
           - Jetpack von WordPress.com v6.0
           - Podlove Podcast Publisher v2.7.4
           - Podlove Subscribe Button v1.3.3
           - Podlove Web Player v2.1.0
           - Öffentliche Vorschau für Beiträge v2.6.0
           - Yoast SEO v7.2
           - WP Mail SMTP v1.2.5
WordPress Database Charset utf8
WordPress Database Collate 
Publisher Version          2.7.4
Web Player Version         player_v2
Twig Version               1.35.3
open_basedir               ok
curl Version               7.35.0
iconv                      available
simplexml                  ok
max_execution_time         30
upload_max_filesize        200M
memory_limit               256M
disable_classes            
disable_functions          
permalinks                 ok (/%year%/%monthnum%/%day%/%postname%/)
podlove_permalinks         ok
podcast_settings           ok
web_player                 ok
podlove_cache              on
assets                     
  - mp3    audio/mpeg       https://mkl.wtf/feed/mp3/
  - m4a    audio/mp4        https://mkl.wtf/feed/aac/
cron                       ok

0 errors
0 notices
Nice, Everything looks fine!

**Comment by tomtjes** [comment]
I can confirm this. Our team is based in different time zones and we get different graphs.
