### ISSUE TITLE
After updating the Wordpress plug-ing everything SUCKS!

### ISSUE THREAD

**Issue by schugo** [podlove/podlove-publisher#981]
### it takes like 30s to load the player, the theme has changed, kiddish animated UI added. the player does not stop anymore when a different player is clicked on.. -> TOTAL FAIL... 

FUCK OFF!!1

**Comment by eteubert** [comment]
❤️💜💚

**Comment by funkenstrahlen** [comment]
Haters on Github?! Wow this is new to me.

♥️♥️♥️♥️♥️
