### ISSUE TITLE
Browser is having problems with detailed statistics for episode page

### ISSUE THREAD

**Issue by KSDaemon** [podlove/podlove-publisher#982]
When trying to navigate to any episode details statistics (/wp-admin/admin.php?page=podlove_analytics&action=show&episode=256) from podlove_analytics page (/wp-admin/admin.php?page=podlove_analytics) → browser shows “Aw, Snap!” error. 

This happens in:
* Chrome Latest Stable 66.0.3359.181 (MacOS). Same in inkognito mode.
* Opera Latest Stable 53.0.2907.37 (MacOS). Same in inkognito mode.

In Firefox Latest Stable 60.0.1 (MacOS) works as expected.

### System information (see `Podlove > Support` menu)
```
PHP Version                7.2.5
WordPress Version          4.9.6
WordPress Theme            TwentyThirteen
Active Plugins             
           - Contact Form 7 v5.0.2
           - Disqus for WordPress v3.0.15
           - WP Facebook Auto Publish v1.4.9
           - Google Analytics for WordPress by MonsterInsights v7.0.6
           - Google XML Sitemaps v4.0.9
           - Hello Dolly v1.6
           - Ограничение попыток авторизации v1.7.1
           - Platinum SEO Pack v1.3.8
           - Podlove Podcast Publisher v2.7.6
           - SSL Insecure Content Fixer v2.6.0
           - SVG Support v2.3.15
           - W3 Total Cache v0.9.7
           - WP to Twitter v3.3.6
WordPress Database Charset utf8
WordPress Database Collate 
Publisher Version          2.7.6
Web Player Version         player_v2
Twig Version               1.35.3
open_basedir               ok
curl Version               7.19.7
iconv                      available
simplexml                  ok
max_execution_time         30
upload_max_filesize        2M
memory_limit               256M
disable_classes            
disable_functions          
permalinks                 ok (/%year%/%monthnum%/%postname%/)
podlove_permalinks         ok
podcast_settings           ok
web_player                 ok
podlove_cache              on
assets                     
  - mp3    audio/mpeg       /feed/podcast/
  - ogg    audio/ogg        no feed
cron                       ok

0 errors
0 notices
Nice, Everything looks fine!
```

**Comment by eteubert** [comment]
Thanks for the report. 

Related discussion: https://community.podlove.org/t/individual-episode-stats-page-crashing-on-chrome/1448

**Comment by KSDaemon** [comment]
@eteubert Thanks! I'll have a look! Will try to help.... But that's not so easy....

**Comment by eteubert** [comment]
I wonder if Chrome/Opera use the same JS engine. I have not touched the Analytics JS in a long time so I can only assume the browser update is the issue. Question is what changed that is now incompatible. Console unfortunately does not show error messages.

**Comment by eteubert** [comment]
Status: Updating all JS libraries (Crossfilter, D3, DC) solves the issue. I will need some more time to get everything working as before though. But there's light on the horizon :)

**Comment by eteubert** [comment]
Should be fixed with current release https://community.podlove.org/t/release-2-7-10-11/1535
