### ISSUE TITLE
After updating loading takes very long and player doesn't stop  when starting another player

### ISSUE THREAD

**Issue by schugo** [podlove/podlove-publisher#983]
EDIT: tl;dr; Simply compare this versions:

SUCKS (Berlin Hipster Player): (long load, design sucks) https://schugo.de/podcast/
COOL: (Cool Audio User) (quick load, cool design) http://schugo.abcde.biz/mix_cds/_www/

+ don't mess with the design of currently installed version (the dark grey design looked much more professional, than the current blue design)

+ tried downgrading to an older version, but then no episodes show up

+ and no, showing only one player per page is not a solution

+ loading one single player on a page now even shows the loading icon for 2s
   -> you blew up the plug-in size from 3MB to now 30MB (not so good)
  -> this is now bloatware - I don't want to use that
   -> I had 40 players loading instantly on one page before

+ adjusting volume now takes an extra click... regression 

### Expected behavior
quick load, stop playing instance when a different instance is clicked on

### Actual behavior
shows loading icon for >15s, clicking another instance doesn't stop previously playing instance

### System information (see `Podlove > Support` menu)
Website                    https://schugo.de/podcast
PHP Version                5.6.31
WordPress Version          4.9.5
WordPress Theme            Twenty Fourteen v2.2
Active Plugins             
           - Podlove Podcast Publisher v2.7.6
WordPress Database Charset utf8
WordPress Database Collate 
Publisher Version          2.7.6
Web Player Version         player_v4
Twig Version               1.35.3
open_basedir               ok
curl Version               7.55.1
iconv                      available
simplexml                  ok
max_execution_time         180
upload_max_filesize        8M
memory_limit               256M
disable_classes            
disable_functions          
permalinks                 ok (/%year%/%monthnum%/%day%/%postname%/)
podlove_permalinks         ok
podcast_settings           ok
web_player                 ok
podlove_cache              on
assets                     
  - mp3    audio/mpeg       http://schugo.de/podcast/feed/mp3/
cron                       ok

0 errors
0 notices
Nice, Everything looks fine!

**Comment by schugo** [comment]
Please tell me how to get back to this cool player... it's fast, professional + doesn't suck
http://schugo.abcde.biz/mix_cds/_www/

**Comment by eteubert** [comment]
You can change the player version in the settings.

The software is provided free of charge, so take it or leave it. You have no grounds to make demands. I'm closing again, since I don't need to listen to your tone in my spare time. If you find your friendly voice, feel free to come back.

**Comment by schugo** [comment]
it even sucks on Tim's website: https://not-safe-for-work.de/
