### ISSUE TITLE
Required information missing, To play the podcast important references to audio files are missing.

### ISSUE THREAD

**Issue by przemm82** [podlove/podlove-publisher#984]
I set up my first podcast exactly as described in your Youtube tutorial video. My audio file has been found, duration detected etc. but when I click Play arrow, nothing happens. The following is displayed at the top:

Required information missing, To play the podcast important references to audio files are missing.

Do you know why it may be happening? Please also see the attached images.
![1](https://user-images.githubusercontent.com/39566632/40441100-4d6e9f1e-5ec0-11e8-96ef-40f3d9e3c5a5.png)
![2](https://user-images.githubusercontent.com/39566632/40441101-4d9b6724-5ec0-11e8-8ea7-66984f67731f.png)

SYSTEM INFORMATION:
PHP Version                5.6.36
WordPress Version          4.9.6
WordPress Theme            Camyno v3.2
Active Plugins             
           - LayerSlider WP v6.4.0
           - Comments Widget Plus v1.0.7
           - Duplicate Post v3.2.2
           - DWL Preloader v1.1
           - SM Youtube Subscribe v2.0.0
           - EU Cookie Law v2.13
           - Responsive Facebook Page Plugin v1.6.3
           - Google Analytics Dashboard for WP (GADWP) v5.3.3
           - Mailster Email Verify v1.3.1
           - Mailster reCaptcha v1.1.1
           - Mailster - Email Newsletter Plugin for WordPress v2.3.6
           - Menu Icons v0.11.2
           - PayPal Donations v1.9.5
           - Podlove Podcast Publisher v2.7.6
           - Post Types Order v1.9.3.6
           - Social Count Plus v3.4.1
           - TablePress v1.9
           - User Role Editor v4.42
           - UserPro v4.9.21
           - Visualizer: Charts and Graphs Lite v3.0.7
           - When Last Login v1.1
           - Wise Chat v2.6.2
           - wpDiscuz v5.0.7
           - Payment Add-on Lite for UserPro v1.0.0
WordPress Database Charset utf8mb4
WordPress Database Collate 
Publisher Version          2.7.6
Web Player Version         podigee
Twig Version               1.35.3
open_basedir               ok
curl Version               7.54.0
iconv                      available
simplexml                  ok
max_execution_time         600
upload_max_filesize        256M
memory_limit               1024M
disable_classes            
disable_functions          
permalinks                 ok (/%year%/%monthnum%/%day%/%postname%/)
podlove_permalinks         ok
podcast_settings           ok
web_player                 ok
podlove_cache              on
assets                     
  - mp3    audio/mpeg  
cron                       ok

0 errors
0 notices
Nice, Everything looks fine!

**Comment by eteubert** [comment]
Hm, your system report says you use the Podigee player but the screenshot shows the Podlove Web Player 4. Can you provide a URL to your website?

**Comment by przemm82** [comment]
Thanks for responding. I tried different players and when I realized system information would be useful, the other player was set. Here is the correct version:

PHP Version                5.6.36
WordPress Version          4.9.6
WordPress Theme            Camyno v3.2
Active Plugins             
           - LayerSlider WP v6.4.0
           - Comments Widget Plus v1.0.7
           - Duplicate Post v3.2.2
           - DWL Preloader v1.1
           - SM Youtube Subscribe v2.0.0
           - EU Cookie Law v2.13
           - Responsive Facebook Page Plugin v1.6.3
           - Google Analytics Dashboard for WP (GADWP) v5.3.3
           - Mailster Email Verify v1.3.1
           - Mailster reCaptcha v1.1.1
           - Mailster - Email Newsletter Plugin for WordPress v2.3.6
           - Menu Icons v0.11.2
           - PayPal Donations v1.9.5
           - Podlove Podcast Publisher v2.7.6
           - Post Types Order v1.9.3.6
           - Social Count Plus v3.4.1
           - TablePress v1.9
           - User Role Editor v4.42
           - UserPro v4.9.21
           - Visualizer: Charts and Graphs Lite v3.0.7
           - When Last Login v1.1
           - Wise Chat v2.6.2
           - wpDiscuz v5.0.7
           - Payment Add-on Lite for UserPro v1.0.0
WordPress Database Charset utf8mb4
WordPress Database Collate 
Publisher Version          2.7.6
Web Player Version         player_v4
Twig Version               1.35.3
open_basedir               ok
curl Version               7.54.0
iconv                      available
simplexml                  ok
max_execution_time         600
upload_max_filesize        256M
memory_limit               1024M
disable_classes            
disable_functions          
permalinks                 ok (/%year%/%monthnum%/%day%/%postname%/)
podlove_permalinks         ok
podcast_settings           ok
web_player                 ok
podlove_cache              on
assets                     
  - mp3    audio/mpeg       http://www.bookiescanlose.com/feed/mp3/
cron                       ok

0 errors
0 notices
Nice, Everything looks fine!

By the way, the Podigee player is loading forever and never displayed,

Here is the link to my test episode: http://www.bookiescanlose.com/2018/05/23/episode-1/

**Comment by eteubert** [comment]
Please check the settings in "Podlove > Expert Settings > Web Player". The asset assignment there should happen automatically but maybe it did not work for you.
