### ISSUE TITLE
Error Updating Podlove Plugin

### ISSUE THREAD

**Issue by mysharepoint** [podlove/podlove-publisher#988]
### Expected behavior
Upddate from 2.7.6 -> 2.7.7 failed
### Actual behavior
![podlove2 7 7](https://user-images.githubusercontent.com/3776963/41458439-e6b0a9ce-7086-11e8-853f-d99ca6489e53.jpg)

### System information (see `Podlove > Support` menu)
Wordpress Version 4.9.6–de_DE

**Comment by eteubert** [comment]
Should work again.
