### ISSUE TITLE
How to add contributors to info tab of Web Player?

### ISSUE THREAD

**Issue by TimoM** [podlove/podlove-publisher#989]
I know to Web Player has the possibility to append a contributor list to the first tab of the player. Is there an option or setting to enable this via the publisher?

**Comment by TimoM** [comment]
I did just that but it won't work. I'm using templates to insert the player. May this be the reason?

**Comment by eteubert** [comment]
Can you provide the website URL please?

**Comment by TimoM** [comment]
Yes, of course. It’s https://wirrewaffeln.de. Thank you for your time by the way.

**Comment by TimoM** [comment]
Nur noch also Info, weil ich es gerade sehe. Die Rollen sind im Backend auch auf Moderator gesetzt.

**Comment by alexander-heimbuch** [comment]
https://github.com/podlove/podlove-web-player/blob/development/src/store/speakers/reducer.js#L11
:(

ich rechne mit `onair` nicht mit `on-air` ich glaube wir müssen da mal was eindeutiges einführen :/

**Comment by timpritlove** [comment]
Dieses "on-air" ist lediglich eine Konvention in meinen Blogs und sollte nicht normativ für den Player sein.

**Comment by eteubert** [comment]
Ich denke der Player sollte alles anzeigen was ihm geliefert wird. Wenn wir im Publisher ein Gruppen-Attribut einführen, Contributor-Gruppen aus der Player-Anzeige auszuschließen, muss der Player davon imho nix wissen.

**Comment by alexander-heimbuch** [comment]
War initial so :)
