### ISSUE TITLE
Tabbed UI on 'Modules' page

### ISSUE THREAD

**Issue by cfoellmann** [podlove/podlove-publisher#992]
How about adding tabs to the `Modules` page?
Also extensions should be able to easily extend the page with its own tabs.

**Comment by eteubert** [comment]
Yes, a rework of the modules page is due. Not sure if tabs are the way to go as you might lose the ability for a quick overview. I would like to have "cards" like Jetpack has (or had?) for its modules.

Feel free to play around with it and send a Pull Request, would be greatly appreciated. However I need to apologize in advance for the not-very-straight-forward way module settings are implemented.

Have a look at https://docs.podlove.org/podlove-publisher/developer/modules.html
