### ISSUE TITLE
No proper page created for new episodes

### ISSUE THREAD

**Issue by Mandelbrot-Talks** [podlove/podlove-publisher#994]
We are experiencing a major problem with our episode page.
When creating a new episode, the created page in the blog is broken (only contains the titel as a heading). 
This also breakes the whole episode page, and only the one broken (empty) episode is displayed there. 
The old episodes can still be accessed though via their respective direct link. 

The RSS-Feed is still working fine, and all episodes (including the new one) can be accessed there.
I've tried changing the theme, but that did not help.
Hope that someone has an idead why this might be happening! Thanks a lot in advance.

Christoph

### System information (see `Podlove > Support` menu)
`Website                    http://mandelbrot-talks.de
PHP Version                7.0.31
WordPress Version          4.9.8
WordPress Theme            Belise Lite v1.0.15
Active Plugins             
           - Elementor v1.9.8
           - Podlove Podcast Publisher v2.7.11
           - Podlove Subscribe Button v1.3.3
           - Podlove Web Player v2.1.0
           - WordPress Importer v0.6.4
WordPress Database Charset utf8mb4
WordPress Database Collate 
Publisher Version          2.7.11
Web Player Version         player_v4
Twig Version               1.35.3
open_basedir               ok
curl Version               7.50.3
iconv                      available
simplexml                  ok
max_execution_time         120
upload_max_filesize        64M
memory_limit               256M
disable_classes            
disable_functions          
permalinks                 ok (/%year%/%monthnum%/%day%/%postname%/)
podlove_permalinks         ok
podcast_settings           ok
web_player                 ok
podlove_cache              on
assets                     
  - mp3    audio/mpeg       http://mandelbrot-talks.de/feed/mp3/
  - chapters.txttext/plain       no feed
cron                       ok

0 errors
0 notices
Nice, Everything looks fine!`

**Comment by eteubert** [comment]
I suspect an error in template rendering. A peek into the PHP error log should help.

Did you perhapts change the templates recently?

**Comment by Mandelbrot-Talks** [comment]
I would get those logfiles from my hosting provider right? 
I'm not aware of having made any changes to be honest, under templates I only find one named default, containing the following:
``{% if not is_feed() %}

	{# display web player for episode #}
	{{ episode.player }}
	
	{# display contributors if module is active #}
	{% if shortcode_exists("podlove-episode-contributor-list") %}
		{# see http://docs.podlove.org/podlove-publisher/reference/shortcodes.html#contributors for parameters #}
		[podlove-episode-contributor-list]
	{% endif %}

{% endif %}

**Comment by eteubert** [comment]
> I would get those logfiles from my hosting provider right?

They should know where to find them, yes.

> under templates I only find one named default

Not the templates then :)

A theme update maybe? It's possible they introduced some changes incompatible with custom post types. However it's unlikely such changes would result in what you describe.

PHP error log should be more enlightening.

**Comment by Mandelbrot-Talks** [comment]
Thank you for the hint! It turn out that by mistake I put an "ü" special character into the .chapters.txt file, and that apparently killed everything else... Replaced the ü by ue, now everything works fine. Thanks very much for your help!
