### ISSUE TITLE
Required php version

### ISSUE THREAD

**Issue by cfoellmann** [podlove/podlove-publisher#996]
The plugin in requires PHP 5.4 and seems to be running fine on PHP 7.x

In the composer.json we have `"php": ">=5.3.0 <5.5",` which brings up a lot of errors in my IDE for PHP 5.4 code.
Should be changed, right?

**Comment by eteubert** [comment]
Trying to recall the reason. Either it had something to do with Travis CI or, more likely, making sure that I don't accidentally upgrade a composer package to somethin that is not 5.4 back-compatible. I believe I ran into that with the Twig dependency.

If you have a better solution for that, thoughts are welcome :)

**Comment by eteubert** [comment]
Yea that should be safe.

greenkeeper.io seems to be for npm, not composer.

**Comment by cfoellmann** [comment]
> greenkeeper.io seems to be for npm, not composer.

Sorry for not seeing that.
